### ISSUE TITLE
User account creation has ambiguous error

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4138] opened 2015-07-22 00:54 UTC
Testing current develop on XP Browser: Chrome
I am unsure why the password I first tried here for a student was rejected by trying a much longer "more secure" password was allowed. There may have been changes made to the password restrictions which I am unaware. Regardless the user would be also, the error states to review the errors below where none are provided?

![2015-07-21_18-28-59](https://cloud.githubusercontent.com/assets/4349806/8815686/d8093210-2fd9-11e5-8320-cdd37937d6fa.png)

**Comment by EdDixon** [comment] 2015-07-28 20:43
Also exists on current develop on MAC
![2015-07-28_14-34-08](https://cloud.githubusercontent.com/assets/4349806/8943206/e8abcd3c-3536-11e5-8bc7-c3303f8da292.png)

**Comment by EdDixon** [comment] 2015-08-26 05:08
Just adding that this still exists on Linux during a PPA installation on 14.03.4 LTS this morning while creating a Coach account. Student account creation seemed unaffected. I wish I had mentioned what type of account was being created in the previous reports knowing this now. Screen Shot of error on Ubuntu 14 LTS below: https://s3.amazonaws.com/uploads.hipchat.com/86198/1302220/m1noWCwQHdsWh9y/2015-08-25_12-33-40.png

**Comment by MCGallaspy** [comment] 2015-08-26 17:28
@rtibbles suggested this might be caused by a bad value for a hidden field, and that https://github.com/learningequality/ka-lite/pull/4192 could resolve it.

**Comment by rtibbles** [comment] 2015-08-26 17:31
I stand by the latter part of that statement, but I was probably in error
as to the cause. More likely due to the redirect to the facility management
page on post requesting a zone id incorrectly, which is corrected by #4192

**Comment by MCGallaspy** [comment] 2015-08-26 17:33
I've asked @EdDixon to try to replicate the issue now that #4192 has been merged in.

**Comment by aronasorman** [comment] 2015-09-01 18:34
@EdDixon can you try replicating this again?

**Comment by MCGallaspy** [comment] 2015-09-01 18:45
He suggested in hipchat that it was resolved.

**Closed by MCGallaspy** 2015-09-01 18:45 UTC
Labels: bug
