### ISSUE TITLE
Some questions do not contain the needed content to answer them.

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3536] opened 2015-04-21 17:47 UTC
Trying to make this as vague as possible because I do not want to point to a specific cause (I have no idea what that cause is) so I will leave this picture of the issue encountered? I think it may be relatd to how the equations are rendered in our code as the same question at the khan academy offical site works fine I will include both pics for reference? 
![2015-04-21_10-23-36](https://cloud.githubusercontent.com/assets/4349806/7258830/23e2c58a-e81c-11e4-985f-033daecbeb1e.png)
![2015-04-21_11-26-36](https://cloud.githubusercontent.com/assets/4349806/7258832/28235128-e81c-11e4-87c9-545b1d3ab0b3.png)

**Comment by EdDixon** [comment] 2015-04-21 18:21
I should note that this replicated on both RaspberryPi and Windows 8.1 ent.

**Comment by MCGallaspy** [comment] 2015-04-28 18:42
Could this possibly be due to missing Mathjax source files? For example, I get a 404 for GET `http://127.0.0.1:8008/static/perseus/ke/third_party/MathJax/2.1/extensions/MathZoom.js` (and a couple others). The file is missing on `develop`. Where can I grab these missing files, @rtibbles?

**Comment by rtibbles** [comment] 2015-04-28 18:45
No, the 'missing' MathJax errors are due to some fiddling I did to try to
get Javascript Front End testing working. I will revert those changes on
develop prior to release.

**Comment by MCGallaspy** [comment] 2015-04-29 19:21
The assessment item API response for an offending exercise:
```json
{"author_names": "['Brenda Hodges']", "id": "x282f1f2733a50cf7", "item_data": "{\"question\": {\"content\": \"The number $b$ is $5$ less than twice the number $c$. The product of $b$ and $c$ is $45$. \\n\\n**Which of the following pairs of equations could be used to find the values of $b$ and $c$ ?**\\n\\n[[\\u2603 radio 1]]\\n\\n\", \"images\": {}, \"widgets\": {\"radio 1\": {\"version\": {\"major\": 0, \"minor\": 0}, \"type\": \"radio\", \"graded\": true, \"options\": {\"onePerLine\": true, \"noneOfTheAbove\": false, \"choices\": [{\"content\": \"$\\\\begin{align} b &= 2-5c \\\\\\\\\\n45 &= bc \\\\end{align}$\", \"correct\": false}, {\"content\": \"$\\\\begin{align} b &= 2c-5 \\\\\\\\\\n45 &= bc \\\\end{align}$\", \"correct\": true}, {\"content\": \"$\\\\begin{align} b &= 2c-5 \\\\\\\\\\n45c &= b \\\\end{align}$\", \"correct\": false}, {\"content\": \"$\\\\begin{align} b &= 2c+5 \\\\\\\\\\n45c &= b \\\\end{align}$\", \"correct\": false}, {\"content\": \"$\\\\begin{align} b &= 2(c+5) \\\\\\\\\\n45 &= bc \\\\end{align}$\", \"correct\": false}], \"displayCount\": null, \"multipleSelect\": false, \"randomize\": false}}}}, \"answerArea\": {\"calculator\": false, \"type\": \"multiple\", \"options\": {\"content\": \"\", \"images\": {}, \"widgets\": {}}}, \"itemDataVersion\": {\"major\": 0, \"minor\": 1}, \"hints\": [{\"content\": \"The following could be used to find the values of $b$ and $c$ :\\n\\n$\\\\begin{align} b &= 2c-5 \\\\\\\\\\n45 &= bc \\\\end{align}$\\n\\n[Watch Sal work through this question.](/learn/khan/test-prep/sat/sat-math-practice/sat-math-level-1/sat-2010-may-6-5/)\", \"images\": {}, \"widgets\": {}}]}", "kind": "AssessmentItem", "resource_uri": "/api/assessment_item/x282f1f2733a50cf7/", "sha": "4c060b73e2b599fce0d32fa68125d12f507d3d35"}
```

Just realized I'm still on develop, let me try it on 0.13.x though.

**Comment by MCGallaspy** [comment] 2015-04-29 19:46
Confirmed that I don't see this issue on `0.13.x`.

**Comment by aronasorman** [comment] 2015-04-29 19:46
Transferring to 0.14 then.

**Comment by rtibbles** [comment] 2015-04-29 19:48
Should we, perhaps, merge in 0.13 into develop, and check if it is extant
then?

**Comment by MCGallaspy** [comment] 2015-04-29 19:53
Yup

**Comment by rtibbles** [comment] 2015-07-09 19:11
Assumed fix by above merge.

**Comment by MCGallaspy** [comment] 2015-07-10 00:23
To my knowledge this was never resolved.

**Comment by aronasorman** [comment] 2015-08-31 22:28
@EdDixon status of this?

**Comment by EdDixon** [comment] 2015-09-01 05:05
This particular question seems to be resolved in 0.14 as shown below and verified on both XP and Mac installations so far however, that is not to say that other question do not have issues. As I am testing the installers here I am randomly going through questions in each installation which is how this one was found? I have not encountered any as bad as this in English yet but, have seen similar type issues in other languages where the assessments themselves have not yet been fully translated. I would like to keep this open long enough to complete the test on the 0.14 release and will update once complete. 

![2015-08-31_22-56-37](https://cloud.githubusercontent.com/assets/4349806/9596645/a9d6dd7c-5034-11e5-9c05-e9b4dd4c7f6f.png)

Thanks,

**Comment by MCGallaspy** [comment] 2015-12-08 02:32
Stale.

**Closed by MCGallaspy** 2015-12-08 02:32 UTC
Labels: bug

**Comment by EdDixon** [comment] 2015-12-09 16:05
Thanks Mike as far as I know it never resurfaced after the attention here. :)
