### ISSUE TITLE
Performance and crash issues occurring regardless of OS and particularly on initial downloading of video files. Maybe due to number in queue.

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#2855] opened 2015-01-13 18:00 UTC
Performance and crash issues occurring regardless of OS and particularly on initial downloading of video files. Maybe due to number in que. Seen on both OSX and Windows installations when selecting large video trees. In both cases there was nothing from the CLI that launched the server that the server had stopped responding other than in a few cases OS python notification. Restarting the server in both cases seems to help resolve the issue and the videos continue to download however there progress is shown in the launching CLI which is not normally the case and the server still is prone to locking up like this. 

May be due to resource demands due to required database manipulation to accommodate the number of downloads processed and might be mitigated by controlling the number of videos processed concurrently.

**Comment by aronasorman** [comment] 2015-01-13 18:04
We don't want this to be a blocker for the 0.13 release, but at the same time we want this solved soon. So this should go in as a point release of KA Lite.

For the release we can just have a warning in the page that says "For low-powered devices like the Raspberry Pi, please download videos one at a time." (Hence the "Beginner" label).

**Comment by aronasorman** [comment] 2015-01-15 22:44
Warning done by @anuragkanungo above. Removed the beginner issue, since the proper fix is a bit more hairy.

**Comment by benjaoming** [comment] 2015-02-02 05:03
Is this because of concurrent instances of cronograph running?

As I see it, if you add 10,000 jobs to the queue and start two CronThreads at the same time, then each of them will say "oh, there are jobs on the queue", and each of them will call the `cron` command, which will then start iterating a queryset which was instantiated at the start of the call. Every job instance has its run() method called, but that one only sets `is_running` but does not look at any fresh data from the database prompting if some other process has already started the job.

Anyways, the new `kalite start` command creates both a PID file for the running cronserver process and a lock file to ensure that `kalite start` can never start a cronserver twice.

I would say, @EdDixon, let us know if you see this issue at the current stage of 0.13, otherwise, the issue could be buried to make room for a more serious fix, namely #2891 and have that scheduled for 0.14 instead :)

**Comment by EdDixon** [comment] 2015-02-02 06:25
Hi @benjaoming , 

Jamie asked me to post the issue because of a problem he was aware of dealing with concurrent database manipulation tied to the selection and download process. Ready and in progress may mean those issues have been better addressed since last tested, I am unsure.  Last tests on hardware not virtualized with dedicated persistence, meaning constantly checking that the process had not frozen and continued stopping and starting of the entire application when it did, eventually the entire download set did happen. The larger issue (at least in my mind) is that there is no indication what so ever from CLI or GUI that the entire application has hung due to this problem. Only by manually tracking which video is downloading or checking that the application is still responsive can you really know?  

There may have been some progress I am unaware of and I really like the idea of the kalite command and I have put some serious effort into that here myself and at this point, we still do not have a kalite command on windows (our leading deployment host), so I fail to see how that can be called a solution to this issue? But we should continue that discussion in its related thread.

I plan to run a complete round of tests on all hardware this week as soon as the exercise capabilities are fully functional and available with in depth testing on Windows 7 in particular. I do hope we have this thing solved because having to download all that (which most teachers will want to do) is extremely time consuming as is but combined with these issues, is in my opinion enough to make them give up and never look back. Again just my opinion but I feel anything that even remotely affects our user base directly such as this should be given top priority because even though all they have to do is reboot the machine a couple hundred times over the course of a week or so to be up and running it is not something they should have to deal with and it does not do our efforts here justice. Glad to hear you have it sorted in Linux though anxious to try it out here!

**Comment by benjaoming** [comment] 2015-02-02 07:46
> we still do not have a kalite command on windows (our leading deployment host)

You can still run `bin/windows/kalite start` :) The problem is that we haven't figured out a bullet-proof way to link it into your command line path, but testing out the CLI is still possible.

**Comment by benjaoming** [comment] 2015-02-02 08:34
I would like to acknowledge that I also see problems downloading. Having started a job of ~106 GB downloads, it stopped after ~7 GB with no feedback. The cronserver was still running. I will inspect the DB more closely if it happens again.

But at the current state I would not suspect a concurrent instances of cronserver to be blamed.

Nor do I understand where the parallel stuff is happening. Downloading videos happens by

Putting a job in the Chronograph => Job "download all undownloaded videos" is run => A single process iterates all undownloaded videos => For each undownloaded video, a request is sent to urllib.urlretrieve which is not a concurrent function, it will not return until a full video has been downloaded.

I would expect the cronserver to be busy as long as a video download job has not completed, thus eliminating the chance of downloading the same file twice. However, running several cronograph servers is still possible, but the `videodownload` command makes a fresh lookup in the DB before every new download, so it should be okay about not trying out the same files, although race conditions may happen if multiple cronservers are doing the same.

Anyways, my main finding here is that a fresh copy of the develop branch failed to download video data upon first request. The only non-clean part of my installation was some 24 GB of old videos that I dumped in the content dir before starting the downloads.

**Comment by benjaoming** [comment] 2015-02-03 21:22
Okay I'm back with some additional debug data after 3 failed attempts to download all videos.

Here's how it fails visually speaking:

![download_stopped](https://cloud.githubusercontent.com/assets/374612/6029692/f9e3fa7c-abfa-11e4-80d7-eaf84f67f5da.png)

The job is marked as failed in the chronograph but not scheduled for a rerun, so it's safe to start a new download job.

![chronograph](https://cloud.githubusercontent.com/assets/374612/6029747/5f54ea06-abfb-11e4-8506-30db2ac19a80.png)

I tried downloading 3 times, and here are the 3 last known jobs in the download process.

![progress_errors](https://cloud.githubusercontent.com/assets/374612/6029708/19c53996-abfb-11e4-87ed-8d56e200f8bd.png)

Apparently downloading completely halts after each failed attempt and does not move to next job in queue. See for instance this row still flagged for download but with 0 progress:

![queue](https://cloud.githubusercontent.com/assets/374612/6029729/3a4a66a0-abfb-11e4-93cc-61638cb2982b.png)

After the failed download, I have a total of 368 videos remaining in my queue.

![video_download_before_restart](https://cloud.githubusercontent.com/assets/374612/6029739/4fdabd62-abfb-11e4-967a-176ced36e101.png)

@aronasorman Would like to nominate this as a release blocker for 0.13...

**Comment by rtibbles** [comment] 2015-02-03 21:23
Seconded!

**Comment by benjaoming** [comment] 2015-02-03 21:24
@aronasorman 
Also, the title of the issue is misleading but my experience is exactly the same as Ed's first sentences describe: **Performance and crash issues occurring regardless of OS and particularly on initial downloading of video files. Maybe due to number in que.**

**Comment by benjaoming** [comment] 2015-02-04 08:14
And so finally, it succeeded downloading the last 38 videos...

![success](https://cloud.githubusercontent.com/assets/374612/6036974/86c9cf9c-ac56-11e4-96b5-97ed85c85037.png)

(noting: That should mean we can rule out 404s)

**Comment by benjaoming** [comment] 2015-02-07 09:05
In the end, I'm left with this:

![4_remaining](https://cloud.githubusercontent.com/assets/374612/6091535/f204ecc4-aeb8-11e4-8e31-8772edee43ba.png)

Last of the updates_updateprogresslog:

	"3M8bwwafMxY","error","2644","Error: 'NoneType' object has no attribute '__getitem__'","videodownload","1","0.31","1","2015-02-02 07:05:33.298741","0.06592662632375189","0","2015-02-02 03:28:48.015368","175"
	"kkpVr5eoyVE","error","2470","Error: 'NoneType' object has no attribute '__getitem__'","videodownload","1","0.08","2","2015-02-03 09:40:08.978713","0.738493927125506","0","2015-02-02 10:07:42.537594","1825"
	"r2syXj4Eb6w","error","648","Error: 'NoneType' object has no attribute '__getitem__'","videodownload","1","0.46","3","2015-02-03 14:26:27.794795","0.43589506172839504","0","2015-02-03 10:34:32.025454","283"
	"yqJB8XMXzE4","error","365","Error: 'NoneType' object has no attribute '__getitem__'","videodownload","1","0.9","4","2015-02-04 04:06:04.399857","0.8983561643835616","0","2015-02-03 23:22:49.426718","328"
	"zxy4KAiSPIc",,"38","Downloaded 38 of 38 videos successfully.","videodownload","1","1","5","2015-02-04 09:56:48.502853","1","0","2015-02-04 09:12:01.505610","38"
	"yyM0yIOJ2yE",,"22","Downloaded 22 of 22 videos successfully.","videodownload","1","1","6","2015-02-07 08:04:18.514715","1","0","2015-02-07 07:48:07.710626","22"

Launching a new download will just say: "Launched video download process successfully." -- but nothing will happen.

**Comment by aronasorman** [comment] 2015-03-04 10:35
Turned this into a release blocker. @anuragkanungo you're up!

**Comment by anuragkanungo** [comment] 2015-03-04 17:00
Error: 'NoneType' object has no attribute '__getitem__'  happens when internet is not available.
I started the download of videos and disconnected internet in between and got the error.

**Comment by aronasorman** [comment] 2015-03-04 17:10
Shouldn't the `cronserver` restart the download? If not, then that looks like a bug. Also, we should add `--traceback` to get a better error on where it's throwing that Error.

**Comment by anuragkanungo** [comment] 2015-03-04 17:12
Terminal output:
DEBUG:kalite:Cannot set priority, psutil module not installed
DEBUG:kalite:Setting videodownload to 6577 total stages.
INFO:kalite:Downloading 'The mummification process'
INFO:kalite:Error: 'NoneType' object has no attribute '__getitem__'
INFO:kalite:Cancelling process videodownload
[04/Mar/2015 22:42:25] "GET /api/updates/progress?process_id=11&_=1425489099222 HTTP/1.1" 200 300

**Comment by anuragkanungo** [comment] 2015-03-04 17:13
It cancels the process.

**Comment by aronasorman** [comment] 2015-03-04 17:14
Hmm, error not helpful. It's probably being caught somewhere. You can try grepping for `logging.error` to see what lines could possibly throw that error.

**Comment by benjaoming** [comment] 2015-03-04 17:14
That would sound like a plausible explanation, Anurag! I was
mass-downloading so no doubt that during those many hours, you'd encounter
a timeout etc.

**Comment by anuragkanungo** [comment] 2015-03-04 17:21
@aronasorman 
The error is python related : It happens when you try to access a null item like
value[2] and value is None.

**Comment by benjaoming** [comment] 2015-03-04 17:36
Writing from my non-dev lodge.. The error is probably something like this:
An exception is caught silently, and then the assignment of data from a url
fetch is None. The fault is not that the value is assigned None but that an
exception is handled silently... that kind of stuff is poison in a
codebase... always let exceptions occur or handle them explicitly...
retrying with an increasing waiting step would be sane.. but user feedback
is always required.

**Comment by aronasorman** [comment] 2015-03-04 18:10
@anuragkanungo right, but we wanna definitively find out why and where it's raising the error in the first place. And the `INFO:kalite:Error` is most printed by a `logging.error` call.

**Comment by aronasorman** [comment] 2015-03-04 18:12
Whoops, I meant a `logging.info`. Thanks @rtibbles

**Comment by anuragkanungo** [comment] 2015-03-04 18:12
Got the problem, will resolve it

**Comment by rtibbles** [comment] 2015-03-11 22:05
@aronasorman I think this has been fixed enough not to block 0.13 release, unless @EdDixon reckons otherwise.

**Comment by rtibbles** [comment] 2015-03-20 22:05
This seems to be running smoothly according to @EdDixon

**Closed by rtibbles** 2015-03-20 22:05 UTC
Labels: bug, has PR, performance
