### ISSUE TITLE
Error signing in in authorised account

### ISSUE THREAD

**Issue by namanspace** [learningequality/ka-lite#3202] opened 2015-03-09 11:20 UTC
Branch: develop
If I try to see the coach reports through an account, It shows both, a success dialog and an error dialog. 
While, it should straight away deny you from logging in if you don't have an authorized account.

![screenshot from 2015-03-09 16 46 13](https://cloud.githubusercontent.com/assets/5255299/6553947/2ab208c4-c67c-11e4-8567-c00cf96fa654.png)

**Comment by namchester** [comment] 2015-03-12 21:38
Steps to reproduce: Trying to open any url from the admin/coach side while using the crredentials of a student to login.

Current behaviour:  It shows both, a success dialog and an error dialog. As showin in the screenshot.
Expected behaviour: Should not show the successful login message. I think it is a major bug which needs to be fixed asap. Can I look into it?

**Comment by MCGallaspy** [comment] 2015-05-25 23:47
It appears the real issue is that the bubbles are not being dismissed as expected; in other words, the successful student login bubble is being displayed along with the "danger" unauthorized bubble. Not entirely clear what the resolution of this should be, but the behavior has almost certainly changed since @rtibbles's new login stuff has been merged in. Can someone try to reproduce this?

**Comment by aronasorman** [comment] 2015-05-26 20:56
I tried simulating this by first opening the [teach](http://127.0.0.1:8008/coachreports/teach/89496a2f004446af85de09268c9287fb/) page as an admin, then restarting my server.

This is what I get:

![screen shot 2015-05-26 at 1 55 41 pm](https://cloud.githubusercontent.com/assets/191955/7823231/f13d81ac-03ae-11e5-901d-eb31364ea6aa.png)

So it looks like our modal login isn't functioning properly @rtibbles?

**Comment by MCGallaspy** [comment] 2015-05-28 21:45
Yeah, it seems this issue no longer exists with the new login logic, but once the redirect behavior is changed by #3729, I wonder what will happen? I mean, what happens if you navigate to an unauthorized page and are prompted to login, but you login in with insufficient credentials?

**Comment by MCGallaspy** [comment] 2015-05-28 21:47
Okay, I think the answer to the above question is that you will see the bubble `You must be logged in with an account authorized to view this page.` and the login modal will be enabled, still. Seems reasonable. I'll say this is resolved by #3729.

**Closed** 2015-06-27 14:37 UTC
Labels: beginner, bug
