### ISSUE TITLE
sidebar and sidebar-tab are not moving harmoniously

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3248] opened 2015-03-10 23:30 UTC
we should either disable sidebar-tab animation or enable sidebar animation

**Comment by MCGallaspy** [comment] 2015-03-11 17:55
@66eli77 you mean the tab and sidebar are moving out of sync? This is small but noticeable on the desktop, agreed. Is it more noticeable on tablets?

**Comment by rtibbles** [comment] 2015-03-11 22:21
This appears to be a duplicate of #2973

**Comment by 66eli77** [comment] 2015-03-11 23:39
@MCGallaspy yes, not only that, it drags the performance significantly on cheap tablet. that's why we disabled the animation at the first place.

**Comment by MCGallaspy** [comment] 2015-05-25 23:52
Closed, see #2973.

**Closed by MCGallaspy** 2015-05-25 23:52 UTC
