### ISSUE TITLE
Sidebar is not updating downloaded videos 

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4483] opened 2015-09-24 17:20 UTC
While testing the current 0.15 MAC develop installer, I noticed that after having downloaded videos as the admin user then going back to the side bar the videos were not listed. I then logged out of admin and logged in as a student still the videos which where downloaded and reflected as downloaded in the video tree where not available to either user using the sidebar.

**Comment by 66eli77** [comment] 2015-09-24 20:35
if you restart the server, will those videos be available on the sidebar?

**Comment by EdDixon** [comment] 2015-09-24 23:07
Testing a restart of the server logged in as admin, the previously downloaded did show up correctly but new videos downloaded before did not show up. Roughly 30 minutes later returning from our standup meeting I found that I had been logged out of the server upon logging back in the videos I had just downloaded where listed. I hope this may help solve the problem?

**Comment by cpauya** [comment] 2015-09-25 03:40
I manually added `DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True` to `~/.kalite/settings.py`, restarted the "KA-Lite-Monitor.app", downloaded a video, checked the sidebar, but the newly downloaded video is still greyed-out.

I tried the following but no dice too:

1. Download a video, navigate to the Learn page - Sidebar - but video is still greyed-out.
2. Download a video, refresh the page, navigate to the Learn page - Sidebar - but video is still greyed-out.
3. Download a video, logout the user, navigate to the Learn page as guest - Sidebar - but video is still greyed-out.
4. Download a video, logout the user, login again, navigate to the Learn page - Sidebar - but video is still greyed-out.

The only solution so far is to restart the server after downloading videos so they are not greyed-out in the sidebar.

I thought adding `DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True` to `~/.kalite/settings.py` should do the trick as mentioned by @rtibbles in the hipchat - Testing room.  

Anything I missed perhaps?

/cc: @rtibbles @aronasorman

**Comment by EdDixon** [comment] 2015-09-25 17:04
With the latest build I am seeing new behavior where everything including the assessments are now greyed-out where before it was just the video content that should be there? 
![2015-09-25_10-50-34](https://cloud.githubusercontent.com/assets/4349806/10106984/1178ba1a-6375-11e5-91ee-c3b154b38836.png)

**Comment by 66eli77** [comment] 2015-09-25 17:05
I also observed that after start the server, if you don't go to the learn page just yet, instead go to download some videos and then go to learn page, the sidebar will initiate( like it always does for the first time open the sidebar) and all downloaded videos shown up correctly.
**this is git install 0.15.x**

**Comment by EdDixon** [comment] 2015-09-25 17:07
@66eli77 That is exactly what I did here but I am having a completely different outcome using the MAC installer not GIT?

**Comment by rtibbles** [comment] 2015-09-25 17:40
This seems to be Mac specific - I cannot replicate on Ubuntu/Chrome from git install 0.15.x.

**Comment by aronasorman** [comment] 2015-09-25 19:03
@cpauya, @66eli77 and I replicated this on his macbook. We set [this value](https://github.com/aronasorman/ka-lite/blob/616098398b205561cf6cf4afb9ae04f1f711e800/python-packages/fle_utils/django_utils/command.py#L110) to be unconditionally false, and now we get the expected behaviour. 

I'm not sure what to do, perhaps we should remove this mac-specific hack, and see how we can avoid making KA Lite crash as per #3704?

**Comment by aronasorman** [comment] 2015-09-25 19:06
The frustrating is that any fix we make for this will only be for 0.15, as @rtibbles' cache invalidation PR doesn't use in memory variables for caching.

**Comment by rtibbles** [comment] 2015-09-25 19:12
Yeah, so this is definitely a threading issue - the 'cache_invalidation' is happening inside the subprocess, so its changes to the global variables are not affecting the actual ones used by KA Lite.

**Comment by EdDixon** [comment] 2015-09-25 19:22
Probably a separate issue but, I just noticed that after restarting the server the assessments are still not listed as expected although the videos are. However this was not an issue until this latest fix to address the issue under discussion here so I think it belongs here as well. 
![2015-09-25_13-18-35](https://cloud.githubusercontent.com/assets/4349806/10110125/684679f0-6388-11e5-978b-d6ffbb830a6e.png)

**Comment by rtibbles** [comment] 2015-09-25 19:54
No fix has been made yet for this issue, @EdDixon, so it is not clear it's related.

**Comment by aronasorman** [comment] 2015-09-25 19:57
Resolution was to just add a warning for Mac users, indicating that they need to restart their server once they download videos.

**Comment by cpauya** [comment] 2015-09-28 10:55
Fixed in #4510 -- now have warning for users of Mac server to "restart server after downloading videos".
![screenshot 2015-09-28 18 46 53](https://cloud.githubusercontent.com/assets/175580/10133728/542c2ad2-6612-11e5-88ca-af08dbaf85d1.png)

**Comment by cpauya** [comment] 2015-10-05 16:15
Re-opening this in reference to [Mac installer to use DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP](https://github.com/learningequality/installers/issues/206)

**Comment by aronasorman** [comment] 2015-10-05 16:40
This was reopened, so we can use` DO_NOT_RELOAD...` for the Mac?

**Comment by rtibbles** [comment] 2015-10-05 17:31
Punting to 0.16. Where it is fixed. Closing.

**Comment by benjaoming** [comment] 2015-10-05 20:16
> I thought adding DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True to ~/.kalite/settings.py should do the trick as mentioned by @rtibbles in the hipchat - Testing room.
> 
> Anything I missed perhaps?

Did you add it after `from kalite.project.settings.base import *` ? :)

**Comment by cpauya** [comment] 2015-10-06 06:34
I added it after the import line, at the end of the `settings.py`.

**Comment by benjaoming** [comment] 2015-10-06 09:19
@cpauya that should work :) You can always test it with:

    kalite shell
    >>> from django.conf import settings
    >>> print settings.DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP

**Comment by MCGallaspy** [comment] 2015-10-12 20:43
Apparently a problem in 0.14.2. Will check before release.

**Comment by MCGallaspy** [comment] 2015-10-13 17:29
User error.

**Closed by MCGallaspy** 2015-10-13 17:29 UTC
Labels: release blocker
