### ISSUE TITLE
a running-time-of-binary-search question has no UI element to enter answer

### ISSUE THREAD

**Issue by quozl** [learningequality/ka-lite#5154] opened 2016-06-13 08:00 UTC
## Summary

One of the questions has no place to make an answer.

## Branch or installer method

 - Installer: Ubuntu 16.04
 - Version: ka-lite-bundle_0.16.6~a1-0ubuntu1_all.deb (from ka-lite-proposed PPA)

## Traceback or relevant snippet from server.log

Nothing remarkable in server.log, but is available if you need it.

## How to reproduce

1. install with dpkg,
1. `kalite manage setup`,
1. open http://127.0.0.1:8008/ and navigate to the computing topic learn/khan/computing/computer-science/algorithms/binary-search/running-time-of-binary-search/

## Screenshots

![running-time-of-binary-search](https://cloud.githubusercontent.com/assets/2936481/16000499/1dc91b5e-3190-11e6-8bc7-7dec2015491e.png)

## Real-life consequences

None, just a developer testing your new release. :grin:

**Comment by benjaoming** [comment] 2016-06-13 08:50
@quozl big thanks for the report!

I'm not sure exactly what the issue could be, but I have it running after refreshing. First time, it didn't work (same result as your screenshot) signalling that a previous static item (javascript file) has been updated to work.

Could you try refreshing?

Furthermore, if you're running `ka-lite-bundle`, it contains the fixed unreleased exercise data, however if you install older versions and choose to download exercise data, it's still picked up from the old location.

**Comment by benjaoming** [comment] 2016-06-13 09:03
Deleted my other comment after discovering this is a randomly occurring exercise within the set of otherwise functional exercises.

But again @quozl -- big time thanks for doing this!! It's incredibly helpful!!

This is how it's supposed to look:

![Uploading Screenshot from 2016-06-13 11:01:28.png…]()

https://www.khanacademy.org/computing/computer-science/algorithms/binary-search/e/running-time-of-binary-search

@rtibbles @aronasorman would you rather fix the problem or exclude the exercises?

**Comment by benjaoming** [comment] 2016-06-14 00:05
@aronasorman confirmed this as a duplicate of #5131, closing in favour of that issues. It's highly prioritized @quozl and thanks for reporting!

**Closed by benjaoming** 2016-06-14 00:05 UTC
Labels: content / perseus
