### ISSUE TITLE
After registering, the "Register now" buttons etc still show up, until next login

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3002] opened 2015-02-09 23:39 UTC
Expected: After registering, the interface should no longer show links/instructions to "register now".

Observed: 
After registering the Manage tab still looks like:
![image](https://cloud.githubusercontent.com/assets/618416/6118363/9a8a3b7e-b071-11e4-96e2-9da19afde67d.png)

But if you click the register now button, it shows:
![image](https://cloud.githubusercontent.com/assets/618416/6118366/b4e18720-b071-11e4-964c-d36f4e9a6078.png)

Note that once you logout and login again, the registration status is properly indicated.

Steps to replicate:
- Register
- Go to Manage tab

**Comment by arceduardvincent** [comment] 2015-02-10 03:06
Hi @jamalex and @aronasorman .
As I examine and replicate this issue I found out this is not a bug but it is a feature that @anuragkanungo made.

Details:
If the boolean statement returns true `is_config_package_nalanda` which declared in `distributed/custom_contex_processor.py` and the `CONFIG_PACKAGE` use is 'Nalanda' the button will appear.

Conclusion:
 @anuragkanungo specify if the device used for Nalanda package only and hide update software for non Nalanda. 

Question:
Does this feature is a bug?
Does we allow the non nalanda user to update software?

Thanks.

**Comment by arceduardvincent** [comment] 2015-02-10 03:33
I use a `Nalanda` package see attach image below.
![screen shot 2015-02-10 at 11 31 42 am](https://cloud.githubusercontent.com/assets/4099119/6121133/9d9a18c8-b118-11e4-9207-92d9b6e57f57.png)

**Comment by jamalex** [comment] 2015-02-10 17:46
This issue doesn't have anything to do with Nalanda in particular. It's that the "Register" button should not appear anymore after the server has already been registered. It's an error in the code that checks the registration status, to know whether or not to show the button.

The "Update" button (unrelated to this issue) should only show up for Nalanda, yeah.

**Comment by arceduardvincent** [comment] 2015-02-11 00:46
hi @jamalex 
thanks for the fast response,

**Comment by arceduardvincent** [comment] 2015-02-19 03:08
@jamalex I think this issue is done. The fix is merged #3026 .

**Closed** 2015-02-19 19:26 UTC
Labels: 0.13.x bug bash, bug, has PR, high priority
