### ISSUE TITLE
"TypeError: list indices must be integers, not str" during demo server start

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3622] opened 2015-05-09 17:37 UTC
Branch: 0.13.x-demo

Partial steps to replicate: Multiple language packs (and many videos) downloaded onto server, but with reinstating a database from before some of those language packs existed. Hard to replicate now (as I deleted the video files), but perhaps the traceback below can help us patch a hole. 

```
INFO:kalite:Preloading topic tree data for language ar.
Traceback (most recent call last):
  File "/home/aron/ka-lite/kalite/../python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/aron/ka-lite/kalite/../python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/home/aron/ka-lite/kalite/../kalite/distributed/management/commands/kaserve.py", line 127, in handle
    self.reinitialize_server()
  File "/home/aron/ka-lite/kalite/../kalite/distributed/management/commands/kaserve.py", line 97, in reinitialize_server
    initialize_content_caches()
  File "/home/aron/ka-lite/kalite/../kalite/caching/__init__.py", line 110, in initialize_content_caches
    topic_tools.get_topic_tree(force=force, annotate=True, language=lang)
  File "/home/aron/ka-lite/kalite/../kalite/topic_tools/__init__.py", line 110, in get_topic_tree
    recurse_nodes(TOPICS[channel][language])
  File "/home/aron/ka-lite/kalite/../kalite/topic_tools/__init__.py", line 75, in recurse_nodes
    node["parent"] = parent
TypeError: list indices must be integers, not str
```

**Comment by rtibbles** [comment] 2015-05-21 00:12
This was caused by an incomplete transition from get_topic_tree returning a dictionary, and get_topic_tree returning a list. Now fixed.

**Closed by rtibbles** 2015-05-21 00:12 UTC
Labels: bug, internationalization
