### ISSUE TITLE
Empty navbar dropdown in some cases

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#2982] opened 2015-02-09 22:40 UTC
We all know this, right?

![screen shot 2015-02-09 at 2 39 41 pm](https://cloud.githubusercontent.com/assets/6601788/6117468/934588b2-b069-11e4-9562-69930dbfd65a.png)

**Comment by rtibbles** [comment] 2015-02-09 22:41
Steps to reproduce?

**Comment by Antrikshy** [comment] 2015-02-09 22:43
I think it happens when user has no points etc. This happens on an admin account, fresh install. At the very least, we shouldn't have the horizontal lines because they're ugly.

**Comment by aronasorman** [comment] 2015-02-10 20:48
duplicate of https://github.com/learningequality/ka-lite/issues/3000

**Closed** 2015-02-10 20:48 UTC
