### ISSUE TITLE
Videos/subtitles not displayed in some browsers (including Firefox)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4993] opened 2016-03-14 14:57 UTC
## Summary

Confirmed on both Beta2 in Ubuntu & build 176 on Windows XP. Windows 8.1 displays video but do not load subtitles. IE11 also has problems with subs, but does display video. Chrome does everything :+1: 

@MCGallaspy 
## Branch or installer method

Beta2 in Ubuntu & build 176 on Windows 
## Traceback or relevant snippet from server.log

Win8 console error.

```
TypeError: w.default.WebVTT.StringDecoder is not a function
require<[581]</</</<[127]</x()  bundle_video.js:16
require<[581]</</</<[127]</O/</<()  bundle_video.js:16

```
## Screenshots

Win XP
![ie8 - winxp ready for ka lite running - oracle vm virtualbox_258](https://cloud.githubusercontent.com/assets/1457929/13747789/44100756-e9fa-11e5-8da4-de3c25eced69.png)

Win8.1
![ie11 - win8 1 ready for ka lite running - oracle vm virtualbox_290](https://cloud.githubusercontent.com/assets/1457929/13748187/0fd3559a-e9fc-11e5-98a8-79e6ed398629.png)

Ubuntu 14.04
![ubuntu 14 04 ready for ka lite running - oracle vm virtualbox_282](https://cloud.githubusercontent.com/assets/1457929/13748230/32202d94-e9fc-11e5-9cb5-0764afc07e1c.png)

**Comment by MCGallaspy** [comment] 2016-03-14 17:07
Just to be clear, you seem to be experiencing two separate errors. In some browsers videos don't work *at all* (with the error `Specific "type" attribute of "video/mp4"...`) and in some the video does work but subtitles do not. I suspect this is a browser compatibility issues rather than some os-specific problem. Can you indicate which browser+version you receive each particular error in?

**Comment by radinamatic** [comment] 2016-03-14 19:32
The above errors are all in latest version (44?) of Firefox @MCGallaspy, in Chrome everything works, and I still have to figure out how to debug stuff in IE :rage4:

**Comment by radinamatic** [comment] 2016-03-14 19:46
0.16 branch on Ubuntu 14.04 - Firefox 45:

![ubuntu 14 04 0 16 beta2 running - oracle vm virtualbox_291](https://cloud.githubusercontent.com/assets/1457929/13757624/b1d20728-ea25-11e5-8c69-24f5d6d593c9.png)

```
Specified "type" attribute of "video/mp4" is not supported. Load of media resource /content/y2-uaPiyoxc.mp4 failed. counting-with-small-numbers
All candidate resources failed to load. Media load paused.
```
@MCGallaspy

**Comment by radinamatic** [comment] 2016-03-14 19:52
Weird, now I'm getting the same error on Chromium too:

![ubuntu 14 04 0 16 beta2 running - oracle vm virtualbox_292](https://cloud.githubusercontent.com/assets/1457929/13757816/9390034a-ea26-11e5-8bbd-bc36b309917e.png)

It was working on Beta2 yesterday... :disappointed:

**Comment by radinamatic** [comment] 2016-03-14 20:15
I installed that `gstreamer0.10-ffmpeg` package (`media.gstreamer.enabled` config was already `true`), even restarted the VM, and I'm still getting the same errors as before on FF, while on Chromium it's different now:

![ubuntu 14 04 0 16 beta2 running - oracle vm virtualbox_293](https://cloud.githubusercontent.com/assets/1457929/13758414/ab97a666-ea29-11e5-8824-06cb61a85843.png)

And my favorite Chrome extension erases all cache and reloads - it didn't help either... :(

**Comment by radinamatic** [comment] 2016-03-14 20:44
Virtually identical errors in XP VM (still on my 0.16 branch through LAN):

Firefox
![ie8 - winxp ready for ka lite running - oracle vm virtualbox_294](https://cloud.githubusercontent.com/assets/1457929/13759265/ca2a9602-ea2d-11e5-940c-24cae5a59e76.png)


Chrome
![ie8 - winxp ready for ka lite running - oracle vm virtualbox_295](https://cloud.githubusercontent.com/assets/1457929/13759278/d201439e-ea2d-11e5-82a0-f4bb6259b4e5.png)

**Comment by MCGallaspy** [comment] 2016-03-14 21:21
Still not sure about the videojs error -- it's definitely occurring because the subtitle resource returns 404, but I don't know why that should be the case.

However with the `Specified "type" attribute of "video/mp4" is not supported...` error it is almost certainly that your browser doesn't have a fallback for mp4 content. Try installing the flash plugin or the [vlc plugin](http://packages.ubuntu.com/trusty/browser-plugin-vlc) on Ubuntu. On Windows XP, try to determine if a fallback exists for that content type and try installing one if it doesn't.

**Comment by radinamatic** [comment] 2016-03-14 21:36
Ok, will investigate if installing these fallback plugins solves the issue. I'm setting up a fresh Ubuntu 15.10 VM to test from scratch.

**Comment by MCGallaspy** [comment] 2016-03-15 20:16
Current efforts can be tracked in https://github.com/learningequality/ka-lite/pull/4996

This appears to be specific to XP -- other OSes play videos just fine.

**Comment by radinamatic** [comment] 2016-03-16 00:45
Regarding Firefox playing videos on Ubuntu, on both 14.04 and 15.10, `Ubuntu restricted extras` solved the issue:

![Ubuntu restricted extras](http://www.tecmint.com/wp-content/uploads/2015/10/Install-Ubuntu-Restricted-Extras.png)

Added to [Pending to be documented](https://trello.com/c/ZIOuvz9L/42-documentation) list on Trello board.

**Comment by radinamatic** [comment] 2016-03-16 00:57
@MCGallaspy I'd transfer the screenshots regarding the `videojs` error related to `Malformed WebVTT signature` to a separate issue, let this be reserved for the "mp4/Flash on Firefox/XP" problem.

**Comment by MCGallaspy** [comment] 2016-03-16 00:59
Have you had subsequent issues with VTT files? I've seen intermittently that the requested VTT file 404s -- refreshing the page always solves it.

**Comment by radinamatic** [comment] 2016-03-16 01:05
No, I'm getting no results with refreshing, weather with or without clearing cache. I'm still viewing your fork pulled locally on my Ubuntu VMs and VTT always gives 404s.

**Comment by MCGallaspy** [comment] 2016-03-16 01:21
Have you downloaded a content pack, in that case?

**Comment by radinamatic** [comment] 2016-03-16 01:28
I already had 4 of them installed previously, and I can see the `y2-uaPiyoxc.vtt` in my `/kalite/static/srt/en/subtitles` folder.

**Comment by aronasorman** [comment] 2016-03-30 00:27
Won't fix for 0.16. Punting to 0.17.

**Comment by radinamatic** [comment] 2016-03-30 22:45
Signed installer for 0.16 on Windows 7, FF and Chrome show videos and subs OK out of the box, IE10 plays video, but does not show subs:

 
![subs-ie10_win7](https://cloud.githubusercontent.com/assets/1457929/14159972/265ec468-f68e-11e5-8ae2-6834228a41fe.png)

Not sure how to debug in IE... :unamused: 

![subs-ie10_win7-2](https://cloud.githubusercontent.com/assets/1457929/14160014/73c78d5c-f68e-11e5-98df-dc22db8849dd.png)

**Comment by amodia** [comment] 2016-04-06 10:17
Watching video on OS X El Capitan using firefox version 45.0.1 is working fine.
![screen shot 2016-04-06 at 5 33 42 pm](https://cloud.githubusercontent.com/assets/8663934/14313199/cc46c01c-fc22-11e5-8605-0ebebd39daa0.png)

I replicate this issue on ubuntu 15.10 using firefox version 45.0.1

![screen shot 2016-04-06 at 5 37 56 pm](https://cloud.githubusercontent.com/assets/8663934/14313321/8b459cd6-fc23-11e5-8d78-6fe75cf4ebcf.png)

**Comment by radinamatic** [comment] 2016-04-06 10:25
Just to sum up @amodia: you cannot see videos OK with FF45 on Ubuntu 15.10? Did you install `Ubuntu restricted extras` package?

![Ubuntu restricted extras](http://www.tecmint.com/wp-content/uploads/2015/10/Install-Ubuntu-Restricted-Extras.png)

**Comment by amodia** [comment] 2016-04-06 10:58
@radinamatic: Yes, it fixed the issue I just install `Ubuntu restricted extras` package.

![screen shot 2016-04-06 at 6 54 34 pm](https://cloud.githubusercontent.com/assets/8663934/14314341/3e9fcd42-fc29-11e5-82ba-ac85922f1164.png)

**Comment by djallado** [comment] 2016-04-06 11:04
Confirmed. I installed `Ubuntu restricted extras` package and I can now view video in FF.
I'm using FF version 45.0.1.
![ubuntu-resticted-extras](https://cloud.githubusercontent.com/assets/8664071/14314484/fb9b475a-fc29-11e5-8a0e-7524853489b3.png)

**Comment by benjaoming** [comment] 2016-06-13 12:27
Related: #5125 

We should consider switching to a different player/polyfill, possibly Webshim.

https://afarkas.github.io/webshim/demos/

**Comment by benjaoming** [comment] 2016-10-22 10:44
@radinamatic seems this issue is being mixed up with restricted-extras, which we have documented that people need to install.

However, it seems there was also an issue on XP. Could you confirm it and narrow it down so we can add it "Known Issues" and perhaps move one to a fresh issue with less confusing input? :)

**Comment by radinamatic** [comment] 2016-12-08 13:03
@benjaoming I agree we could close this. The following **Known issues** are still valid for 0.17:

- Viewing subtitles on Ubuntu requires ubuntu-restricted-extras
- On Windows XP you must use Chrome in order to view videos

**Closed** 2016-12-17 01:43 UTC
Labels: browser compatibility, bug, has PR, release blocker
