### ISSUE TITLE
Coach report: Unable to select topic/report

### ISSUE THREAD

**Issue by tk21** [learningequality/ka-lite#3048] opened 2015-02-14 00:54 UTC
Branch: develop
Expected Behavior: Be able to select a topic from the dropdown menu, or a report
Current behavior: Unable to select a topic from the drop down menu :( Drop down menus for "Select Report" and "Select Topic" are unresponsive.

Steps to reproduce:
1. Log in as coach
2. Go to reports
3. Attempt to 'select report'/'select topic'

**Comment by cpauya** [comment] 2015-02-19 09:41
The "Select Topic" can only be selected by selecting the "Tabular Report" then clicking the `Go` button.

It is working as intended, as per the latest `develop` branch, so I'm closing this issue now.

Please re-open if issue is still there.

**Closed by cpauya** 2015-02-19 09:41 UTC

**Comment by tk21** [comment] 2015-02-19 18:08
This occurs after attempting to switch between tabular/scatter/timeline report multiple times. Currently unable to test this as I am on a work machine, but it either happens after switching between the three reports or having KA Lite open for a while. Will test this out again soon.

**Comment by MCGallaspy** [comment] 2015-02-19 18:14
@tk21 let me know if you're able to replicate.
