### ISSUE TITLE
Permissions error during language pack download

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#3976] opened 2015-07-02 21:27 UTC
Branch: 0.14.x
Platform: Ubuntu
Installer: .deb

Expected behaviour: Language pack download should complete successfully.
Current behaviour: Language pack download results in a permissions error.

![image](https://cloud.githubusercontent.com/assets/1680573/8488294/6b6b0fec-20c6-11e5-87fe-87f76424ff7a.png)

**Comment by aronasorman** [comment] 2015-07-03 16:24
Despite being filed earlier, i'm closing this as a duplicate of https://github.com/learningequality/ka-lite/issues/4003#issuecomment-118376578 since there's more discussion in there.

You get points for filing earlier though.

**Comment by rtibbles** [comment] 2015-07-03 16:38
As long as I get my Bug Bash Points™ I am fine with this.

**Comment by aronasorman** [comment] 2015-07-03 17:43
Reopening so my script can count this.

**Comment by benjaoming** [comment] 2015-07-05 23:40
It's counted, right? :)

**Closed by benjaoming** 2015-07-05 23:40 UTC
Labels: 0.14.x bug bash, bug
