### ISSUE TITLE
Possible server crash after cookie expiration

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4528] opened 2015-09-28 22:51 UTC
On 0.15 while testing the latest MAC develop release while logged into a fresh installation as admin, I was distracted by a google voice call lasting well over the 30 minutes of expiration time the session cookie allows the admin login. During the call I noticed the browser had become unresponsive and afterwards crashed. Closing the browser I notification flashed that the ka-lite server had started although it was already started and I was logged in earlier. Seems @rtibbles may have a clue what is happening so tagging him and @cpauya on this one? Screenshot one shows the state of the browser before expiration and the second notification of the crash. I did have several other tabs open but the Activity Monitor did not show an overload on the system? 

![2015-09-28_11-15-02](https://cloud.githubusercontent.com/assets/4349806/10151076/2124ae4a-6601-11e5-9f1c-c3f1a8ed0d1e.png)

![2015-09-28_15-26-12](https://cloud.githubusercontent.com/assets/4349806/10151082/2ad13184-6601-11e5-8c00-0f221b6eea38.png)

**Comment by rtibbles** [comment] 2015-09-28 22:55
My assumption is that this is related to some long running Javascript process that eventually causes an issue (possibly on cookie expiry, or possibly just due to bloating the memory). Would be good to track down, so that our front end code doesn't kill itself.

**Comment by aronasorman** [comment] 2015-09-28 23:02
Is this the first time this happened recently @EdDixon?

**Comment by EdDixon** [comment] 2015-09-28 23:36
First time I have ever seen a crash like this, definitely yes.

**Comment by EdDixon** [comment] 2015-09-30 15:22
Despite a lot of testing, I have not been able to replicate this since that first reported occurrence.

**Comment by benjaoming** [comment] 2015-09-30 16:00
Okay but I'm removing the Mac label, because there's no "Mac"-related issues anymore... if you can only create it on a Mac, it's a browser issue or an issue with the installer. I can see that it's something with the JavaScript crashing, so supposing it's a browser issue is a good start :)

**Comment by rtibbles** [comment] 2015-09-30 16:04
I wouldn't call it Browser Compatibility either, as that implies that it is failing to work properly on a particular browser.

**Comment by aronasorman** [comment] 2015-10-05 16:50
@EdDixon any updates on reproducing this behaviour?

**Comment by EdDixon** [comment] 2015-10-08 20:55
Regretfully no and now that I cannot install on the current version of OSX to continue testing for this I may not be able to add much about the MAC issues here but I am replicating consistently other issues with the cookie expiration which could be related? I am looking to see f we have any issues open about that yet and ran across this one. I will either create an issue about it or update current as soon as I find one here.

**Comment by aronasorman** [comment] 2015-10-12 17:37
Closing this, until we have concrete reproducible steps.

**Closed by aronasorman** 2015-10-12 17:37 UTC
Labels: bug
