### ISSUE TITLE
Questions are not loading for few exercises - Version 0.16.5

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5119] opened 2016-05-17 06:08 UTC
## Summary
Questions for the following exercises are not loading:
1. Math ---> Grade 7 (NCERT) --> Chapter 12: Algebraic Expression --> How are expressions formed? --> Writing expressions with variables
2. Math --> Grade 7 (NCERT) --> Chapter 1: Integers --> Division of integers --> Multiplying & dividing negative numbers.
. Math >Pre-algebra >Measurement > Area> Basics> Area of sqaure and rectangle (excercise)
4. Math> Arithmetic> Negative numbers and absolute value> Multiplying and Dividing negative number> Multiplying and Divind negative number (excercise)
5. Math>Arithmetic> Decimals > Adding and subtracting decimals > Subtracting decimals (tenths)
6. Math > Pre-algebra> Decimals > Intro to percentage > Finding percentage
7. Math > Pre-algebra > Arithmetic Properties > Order of Operations > Order of operations (excercise)
8. Math > Pre-algebra > Arithmetic Properties > Order of Operations > Order of operations with negative numbers
9. Math > Geometry > Tools of geometry > Point, line & planes > Point, line and planes (exercise)
10. Math> Algebra basic > Linear equations and inequalities > Ratios and proportions > Writing proportions (exercise)
11. Math > Algebra 1 > introduction to Algebra > writing algebriaic expressions introduction > Writing expression with variables (exercise) 
12. Math > Geometry > Perimeter, area and volume > Area and circumference of circles > Shaded area (exercise)
13. Math > Basic Geometry > Lines > Measuring segments > Measuring segments (exercise)

## Branch or installer method
OS: Ubuntu version 14.04 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup"
Version: 0.16.5
assessment file: en.zip

## How to reproduce

1. Access all the exercises mentioned above.

2. Questions are not loading, even after refreshing page multiple times.

## Screenshots
![screenshot from 2016-05-17 11_17_29](https://cloud.githubusercontent.com/assets/13453618/15312660/bccd6354-1c23-11e6-8e50-138d1e0d2907.png)
![screenshot from 2016-05-17 11_36_06](https://cloud.githubusercontent.com/assets/13453618/15312659/bc632d18-1c23-11e6-96b8-1b8aadb5e8a7.png)

**Comment by benjaoming** [comment] 2016-05-17 16:21
Confirmed. Apparently a javascript error occurs. Assigning @rtibbles for more clarification.

```
TypeError: this.props.hints is undefined
require<[74]</</</l<.render()
 bundle_exercise.js:747
require<[514]</</ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext()
 bundle_exercise.js:438
require<[514]</</ReactCompositeComponentMixin._renderValidatedComponent()
 bundle_exercise.js:438
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[514]</</ReactCompositeComponentMixin.mountComponent()
 bundle_exercise.js:438
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[560]</ReactReconciler.mountComponent()
 bundle_exercise.js:481
require<[514]</</ReactCompositeComponentMixin.mountComponent()
 bundle_exercise.js:438
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[560]</ReactReconciler.mountComponent()
 bundle_exercise.js:481
mountComponentIntoNode()
 bundle_exercise.js:410
require<[588]</</Mixin.perform()
 bundle_exercise.js:472
batchedMountComponentIntoNode()
 bundle_exercise.js:410
require<[529]</ReactDefaultBatchingStrategy.batchedUpdates()
 bundle_exercise.js:271
batchedUpdates()
 bundle_exercise.js:467
require<[548]</</ReactMount._renderNewRootComponent()
 bundle_exercise.js:410
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[548]</</ReactMount._renderSubtreeIntoContainer()
 bundle_exercise.js:410
require<[548]</</ReactMount.render()
 bundle_exercise.js:410
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[74]</</</m<.update()
 bundle_exercise.js:747
<anonymous>
 self-hosted:749
require<[74]</</</m<.componentDidMount()
 bundle_exercise.js:747
require<[482]</</<.notifyAll()
 bundle_exercise.js:477
require<[559]</ON_DOM_READY_QUEUEING.close()
 bundle_exercise.js:227
require<[588]</</Mixin.closeAll()
 bundle_exercise.js:472
require<[588]</</Mixin.perform()
 bundle_exercise.js:472
batchedMountComponentIntoNode()
 bundle_exercise.js:410
require<[588]</</Mixin.perform()
 bundle_exercise.js:472
require<[529]</ReactDefaultBatchingStrategy.batchedUpdates()
 bundle_exercise.js:271
batchedUpdates()
 bundle_exercise.js:467
require<[548]</</ReactMount._renderNewRootComponent()
 bundle_exercise.js:410
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[548]</</ReactMount._renderSubtreeIntoContainer()
 bundle_exercise.js:410
require<[548]</</ReactMount.render()
 bundle_exercise.js:410
require<[554]</</ReactPerf.measure/a()
 bundle_exercise.js:561
require<[68]</</Exercises.PerseusBridge.render_item()
 bundle_exercise.js:26
require<[70]</</ExerciseView<.render_perseus_exercise/<()
 bundle_exercise.js:7
require<[414]</</<.Deferred/r.then/</</<()
 bundle_common.js:808
require<[414]</</Z.Callbacks/c()
 bundle_common.js:808
require<[414]</</Z.Callbacks/f.add()
 bundle_common.js:808
require<[414]</</<.Deferred/r.then/</<()
 bundle_common.js:808
require<[414]</</<.each()
 bundle_common.js:807
require<[414]</</<.Deferred/r.then/<()
 bundle_common.js:808
require<[414]</</<.Deferred()
 bundle_common.js:808
require<[414]</</<.Deferred/r.then()
 bundle_common.js:808
require<[70]</</ExerciseView<.render_perseus_exercise()
 bundle_exercise.js:7
<anonymous>
 self-hosted:755
require<[133]</</</p/t[e]<()
 bundle_common.js:801
require<[661]</</m.before/<()
 bundle_common.js:805
require<[133]</</</_()
 bundle_common.js:801
require<[133]</</</m()
 bundle_common.js:801
require<[133]</</</d()
 bundle_common.js:801
require<[133]</</</c.trigger()
 bundle_common.js:801
require<[133]</</</<.fetch/t.success()
 bundle_common.js:801
require<[414]</</Z.Callbacks/c()
 bundle_common.js:808
require<[414]</</Z.Callbacks/f.fireWith()
 bundle_common.js:808
n()
 bundle_common.js:809
require<[414]</</</<.send/t/<()
 bundle_common.js:809
```

**Comment by benjaoming** [comment] 2016-05-17 16:23
Thanks for a good report, @harishbalachandran :)

**Comment by harishbalachandran** [comment] 2016-06-03 06:06
[https://github.com/learningequality/ka-lite/issues/5130](url)

Linking the defects

**Comment by harishbalachandran** [comment] 2016-06-03 06:07
#5130

**Comment by aronasorman** [comment] 2016-06-08 19:58
Hi @harishbalachandran,

Thanks for reporting these. While I was debugging the issue related to the missing topic in Grade 6 (NCERT), I installed the latest english content pack. I tried replicating this issue with the said content pack, and wasn't able to.

@harishbalachandran can you try it out on your side and see if it fixes things? First, download the bleeding edge english content pack here: http://dungeon.learningequality.org/artifact/CP-KL/shared/build-179/English-content-pack/en.zip

then install it using this command:

```
kalite manage retrievecontentpack local en <path to en.zip>
```

That should update your Khan Academy exercises. Can you check then if that fixes your issue? If it does, then the KA Lite team should discuss whether it's worth updating the english content pack.

**Comment by aronasorman** [comment] 2016-06-08 22:00
Actually, never mind. I may have spoken too early. I can replicate this on my side after clearing Firefox's cache.

**Comment by aronasorman** [comment] 2016-06-08 22:07
Whoops, wrong issue. I was referring to #5131 -- I too have no textbox when answering questions. The questions listed here work properly for me.

So @harishbalachandran, please continue with installing the content pack with the instructions above, and see if it solves this issue.

**Comment by benjaoming** [comment] 2016-06-08 23:07
1: works
2: works
3: works
4: works
5: works
6: works
7: works
8: works
9: works
10: works
11: works
12: works
13: works

100% works!!

Big thanks to @harishbalachandran for a clear list.

@aronasorman now that I've tested and can report that all of the 13 exercises reported to fail are working again, would you feel safe about publishing the build above? :)

**Comment by aronasorman** [comment] 2016-06-09 00:18
Thanks for testing @benjaoming! @rtibbles @jamalex @cpauya @harishbalachandran @radinamatic if there are no issues on doing so by Thursday afternoon, I'll update `en.zip` and `en-minimal.zip` on pantry Friday morning. Then people can reinstall their respective full installers to fix this bug.

**Comment by radinamatic** [comment] 2016-06-09 00:31
I'll definitely confirm this by Thursday afternoon PT! 👍

**Comment by radinamatic** [comment] 2016-06-09 16:08
Confirming all the reported exercises fixed with the latest `en.zip` in KA Lite 0.16.5 on Ubuntu 16.04 and Windows 7! You can proceed with updating the files in pantry @aronasorman... 😃

**Comment by benjaoming** [comment] 2016-06-09 20:20
@aronasorman remember the legacy khan_assessment.zip ;)

**Comment by radinamatic** [comment] 2016-06-09 20:30
@benjaoming Could you describe the correct test case steps for testing the legacy `khan_assessment.zip`?

**Comment by benjaoming** [comment] 2016-06-09 20:34
@radinamatic once it's build, should be like this:

1) Install pre-release into clean environment (delete .kalite) `pip install ka-lite --pre`
2) Download khan_assessment.zip from where @aronasorman puts it
3) `kalite manage unpack_assessment_zip location_of.zip`
4) `kalite start`

**Comment by aronasorman** [comment] 2016-06-09 20:36
You can find `khan_assessment.zip` here, along with `en.zip` and
`en-minimal.zip`:
http://dungeon.learningequality.org/browse/CP-KL-182/artifact/shared/English-content-pack/

Although the bug here seems to be in the assessment item data itself, not
the images, so you'll need to install an updated `en-minimal.zip` as well.

**Comment by benjaoming** [comment] 2016-06-09 20:41
Good call, @aronasorman, the wrong (old) en-minimal is bundled into the current pre-release. I'll make a new one.

**Comment by harishbalachandran** [comment] 2016-06-10 12:50
Retested with the latest content pack provided by @aronasorman , all the exercises are working fine. 

Thank you so much for fixing this!!

**Comment by benjaoming** [comment] 2016-06-10 22:51
@radinamatic quick note that a new prerelease is up with a built-in en-minimal, same as @aronasorman 's test build.

**Comment by quozl** [comment] 2016-06-10 22:58
> a new prerelease is up with a built-in en-minimal

Where?  I looked on installation guide and the Launchpad PPA but nothing new.

**Comment by benjaoming** [comment] 2016-06-11 17:36
Hi @quozl this prerelease is on PyPi, sorry for being unclear. You can install it like this: `pip install --pre ka-lite`

**Comment by aronasorman** [comment] 2016-06-13 23:33
Uploaded the new content pack files!

In case anyone wants to update their installation's content pack, you can do so by running this line:

```
kalite manage retrievecontentpack download en
```
Make sure you have the same permissions as the one that installed KA Lite. Otherwise, just wait for the 0.16.6 installers!

**Closed by aronasorman** 2016-06-13 23:33 UTC
Labels: content / perseus
