### ISSUE TITLE
Show scratchpad button does not work sometimes

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3096] opened 2015-02-23 21:55 UTC
1. Go to an exercise.
2. Open scratchpad to confirm it works.
3. Go to another exercise.
4. Attempt to open scratchpad and be surprised.

Reload page to make it work again.

Related: After switching exercises, the show hints button seems to misbehave (even goes to -1 hints).

**Comment by MCGallaspy** [comment] 2015-02-23 21:59
Are you able to open the scratchpad on a different exercise after refresh? You're sure it's not an issue of the scratchpad simply not being available for that exercise?

**Comment by Antrikshy** [comment] 2015-02-23 22:01
Yep. This seems to affect all exercises. Also, if there are exercises with no scratchpad support, it would be nice to disable the scratchpad button on them.

**Comment by MCGallaspy** [comment] 2015-02-23 23:37
I'm labeling this as high priority since it could potentially prevent learners from completing exercises normally.

**Comment by MCGallaspy** [comment] 2015-02-24 01:02
I think the problem is that a listener is attached to the `#scratchpad-show` button, but a new such button is created on a backbone navigation event without attaching a listener.

**Comment by MCGallaspy** [comment] 2015-02-24 01:18
Plot twist: the listener is registered twice and thus clicking the button calls the scratchpad visibility toggling function twice.

**Comment by Antrikshy** [comment] 2015-02-24 01:27
That is hilarious.

**Comment by rtibbles** [comment] 2015-02-26 01:15
Fixed in #3117 .

**Closed by rtibbles** 2015-02-26 01:15 UTC
Labels: bug, high priority
