### ISSUE TITLE
KA Lite start at boot does not work on Windows.

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#2926] opened 2015-01-30 23:30 UTC
I've installed KA Lite on Windows XP and Win 7 and never been able to get KA Lite to start automatically on boot. There are frequent power outages and this function is really important to us at VIrginia DOC.

In our pilot, I've installed servers running both WIndows and Linux. Running Linux this works perfectly. Is this a known issue?

**Comment by benjaoming** [comment] 2015-02-03 07:03
Hi @waltonrp, did you install from the windows installer or from github, and that case the master or develop branch?

**Comment by waltonrp** [comment] 2015-02-03 10:42
Installed via the downloaded installer.

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by benjaoming** [comment] 2015-02-03 19:28
Okay so maybe @ruimalheiro knows more or can tell you how to retrieve debug info.

**Comment by ruimalheiro** [comment] 2015-02-03 20:50
Hi @waltonrp !

Thanks for reporting that. When you set the option, to autostart, what happens? Is there any error? You should see a promt asking for admin password. Are you using the latest version of KA Lite installer?

**Comment by waltonrp** [comment] 2015-02-19 11:36
Sorry for the delay in answering. No error. It does not ask for password

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by EdDixon** [comment] 2015-02-24 10:49
Maybe tied to issue 3116 involving line feeds on windows installer which many DOC users are forced to use (no internet access). Git appears to pull the files with proper formatting.

**Comment by waltonrp** [comment] 2015-02-24 10:57
I'm not sure what you mean, Ed. When I install, I do so out of facility, so the machine has Internet connectivity.

**Comment by EdDixon** [comment] 2015-02-24 11:10
Your one of the lucky ones able to do that then :) so have tried installing using IT? I feel that may help resolve the issue (hopefully). Can you look at the bat files in the scripts folder and see if they look ok? The ones creating problems will have little squares when viewed using notepad or wordpad. Like this: https://github.com/learningequality/ka-lite/issues/3116 on the left is what they should look like on the right is what happenes when installed right now using the windows installer. https://github.com/learningequality/ka-lite/issues/3116

**Comment by waltonrp** [comment] 2015-02-24 11:12
I’m not sure what you mean IT?

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by EdDixon** [comment] 2015-02-24 11:15
Sorry I meant GIT which is a source code repository manager which can also be used to install KA-Lite. But if you give us a little time here I think we can fix the installer which will be a better fix for many other DOC's out there and easier for your team to manage internally once deployed.

**Comment by waltonrp** [comment] 2015-02-24 11:18
Okay, thanks, I’m IT so was confused. Checking that script file…

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by waltonrp** [comment] 2015-02-24 11:39
Here's a screen shot
![cronstart](https://cloud.githubusercontent.com/assets/9379591/6348659/cbaae6fc-bbef-11e4-881d-0bfb0b163a1b.jpg)

**Comment by EdDixon** [comment] 2015-02-24 11:43
That one file is just an example of many that will need to be fixed on our part here. This one bug corrected should resolve many issues but starting the KA-Lite program on reboot is one that is for sure directly related to this. Is word wrap turned on in that capture? Odd that I do not see the LF's but also that there are no line breaks in that batch file which would still corrupt it? Also, just sent an email regarding some of this... But yea what you have there wont work either and is most likley related to what I am reporting to the team here.  Thanks we should have this sorted soon!

**Comment by waltonrp** [comment] 2015-02-24 11:45
I had to turn on word wrap

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by benjaoming** [comment] 2015-02-26 07:36
I can't fix this now, but suggesting someone to do this from a Linux
machine...

    cd scripts
    sed -i 's/$/\r/' *bat

This adds the CR character to the end of all lines so Windows will
understand.. I don't know if this actually causes any issues with the
scripts.

**Comment by MCGallaspy** [comment] 2015-02-28 02:29
I'm not convinced this issue has anything to do with linefeeds. I just installed on XP (grabbed the installer from http://learningequality.org/downloads/KALiteSetup-0.13.0.exe, 2/27/15) and got the following error:
![ss](https://cloud.githubusercontent.com/assets/8888020/6424443/77c51e42-beae-11e4-96a7-1cff52d52abc.png)
So maybe it's just an issue with the way the installer is invoking the script?

**Comment by MCGallaspy** [comment] 2015-02-28 02:45
Running the script from cmd.exe works (or double clicking in explorer), but the service fails to start on XP if the user doesn't have a password.

**Comment by MCGallaspy** [comment] 2015-02-28 02:50
Service still fails to start on XP, even when the user has a password.

**Comment by EdDixon** [comment] 2015-02-28 03:00
I agree, after having done more testing here, I do not feel it is related
to the line feeds alone although I would still prefer properly formatted
scripts because I can not be 100% sure its still not a part of the cause as
is. As we discussed earlier today though there are other factors in how
this installer was built that generated the line feeds that I now feel may
be a larger part of the issue. Particularly the differences in terms of how
wine expects Windows to be configured and the particular version of Windows
the installer ends up running on.

Hope this helps!

On Fri, Feb 27, 2015 at 7:50 PM, Michael Gallaspy <notifications@github.com>
wrote:

> Service still fails to start on XP, even when the user has a password.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/2926#issuecomment-76506515>
> .
>



-- 
Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE <https://learningequality.org/give/>, Support FLE via Amazon
Smile! <http://smile.amazon.com/ch/46-2676188>
M (575)-636-9549

**Comment by ruimalheiro** [comment] 2015-02-28 14:02
Hello everyone, sorry about the late reply. I have been super busy these days and had no time to dig in the issue.

So, I've run a test under windows 7 (By choosing the option in the tray menu), and it worked properly. 

@MCGallaspy , could you try this please? The issue can be related with the installer. Btw, that script requires admin privilledges,


![image](https://cloud.githubusercontent.com/assets/1102381/6426431/67c1c87a-bf52-11e4-9597-192502cf78cc.png)


![image](https://cloud.githubusercontent.com/assets/1102381/6426433/751ac4cc-bf52-11e4-98b8-a13e9f029f44.png)
.

**Comment by ruimalheiro** [comment] 2015-02-28 14:04
@EdDixon any chance you can run a test under windows XP?

**Comment by ruimalheiro** [comment] 2015-02-28 14:09
Removal should prompt:

![image](https://cloud.githubusercontent.com/assets/1102381/6426455/5389ba56-bf53-11e4-8784-3e8aac5f3b3d.png)


NOTE: It will not ask for password but it requires the user to be Admin for both: Registering the task and removing the task.

**Comment by MCGallaspy** [comment] 2015-03-02 23:37
Trying to use the system tray icon gives me the same file association error in XP.

**Comment by cpauya** [comment] 2015-03-08 06:17
I just tested this on an [IE8 on Windows 7 Enterprise virtual box](https://www.modern.ie/en-us/virtualization-tools) using the Windows installer from the [Install Guide](https://learningequality.org/ka-lite/user-guides/install-guide-012) and can confirm that enabling the "Run KA-Lite at system start-up" option did not work.

No error is displayed, the prompt also shows when I enable or disable the option.  So, I have to launch the app after a restart even when the option is enabled.  Also, the user is already an administrator so there was no prompt for a password.

I have other versions of the above VMs and will try them next.

@ruimalheiro I have no "Options" menu when I right-click on the systray icon, may I know what installer did you use?

Screenshot .gif
![ka-lite-2](https://cloud.githubusercontent.com/assets/175580/6544830/8cafc56e-c59d-11e4-8ce1-146f983d6c08.gif)

**Comment by cpauya** [comment] 2015-03-08 06:27
Oh, when I check the "Options -> Run KA Lite when the user log" (I think that should be login?) - this actually works when I restart.  That could be another work-around?

**Comment by cpauya** [comment] 2015-03-08 07:49
I have tested on most variants of Windows 7 (from modern.ie) and the "Options -> Run KA-Lite at system start-up" option do not work.  Whether it's set upon installation or on the KA-Lite options menu.

The work-around solution for @waltonrp is to use the "Options -> Run KA Lite when the user log" option (which would require the Windows auto-login feature to run KA-Lite when power black-outs happen).  That is, until we have identified the root cause of this under Windows 7.

**Comment by EdDixon** [comment] 2015-03-08 10:04
Thank you for getting on this @cpauya  and @MCGallaspy and @ruimalheiro  in corrections we often have power outages for testing emergency generators and such and this needs to be a reliable option. Sorry my medical stuff has prevented me from going the distance on this one but hopefully I can become part of the solution now that you have found a way to mitigate the cause temporarily. I will start next week on testing the XP version and the associated browser trouble @waltonrp is reporting on all those environments. I notice several of the screen shots are showing KA-Lite 0.12 but in a conversation related to this last week @mike was recommending we fix this for 0.13 since as we are near release on that version anyway and gaining other known fixes in that release for this particular deployment. You mention the user is running as administrator but this would be the only platform I am aware of where we are finding a need to elevate the user privileges and could be a part of the cause of the problems where pathing is concerned which I feel is likely due to how it was built pointing back to building this in wine which is also causing the line feed issues. I will try rebuilding the installer for 0.13 again with the complete pack of assessments for these tests using the VS express method as recommended to see if that turns out to be the case. In a typical GIT install the installer batch file usually fails when attempts are made to run as admin under windows. Thank guys so much for your help with this!

**Comment by ruimalheiro** [comment] 2015-03-08 12:22
@cpauya , I used 0.13

**Comment by cpauya** [comment] 2015-03-09 02:32
Thanks for your feedback @EdDixon and @ruimalheiro.  

Here's a link to the latest [ka-lite windows installer for 0.13.x](https://learningequality.org/downloads/KALiteSetup-0.13.0.exe) from @aronasorman.  I didn't find any link to it so thought I'd put it here instead.

**Closed** 2015-03-14 00:02 UTC
Labels: bug, Windows
