### ISSUE TITLE
My Progress show error message when learner has 0 points

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4662] opened 2015-11-10 23:37 UTC
branch: develop
OS: Mac
reproduce: create a new student account and go to "My Progress" with 0 point, you will see this scary error message
![screen shot 2015-11-10 at 3 31 46 pm](https://cloud.githubusercontent.com/assets/5577205/11079336/635f34c0-87c0-11e5-9c7a-5cef17957681.png)

expected behavior: should not see anything

**Comment by shubhsingh594** [comment] 2016-02-08 14:05
I would like to work on this issue.
I also noticed that this issue has been resolved in the branch - 0.15.x

**Comment by MCGallaspy** [comment] 2016-02-08 22:04
If it's resolved, then there's nothing to work on! Can you identify the PR that should close this?

**Comment by MCGallaspy** [comment] 2016-02-08 22:09
I did a cursory search for the closing PR, couldn't find it -- we'll re-open this issue if it comes up again.

**Comment by shubhsingh594** [comment] 2016-02-08 23:01
although the issue seems to be resolved in the branch - 0.15.x ( i wasn't able to reproduce the error and was getting the required blank progress report). The problem still persists in the branch - 0.16.x .

**Comment by shubhsingh594** [comment] 2016-02-09 15:09
i have submitted a pull request to the develop branch https://github.com/learningequality/ka-lite/pull/4825 
@MCGallaspy  @66eli77 , please review the code and suggest changes. thankyou :)

**Comment by radinamatic** [comment] 2016-02-26 00:45
Original issue fixed in #4832, tested on both Alpha4 deb on Ubuntu & build 150 on W7. 

However, while testing I found a curious thing: message for the user appears on both FF & Chromium on Ubuntu, and Chrome on Windows, but is missing on FF on Windows:

![workspace 1_002](https://cloud.githubusercontent.com/assets/1457929/13339545/dec13434-dc29-11e5-9737-b7a7928cf3f0.png)

(Win screenshot coming)

Heading "Progress report" seems to load at first, but then disappears as the message for the user is displayed. This might be an a11y issue, so even if there's nothing to report, I believe page H1 should appear above the user message.

Filing all this as a separate issue.

**Closed** 2016-02-29 23:03 UTC
Labels: bug
