### ISSUE TITLE
IE9 Javascript issues

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4572] opened 2015-10-05 21:42 UTC
On `0.15.x`, using the windows installer, IE9/Windows 7. Seems to be some js issues. Not a problem on chrome.

Logging in as admin/coach gives this js error:
`SCRIPT5007: Unable to get value of the property 'remove': object is null or undefined 
learn, line 1 character 1`

Prevents the "User" dropdown menu from functioning correctly, and also the Videos/Languages/Facilities tabs don't appear on user management page.

**Comment by rtibbles** [comment] 2015-10-05 21:52
This is caused by this non-jQuery DOM manipulation:

https://github.com/learningequality/ka-lite/blob/0.15.x/kalite/distributed/static/js/distributed/user/views.js#L529

```classList``` is *not* supported by IE9.

**Comment by rtibbles** [comment] 2015-10-07 17:45
Fixed in #4573

**Closed by rtibbles** 2015-10-07 17:45 UTC
Labels: browser compatibility, has PR
