### ISSUE TITLE
Cherrypy gives wrong HTTP header content-type for well-known MIME types

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5233] opened 2016-08-01 15:37 UTC
## Summary

Exercise `/math/early-math/cc-early-math-add-sub-basics/cc-early-math-add-sub-intro/addition_1/` is not loading properly (not sure what): only the answer field is visible, but not the question (simple 1+2).

I checked both English and Spanish versions, the issue appears on all browsers (Crome, FF & IE11), tried reloading and restarting the server, just in case, no dice.

## Branch or installer method

 - Installer: Windows 0.16.7 build 302 on Win 7

## Traceback or relevant snippet from server.log

Nothing visible in the console. 

## How to reproduce

1. Login as Learner
1. Go to fist exercise in the Early math - Intro to Addition & Subtraction

#### FF
![ie11 - win7 ready running - oracle vm virtualbox_587](https://cloud.githubusercontent.com/assets/1457929/17299234/cb54dabc-580d-11e6-993b-a62d839052af.png)

#### Chrome
![ie11 - win7 ready running - oracle vm virtualbox_588](https://cloud.githubusercontent.com/assets/1457929/17299241/d3681124-580d-11e6-9447-54b86f5d684a.png)

#### IE11
![ie11 - win7 ready running - oracle vm virtualbox_589](https://cloud.githubusercontent.com/assets/1457929/17299246/daa1e92e-580d-11e6-8ba8-b4cc101cb42c.png)

## Real-life consequences 

Exercise not usable.

@benjaoming @aronasorman @arceduardvincent

**Comment by radinamatic** [comment] 2016-08-01 15:39
As expected, `early-math-add-sub-intro/subtraction_1/` has the same issue:

![ie11 - win7 ready running - oracle vm virtualbox_590](https://cloud.githubusercontent.com/assets/1457929/17299517/e9ac8fd6-580e-11e6-876d-f6b205cb0b6e.png)

**Comment by radinamatic** [comment] 2016-08-01 15:50
Another with missing image inside question area:
`/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/`

![ie11 - win7 ready running - oracle vm virtualbox_591](https://cloud.githubusercontent.com/assets/1457929/17299886/58b9b5c4-5810-11e6-94cf-75b83c0ff726.png)

**Comment by benjaoming** [comment] 2016-08-01 15:53
@radinamatic I think you need to upgrade the content packs.. running both the Spanish and English content packs, these exercises don't exist.

Could they be artifacts from previous installations on your test system?

**Comment by radinamatic** [comment] 2016-08-01 15:55
@benjaoming This is a fresh Win VM, no previous installation.

English contentpack is the one that came with the built installer, and Spanish just downloaded from the Manage - Languages, both are failing.

**Comment by radinamatic** [comment] 2016-08-01 16:13
@benjaoming You must be referring to another exercise, this one fails on Ubuntu too, the `0.16.7~b4-0ubuntu1` installer that I installed on Friday:

![ubuntu16 ready running - oracle vm virtualbox_592](https://cloud.githubusercontent.com/assets/1457929/17300659/9faad366-5813-11e6-8c36-3610080d1de2.png)

**Comment by benjaoming** [comment] 2016-08-01 16:28
Oh okay, now I get it, sorry I had a copy+paste error w/ the URL path.

I'm afraid that we have browser issues. This one renders on my system. Could you try waiting for several seconds for the page to load?

**Comment by benjaoming** [comment] 2016-08-01 16:40
Okay this works on 0.16.7b4 debian packages which were built using latest assessment.zip -- but it fails on 0.16.7 with en.zip content pack.

@aronasorman would you be able to tell about a difference between those two judging from what you seen in http://pantry.learningequality.org/downloads/ka-lite/0.16/content/ ?

I can see that khan_assessment.zip is from June 26 while en.zip is from June 16.

**Comment by benjaoming** [comment] 2016-08-01 18:12
I investigated further and made a full diff between said en.zip and khan_assessment.zip and there are no differences in the static files, sizes and names.

I can continue to investigate since it's pretty simple, I have a functional installation (0.16.7b4 w/ assessment items) and a broken one (0.16.7 pre-build with content pack downloaded and installed).

**Comment by benjaoming** [comment] 2016-08-01 18:13
@aronasorman if you have any hints at this point, it'd be greatly appreciated though :)

**Comment by radinamatic** [comment] 2016-08-01 18:14
OK, let me know then it needs testing on my side! :+1:

**Comment by benjaoming** [comment] 2016-08-01 18:25
The main concern is: Gotta figure out if this is related to content packs or the release itself...

**Comment by benjaoming** [comment] 2016-08-01 18:33
Case in question:

![screenshot from 2016-08-01 20 32 41](https://cloud.githubusercontent.com/assets/374612/17304710/34d684ae-5827-11e6-95c2-8a12ec6d42b9.png)

**Comment by radinamatic** [comment] 2016-08-01 18:34
Is that with English contentpack or assessment items zip?

**Comment by benjaoming** [comment] 2016-08-01 18:34
That's with the legacy assessment item zip which in installed while installing the .deb, ka-lite-raspberry-pi

**Comment by benjaoming** [comment] 2016-08-01 18:41
And here is 0.16.7b4 with en.zip content pack

![screenshot from 2016-08-01 20 41 10](https://cloud.githubusercontent.com/assets/374612/17304933/54ad2368-5828-11e6-89de-c16985eb9959.png)

**Comment by benjaoming** [comment] 2016-08-01 18:51
Can't recreate it, now I'm starting to worry that the issue is this:

On ka-lite-raspberry-pi, we serve static stuff with nginx and it works, but with cherrypy, I made a fix for content types,  #5218, and this is not active in the version that's working!

**Comment by benjaoming** [comment] 2016-08-01 18:57
Yup, issue found, thanks @radinamatic for being thorough!!

Correct w/ nginx:

![screenshot from 2016-08-01 20 56 50](https://cloud.githubusercontent.com/assets/374612/17305399/87c8168e-582a-11e6-8b0b-911ed7812ace.png)

Incorrect w/ Cherrypy:

![screenshot from 2016-08-01 20 56 34](https://cloud.githubusercontent.com/assets/374612/17305419/94ac1634-582a-11e6-9c58-da63a1234f7c.png)

**Comment by benjaoming** [comment] 2016-08-01 18:59
0.16.7 is hereby blocked until this is resolved... luckily no source dist has been released yet... I'll overwrite the appropriate tags since no harm has been done yet.

**Comment by radinamatic** [comment] 2016-08-01 19:08
I'd gladly take the credit, but it was pure luck that I tested those exercises today! :stuck_out_tongue: 

Makes me worry about how many of other hidden issues I don't manage to stumble upon by luck... :worried:

**Comment by radinamatic** [comment] 2016-08-01 19:11
Is it possible to have some kind of protocol for these cases, there are 20k exercises in KA channel and nowhere near time to test if they all load correctly every time we make release...

**Comment by benjaoming** [comment] 2016-08-01 19:12
Well I guess it was also lucky that I had a ka-lite-raspberry-pi installation because the nginx serving of static items is the one that indicated the content type issue... I'm still baffled as to how cherrypy with the  #5218 patch manages to get PNG content types right and then suddenly generates wrong content types for other MIMEs... I'll try to fetch a copy of Nginx's content type table and just statically copy that.

**Comment by arceduardvincent** [comment] 2016-08-01 19:47
@benjaoming and @radinamatic 
I replicate the same issue here.
![screen shot 2016-08-02 at 3 36 50 am](https://cloud.githubusercontent.com/assets/4099119/17306421/8ef97a1e-5862-11e6-9d0e-f050d2b86253.png)

**Comment by benjaoming** [comment] 2016-08-01 19:50
@arceduardvincent thanks - I guess it's fully repeatable across all browsers and platforms since it's the HTTP headers of the font .woff2 extension that's guessed wrongly.

**Comment by benjaoming** [comment] 2016-08-01 20:45
Fixed in #5234 -- I dare say it's closed because I verified stated exercise and made an extra long list of MIME types just to be sure.

**Closed by benjaoming** 2016-08-01 20:45 UTC
Labels: release blocker
