### ISSUE TITLE
Problem with multiplication exercise comparing with multiplication

### ISSUE THREAD

**Issue by tarunsharma1** [learningequality/ka-lite#3456] opened 2015-03-31 13:55 UTC
Current behaviour : gives me an error when I land on this page. This apart from #3450 
Happens only for this exercise .
![screenshot 149](https://cloud.githubusercontent.com/assets/8834964/6920378/901c92cc-d7db-11e4-8407-74efb52d7557.png)
Steps to reproduce : login and go to this exercise
http://127.0.0.1:8008/learn/khan/math/arithmetic/multiplication-division/mult-div-word-problems/comparing-with-multiplication/

**Comment by tarunsharma1** [comment] 2015-03-31 14:12
I am also not able to reach any question apart from the first one. Points increase if i answer correctly but the next question button refreshes the page to the same error and same question underneath..points have increased though

**Comment by rtibbles** [comment] 2015-03-31 14:21
This issue is fixed on 0.13. Duplicate of #3413.

**Closed by rtibbles** 2015-03-31 14:21 UTC
