### ISSUE TITLE
Unable to load localized exercises in Spanish (404 error)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4186] opened 2015-07-29 21:06 UTC
**Branch**: 
*KALiteSetup-0.14.0.exe* compiled on Jul 24 14:13, tested on Windows 8 & XP
*0.14 alpha12 - ka-lite-bundle* installed from PPA, tested on Ubuntu 15.04

**Spanish set as Default language**
On all installations, for exercises that appear as available in the sidebar, most of them load in English but few (that I suspect ARE localized), give 404 error.

**Windows XP:**
![miss-es](https://cloud.githubusercontent.com/assets/1457929/8969841/314cfb78-3646-11e5-8026-49005752c73a.png)

**Ubuntu 15.04:**
![miss-es-linux](https://cloud.githubusercontent.com/assets/1457929/8969877/59e0de4c-3646-11e5-9c02-8dcaad71adad.png)

**Comment by radinamatic** [comment] 2015-07-30 17:05
Folder `G:\Documents and Settings\<User>\.kalite\exercises\es` on Windows contains 426 html files, all apparently (checked about 10 at random) localized in Spanish. So the content is there, just not fetched properly. 

@aron @MCGallaspy

**Comment by radinamatic** [comment] 2015-07-30 17:10
Folder structure on Linux is different, I can't seem to find the equivalent of the above. There is `/home/<user>/.kalite/httpsrv/static/perseus/ke/exercises` but I don't see any indication of folders for localized versions.

**Comment by aronasorman** [comment] 2015-07-31 18:24
Will investigate what's causing this.

**Comment by radinamatic** [comment] 2015-07-31 20:27
And another *important* thing that is probably related: **sidebar always displays in English**, and I know I've seen it localized in Spanish at some point in the past. Lately I haven't been able to manage displaying in in Spanish, neither on `develop` nor with any of the installers I tested.

**Comment by aronasorman** [comment] 2015-07-31 23:19
Hi @radinamatic,

re: sidebar always english -- I think the problem here is that the current production central servers don't have functional language packs for 0.14. I can reproduce this with the latest Mac installer. Can you try running the server with this command:

```
kalite start --settings=kalite.project.settings.dev
```

the `--settings` option is the important flag here, as it downloads language packs from the development version of the central server, which should give you working language packs, as shown here:

![screen shot 2015-07-31 at 16 15 18](https://cloud.githubusercontent.com/assets/191955/9019409/e0e588f2-379f-11e5-8255-21acd85a95e1.png)

I think you need to restart your server too, after downloading.

**Comment by aronasorman** [comment] 2015-07-31 23:21
However, I can confirm that espanyol khan exercises aren't working:

![screen shot 2015-07-31 at 16 20 56](https://cloud.githubusercontent.com/assets/191955/9019429/3ab12e72-37a0-11e5-9f66-fd626c15769a.png)

**Comment by radinamatic** [comment] 2015-07-31 23:26
Wow, I see Spanish again! :eyes: 

Will test that immediately!

**Comment by rtibbles** [comment] 2015-07-31 23:37
Good to know not everything is messed up!

**Comment by radinamatic** [comment] 2015-08-01 00:14
@aronasorman Yes, `--settings=kalite.project.settings.dev` did the trick, and I was able to download & activate the Spanish language pack, yay!. :)

One thing though: this worked only on ka-lite-bundle I installed from .deb, not on my development repo. How do I get Spanish there too?

**Comment by aronasorman** [comment] 2015-08-01 00:24
@radinamatic have you tried deleting your old es language pack first? What branch is your dev repo running?

**Comment by radinamatic** [comment] 2015-08-01 00:34
@aronasorman Tota11y right, I probably had my newest `videojs-focus` branch on in my dev repo, I'll delete and re-download the langpack!

**Comment by radinamatic** [comment] 2015-08-01 01:39
¡Todo bien por aquí! :)

(All is well over here), well mostly, but it's too late to be nitpicking!

**Comment by radinamatic** [comment] 2015-08-03 17:59
http://staging.learningequality.org/ seems down all day today, I can't update another branch.

**Comment by aronasorman** [comment] 2015-08-05 21:31
![image](https://cloud.githubusercontent.com/assets/191955/9098391/7ab4286c-3b7e-11e5-89c5-a11a6aed0e8e.png)


Pushed my fix in the commit above. Can you see if everything is *bueno* in the latest 0.14.x? You have to redownload the language pack for it to work.

**Comment by radinamatic** [comment] 2015-08-05 21:35
Ok, checking now!

**Comment by radinamatic** [comment] 2015-08-06 16:02
This was a beautiful site yesterday, please merge this into `develop` as soon as you can! :+1: 

![learn trigonometria 0 5 _ ka lite - chromium_011](https://cloud.githubusercontent.com/assets/1457929/9116549/38d0127a-3c65-11e5-937c-b0ccba9efc68.png)

**Comment by aronasorman** [comment] 2015-08-06 16:20
Feel free to open a PR that merges 0.14.x to develop @radinamatic!

**Comment by radinamatic** [comment] 2015-08-06 16:24
Love it when people have so much confidence in my abilities... :P

**Comment by MCGallaspy** [comment] 2015-08-07 21:45
I re-opened the issue based on @radinamatic's report in #4214, but upon looking in to it it seems like a problem with the language packs available for download from the production central server -- changing the settings to point the central server to staging.learningequality.org, re-creating a database, registering, and then downloading the language pack from that location works fine. So let's close this after we update the production central server.

**Comment by radinamatic** [comment] 2015-08-08 01:27
@MCGallaspy 

Sofar mixed results, with the `settings.py` as you recommended (changed before I started the app the first time):

```
# This is the default location where the kalite command finds its settings
# You can change the below lines to use different default settings or
# you can run kalite <command> --settings=other_module

from kalite.project.settings.base import *

# from kalite.project.settings.dev import *
# from kalite.project.settings.raspberry_pi import *

# Put your custom settings here
# MY_SETTING = 123
SECURESYNC_PROTOCOL = "http"
CENTRAL_SERVER_HOST = "staging.learningequality.org"
CENTRAL_SERVER_URL = "%s://%s" % (SECURESYNC_PROTOCOL, CENTRAL_SERVER_HOST)
```
Spanish langpack downloaded and restarted, I do get the localized sidebar, but no exercises: 


![es assessment-not-loading](https://cloud.githubusercontent.com/assets/1457929/9148084/04e9dc1c-3d72-11e5-8f04-2d869aa9fca3.png)  

As you can see all are actually there in the respective folder, but they do not load:

![es assessment-not-loading2](https://cloud.githubusercontent.com/assets/1457929/9148086/13bb1b16-3d72-11e5-89e4-29aa259eee7e.png)  

At this point I'm not really sure if the i18n fix by @aronasorman was merged and/or working correctly... :(

**Comment by aronasorman** [comment] 2015-08-08 23:16
Strange, although it seems like the es language pack wasn't downloaded properly, as the text I expect to be translated is still in English ("Practicing").

Does it still return a 404 for that specific exercise html file?

**Comment by radinamatic** [comment] 2015-08-09 00:48
Strange indeed, I don't see a 404 just a 301, but there is a following error in the Console on FF, while when I open it in Chrome, the Console is completely empty:

`The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.`

**Comment by radinamatic** [comment] 2015-08-09 00:50
Even weirder: opening from a networked machine in Ubuntu, there is "Practicando", but no exercise:

![learn restas hasta el cinco ka lite - mozilla firefox_016](https://cloud.githubusercontent.com/assets/1457929/9153013/5cea9da0-3e41-11e5-9825-2f8b10a04840.png)

301 error:

![inspect network request_017](https://cloud.githubusercontent.com/assets/1457929/9153017/6c4be358-3e41-11e5-9ea3-662bb07e7897.png)

**Comment by aronasorman** [comment] 2015-08-09 17:17
ha, what? `Moved Permanently`? It seems like there's something funky going on with the API in the first place, and it doesn't get to load the actual html for the exercise. @rtibbles can you see if my understanding is correct?

Otherwise, my only suspicion is that this is some strange server side caching issue. Instead of running this with `kalite start`, can you try it with `kalite manage kaserve` or `kalite manage runserver`, and make sure your settings has `DEBUG = True`?

**Comment by radinamatic** [comment] 2015-08-10 13:28
Added `DEBUG = True` to the above `G:\Documents and Settings\meda\.kalite\settings.py` file, and tried running both `kalite manage kaserve` and `kalite manage runserver`. Both still gave the `301 MOVED PERMANENTLY` error on those Addition and Substraction exercises in Spanish:

![ad301a](https://cloud.githubusercontent.com/assets/1457929/9172467/160c8950-3f74-11e5-86b9-d9ab026e04c2.png)


![ad301c](https://cloud.githubusercontent.com/assets/1457929/9172511/574f4e98-3f74-11e5-8f16-3983cb09a0bd.png)


Console in Chrome still comes up empty, this is the only output I could get:
![ad301b](https://cloud.githubusercontent.com/assets/1457929/9172488/2b8e88b4-3f74-11e5-99fc-ffb7f3d280b4.png)

**Comment by radinamatic** [comment] 2015-08-10 13:40
Ah, `kalite manage runserver` loads the sidebar in Spanish, but nothing else localized in the interface:

![ad301-runserver](https://cloud.githubusercontent.com/assets/1457929/9172762/01a19508-3f76-11e5-9ea9-360e13a58806.png)

**Comment by aronasorman** [comment] 2015-08-10 16:04
I'll try copying the language packs from the staging server, then try replicating this with the Mac installation.

**Comment by radinamatic** [comment] 2015-08-10 16:26
Ok, I'm testing to see if I can replicate anything of this on the latest Ubuntu deb.

**Comment by rtibbles** [comment] 2015-08-10 16:32
A quick note that the 301 here is on the API endpoint, and not for loading
the exercise template (which will be the problematic part for Khan Exercise
exercises).

**Comment by aronasorman** [comment] 2015-08-10 16:59
@radinamatic transferred the language packs. Prod server should now have the latest language packs in there. With a somewhat fresh install of KA Lite, I redownloaded `es`, and got this:

![screen shot 2015-08-10 at 09 57 19](https://cloud.githubusercontent.com/assets/191955/9177507/6ceca968-3f46-11e5-9a4d-8118fdf41812.png)

So I can't replicate the 301 error you're getting.

**Comment by rtibbles** [comment] 2015-08-10 17:08
The 301 is not an error, but rather due to the lack of the trailing slash
on the API endpoint URL.

api/exercise/subtraction_1 - 301
api/exercise/subtraction_1/ - 200

The reason that the exercise is not displaying above is due to the
TypeError this.pages[(page - 1)] is not defined.

This line of code appears nowhere in the 0.14.x Javascript codebase, so I
honestly have no idea where it might be coming from.

**Comment by radinamatic** [comment] 2015-08-10 17:35
Me, in deep mud again... :stuck_out_tongue: 

I'm trying to remember if I did something special before that `TypeError this.pages[(page - 1)] is not defined` error appeared, but nothing comes to mind. That error appeared only once, though.

**Comment by radinamatic** [comment] 2015-08-10 19:28
@MCGallaspy 
Something wrong with HipChat tonight, so I'll continue here since the results are more or less the same as for Spanish... :cry: 

Installation went on smoothly, I didn't start from the checkbox inside the last wizard window, but used the Desktop shortcut and the task bar app. 

There is more of the interface translated, videos download fine, but the exercises do not load:

![miss-fr](https://cloud.githubusercontent.com/assets/1457929/9181701/a51a22ce-3fa6-11e5-8ab2-fd705236768b.png)

**Comment by radinamatic** [comment] 2015-08-10 19:30
This was XP, I'll test on Win 7 now.

**Comment by radinamatic** [comment] 2015-08-10 20:56
Different machine, Windows 7 Ultimate:  
 
- Uninstalled all previous KA Lite versions
- Deleted the `<HOME>\.kalite\` folder
- Installed and started from task bar
- Admin Login and registered the device
- Downloaded French langpack
- Interface and sidebar appear localized immediately
- Exercises do not load (same 301 error)
- Restarted the server
- Exercises still not loading:

![miss-fr-w7](https://cloud.githubusercontent.com/assets/1457929/9184009/f76c29c6-3fb2-11e5-819b-f2ad21111f4c.png)

**Comment by aronasorman** [comment] 2015-08-10 20:58
@radinamatic might be somehow your screen reader software is interacting strangely with browsers?

**Comment by radinamatic** [comment] 2015-08-10 20:58
Forgot to mention that dubbed videos download and play correctly.

@MCGallaspy, I can test on W8 too, but at this point I doubt it'll make a difference.

**Comment by radinamatic** [comment] 2015-08-10 20:59
On this W7 machine I do not use the screen reader, so I don't see how...?

**Comment by radinamatic** [comment] 2015-08-10 21:02
And that `TypeError this.pages[(page - 1)] is not defined` must have been a "fluke", since I haven't noticed it again.

**Comment by radinamatic** [comment] 2015-08-10 21:09
I did get one error at the first exercise I tried to load (before the restart), but it only appeared once and there was no way to debug it further (is there a script in this release which prevents the Console to work properly?):

![miss-fr-w7b](https://cloud.githubusercontent.com/assets/1457929/9184304/b4003ebe-3fb4-11e5-8a37-66530358f782.png)  

No idea if this can shed any more light on the problem.

**Comment by aronasorman** [comment] 2015-08-10 21:21
Ah interesting. I also get this 301 error. However, my browser follows the link it redirects to and doesn't simply error out:

![screen shot 2015-08-10 at 14 19 50](https://cloud.githubusercontent.com/assets/191955/9184579/f9284d00-3f6a-11e5-93b1-1cb8d5a92b8e.png)

![screen shot 2015-08-10 at 14 20 47](https://cloud.githubusercontent.com/assets/191955/9184587/0690aa96-3f6b-11e5-91e9-dcbe430a6d3f.png)

**Comment by aronasorman** [comment] 2015-08-10 21:22
I'm also using Chrome, and no blocker scripts present :)

**Comment by radinamatic** [comment] 2015-08-10 21:23
Well, for me it happens on both Chrome and FF.

**Comment by aronasorman** [comment] 2015-08-10 21:30
Actually it seems like the API resource is loading correctly: https://cloud.githubusercontent.com/assets/1457929/9172511/574f4e98-3f74-11e5-8f16-3983cb09a0bd.png

So that 301 error is a red herring. Do you see any other error in there? Does it load the html file?

**Comment by radinamatic** [comment] 2015-08-10 21:32
Where exactly can I see if the HTML is loaded? All that I see is the title in English and empty exercise content.

**Comment by aronasorman** [comment] 2015-08-10 21:37
It should appear the in the 'network' tab (or the equivalent in FF): 
![screen shot 2015-08-10 at 14 33 28](https://cloud.githubusercontent.com/assets/191955/9184876/da7ad4c0-3f6c-11e5-83e2-fbb85bc2d759.png)

That's what was copied over into the `httpserv` dir you saw.

**Comment by radinamatic** [comment] 2015-08-10 22:10
This is what I manage to see:

![miss-fr4](https://cloud.githubusercontent.com/assets/1457929/9185469/6f4071e2-3fbc-11e5-9be9-3074299480da.png)  

![miss-fr3](https://cloud.githubusercontent.com/assets/1457929/9185474/789b7610-3fbc-11e5-9838-067484e1190b.png)

![miss-fr5](https://cloud.githubusercontent.com/assets/1457929/9185507/bc2e0942-3fbc-11e5-93cb-fe9f392b28ee.png)

![miss-fr6](https://cloud.githubusercontent.com/assets/1457929/9185586/5566ceb4-3fbd-11e5-859e-343a518be3fc.png)

**Comment by rtibbles** [comment] 2015-08-10 22:23
As I said above:

> The 301 is not an error, but rather due to the lack of the trailing slash
>  on the API endpoint URL.

The 301 is certainly a red herring. The key thing here is that 'the content was not found'. This means that the HTML template is not in the location that the availability stamping is expecting.

This means that the directory that i18n is pointing it to is incorrect.

If this happens then the content will not be loaded, so the .html file is not fetched.

Again, this is an issue in availability stamping where i18n is not pointing to the correct location for the locale files for exercise templates.

**Comment by aronasorman** [comment] 2015-08-10 22:34
@rtibbles [the solution I implemented was to place the html files inside static-libraries/perseus/ke](https://github.com/learningequality/ka-lite/commit/d38e0da5ed43d5348289e70af9446d889a330c6f). This seems to have worked for both my Linux dev VM and my OS X machine, as both show that the specific exercise is available. So I'm not entirely sure what I'm missing here -- is there a better way to fix this? 

My only hunch right now is that this error is specific to Windows, but then again I think @MCGallaspy tested this last Friday and it seems to be working for him too.

**Comment by rtibbles** [comment] 2015-08-10 22:53
```
        # English-language exercises live in application space, translations in user space
        if language == "en":
            exercise_root = os.path.join(settings.KHAN_EXERCISES_DIRPATH, "exercises")
        else:
            exercise_root = os.path.join(django_settings.USER_DATA_ROOT, "exercises")
        if os.path.exists(exercise_root):
            exercise_path = os.path.join(exercise_root, language) if language != "en" else exercise_root
            try:
                exercise_templates = os.listdir(exercise_path)
            except OSError:
                exercise_templates = []
        else:
            exercise_templates = []
```

The code on 0.14.x is looking for the exercise templates in ```exercise_root = os.path.join(django_settings.USER_DATA_ROOT, "exercises")``` so, I doubt just copying them into staticfiles is going to help.

**Comment by aronasorman** [comment] 2015-08-10 23:05
Ah right. I did forget to change that. Let me open a PR to change that part as well.

**Comment by radinamatic** [comment] 2015-08-10 23:13
Getting closer! :+1:

**Comment by aronasorman** [comment] 2015-08-10 23:33
Note: I think the reason why it's succeeding for me and @MCGallaspy, and not for @radinamatic, is that we had `.kalite/exercises/` which was placed there by a previous version of the code (before my first fix). Since @radinamatic doesn't have that, it's not detecting it, and is thus shown as unavailable. 

My commit above should fix that, and thus both fixes should finally get this issue resolved.

**Comment by radinamatic** [comment] 2015-08-10 23:34
Ok, get that installer going so I can retest it tonight ;)

**Comment by radinamatic** [comment] 2015-08-10 23:40
And btw, I just checked and the same issue was present on Ubuntu where I installed the `ka-lite_0.14~b1-0ubuntu1` today, so @benjaoming will probably have to compile again!

**Comment by benjaoming** [comment] 2015-08-11 08:19
PR reference?

So we want a beta2 released ASAP with this?

**Comment by radinamatic** [comment] 2015-08-11 08:38
beta2 should include https://github.com/learningequality/ka-lite/commit/3f5e60cb92474d36ea2ab17eaf1f84e8ca66226e, that one was the final fixer!

**Comment by benjaoming** [comment] 2015-08-11 11:55
Okay great! @aronasorman it's confusing with commits directly into 0.14.x ... it's fine that it gets merged directly... just a bit confusing because I was looking for a PR that wasn't there :)

Releasing another beta, stay tuned for a PR tracking it.

**Comment by radinamatic** [comment] 2015-08-11 19:14
@aronasorman @MCGallaspy  French on XP :+1:

This one is so cool
![miss-fr-no-more](https://cloud.githubusercontent.com/assets/1457929/9207419/d5b9159e-406d-11e5-8665-3ab9cc716a49.png)
 it even turns!

**Comment by radinamatic** [comment] 2015-08-11 20:25
KA Lite running on XP, viewed from a networked Ubuntu laptop with Spanish user interface! :)

![learn diciendo la hora en un reloj con numeros ka lite - chromium_022](https://cloud.githubusercontent.com/assets/1457929/9209607/c363b962-4077-11e5-81d9-73ff27f2dc08.png)

**Comment by radinamatic** [comment] 2015-08-11 20:26
I could go on testing on other Windows machines, but I'd say the issue is nailed and fixed!

**Comment by aronasorman** [comment] 2015-08-11 20:51
:boom:

**Closed by aronasorman** 2015-08-11 20:51 UTC
Labels: has PR
