### ISSUE TITLE
keypad functionality on multiple answer (Perseus) questions

### ISSUE THREAD

**Issue by mjptak** [learningequality/ka-lite#3058] opened 2015-02-18 03:49 UTC
branch: develop
issue: keypad functionality limits ability to move to next answer box

steps to duplicate:  url below...

http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-place-value-topic/cc-early-math-skip-counting/skip-counting-by-5s/

Even if one closes the keypad and changes focus with the mouse the focus returns to the first box upon recalling the keypad a second time.

**Comment by MCGallaspy** [comment] 2015-02-19 00:04
Duplicate of #2944.

**Closed by MCGallaspy** 2015-02-19 00:04 UTC
