### ISSUE TITLE
Learner's points get incorrectly increased when doing exercise

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3186] opened 2015-03-05 23:23 UTC
Branch: develop
Expected Behavior: Doing a exercise, when correctly answer a question, earned points for only this question get added to total points.
Current Behavior: Doing a exercise accumulated earned points including from all previous questions get added to total points.

Steps to reproduce:
1. log in as learner
2. choose a exercise that contain multiple questions
3. answer questions under that exercise and check for points you earn and your total points.

![screen shot 2015-03-05 at 3 21 55 pm](https://cloud.githubusercontent.com/assets/5577205/6516990/9cab8790-c34b-11e4-9ec7-995c9ac56a18.png)
![screen shot 2015-03-05 at 3 22 17 pm](https://cloud.githubusercontent.com/assets/5577205/6516992/9fa1707c-c34b-11e4-8059-22352a6d5bec.png)
![screen shot 2015-03-05 at 3 23 03 pm](https://cloud.githubusercontent.com/assets/5577205/6516993/a201dab4-c34b-11e4-852f-5627f6d50475.png)

**Comment by anuragkanungo** [comment] 2015-03-09 16:57
There could be two scenarios as per I think,

1. We are just having the display issue, so if you go to home page and come back, you are able to see correct points. OR
2. As per Image points are adding like the total points of the exercise 757 + 26 = 783 + 39 =822 , instead of 757 + 13 = 770 + 13 = 783.

So, the mistake could be with formula.

**Comment by tarunsharma1** [comment] 2015-03-09 17:06
I have tried it out...for a few different student accounts and different quizes...It is a display issue as you guessed...if you go to the home page and then check your score..the score is the correct one...
Any idea how i can try to fix this?

**Comment by rtibbles** [comment] 2015-03-09 17:15
Hi @tarunsharma1 this bug is coming from the way that 'newpoints' is being set on the statusModel in kalite/distributed/static/js/distributed/exercises/views.js and then used in kalite/distributed/static/js/distributed/distributed-server.js in the StatusModel definition.

Basically it listens for an update in 'newpoints' and updates its own points from there. We should probably sidestep this, and just update the 'points' attribute of the statusModel directly.

I also fear this may have got regressed, as I think @MCGallaspy and I had got this working previously.

**Comment by MCGallaspy** [comment] 2015-03-09 17:29
Sadly, it regressed because the relevant test is skipped in Travis.

**Comment by rtibbles** [comment] 2015-03-09 17:47
Not sure this is actually a regression, as the point of failure was unedited in your PR.

**Comment by rtibbles** [comment] 2015-03-10 00:16
@tarunsharma1 Thanks for looking into this, have resolved this in #3213 now, as it is critical.

**Comment by tarunsharma1** [comment] 2015-03-10 15:10
dam i was just about to get it myself :/

**Comment by rtibbles** [comment] 2015-03-10 15:18
Yeah, we are having a bug bash today, so wanted to make sure it was merged before then.

**Closed** 2015-03-10 18:04 UTC
Labels: bug, has PR
