### ISSUE TITLE
Activating simplified login results in blank login modal

### ISSUE THREAD

**Issue by Aypak** [learningequality/ka-lite#5255] opened 2016-08-08 10:06 UTC
## Summary

Simplified login is a feature that is supposed to allow users to login with username only. However, when this feature is activated, it produces a blank login modal and the error `Uncaught ReferenceError: setGetParamDict is not defined` in the console. This issue was previously closed in #3553 but seems to have  resurfaced. It is not clear in which release of kalite it first re-emerged.

## System information
 - Operating system: Ubuntu 16.04
 - Version: 0.16.8
 - Browser: Chrome

## How to reproduce

1.  Add SIMPLIFIED_LOGIN = True to settings.py
2. Restart kalite server
3. Attempt to log in

## Screenshots
![untitled](https://cloud.githubusercontent.com/assets/7353802/17475737/bfebb7e6-5d5c-11e6-8cce-23756e2028e9.png)

## Real-life consequences 
When using kalite with very young learners, they often forget their passwords. It is easier to have them type in their username only in order to login. This will save alot of time and frustration for the young ones.
Thanks!

**Comment by Aypak** [comment] 2016-09-28 13:06
Hi Everybody, I hope i'm not too late to the party. Thanks for all your effort in resolving this. However, i noticed that admins and coaches were not able to login if LOCKDOWN is also activated
![screenshot at 2016-09-28 14-33-34](https://cloud.githubusercontent.com/assets/7353802/18913594/e092e380-8588-11e6-9d6a-38112d304c07.png)

I created a PR to fix this - #5297. Now it works perfectly when lockdown is also activated.
Thanks again!

**Comment by benjaoming** [comment] 2016-09-28 15:10
This has already been fixed.. on which version did you encounter the issue?

I've been running with LOCKDOWN locally for a while, it was working also with admin/coach logins.

**Comment by Aypak** [comment] 2016-09-29 08:35
I encountered this issue in the latest release. It only happened when both lockdown and simplified login were both activated. Thanks for reviewing the PR

**Comment by benjaoming** [comment] 2016-10-02 15:27
@Aypak 's fix is implemented for the 0.17 release (current `develop`). I'm guessing because the fix was so simple and has already been confirmed as working, that we can skip any further confirmation and just close this issue :)

**Closed by benjaoming** 2016-10-02 15:27 UTC
Labels: has PR
