### ISSUE TITLE
Unable to access videos & exercises as a logged-in user: "no such column: main_attemptlog.response_count" error

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#3546] opened 2015-04-23 16:51 UTC
Branch: develop (after fetching today's upstream)

Expected Behavior: After choosing the topic from sidebar, user should be able to see the exercise or video. 

Current Behavior: 
- If the chosen activity is a video: sidebar folds back and leaves a blank screen
- if the activity is exercise: "no such column: main_attemptlog.response_count" error appears with a traceback (see the screenshot)

Steps to reproduce:
1. Log in as the either administrator, coach or learner.
2. Choose "Learn" from the main menu.
3. Choose the topic from the sidebar topic tree.

***If i try to access videos & exercises without login, everything works.***

![no_such_column](https://cloud.githubusercontent.com/assets/1457929/7302380/4d18f95a-e9e9-11e4-8e1f-ab951079d514.png)

**Comment by radinamatic** [comment] 2015-04-23 19:03
I don't know if it's related but I just noticed another error message at the bottom of the screen while trying to view videos:

"File failed to load: http://192.168.1.33:8008/static/perseus/ke/third_party/MathJax/2.1/extensions/MathMenu.js"

I have no "extensions" folder inside \ka-lite\kalite\static\perseus\ke\third_party\MathJax\2.1, therefore no MathMenu.js or any other ftm...

![failed_load_mathmenu js](https://cloud.githubusercontent.com/assets/1457929/7305096/bcd9cc62-e9fb-11e4-9025-6cd44866e29d.png)

**Comment by rtibbles** [comment] 2015-04-23 19:04
This is unrelated, and is due to something funky I made happen to be able to compile our static files. I will probably undo it at some point.

Make sure to do a syncdb --migrate to see if it resolves the main issue.

**Comment by radinamatic** [comment] 2015-04-23 19:33
Did the syncdb --migrate and got this output:

Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for facility:
- Nothing to migrate.
 - Loading initial data for facility.
Installed 0 object(s) from 0 fixture(s)
Running migrations for config:
- Nothing to migrate.
 - Loading initial data for config.
Installed 0 object(s) from 0 fixture(s)
Running migrations for securesync:
- Nothing to migrate.
 - Loading initial data for securesync.
Installed 0 object(s) from 0 fixture(s)
Running migrations for i18n:
- Nothing to migrate.
 - Loading initial data for i18n.
Installed 0 object(s) from 0 fixture(s)
Running migrations for main:
- Nothing to migrate.
 - Loading initial data for main.
Installed 0 object(s) from 0 fixture(s)
Running migrations for chronograph:
- Nothing to migrate.
 - Loading initial data for chronograph.
Installed 0 object(s) from 0 fixture(s)
Running migrations for updates:
- Nothing to migrate.
 - Loading initial data for updates.
Installed 0 object(s) from 0 fixture(s)
Running migrations for playlist:
- Nothing to migrate.
 - Loading initial data for playlist.
Installed 0 object(s) from 0 fixture(s)
Running migrations for student_testing:
- Nothing to migrate.
 - Loading initial data for student_test
Installed 0 object(s) from 0 fixture(s)
Running migrations for store:
- Nothing to migrate.
 - Loading initial data for store.
Installed 0 object(s) from 0 fixture(s)
Running migrations for tastypie:
- Nothing to migrate.
 - Loading initial data for tastypie.
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.sessions
 > django.contrib.auth
 > django.contrib.messages
 > django.contrib.staticfiles
 > south
 > kalite.testing
 > kalite.topic_tools
 > kalite.contentload
 > django_extensions
 > django.contrib.admin
 > kalite.testing.loadtesting
 > kalite.coachreports
 > kalite.control_panel
 > kalite.dynamic_assets
 > django.contrib.contenttypes
 > kalite.distributed
 > compressor
 > kalite.basetests

Migrated:
 - kalite.facility
 - fle_utils.config
 - securesync
 - kalite.i18n
 - kalite.main
 - fle_utils.chronograph
 - kalite.updates
 - kalite.playlist
 - kalite.student_testing
 - kalite.store
 - tastypie

I'm not sure if any syncing or migrating actually happened, as I'm still getting the same error... :(
(stopped kalite and restarted just in case)

**Comment by rtibbles** [comment] 2015-04-24 23:56
This is due to a bug that was extant on 0.13/develop that has now been fixed. Any database created with the buggy repo needs to be dropped and reinitialized.

**Comment by radinamatic** [comment] 2015-04-25 02:15
Got migration errors after flushing db, and had to literally remove the old data.sqlite file from the folder and run the ``manage setup`` again.

Anyway, I'm not getting the "no such column: main_attemptlog.response_count" error anymore, but I'm still unable to view any videos (neither old, nor newly downloaded).

**Comment by radinamatic** [comment] 2015-05-07 23:28
Anybody else having this issue a part from me? I'm still unable to see any videos when logged in... :(
Tested on both FF & Chrome on XP, and FF on Ubuntu/GNOME 14.10.

**Comment by aronasorman** [comment] 2015-05-13 21:32
Hi @radinamatic, can't manage to replicate this. Saw this on @jtamiace's laptop (she's using Windows 7) and all we had to do was delete the DB. Can you try replicating again with the latest develop?

**Comment by radinamatic** [comment] 2015-05-14 15:34
@aronasorman it's still happening, with deleted db and develop pulled 5 minutes ago. I can see videos no prob as a guest, but as soon as I log in, be it as admin or learner, I just get a blank screen. Testing now on GNOME, will get back soon...

**Comment by radinamatic** [comment] 2015-05-14 16:03
Just retested on GNOME/Ubuntu 14.10 too. Pulled the latest upstream, deleted and recreated the DB and the same error persists: videos run fine as guest, but no dice as soon as I log in... :(

**Comment by aronasorman** [comment] 2015-05-14 16:07
Haha this is so strange. Did you run `pip install -e .` or `python setup.py install`?

**Comment by aronasorman** [comment] 2015-05-14 16:10
If it's the latter, that copies KA Lite into `/etc/` and `/usr/`. So you may deleting the wrong DB.

**Comment by radinamatic** [comment] 2015-05-14 21:48
I don't recall running those commands, but rechecked, just in case... No KA Lite in either /etc/ or /usr/, nor another data.sqlite a part form the one I deleted.

And anyway, I'm getting the same exact behavior on two different machines with two different OSes so it can't just be a Linux issue...

**Comment by MCGallaspy** [comment] 2015-05-26 22:40
I can't reproduce this either. Pulled `develop`, ran `bin/kalite setup`, `bin/kalite start`, downloaded some videos as an admin. I can view them fine with all account types.

**Comment by MCGallaspy** [comment] 2015-05-26 22:43
@radinamatic 
> deleted and recreated the DB

The only possibility I can think of is that you're doing something different for this step. When you run `bin/kalite setup`, it should prompt you to delete the DB if one exists (say yes). If no DB exists, it'll just create one. It's also possible that some .pyc files are laying around if you're switching from `master` or `0.13.x` to `develop`, be sure to delete any first.

**Comment by MCGallaspy** [comment] 2015-05-26 22:44
Anyway, it's quite separate I think from the title issue. Closing.

**Closed by MCGallaspy** 2015-05-26 22:44 UTC
Labels: bug

**Comment by radinamatic** [comment] 2015-06-11 21:11
Cloned the repo from scratch and everything seems to be running like magic again... :)
