### ISSUE TITLE
Not seeing videos in v0.16.2 windows 

### ISSUE THREAD

**Issue by jumbojim101** [learningequality/ka-lite#5115] opened 2016-05-05 03:42 UTC
## Summary

Not seeing videos in v0.16.2 windows 

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows (Windows 7)
 - Version: 0.16.2

or:

 - Branch: develop (?)

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

I installed V0.16.2 on windows 7 
Downloaded v16 resized videos
copied videos to content folder,
scanned content folder (I had no indication this process finished and let it run several hours)
restarted server . I have exercises but no videos

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by CoconutTish** [comment] 2016-05-05 16:09
I can back this up, not working for me either on Windows 8.1 Pro.

Have downloaded resized v16 videos and placed them on my microSD card. Then altered the settings.py file in the /.kalite folder with the added CONTENT_ROOT = '<NewPathForVideos>' as I've done in all previous versions, and all I can see on KA Lite are the exercises. Videos are greyed out with no option to play them. 

In the 'Manage' tab, the bullet point circles under the topics are empty (not solid green), though KA Lite lets me download videos from its interface and these play without a problem (but are not stored in the default content folder).

Would appreciate any help!

**Comment by benjaoming** [comment] 2016-06-13 23:40
Cannot reproduce on Ubuntu (current 0.16.x branch).

@cpauya could you triage this on Windows?

**Comment by benjaoming** [comment] 2016-06-17 17:57
@radinamatic will test further! :)

**Comment by benjaoming** [comment] 2016-06-21 14:14
@radinamatic any "luck" reproducing the above report?

**Comment by radinamatic** [comment] 2016-06-21 15:22
Yes, @benjaoming, I did test this during the weekend, but failed to report back... :disappointed: 
My apologies, your neighbors from across the Skagerrak are keeping us mighty busy!

On both my test VMs, Ubuntu 16.04 and Windows 7, scanning for videos work correctly, but I do have one possible caveat: I did not have the videos from the resized torrent file (did not think to bring those with me), so I copied those downloaded from inside a separate VM with another running KA Lite  instance. Could it be that the problem lies in the resized files itself?

**Comment by benjaoming** [comment] 2016-06-21 15:27
@radinamatic in case those files do not have the correct names, then yes -- but it's hard to believe that wouldn't cause any more "noise". Worth verifying before closing this issue.

**Comment by benjaoming** [comment] 2016-06-21 17:56
Tested by @radinamatic and confirmed that scanning for videos work with the resized videos from .torrent as well.

@CoconutTish please try this with our latest version (0.16.6) for Windows and do reach out if you still have problems!

**Closed by benjaoming** 2016-06-21 17:56 UTC

**Comment by CoconutTish** [comment] 2016-06-23 15:23
Hi @benjaoming and @radinamatic thanks very much for looking into this. I did a fresh install of Windows KA Lite v 0.16.6 and still have the same problem. The only alteration I'm making after a new installation is to change the directory/path of the video content in settings.py. This change alone has let me access resized videos in every other version of KA Lite (0.15 most recently) but doesn't seem to work here. I've uploaded a screenshot to show you how I've altered the path: http://imgur.com/X5Cffzx.

Any tips? Thanks in advance!

**Comment by benjaoming** [comment] 2016-06-25 01:28
@CoconutTish I know this is a very basic question, but if you copy the exact string from your `settings.CONTENT_ROOT`, what does it say?

Another test is to see if indeed this `settings.py` is located in the right place and used. I've verified that the custom `settings.py` is loaded and used, and it is. So another cause of the problem would be that yours simply isn't. You can try running `kalite manage shell`. Then do:

    from django.conf import settings
    print settings.CONTENT_ROOT

And verify that it's the correct output.
