### ISSUE TITLE
Videos unavailable using 0.15.x on RPi

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4781] opened 2016-01-08 18:25 UTC
In a [different thread](https://github.com/learningequality/ka-lite/issues/4738#issuecomment-162718386) @3kay said the following:

> I am having a similar problem with a 0.15 installation on a Raspberry Pi. I had earlier downloaded resized videos in bulk and tried to use the folder in a usb stick plugged into raspberry pi with a soft link from ./kalite/content . I see all videos grayed out. When I try video download in management, I see all dots for topics fully green and no check boxes available for downloading any videos through the ka-lite interface.
The same videos are working fine in an ubuntu installation on a laptop.

@3kay when you say it's working fine on Ubuntu, did you similarly create a soft link from `~/.kalite/content` to the resized videos? In both cases (on the RPi and on Ubuntu) what is the full path to the `.kalite/content` folder? And which user is running the kalite process? You can check which user is configured to run the kalite process in `/etc/kalite/username` (I think that's the right file, let me double check). Tagging @benjaoming.

**Comment by benjaoming** [comment] 2016-01-08 19:03
@3kay
I would like some feedback regarding what @MCGallaspy said, but otherwise this might be an issue regarding nginx that serves the video files on Raspberry Pi -- the issue could well be that nginx (for security reasons) won't follow your symbolic link to a location outside of the served folder. You can circumvent this in `/etc/nginx/sites-available/ka-lite.conf` by inserting:
    
    disable_symlinks off;

Source: http://unix.stackexchange.com/questions/157022/make-nginx-follow-symlinks

**Comment by 3kay** [comment] 2016-01-09 09:30
It does not look like an issue of symbolic link. First, it is not a clean
install. I was trying to replace ka-lite in an installation of RACHEL. I
may have messed it up.

No - Ubuntu is a ppa install and i do not have any symbolic link to content
folder.

The username is pi in /etc/ka-lite/username

I used the .deb package install on Raspberry Pi.

I noticed that the '/home/pi/.kalite/content' folder was empty after
installation. In my earlier installs, usually some default videos are there
at installation.

I find this error when I use "kalite start":

Going to daemon mode, logging to /home/pi/.kalite/server.log
Exception TypeError: TypeError("'NoneType' object is not callable",) in
<bound method SqliteDict.__del__ of
SqliteDict(/home/pi/.kalite/channel_cache_data/contents.sqlite)> ignored

I removed the symbolic link, created a clean empty ./kalite/content folder
with matching user (pi:pi) and permissions, re-run "kalite manage setup"
and got a system with no video shown (no green dot). Then I tried to
download a video and received an error about
/home/pi/.kalite/channel_cache_data/contents.sqlite ....

I  transferred a single video on "introduction to addition"  to the
~./kalite/content folder. The video does show up as a single green dot in
the interface but does not play in "Learn" mode. The URL tries at:

http://10.10.10.10:8008/learn/khan/math/early-math/cc-early-math-add-sub-basics/cc-early-math-add-sub-intro/addition-introduction/

Best,

lkk

**Comment by benjaoming** [comment] 2016-01-09 13:36
> I transferred a single video on "introduction to addition" to the
> ~./kalite/content folder. The video does show up as a single green dot in
> the interface but does not play in "Learn" mode. The URL tries at:

Try running the command `kalite manage videoscan` and your system should be
updated with the videos present in `~/.kalite/content`.

**Comment by 3kay** [comment] 2016-01-09 13:58
I did a kalite stop and start before to make sure that the video is made
available with no success.

Doing what you suggested produces this:

pi@tcfn01 ~ $ kalite manage videoscan
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py",
line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File
"/usr/share/kalite/python-packages/fle_utils/chronograph/management/croncommand.py",
line 40, in execute
    raise CommandError("This command cannot be run from the command-line.")
CommandError: This command cannot be run from the command-line.

**Comment by benjaoming** [comment] 2016-01-09 15:09
Ah yes, sorry, add option `--commandline`

**Comment by 3kay** [comment] 2016-01-11 08:21
Checked the symbolic link in Ubuntu install - it is working perfectly.

**Comment by MCGallaspy** [comment] 2016-01-11 21:56
Great to see you resolved the issue @3kay!

@benjaoming in your opinion, is this a bug or user error?

**Comment by 3kay** [comment] 2016-01-11 22:18
I went back to 0.13 on rpi to let the system run for the time being.
Regretfully, all my attempts to install 0.15 on a raspberry pi have so far
ended up in problems - one way or the other. I did a clean install of 0.15
on rpi with the latest raspbian over the last weekend and it would say port
8008 is occupied. Its (0.15) ppa install is perfectly working on Ubuntu.
You can consider this issue closed for the time being. I will give another
try to .15 on rpi after a week or so.
Thank you so much for your time and extending help.

LK

**Comment by benjaoming** [comment] 2016-01-12 14:38
@3kay thanks so much for your patience and for testing further on this. Which RPI and Raspian versions are you running btw? Maybe we have some hardware at the office, we can try out, too.

**Comment by 3kay** [comment] 2016-01-13 20:23
@benjaoming , I have a Raspberry Pi 2 Model B and the last test was with RASPBIAN JESSIE LITE OS. I am using Tenda W311Ma wifi dongle and a similar high power larger wifi device. Both work fine in all systems I have running ka-lite 0.12 and 0.13, I do not have a 0.14. 
Surprisingly, ka-lite 0.15 got successfully installed on Jassie Lite, I got it registered also and downloaded a test video too. It gave me a port 8008 occupied error after I rebooted the system. 
I had earlier spent a lot of time in dealing with 0.15 and port 8008/7007 problem on Raspbian Wheezy and therefore decided to go back to 0.13 for the time being. 
If you can suitably modify the ppa install of 0.15 for Ubuntu to work with Raspbian (Jassie), It would be of great help to pi users. I will give it another try on a full Raspbian Jassie rather than the Lite version.

Best,

LK

**Comment by benjaoming** [comment] 2016-01-14 12:18
@aronasorman I think this is the RPI model I have at my office, but would you happen to also have one?

I'm gonna try to get the status of this report confirmed / disconfirmed by installing on a clean system as it seems there might be some upgrade complexity in the original case.

**Comment by 3kay** [comment] 2016-01-14 12:23
I have five of these lying ;)

**Comment by benjaoming** [comment] 2016-01-27 16:25
@3kay 
>  I did a clean install of 0.15 on rpi with the latest raspbian over the last weekend and it would say port 8008 is occupied. 

Regarding this issue, you are doing the following "wrong" (I admit, it's confusing).

On Raspberry Pi, nginx is running on port 8008 and KA Lite runs on port 7007. This is because the builtin HTTP server of KA Lite isn't as efficient for static media as nginx.

If you want to start/stop/restart KA Lite, you should use the system service which is the one that's auto-configured.

For instance, to restart it:

    sudo service ka-lite restart

If you want to do ka-lite stuff directly on the terminal with the `pi` user, add the `--port` option:

    kalite restart --port=7007

I hope at least this solves some of the issues.

**Comment by 3kay** [comment] 2016-01-27 16:55
@benjaoming , Thanks a lot. I will give it a try.

**Comment by batcheze** [comment] 2016-01-30 15:52
I went through all the steps above and are unable to display any videos.  The install process works well, but it doesnt register any content.  It seems like there is a disconnect between nginx and Ka-lite
Here is my setup:
Raspberry pi 2
Raspbien (Tried Jessie and Wheezy) 
64gb micro sd
Edimax wifi

I am setting this up for my fellow sailors on a Military ship so we can further our education while out to sea.  We are leaving in a couple of weeks and was wondering if there is a way to get .13?  That one seems to be stable on my current setup based on all the comments.

**Comment by benjaoming** [comment] 2016-01-31 22:29
Hi @batcheze I'm currently investigating this. There seems to be a smaller issue as described in #4791 -- could this be the issue?

Otherwise:

Which port are you accessing the server?
Is it a problem that previously downloaded and/or copied videos don't display? Or are they freshly downloaded through the Manage tab?
Did you install with the ka-lite-raspberry-pi debian package?
Did you add any additional configuration?

I've been unsuccessful in recreating the issue so far, and I need more guidance to recreate it.

Thanks!

**Comment by batcheze** [comment] 2016-02-01 01:11
@benjaoming 

> Which port are you accessing the server

:8080

>Is it a problem that previously downloaded and/or copied videos don't display? Or are they freshly downloaded through the Manage tab?

I downloaded the re-sized torrent due to my install being on a 64g card.  I would transfer them by samba over to the content folder.  They would show in the manage videos tab, but would not play when i viewed them directly

>Did you install with the ka-lite-raspberry-pi debian package?

I followed the directions @ http://ka-lite.readthedocs.org/en/latest/installguide/install_all.html#raspberry-pi

sudo apt-get install python-m2crypto python-pkg-resources nginx python-psutil

sudo wget https://learningequality.org/r/deb-pi-installer-0-15 --no-check-certificate --content-disposition

sudo dpkg -i ka-lite-raspberry-pi*.deb

>Did you add any additional configuration?

I did not add any.  I went step by step from the install guide.

**Comment by benjaoming** [comment] 2016-02-01 21:12
@batcheze 

> They would show in the manage videos tab, but would not play when i viewed them directly

How does this look? Can you post a screen shot?

**Comment by benjaoming** [comment] 2016-02-01 21:13
...and thanks for the feedback btw, much appreciated :)

**Comment by rtibbles** [comment] 2016-02-01 21:14
Have the content cache files been deleted after content import? If not, then no new content will be discovered in the topic tree.

**Comment by benjaoming** [comment] 2016-02-01 21:21
@rtibbles could you give a guide to precisely what you mean by "been deleted"? Is there a command for this?

**Comment by rtibbles** [comment] 2016-02-01 21:32
No command, has to be done on the command line atm, I think. It normally happens during video download, but obviously that isn't happening in this case.

**Comment by benjaoming** [comment] 2016-02-01 21:40
@rtibbles only if the reporter confirms that they are looking at an empty menu -- but it sounds like it's problems with the video player?

**Comment by rtibbles** [comment] 2016-02-01 21:42
In 0.15 the video manage tab uses the VideoFile database models, that are being updated at content load - the topic tree uses the content caches.

This mess is why the content backed db stuff was so important to me for 0.16.

**Comment by batcheze** [comment] 2016-02-02 00:09
@benjaoming   This is what the manage video tab looks like.
![image](https://cloud.githubusercontent.com/assets/1376788/12735605/19165694-c917-11e5-8a69-940ca79bf7c6.png)

This is what the content looks like in the learn tab.
![image](https://cloud.githubusercontent.com/assets/1376788/12735574/e62d4a76-c916-11e5-86e5-fa7625cf3206.png)

**Comment by batcheze** [comment] 2016-02-02 00:12
When i go to the greyed out lessons, this is what shows up on the page...

![image](https://cloud.githubusercontent.com/assets/1376788/12735681/9c634962-c917-11e5-900e-bf359611e565.png)

**Comment by rtibbles** [comment] 2016-02-16 19:14
This is due to the use of disk based content caches on the Raspberry Pi - these caches need to be deleted when content is manually copied in.

To do this:

To delete the files named topics from this filepath:
in django_settings.USER_DATA_ROOT in the 'cache' folder.

 and the sqlite db from this one: from the 'channel_cache_data' also in the django_settings.USER_DATA_ROOT.

**Comment by batcheze** [comment] 2016-02-17 02:51
@rtibbles having trouble finding the locations to delete the files.. Can you expand on where to go?

**Comment by j-schwartz** [comment] 2016-02-17 02:55
I wasn't able to get this solved, but there is much more information on these two files here: #4835

**Comment by benjaoming** [comment] 2016-03-01 21:41
I'll make an assessment once 0.16b1 is out tomorrow. Note to everyone: 0.16's way of fixing this is to implement a single-threaded download queue.. one file at a time. This is much less problematic for the RPi, but we're aware of the disadvantages and as the above PR shows, we have an intention of fixing it in 0.17.

**Comment by kenny55d** [comment] 2016-03-04 11:29
Good day All,

I have also been having trouble getting the videos to play on the raspberry pi and finally got it to work after much searching.

I am running it on a raspberry pi 2 on raspbian-jessie and have installed "ka-lite-raspberry-pi-0.15.1.deb" following the instructions from http://ka-lite.readthedocs.org/en/latest/installguide/install_all.html#raspberry-pi

As rtibbles said, "it is due to the use of disk based content caches on the Raspberry Pi" so to get the videos to play, I just disabled that setting.

Steps followed:
1. Delete the 'cache' and 'channel_cache_data' folder located in /home/pi/.kalite
2. Open /home/pi/.kalite/settings.py and add the following line:
DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = False
3. From the console run: 
    kalite manage setup
    kalite restart --port=7007

The downloaded videos should now play.
The down side to disabling the cache is that it now takes about 5 minutes for kalite on the pi to start, instead of 1 minute.

Anyone know how to get it to work with the cache enabled???

Thank you

**Comment by MCGallaspy** [comment] 2016-03-05 01:03
Hi @kenny55d thanks for the sleuthing!

> Anyone know how to get it to work with the cache enabled???

I'll look in to it.

**Comment by rtibbles** [comment] 2016-03-05 07:08
Getting this to work requires deleting the cache files on the Raspberry Pi, as I suggested above and in #4835. More info on finding these files here: https://github.com/learningequality/ka-lite/issues/4835#issuecomment-184904884

Seems for @j-schwartz's case at least, the files were not appearing in his file system for reasons I am at a loss to explain.

**Comment by kenny55d** [comment] 2016-03-05 10:24
@rtibbles
In addition to deleting the cache files, there is still a need to disable the cache setting, otherwise the files simply get recreated next time the service is restarted, the system will unsuccessfully attempt to use them and the videos won't play. 

Hence the need to add the following line to  /home/pi/.kalite/settings.py

DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = False

Once that's done, settings.py contents should now appear as follows:

from kalite.project.settings.raspberry_pi import *
DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = False

The reason for setting this to False is because it is set to True in settings.raspberry_pi so to disable it, you override by adding that line.

**Comment by rtibbles** [comment] 2016-03-05 19:49
The caches get recreated with the new information based on the current
downloaded videos, meaning that the information doesn't have to get
recreated at every boot. The caches being out of date are the problem, not
the caches per se.

**Comment by MCGallaspy** [comment] 2016-03-10 00:31
@rtibbles the intent is that downloading videos will invalidate the cache, yes? Is it possible that the cache is rebuilt incredibly slowly, hence the videos apparently are not updated? Any guidance on confirming or denying this, if it's possible?

**Comment by MCGallaspy** [comment] 2016-03-10 00:36
Indeed, I downloaded a video on the pi but it's availability wasn't registered. But triggering a manual update with the command `kalite manage annotate_content_items` does the trick. Seemingly the problem is that the cache is not invalidated when videos are downloaded.

**Comment by rtibbles** [comment] 2016-03-10 00:52
The issue on 0.15 will be completely different to any possible problems on
0.16. Is this behaviour still extant on RPi on 0.16?

**Comment by MCGallaspy** [comment] 2016-03-10 01:13
>Is this behaviour still extant on RPi on 0.16?

No, I thought so at first, but I just downloaded some videos without any issue.

**Comment by MCGallaspy** [comment] 2016-03-10 01:18
Unclear what the status of this issue is, then... are we suggesting upgrading to 0.16.0 when it's released?

**Comment by rtibbles** [comment] 2016-03-10 01:23
Yes, hence testing on RPi and being sure that is a solution is important!

**Comment by benjaoming** [comment] 2016-03-10 11:00
On 03/10/2016 02:31 AM, Michael Gallaspy wrote:
>
> @rtibbles <https://github.com/rtibbles> the intent is that downloading
> videos will invalidate the cache, yes? Is it possible that the cache
> is rebuilt incredibly slowly, hence the videos apparently are not
> updated? Any guidance on confirming or denying this, if it's possible?
>

What I experienced was that the update would take place in the
background, leaving the topic blank during the process.

If you'd restart the server and thus kill that job, I don't know whether
it'd pick up again or not.... but I think the default of the
chronopgraph is to restart uncompleted jobs.

**Comment by kenny55d** [comment] 2016-03-10 12:50
> @MCGallaspy But triggering a manual update with the command kalite manage annotate_content_items does the trick. Seemingly the problem is that the cache is not invalidated when videos are downloaded.
> 
> Edit: Just to be clear, this is using a beta version (0.16b1). For those following this thread, note that this is a possible manual workaround. I haven't tested it on 0.15.1, but I expect it to work just the same. You could also try the beta version, but I highly recommend waiting for the official release.

Thanks All,

I just ran the command **kalite manage annotate_content_items** on 0.15.1 but got the following error:
     
     Unknown command: 'annotate_content_items' 
     Type 'kalite manage help' for usage.

Any chance we could get the steps required to do this manually?

Thanks.

**Comment by rtibbles** [comment] 2016-03-10 13:00
That command does not exist on 0.15.1 - it is new in 0.16.

**Comment by synetics** [comment] 2016-03-29 04:22
Hi
Those of you had problems with display of video on Raspberry Pi using kalite 0.15.1, please try the change I used for settings.py :
from kalite.project.settings.base import *
Do a videoscan and restart the kalite server.
I got video working with it on my Raspberry Pi 3 with Raspbian.
Post your results.
Joseph Mathew

**Comment by benjaoming** [comment] 2016-07-29 16:34
Going to close this issue as both the content cache and video downloading has been greatly improved and refactored for in the 0.16 series.

Thanks all for your feedback!

**Closed by benjaoming** 2016-07-29 16:34 UTC
Labels: bug, ready

**Comment by promiseowolabi** [comment] 2016-07-30 11:59
Hi Benjamin,

Thanks for the great work you guys at Learning Equality do. Please how long does a raspberry pi take to scan the entire resized English content?

Thanks
