### ISSUE TITLE
As a teacher user, both nav paths for 'admin' and 'teacher' are available when learn tab is clicked

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#2997] opened 2015-02-09 23:15 UTC
steps to reproduce:
- log in as teacher
- click learn
- click out of side bar

![teacher](https://cloud.githubusercontent.com/assets/6668144/6118051/717f579e-b06e-11e4-9458-ed1371d2fe86.PNG)

**Comment by aronasorman** [comment] 2015-02-10 19:45
Duplicate of https://github.com/learningequality/ka-lite/issues/2990

**Comment by MCGallaspy** [comment] 2015-02-12 17:38
@cpauya is this a separate issue from #2997? If not then perhaps we can close it.

**Comment by cpauya** [comment] 2015-02-13 00:28
No @MCGallaspy it is the same issue as mentioned in https://github.com/learningequality/ka-lite/issues/2990#issuecomment-74043787

**Closed by cpauya** 2015-02-13 00:28 UTC
Labels: has PR
