### ISSUE TITLE
Unable to run "bin/kalite manage setup" on Windows

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#4198] opened 2015-08-01 21:25 UTC
OS: Windows 8.1 

This error occurs for environment setup.
The command tries to write dubbed_video_mappings.json into a 'locale' folder, which doesn't exist.

**Comment by aronasorman** [comment] 2015-08-06 20:16
Branch @jtamiace?

**Comment by jtamiace** [comment] 2015-08-06 23:14
develop

**Comment by rtibbles** [comment] 2016-01-31 18:04
Dupe of #4796 - closing this as other issue has more context.

**Closed by rtibbles** 2016-01-31 18:04 UTC
Labels: bug
