### ISSUE TITLE
Multiple choice answer options in Perseus don't seem to be in random order

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2834] opened 2015-01-06 22:03 UTC
E.g. for http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/count-to-100/
the middle of the 3 answers, when it's below the number grid, always seems to be correct.

**Comment by aronasorman** [comment] 2015-01-13 21:43
Is this for *every* multiple choice question? If not, maybe this can go to a bugfix releaes.

**Comment by rtibbles** [comment] 2015-01-22 18:42
I don't think this is currently happening, but would be good for you two to check today @aronasorman and @jamalex.

**Comment by aronasorman** [comment] 2015-01-22 18:47
Will do check this along with your PR @rtibbles

**Comment by MCGallaspy** [comment] 2015-01-29 19:27
On develop, I get the following 400 response:
Request URL: `http://127.0.0.1:8008/api/assessment_item/x53f0c415af612d3f/?_=1422559388441`
Request method: `GET`
The response: `{"error": "The object '<kalite.main.api_resources.AssessmentItem instance at 0xaa0d3f8>' has an empty attribute 'tags' and doesn't allow a default or null value."}`

Presumably this is a problem with my `data/khan/assessmentitems.json` file... is there a canonical download location/does anyone else get this error?

**Comment by MCGallaspy** [comment] 2015-01-29 19:48
I can't reproduce this issue. Are you sure it wasn't just bad luck @jamalex?

**Comment by amodia** [comment] 2015-02-04 06:33
Hi @jamalex and @aronasorman 

branch: `develop`

I verify that Multiple choice exercises has randomize answer.
i use this exercise http://127.0.0.1:8008/learn/khan/math/algebra/solving-linear-equations-and-inequalities/solving_for_variable/solving_for_a_variable/

**Comment by MCGallaspy** [comment] 2015-02-04 18:52
I think we can close this issue, then.

**Comment by rtibbles** [comment] 2015-02-04 22:23
Closing. Reopen if recurrence is discovered.

**Closed by rtibbles** 2015-02-04 22:23 UTC
Labels: bug, high priority

**Comment by aronasorman** [comment] 2015-02-05 18:42
Cool. Let's close this then, then reopen if it comes back.
