### ISSUE TITLE
Peer-to-peer content discovery

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#2628] opened 2014-11-06 20:06 UTC
Once peer-to-peer sync is enabled, devices subscribed to the same channel should be able to share newer content to devices connected within the same network. 

Required work:
- [ ] Protocol for transferring content between two devices
- [ ] UI for showing the content in peer devices with the same channel

Related to #722.

**Comment by benjaoming** [comment] 2016-06-13 15:03
Duplicate of #2628

**Closed by benjaoming** 2016-06-13 15:03 UTC
Labels: new feature, ux / frontend
