### ISSUE TITLE
First result from search box "drop-down" gets selected by default

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4011] opened 2015-07-03 15:12 UTC
**Branch**: 0.14

**Actual behavior**: When user starts typing a query in the search form, a list of possible results appear in the drop-down, and the **first result gets selected by default**. This way, as soon as the user finishes typing and presses Enter, instead of landing on a Search result page, they land on the page with the content that was first on the drop-down list. 

![search-focus](https://cloud.githubusercontent.com/assets/1457929/8501374/15537f6a-21a5-11e5-947b-bc6410476c07.png)

**Expected behavior**: It sounds like the Google "I'm feeling lucky", which I never used/liked, but at this point I'm not sure if this behavior was intended. Personally, I always prefer to see all the possible results and choose what I need. If user is like me, once they realize why they are not getting the result page, they have to retype the query, actively deselect the first drop-down result with the up arrow key, and than press Enter.  

**Steps to reproduce**:

1. Starts typing a query in the search form, and press Enter.

**Comment by aronasorman** [comment] 2015-07-03 15:26
Oh really? I prefer the actual behaviour. It's very rarely that I want an overview of all topics, especially if I know what I'm looking for.

I guess the way I can describe using it is as a quick jump feature to a certain topic. It's a nice feature for power users, and I think both actual and expected behaviours you described are valid.

**Comment by radinamatic** [comment] 2015-07-03 15:35
On a practical level (I guess I might have particular needs/tastes) I actually never "got lucky" by Google... :P
On a subjective level, it feels like something has been chosen for me, instead of me being the actor and choosing by myself.

I have no issue with drop-down list itself, just the fact that it grabs the first option by default. The main thing is it's not how search systems work usually work (Google offers it, but it's not imposed), so it's UX issue of offering the user the most common path.

**Comment by jtamiace** [comment] 2015-07-06 17:25
^ I see what you mean. The way that you get to the general search page currently is only by clicking the button, not hitting enter.

My intuition tells me that most people use the enter key with search forms One example of user research done on this at http://ux.stackexchange.com/questions/28158/whats-used-more-to-submit-a-search-enter-or-submit-button. 26% of people click a button for search and 74% used the enter key ( Further user testing can be done on this if we want to see ourselves )

Also, if I wanted to see everything related to "addition" for example, and used enter, being navigated to a specific item instead of the general search page with many different items is an unexpected and undesirable result because it doesn't match the mental model of how search bars are used ( in the bulleted list at http://www.nngroup.com/articles/mental-models-for-search/ )

User research backed reasons that I think that the first item should not be auto-selected.

**Comment by radinamatic** [comment] 2015-07-06 17:33
@jtamiace You're reading my mind... :)
I can't even remember if I tried clicking the button, I just use the Enter key as usual whenever I search, so I do fall into the 74% from the research you mention

**Comment by rtibbles** [comment] 2015-09-14 23:46
@jtamiace This will involve changing a single setting in the search autocomplete, straight forward fix!

**Comment by rtibbles** [comment] 2015-09-24 23:53
Fixed in #4453

**Closed by rtibbles** 2015-09-24 23:53 UTC
Labels: has PR, ux issue
