### ISSUE TITLE
Device Registration error 

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3318] opened 2015-03-17 10:49 UTC
![github](https://cloud.githubusercontent.com/assets/10394619/6685565/212e99a2-ccc1-11e4-899f-1937a6c68448.png)
I am connected to Internet and everything is working fine but still getting this error.
branch: Develop

**Comment by anuragkanungo** [comment] 2015-03-17 11:43
I can confirm, facing on other branches as well.
Will look into it.

**Comment by sharprakeshverma** [comment] 2015-03-18 04:17
The "No Internet Error" Changed to this today.
Branch:Develop
Attribute error "bool attribute has no object strip"
Steps: Log in.
Expected Behaviour : A nice decent Device registration page.

![attributeerror](https://cloud.githubusercontent.com/assets/10394619/6702539/311c301c-cd53-11e4-85f2-346e313b22eb.png)

**Comment by georgyberdyshev** [comment] 2015-03-30 05:43
Hello everyone,
@anuragkanungo is this still relevant I cannot reproduce it in develop?

@sharprakeshverma Could you post the output of the Traceback, as it is not fully visible in the screenshot?

Thanks in advance, Georgy

**Comment by sharprakeshverma** [comment] 2015-03-30 06:13
Error was resolved. I dont know how but it was.

**Comment by georgyberdyshev** [comment] 2015-03-30 06:13
Thanks @sharprakeshverma

**Comment by rtibbles** [comment] 2015-03-30 06:45
Closing, will reopen if reoccurs.

**Comment by EdDixon** [comment] 2015-03-30 08:18
@rtibbles this has been recurring a lot in our testing, Friday in the testing room we pretty much resolved how to reproduce it, but I do not want to take the server out if it is working for others to prove the point? It requires many screenshots and device registrations to recreate and report this issue and would involve messing it up for others. Can you please look at the conversation thread @aronasorman and I had in testing Friday? Thanks,

**Comment by aronasorman** [comment] 2015-05-26 21:04
Hi @sharprakeshverma, we've fixed this issue during the bug squashing phase for 0.13. I'm closing this issue, but if you still encounter this please don't hesitate to file another one.

**Closed by aronasorman** 2015-05-26 21:04 UTC
Labels: bug
