### ISSUE TITLE
Student progress page error

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4843] opened 2016-02-15 12:43 UTC
#### Upgrade scenario

From 0.14 to 0.16 on OSX Yosemite.
Build: # 64 .pkg installer

#### Expected Behavior

New learner user should read some basic "welcome-go-enjoy" message when they visit their empty progress page:

```
This is your progress report page. Come back after watching some videos and doing exercises to see the details for your progress with KA Lite learning materials.
Enjoy!
```

#### Current Behavior

Page is empty, a part from the title, and backstage the console reports errors:

![sprintf_err_0 14-to-016_yosemite](https://cloud.githubusercontent.com/assets/1457929/13048777/792bd6b8-d3e8-11e5-9cad-a02999921cbb.png)

#### Steps to reproduce

1. Log in as Learner.
2. Check the `My progress` page from the menu.

**Comment by radinamatic** [comment] 2016-02-15 17:06
Confirmed on fresh 0.16 (build # 64) on OSX El Capitán.

I updated the title as this occurs even with accumulated points.

**Comment by radinamatic** [comment] 2016-02-15 20:57
With latest merges on 0.16 branch, this error changed to `ReferenceError: show_message is not defined`:

![user_report_welcome___ka_lite](https://cloud.githubusercontent.com/assets/1457929/13060064/0698dd2a-d42f-11e5-91c7-86ff09485170.png)

**Comment by MCGallaspy** [comment] 2016-02-16 17:17
Thanks for the report @radinamatic! I think this is a duplicate of https://github.com/learningequality/ka-lite/issues/4840.

**Closed by MCGallaspy** 2016-02-16 17:17 UTC
