### ISSUE TITLE
MCQ options have inconsistent position for "Quiz" and "Test your Knowledge"

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3280] opened 2015-03-13 13:30 UTC
The display of MCQ options is not consistent as can be seen in the below given screenshots.

![screenshot from 2015-03-13 18 48 52](https://cloud.githubusercontent.com/assets/6399612/6639093/908807b4-c9b2-11e4-9591-347d47ed9c10.png)

and this 
![screenshot from 2015-03-13 19 00 06](https://cloud.githubusercontent.com/assets/6399612/6639158/2fe1d89e-c9b3-11e4-9c1d-2d3054bf3563.png)

**Comment by tarunsharma1** [comment] 2015-03-13 14:34
this is the same as bug #3182

**Comment by rtibbles** [comment] 2015-03-13 19:35
Duplicate of #3182, closing.

**Closed by rtibbles** 2015-03-13 19:35 UTC
