### ISSUE TITLE
Practicing Coin flip sequences Overlaps footer section

### ISSUE THREAD

**Issue by natnael2012** [learningequality/ka-lite#3378] opened 2015-03-21 08:04 UTC
Branch develop

Current behavior - Practice area overlaps footer section and messes up layout due to hidden div containing svg element with fixed height.

![2](https://cloud.githubusercontent.com/assets/8178368/6764304/135c1fb2-cf68-11e4-8e02-231461e1fd04.png)

The DOM when inspected by developer tool
![3](https://cloud.githubusercontent.com/assets/8178368/6764267/e8df22cc-cf65-11e4-97a6-8cc0600df83a.png)

**Comment by rtibbles** [comment] 2015-06-18 15:25
This is caused by code internal to Khan Academy exercises, it is a minor issue, so I am not going to fix it for 0.14 (and am not sure how without a horrendous hack).

**Comment by benjaoming** [comment] 2017-04-06 19:32
#wontfix

Thanks for reporting this @natnael2012 - I hope the issues is gone now since it's quite old and was related to upstream data.

**Closed by benjaoming** 2017-04-06 19:32 UTC
