### ISSUE TITLE
Tweaks to make to embedded documentation

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4348] opened 2015-09-02 19:19 UTC
- [ ] Provide an easy way to link back to the KA Lite interface itself -- currently, no escape. Perhaps (eventually) embedding the docs directly within the KA Lite interface (having a view under /docs/ that maps paths, loads the appropriate HTML docs file, and renders it into the main page context in the content area)
- [ ] Allow link to docs even when not logged in
- [ ] Don't include "install guide"? Maybe? Or at least link to /static/html/usermanual/userman_main.html as the default page. Most of the sections other than "usermanual" are actually largely not so useful on an installed offline server, so we may want to just ship the "usermanual" portion?
- [x] Don't include "View page source" or "View on Github" links, to avoid confusion.
- [ ] Don't include links in "Built with Sphinx using a theme provided by Read the Docs." text at bottom (or delete whole line)
- [x] Change "Copyright 2015, FLE" to "Copyright 2015, Learning Equality, licensed under a Creative Commons Attribution-ShareAlike 4.0 International License".
- [x] Remove online badges

Ad Removing online badges:

In 0.15, we started using an ReST README because it can be reused for the docs so we don't maintain the same stuff in multiple places. It would be nice if the offline build had the section with badges from online sources disabled, though

http://sphinx-doc.org/config.html#conf-tags
http://sphinx-doc.org/markup/misc.html#including-content-based-on-tags

**Comment by MCGallaspy** [comment] 2015-09-02 20:16
I'd like to first address these in 0.15, and then create a patch for 0.14.x time permitting.

**Comment by benjaoming** [comment] 2015-09-04 16:32
#4375 addresses that documentation is actually not part of what's currently distributed. That needs to be solved.

@MCGallaspy The release notes actually mention that we are going to have documentation for OSX/deb for 0.14 soon.

**Comment by benjaoming** [comment] 2015-09-04 16:33
> Don't include "View page source" or "View on Github" links, to avoid confusion.

The "Edit on Github" is IMO very important. Having a very very low bar for contributing to the documentation is important.

The documentation is intended for administrators / devs, so I think they can understand that it's pointing to an online location. Even if they don't have internet access, it'll just signal that this is an open source thing.

**Comment by MCGallaspy** [comment] 2015-09-04 16:54
> The release notes actually mention that we are going to have documentation for OSX/deb for 0.14 soon.

Including the documentation at all is quite separate from addressing this issue. If we wish to include documentation in 0.14 for other OSes, I think we should just drop in the static HTML (a la Windows) since it requires a minimum of effort, and focus on improving offline documentation in future versions. Otherwise I'm afraid we'll be ineffectively splitting our effort between many different versions.

Re: this issue, after giving it a bit of thought, I wonder if the best approach for creating offline documentation is to create another sphinx builder? I.e. something which instead of outputting html outputs Django templates. That will let us use template context variables to allow tighter integration with the app (back links, etc). Check out [the sphinx docs on builders](http://sphinx-doc.org/extdev/tutorial.html#important-objects). My guess is that we could extend the default html builder to suit our specific needs here.

**Comment by benjaoming** [comment] 2015-09-04 17:17
@MCGallaspy I thought you made a patch so that if docs/_build/html exists, it gets served, right? So I'm just gonna make sure that the next 0.14 patch release also has them -- that'd work, right? I don't think the docs need any updating for that to happen.

**Comment by MCGallaspy** [comment] 2015-09-04 18:44
> I thought you made a patch so that if docs/_build/html exists, it gets served, right?

Correct.

**Comment by jamalex** [comment] 2015-09-29 17:55
> The "Edit on Github" is IMO very important. Having a very very low bar for contributing to the documentation is important.
> The documentation is intended for administrators / devs, so I think they can understand that it's pointing to an online location. Even if they don't have internet access, it'll just signal that this is an open source thing.

The online docs definitely need this -- and yes, they're targeted more at admins/devs. The offline docs bundled into KA Lite (that's what this issue is about) are the opposite -- they're going to be used **primarily** by teachers and learners, and hence links like this are just a distraction/confusion.

**Comment by MCGallaspy** [comment] 2016-02-08 23:26
This is not a "beginner" issue, but it could be a good issue for a GSoC student -- I'm willing to mentor.

**Comment by MCGallaspy** [comment] 2016-02-08 23:26
@rtibbles your thoughts?

**Comment by rtibbles** [comment] 2016-02-09 19:35
I guess my only concern is if it would be extensive enough to occupy someone for an entire summer?

**Comment by MCGallaspy** [comment] 2016-02-09 19:49
Yes, I think so. Note this is how I envision closing this ticket (from an earlier comment):

> Re: this issue, after giving it a bit of thought, I wonder if the best approach for creating offline documentation is to create another sphinx builder? I.e. something which instead of outputting html outputs Django templates. That will let us use template context variables to allow tighter integration with the app (back links, etc). Check out the sphinx docs on builders. My guess is that we could extend the default html builder to suit our specific needs here.

So the potential GSoCer would have to design & implement a new sphinx builder, as well as test it out and integrate it with KA Lite. If it turns out to be very fast, then I'm sure we can find some stretch goals.

**Comment by benjaoming** [comment] 2016-02-09 20:11
It's also worth considering what the integration with the application
itself means in terms of solving stuff that inline help solves better. With
docs it's also quality over quantity: Better few, well-maintained docs than
long/advanced docs.

An idea for a problem to solve could be: How do we integrate
users/community better in our docs such that the docs are written *by the
community, for the community*.

Also, worth being vary of this paradox: On the one hand, people would like
a nice "field manual" that can solve issues that occur in an offline
setting. On the other hand, when we write and ship the docs, we don't know
these because they are often unintentional technical issues.

**Comment by cpauya** [comment] 2016-02-10 07:44
Just want to note here that the link "View on Github" at the Documentation page points to this URL https://github.com/learningequality/ka-lite/blob/0.14.x/sphinx-docs/index.rst which results in a 404.

This is on the latest `develop` branch of KA-Lite.  

I agree with @jamalex that the offline versions of KA-Lite shouldn't display this link.

**Comment by benjaoming** [comment] 2016-02-10 09:53
@cpauya the link [on this page](http://ka-lite.readthedocs.org/en/develop/) looks fine, but you're right that the one in the offline version didn't.

**Comment by MCGallaspy** [comment] 2016-02-10 19:28
@cpauya that can be changed with this LOC: https://github.com/benjaoming/ka-lite/blob/rm-docs-github-link/docs/kalite-theme/theme.conf#L5

**Comment by benjaoming** [comment] 2016-03-01 19:11
@MCGallaspy could you assess this issue and possibly push it for 0.17 if necessary?

**Comment by benjaoming** [comment] 2017-04-06 21:07
Re:
>  Allow link to docs even when not logged in

I think we removed this because it was too confusing for non-logged in students.

**Comment by benjaoming** [comment] 2017-04-06 21:18
I'm very much +1 for

>  Remove online badges

I tried the below, and it doesn't parse on Githubs markdown parser. Also, since Github's markup maintainers have confirmed that it won't be done, I'm gonna do a full-blow non-DRY implementation to deal with this.

See: https://github.com/github/markup/issues/554

This is the code that doesn't parse (just gets converted to a code block):

```
.. only:: not html

   |Build Status| |Coverage Status| |Docs|

   .. |Build Status| image:: https://circleci.com/gh/learningequality/ka-lite/tree/develop.svg?style=svg
      :target: https://circleci.com/gh/learningequality/ka-lite/tree/develop

   .. |Coverage Status| image:: http://codecov.io/github/learningequality/ka-lite/coverage.svg?branch=develop
      :target: http://codecov.io/github/learningequality/kolibri?branch=develop

   .. |Docs| image:: https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat
      :target: http://ka-lite.readthedocs.org/
```

**Comment by benjaoming** [comment] 2017-04-06 21:22
These, I'm going to skip to avoid further division between online RTD version and offline embedded. I do sympathize with them.

> Provide an easy way to link back to the KA Lite interface itself -- currently, no escape. Perhaps (eventually) embedding the docs directly within the KA Lite interface (having a view under /docs/ that maps paths, loads the appropriate HTML docs file, and renders it into the main page context in the content area)

> Don't include "install guide"? Maybe? Or at least link to /static/html/usermanual/userman_main.html as the default page. Most of the sections other than "usermanual" are actually largely not so useful on an installed offline server, so we may want to just ship the "usermanual" portion?

> Don't include links in "Built with Sphinx using a theme provided by Read the Docs." text at bottom (or delete whole line)

**Comment by benjaoming** [comment] 2017-04-07 09:13
Closing this with a decision to keep online and offline docs aligned.

**Closed by benjaoming** 2017-04-07 09:13 UTC
Labels: documentation, has PR
