### ISSUE TITLE
Heroku build throws 'securesync.settings' ImportError

### ISSUE THREAD

**Issue by Kevsy** [learningequality/ka-lite#5330] opened 2016-10-17 15:59 UTC
## Summary

I'm trying to deploy KA Lite as an Heroku app, for basic demo purposes (otherwise we can only demo to colleagues who have a KA Lite instance in their network). This uses the standard KA Lite codebase but adds the Heroku Procfile, which contains the following line:

```
web: gunicorn --pythonpath 'kalite/project' kalite.wsgi --log-file -
```

Committing the app and deploying with `git push heroku master` results in the build apparently succeeding but a crash on deployment:

log snippet of the fatal exception: 
`2016-10-17T15:44:09.137726+00:00 app[web.1]:   File "/app/kalite/settings/base.py", line 547, in <module>
2016-10-17T15:44:09.137727+00:00 app[web.1]:     from securesync.settings import *
2016-10-17T15:44:09.137725+00:00 app[web.1]:   File "/app/kalite/settings/__init__.py", line 18, in <module>
2016-10-17T15:44:09.137725+00:00 app[web.1]:     from kalite.settings import *  # @UnusedWildImport
2016-10-17T15:44:09.137728+00:00 app[web.1]: ImportError: No module named securesync.settings`
## How to reproduce
1. Clone KALite git repo
2. Add Procfile as per https://devcenter.heroku.com/articles/django-app-configuration , using `web: gunicorn --pythonpath 'kalite/project' kalite.wsgi --log-file -`
3. add Procfile, commit, then `git push heroku master`

Any hints very welcome. Many thanks!

**Comment by aronasorman** [comment] 2016-10-17 16:38
Hi Kevsy,

Thanks for pushing through with this! Unfortunately there are a couple of blockers to getting `kalite` running smoothly on Heroku right now:

1. Biggest one is that we default to SQLite. That means, since Heroku can potentially serve each request on a separate dyno, that they'll have different databases. User information will not be consistent across requests.

2. Instead of running gunicorn, you'll need to run our prebuilt webserver. The said webserver adds all the required `PYTHONPATH` entries to get everything working. It also serves the assets for you.

To do that, run `bin/kalite start --port <heroku allowed port>`.

3. It might be better to build `kalite` first, install it, then run that installed version, since that ensures that everything in your path is set up correctly. You can build everything by running:

```
pip install -r requirements_dev.txt
pip install -r requirements_dist.txt
make dist
pip install dist/kalite*.tar.gz
```

that will generate a `kalite-static*tar.gz` under the `dist/` folder. It will install it too. If you can have heroku do those steps when you push to their git repo, that should make it more convenient.

Hope that helps! I'm interested in getting `kalite` running there too, as it will make our demo server easier to take down and rebuild!

**Comment by aronasorman** [comment] 2016-10-17 16:44
I forgot that `make dist` also requires a nodejs installation. Do you know if the Heroku environment provides that?

**Comment by Kevsy** [comment] 2016-10-17 16:45
Thanks! I will give that a go - Heroku indeed provides nodejs. Will report back...

**Comment by Kevsy** [comment] 2016-10-18 08:53
update:
1. tried changing Procfile to `web: bin/kalite start --port=$PORT` ($PORT is assigned dynamically by Heroku), results in Django exception:

    ImportError: No module named build

2. I'm not sure how to build and deploy outside of the `heroku create` command, since you don't get raw SSH access. But this looks promising, custom Heroku buildpacks: https://www.petekeen.net/introduction-to-heroku-buildpacks .

**Comment by benjaoming** [comment] 2016-10-18 10:56
@Kevsy - is that a Python exception? In KA Lite's codebase, there's no modules named `build`.. probably best with some kind of full traceback. Do you receive the error during `kalite start`?

Try running `bin/kalite start --foreground --traceback`, I think it renders a full traceback, although I'm not 100% sure because many of the sub-processes might still hide tracebacks.

**Comment by Kevsy** [comment] 2016-10-18 12:00
@benjaoming oops! here's the full traceback. I changed the Procfile to include the switches specified above.

     ~/Code/kalite-web/ka-lite-master$ vi Procfile
 ~/Code/kalite-web/ka-lite-master$ git add Procfile 
 ~/Code/kalite-web/ka-lite-master$ git commit -am "add traceback"
[master ac99ccf] add traceback
 1 file changed, 1 insertion(+), 1 deletion(-)
 ~/Code/kalite-web/ka-lite-master$ git push heroku master
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 317 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote:      $ pip install -r requirements.txt
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 55.4M
remote: -----> Launching...
remote:        Released v10
remote:        https://kalite.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/kalite.git
   2a0530e..ac99ccf  master -> master
 ~/Code/kalite-web/ka-lite-master$ heroku ps
Free dyno hours quota remaining this month: 549h 50m (99%)
For more information on dyno sleeping and how to upgrade, see:
https://devcenter.heroku.com/articles/dyno-sleeping

=== web (Free): bin/kalite start --foreground --traceback --port=$PORT (1)
web.1: crashed 2016/10/18 12:45:23 +0100 (~ 55s ago)

 ~/Code/kalite-web/ka-lite-master$ heroku logs
2016-10-18T09:07:38.701305+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 183, in activate
2016-10-18T09:07:38.701306+00:00 app[web.1]:     _active.value = translation(language)
2016-10-18T09:07:38.701306+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 172, in translation
2016-10-18T09:07:38.701307+00:00 app[web.1]:     default_translation = _fetch(settings.LANGUAGE_CODE)
2016-10-18T09:07:38.701309+00:00 app[web.1]:     app = import_module(appname)
2016-10-18T09:07:38.701308+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 154, in _fetch
2016-10-18T09:07:38.701309+00:00 app[web.1]:   File "/app/python-packages/django/utils/importlib.py", line 35, in import_module
2016-10-18T09:07:38.701311+00:00 app[web.1]: ImportError: No module named build
2016-10-18T09:07:38.701310+00:00 app[web.1]:     __import__(name)
2016-10-18T09:07:38.781670+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T09:07:38.822685+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-18T09:53:50.424643+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-18T09:53:54.908144+00:00 heroku[web.1]: Starting process with command `bin/kalite start --port=59552`
2016-10-18T09:53:57.171777+00:00 app[web.1]: Running 'kalite start' as daemon (system service)
2016-10-18T09:53:57.171791+00:00 app[web.1]: 
2016-10-18T09:53:57.171793+00:00 app[web.1]: Stand by while the server loads its data...
2016-10-18T09:53:57.171793+00:00 app[web.1]: 
2016-10-18T09:53:57.177724+00:00 app[web.1]: Generating a new secret key file /app/secretkey.txt...
2016-10-18T09:53:57.177725+00:00 app[web.1]: 
2016-10-18T09:53:57.428772+00:00 app[web.1]: Traceback (most recent call last):
2016-10-18T09:53:57.428781+00:00 app[web.1]:   File "/app/python-packages/django/core/management/base.py", line 224, in run_from_argv
2016-10-18T09:53:57.428782+00:00 app[web.1]:     self.execute(*args, **options.__dict__)
2016-10-18T09:53:57.428782+00:00 app[web.1]:   File "/app/python-packages/django/core/management/base.py", line 258, in execute
2016-10-18T09:53:57.428783+00:00 app[web.1]:     translation.activate('en-us')
2016-10-18T09:53:57.428784+00:00 app[web.1]:     return _trans.activate(language)
2016-10-18T09:53:57.428784+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/__init__.py", line 90, in activate
2016-10-18T09:53:57.428785+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 183, in activate
2016-10-18T09:53:57.428785+00:00 app[web.1]:     _active.value = translation(language)
2016-10-18T09:53:57.428786+00:00 app[web.1]:     default_translation = _fetch(settings.LANGUAGE_CODE)
2016-10-18T09:53:57.428786+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 172, in translation
2016-10-18T09:53:57.428787+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 154, in _fetch
2016-10-18T09:53:57.428787+00:00 app[web.1]:     app = import_module(appname)
2016-10-18T09:53:57.428788+00:00 app[web.1]:   File "/app/python-packages/django/utils/importlib.py", line 35, in import_module
2016-10-18T09:53:57.428789+00:00 app[web.1]:     __import__(name)
2016-10-18T09:53:57.428789+00:00 app[web.1]: ImportError: No module named build
2016-10-18T09:53:57.514579+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T09:53:57.547580+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-18T11:22:19.740283+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-18T11:22:24.302387+00:00 heroku[web.1]: Starting process with command `bin/kalite start --port=42201`
2016-10-18T11:22:27.300179+00:00 app[web.1]: Running 'kalite start' as daemon (system service)
2016-10-18T11:22:27.300289+00:00 app[web.1]: 
2016-10-18T11:22:27.300291+00:00 app[web.1]: Stand by while the server loads its data...
2016-10-18T11:22:27.300292+00:00 app[web.1]: 
2016-10-18T11:22:27.312204+00:00 app[web.1]: Generating a new secret key file /app/secretkey.txt...
2016-10-18T11:22:27.312207+00:00 app[web.1]: 
2016-10-18T11:22:27.704732+00:00 app[web.1]: Traceback (most recent call last):
2016-10-18T11:22:27.704750+00:00 app[web.1]:   File "/app/python-packages/django/core/management/base.py", line 224, in run_from_argv
2016-10-18T11:22:27.704751+00:00 app[web.1]:     self.execute(*args, **options.__dict__)
2016-10-18T11:22:27.704752+00:00 app[web.1]:     translation.activate('en-us')
2016-10-18T11:22:27.704753+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/__init__.py", line 90, in activate
2016-10-18T11:22:27.704752+00:00 app[web.1]:   File "/app/python-packages/django/core/management/base.py", line 258, in execute
2016-10-18T11:22:27.704754+00:00 app[web.1]:     return _trans.activate(language)
2016-10-18T11:22:27.704754+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 183, in activate
2016-10-18T11:22:27.704755+00:00 app[web.1]:     _active.value = translation(language)
2016-10-18T11:22:27.704755+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 172, in translation
2016-10-18T11:22:27.704756+00:00 app[web.1]:     default_translation = _fetch(settings.LANGUAGE_CODE)
2016-10-18T11:22:27.704757+00:00 app[web.1]:   File "/app/python-packages/django/utils/translation/trans_real.py", line 154, in _fetch
2016-10-18T11:22:27.704758+00:00 app[web.1]:     app = import_module(appname)
2016-10-18T11:22:27.704758+00:00 app[web.1]:   File "/app/python-packages/django/utils/importlib.py", line 35, in import_module
2016-10-18T11:22:27.704759+00:00 app[web.1]:     __import__(name)
2016-10-18T11:22:27.704760+00:00 app[web.1]: ImportError: No module named build
2016-10-18T11:22:27.849086+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-18T11:22:27.829102+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T11:45:09.852260+00:00 heroku[api]: Deploy ac99ccf by kevin.smith@vodafone.com
2016-10-18T11:45:09.852260+00:00 heroku[api]: Release v10 created by kevin.smith@vodafone.com
2016-10-18T11:45:10.021119+00:00 heroku[slug-compiler]: Slug compilation started
2016-10-18T11:45:10.021125+00:00 heroku[slug-compiler]: Slug compilation finished
2016-10-18T11:45:10.258341+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-18T11:45:14.706462+00:00 heroku[web.1]: Starting process with command `bin/kalite start --foreground --traceback --port=52130`
2016-10-18T11:45:17.185465+00:00 app[web.1]: Cannot mix django manage command options with kalite options. Always put django management options last.
2016-10-18T11:45:17.185481+00:00 app[web.1]: 
2016-10-18T11:45:17.185533+00:00 app[web.1]: Usage:
2016-10-18T11:45:17.185535+00:00 app[web.1]:   kalite start [--foreground --watch] [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:17.185535+00:00 app[web.1]:   kalite stop [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:17.185536+00:00 app[web.1]:   kalite restart [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:17.185536+00:00 app[web.1]:   kalite status [options]
2016-10-18T11:45:17.185536+00:00 app[web.1]:   kalite shell [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:17.185537+00:00 app[web.1]:   kalite test [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:17.185537+00:00 app[web.1]:   kalite manage [options] COMMAND [DJANGO_OPTIONS ...]
2016-10-18T11:45:17.185538+00:00 app[web.1]:   kalite diagnose [options]
2016-10-18T11:45:17.185538+00:00 app[web.1]:   kalite -h | --help
2016-10-18T11:45:17.185540+00:00 app[web.1]:   kalite --version
2016-10-18T11:45:17.315515+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-18T11:45:17.316400+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-18T11:45:17.277927+00:00 heroku[web.1]: Process exited with status 1
2016-10-18T11:45:21.250365+00:00 heroku[web.1]: Starting process with command `bin/kalite start --foreground --traceback --port=46870`
2016-10-18T11:45:22.986021+00:00 app[web.1]: Cannot mix django manage command options with kalite options. Always put django management options last.
2016-10-18T11:45:22.986041+00:00 app[web.1]: 
2016-10-18T11:45:22.986046+00:00 app[web.1]: Usage:
2016-10-18T11:45:22.986047+00:00 app[web.1]:   kalite start [--foreground --watch] [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:22.986047+00:00 app[web.1]:   kalite stop [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:22.986048+00:00 app[web.1]:   kalite restart [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:22.986048+00:00 app[web.1]:   kalite status [options]
2016-10-18T11:45:22.986049+00:00 app[web.1]:   kalite shell [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:22.986050+00:00 app[web.1]:   kalite test [options] [DJANGO_OPTIONS ...]
2016-10-18T11:45:22.986050+00:00 app[web.1]:   kalite manage [options] COMMAND [DJANGO_OPTIONS ...]
2016-10-18T11:45:22.986051+00:00 app[web.1]:   kalite diagnose [options]
2016-10-18T11:45:22.986051+00:00 app[web.1]:   kalite -h | --help
2016-10-18T11:45:22.986052+00:00 app[web.1]:   kalite --version
2016-10-18T11:45:23.068531+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-18T11:45:23.054574+00:00 heroku[web.1]: Process exited with status 1

**Comment by benjaoming** [comment] 2016-10-18 12:23
This seems to be because somewhere in `settings.INSTALLED_APPS`, there's a module listed called `build`, this is `'fle_utils.build'`. The problem is then that the path environment isn't set correct.

But I'm not quite convinced about the way you're running this with heroku is a good idea. KA Lite isn't supposed to be run statically from its source directory.. it might work for development purposes, but that isn't what you want.

Maybe instead create a new project and list `ka-lite` as a dependency... and then deploy that project to Heroku and simply call `kalite` from the command line.

In 0.17, the way we set the path environment will be simplified, and running KA Lite from source will be entirely banned :)

**Comment by Kevsy** [comment] 2016-10-18 12:24
Seems sensible - will give that a go later. `heroku run` should allow command line invocation, I hope :)

Cheers!

**Comment by benjaoming** [comment] 2016-11-21 12:58
@Kevsy Did you get things to run?

**Comment by Kevsy** [comment] 2016-11-21 13:31
Sorry not yet - we've been testing on various hosting providers but seems not to work unless it is a dedicated server. I will look again at Heroku towards the end of the week.

**Comment by benjaoming** [comment] 2016-11-21 15:53
Hmm, strange - could perhaps have something to do with the `~/.kalite` directory and the fact that you don't get persistent data on Heroku (the free version).

**Comment by benjaoming** [comment] 2016-12-17 00:24
Closing this, but please note that we are always happy to help in case there are issues on any kinds of deployments, including Heroku :)

**Closed by benjaoming** 2016-12-17 00:24 UTC
