### ISSUE TITLE
Device Registration error at initial setup

### ISSUE THREAD

**Issue by sharprakeshverma** [learningequality/ka-lite#3206] opened 2015-03-09 13:22 UTC
As i install KA-lite, i am getting this error at my first login and as i am fairly new to KA-lite, i just want to solve it ASAP to start working ahead. I have already updated it several times.
"""
Sorry, there was an error during registration. Please make sure your device is fully up to date (run python manage.py update and then stop/start the server).

The error message was: <!DOCTYPE HTML> <html> <head>  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <title>Error | KA Lite: An Offline, Installable Version of Khan Academy</title>  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css"></link> <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/bootstrap.css"></link> <link rel="stylesheet" type="text/css" href="/static/css/bootstrap/responsive.css"></link> <link rel="stylesheet" type="text/css" href="/static/css/style.css"></link> <link rel="stylesheet" type="text/css" href="/static/css/bootstrap-alerts.css"></link> <link rel="shortcut icon" href="/static/images/favicon.ico"> <script type="text/javascript" src="/static/js/jquery-1.9.1.min.js"></script> <script type="text/javascript" src="/static/js/jquery-ui/jquery-ui.min.js"></script> <script type="text/javascript" src="/static/js/purl.js"></script> <script type="text/javascript" src="/static/js/underscore-min.js"></script> <script type="text/javascript" src="/static/js/backbone-min.js"></script> <script type="text/javascript" src="/static/js/backbone/backbone-tastypie.js"></script> <script type="text/javascript" src="/static/js/bootstrap.min.js"></script> <script type="text/javascript" src='/static/js/bootstrap-timepicker.min.js'></script> <script type="text/javascript" src="/static/js/sprintf.min.js"></script> <script type="text/javascript" src="/static/js/i18n/en.js"></script> <script type="text/javascript" src="/static/js/khan-lite.js"></script> <script> var USER_LOGIN_URL = "/accounts/login/"; var CURRENT_LANGUAGE = "en"; var DELETE_USERS_URL = "/securesync/api/delete_users"; var DELETE_GROUPS_URL = "/securesync/api/group_delete"; var MOVE_TO_GROUP_URL = "/securesync/api/move_to_group"; var SERVER_INFO_PATH = "/securesync/api/info"; $(function() { $(".header__horizontal-menu__right").addClass("js").before('<div id="menu">&#9776;</div>'); $("#menu").click(function(){ $(".header__horizontal-menu__right").toggle(); }); $(window).resize(function(){ if(window.innerWidth > 768) { $(".header__horizontal-menu__right").removeAttr("style"); } }); // Code below overwrites khan-lite.js setup to ensure that the correct csrftoken is passed for the central server. var csrftoken = getCookie("csrftoken_central") || ""; $.ajaxSetup({ cache: false, crossDomain: false, beforeSend: function(xhr, settings) { if (!csrfSafeMethod(settings.type)) { xhr.setRequestHeader("X-CSRFToken", csrftoken); } } }); }); </script>  <script src="/static/js/handlebars/handlebars-v1.3.0.js"></script> <script src="/static/js/handlebars/handlebars-helpers.js"></script> <script src="/static/js/handlebars/handlebars-wrapper.js"></script> <script type="text/javascript"> var _gaq = _gaq || []; _gaq.push(['_setAccount', 'UA-36937407-1']); _gaq.push(['_trackPageview']); (function() { var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true; ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s); })(); // track time on site/page more accurately (function (tos) { window.setInterval(function () { tos = (function (t) { return t[0] == 50 ? (parseInt(t[1]) + 1) + ':00' : (t[1] || '0') + ':' + (parseInt(t[0]) + 10); })(tos.split(':').reverse()); window.pageTracker ? pageTracker._trackEvent('Time', 'Log', tos) : _gaq.push(['_trackEvent', 'Time', 'Log', tos]); }, 10000); })('00'); // track outbound link clicks (function($) { $(function() { $('a[href^="http"]:not([href*="' + document.domain + '"])').click(function(e) { // When a user clicks an external link if ($(this).attr('target') !== '_blank') { e.preventDefault(); // If the link is not set to target='_blank' // set a 300ms delay before loading this page // which allows Google Analytics to register the event (function(a) { setTimeout(function() { document.location = a.attr('href'); },300) })($(this)); } window.pageTracker ? pageTracker._trackEvent('Outbound', $(this).attr('href'), "#" + $(this).closest('[id!=""]').attr('id')) : _gaq.push(['_trackEvent', 'Outbound', $(this).attr('href'), "#" + $(this).closest('[id!=""]').attr('id')]); }); }) })(jQuery) // track real user loadtimes in Pingdom var _prum = [['id', '53619b09abe53d25686956f7'], ['mark', 'firstbyte', (new Date()).getTime()]]; (function() { var s = document.getElementsByTagName('script')[0] , p = document.createElement('script'); p.async = 'async'; p.src = '//rum-static.pingdom.net/prum.min.js'; s.parentNode.insertBefore(p, s); })(); </script> </head> <body> <div class="row-fluid" id="navbar-container"> <div class="max-width-container"> <div class="row-fluid"> <div class="span12"> <ul class="header__horizontal-menu"> <li class="header__logo"><a href="/"><img src="/static/images/horizontal-logo-small.png" alt="Home"></a></li> <ul class="header__horizontal-menu__right"> <li> <a href="https://learningequality.org/ka-lite/" target="_blank"> About </a> </li> <li> <a href="/accounts/login/" id="login" class=""> Login </a> </li> <li> <a href="/accounts/register/" id="sign_up" class=""> Sign Up </a> </li> </ul> </ul> </div> </div> </div> </div> <div class="container-fluid"> <div class="row-fluid content"> <div class="span12 content-padding"> <div id="message_container">  </div> <h1>Error</h1> <p>Sorry, but there was an error while trying to load the page.</p> </div> </div> <div class="row-fluid">  <div class="span12 float-right"> <p> &copy; 2014 <a href="//learningequality.org/about/">Foundation for Learning Equality, Inc</a> </p> <p> Except where otherwise noted, content on this site is licensed under a<br/> <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International license.</a> </p> </div> </div> </div>  </body> </html>
"""

**Comment by anuragkanungo** [comment] 2015-03-09 13:46
Duplicate of #3197

**Closed** 2015-03-09 14:18 UTC
