### ISSUE TITLE
"Already stopped. Status was: Failed to start (check logs)"

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#3601] opened 2015-05-04 21:29 UTC
On: demo server (master branch).

At one point, the server stopped responding, and when I went in to try to restart it, I got the following:

```
$ sudo bin/kalite stop
Already stopped. Status was: Failed to start (check logs)
```

Where are these logs of which it speaks? Also, I couldn't find a clean way to get the server restarted after that.

**Comment by EdDixon** [comment] 2015-05-04 23:06
if you issue a second sudo bin/kalite stop stop it should stop clean I think allowing a restart. I have seen that behavior a few times in the past with the older bat scripts as well. In a real pinch, sudo killall python will stop it also but if you have any other python apps running you may want to seriously consider what effects that will have.

**Comment by benjaoming** [comment] 2015-05-04 23:20
@jamalex you mean restarting by doing `kalite restart` ?

I think that if you can't do `kalite stop` in a clean and predictable way, it can fail as long as doing `kalite start` will still start it in case it had an "Already stopped" status.

But I would think that `kalite restart` shouldn't fail in case the server wasn't running... because that's how service commands work on Linux so I would think it's expected behaviour.

That message about logs doesn't make any sense if there aren't any logs, which I guess there aren't by default? So that should go.... But we really need to clean up the way things are logged so it's easy to determine log output and where it goes...

**Comment by EdDixon** [comment] 2015-05-04 23:40
Yea I always kind of felt the second stop I issued was just confirmation that the first one worked. CherryPy should be logging to /var/logs right?  As an httpd service I would think they would want that?

**Comment by EdDixon** [comment] 2015-05-05 11:19
Was just looking over their docs and CherryPy does support logging http://docs.cherrypy.org/en/3.3.0/refman/_cplogging.html#module-cherrypy._cplogging if configured also found this example: http://stackoverflow.com/questions/4056958/cherrypy-logging-how-do-i-configure-and-use-the-global-and-application-level-lo If we are not taking advantage of logging we might want to consider it as it?

**Comment by jamalex** [comment] 2015-05-12 17:02
It seems to be getting into a zombie state, where python2 (with `kalitectl.py start`) is still running in the background (though not serving requests), but `kalite status` shows "Failed to start (check logs) (6)". When I try to either start or restart it, it says "DatabaseError: database is locked". Trying to do anything with the DB via the `sqlite3` REPL directly also throws a "locked" error. So, it seems the background zombie process is locking up the DB and preventing a restart.

**Comment by benjaoming** [comment] 2015-05-13 15:23
@jamalex would you by any chance have found a recipe for recreating the issue?

I mean, I've tried the thing with hanging processes #3550 but now it's gone and I don't know how to get it back :)

Running `kalite start` multiple times doesn't cause any problems for me... the startup lock file works fine, and stopping kalite cleans up processes as it's supposed to.

**Comment by aronasorman** [comment] 2015-05-13 15:44
@benjaoming it might also be solved in the latest develop. Have you tried replicating it on 0.13.x? That's what's released.

**Comment by jamalex** [comment] 2015-05-13 19:25
@benjaoming I wasn't able to replicate it manually (though I saw it multiple times), but I wonder whether it might have something to do with the cron stuff? Maybe the background sync process? Has that stuff changed a lot in 0.13?

**Comment by benjaoming** [comment] 2015-05-14 17:03
@aronasorman 
I can't recreate it on 0.13.x branch.

@jamalex You are right, maybe I should try to recreate it while the cronograph is doing something... then it might not die....

**Comment by EdDixon** [comment] 2015-05-14 17:53
I saw this error several times yesterday while testing the current develop branch installer on mac after allowing it to fail to start the server using the gui. Which would be a means to repliate here if more testing is needed?

**Comment by benjaoming** [comment] 2015-05-15 10:52
Thanks @EdDixon !

Could you elaborate on this?

> allowing it to fail to start the server using the gui.

**Comment by EdDixon** [comment] 2015-05-16 15:02
@benjaoming This is on Mac using the last develop installer tested would stall when trying to start the server using the included menubar icon at which point I tried to drop to terminal to use the kalite command to check status and start up as a work around. On kalite start It which actually completed the installation and allowed it run successfully however using kalite status before that I was greeted by that same error: 
kalite status
Already stopped. Status was: Failed to start (check logs)

**Comment by benjaoming** [comment] 2015-05-17 12:57
@EdDixon this sounds like a different issue then, perhaps caused by how the installer configures things... could you create an issue with this information in the kalite-installers repo and alert @cpauya ?

**Comment by EdDixon** [comment] 2015-05-17 14:17
@benjaoming How can that be when it is in fact the exact same error?  

>Already stopped. Status was: Failed to start (check logs)

>> At one point, the server stopped responding, and when I went in to try to restart it, I got the following:

>>$ sudo bin/kalite stop
>>Already stopped. Status was: Failed to start (check logs)

>>Where are these logs of which it speaks? Also, I couldn't find a clean way to get the server restarted after that.

Just not using a different method to get there. As we start to get more uniform in using our command structure we should be seeing more of these cross platform issues right? To me that is a good thing representing progress towards unifying those methods. All I was trying to say here is that using that older MAC installer anyone should be able to replicate that state reliably to help try to resolve it.

**Comment by benjaoming** [comment] 2015-05-17 14:53
@EdDixon They are not the same error. @jamalex does not have an error on `kalite start`, which you do.. and that error describes a problem that's most likely because of a bad installation.

**Comment by EdDixon** [comment] 2015-05-17 16:50
@benjaoming It was a "kalite stop" after having tried to start the server via the gui which stalled resulted in the same error message:
>Already stopped. Status was: Failed to start (check logs)

The kalite start actually ended up resolving the issue and completing the installation properly LOL. Again I feel this could be something related to a common script regardless of platform or at least I hope so! We can agree that kalite start or stop issued at any point resulting in an error message indicates a problem? However this one is simply stating that the server is stopped and we just tried to stop it again which is  a problem when it is known to be running but stalled. That error message has been around for a very long time (I have seen it here far too many times, far too long, and on all desktop platforms) and the solution will likely be found in one of the older scripts our new commands are calling but my point was I feel my method of replicating the error beats starting it up and waiting an unknown amount of time for it to stall to reach that same state and was a reliable way of getting it in a condition that might provide clues as to why we are seeing it.

**Comment by benjaoming** [comment] 2015-05-17 17:03
Attempts to recreate by `kalite stop` while the cronograph is running jobs (videodownload) also failed. Will have a closer look at jamie's method from the demo server..

**Comment by EdDixon** [comment] 2015-05-19 19:49
Issue replicated again using latest MAC installer from Dungeon (#50) screen shot attached, details in the testing room.
![2015-05-19_13-45-22](https://cloud.githubusercontent.com/assets/4349806/7712305/e1b8d50a-fe2d-11e4-8034-1120ed06d1c9.png)

**Comment by benjaoming** [comment] 2015-05-19 21:59
@EdDixon I can't find the details in the room. I think the main information you can provide for this is an output from a `kalite start` command. In case you started it from the UI, then the problem belongs on the installers' issue tracker.

**Comment by EdDixon** [comment] 2015-05-19 22:17
Just my take on this issue but the error message occurs when the server stalls which is happening when started on a mac using the current in development installer builds and starting via the added menubar icon in the installation package. I feel regardless of how it is started the error occurs when the server stalls and I can replicate that via this method. Thats what I am trying to explain here. I am going to add the full trace back to help further explain what is seen on my end when using the kalite command once the server is in this state. Traceback here: https://s3.amazonaws.com/uploads.hipchat.com/86198/1302220/425YbD0qoiEuIF1/MAC%2350.rtf

**Comment by benjaoming** [comment] 2015-05-19 22:22
It looks like you don't have any problems running `kalite start` so it's a problem of how the installer has invoked kalite. It's true that `kalite stop` will display this error when somehow kalite has failed to start, but that's only natural.

The missing logs is an issue all by itself, but we have to solve that separately.

What @jamalex  is describing is different: He's doing `kalite start` and then somehow he can't stop the server and has to kill stuff by force.

**Comment by benjaoming** [comment] 2015-06-29 17:17
Just making one minor amendment ;)

**Closed** 2015-06-30 17:01 UTC
