### ISSUE TITLE
Alignment bug for "completing streak" screen

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3104] opened 2015-02-23 23:21 UTC
Logged in as a student user

![congrats](https://cloud.githubusercontent.com/assets/6668144/6339932/34349dac-bb6f-11e4-9142-f625cd05951f.PNG)

**Comment by MCGallaspy** [comment] 2015-02-23 23:41
Duplicate of #3103.

**Closed by MCGallaspy** 2015-02-23 23:41 UTC
