### ISSUE TITLE
For Mac OS, upon starting KA Lite, can not process to open the website

### ISSUE THREAD

**Issue by JohnJCZhou** [learningequality/ka-lite#4021] opened 2015-07-04 03:37 UTC
Click on KA-Lite monitor and after it is loaded it will look like this:
<img width="608" alt="2015-07-03 8 10 24" src="https://cloud.githubusercontent.com/assets/9564925/8506309/99dec20e-21c2-11e5-87f4-c9fe4fdad4a4.png">

After clicking on "Start KA Lite" the the system will get stuck in this status:
<img width="177" alt="2015-07-03 8 15 35" src="https://cloud.githubusercontent.com/assets/9564925/8506319/e96978dc-21c2-11e5-97e5-1eed4adb5177.png">
Even if I try to open it in browser by manually typing address: 127.0.0.1:8008, the page won't load.

**Comment by cpauya** [comment] 2015-07-04 06:37
Hi @JohnJCZhou - I assume that you have already configured your Preferences?  What build of the .dmg did you use?

Can you open `Terminal` and type `kalite status`?  If it's open already, please close it and re-open (to load the environment variables used by the `kalite` executable).

**Comment by amodia** [comment] 2015-07-04 08:56
@JohnJCZhou & @cpauya I reproduced this issue, if I download any `kalite videos` that fails to download and I stop and start the `kalite monitor`. And If I don't download any `kalite videos` and I stop and start the `kalite monitor` this issue will not reproduce. I used build #165 osx installer from dungeon.

**Comment by cpauya** [comment] 2015-07-04 08:58
@JohnJCZhou and @amodia:

I think what happened was that you tried to download a video first, which failed throwing the `DatabaseError: no such table: chronograph_job` error as [commented here](https://github.com/learningequality/ka-lite/issues/3704#issuecomment-118479719) - then tried to start/stop the server.

**To verify the above**

1. Make a clean install of the OSX installer using build 165.
1. Start the server.
1. Download a video, which will fail.
1. Go to the `Terminal` and run `kalite start` which will give this output:

```bash
cyril-lappy6:~ cyril$ kalite start
Running 'kalite start' as daemon (system service)

Stand by while the server loads its data...

/Applications/KA-Lite Monitor.app/Contents/Resources/ka-lite/kalite/settings/base.py:43: RemovedInKALite_v015_Warning: We will be deprecating the old way of statically importing custom settings, in favor of a more flexible way. The easiest way to update your installation is to rename your local_settings.py (keeping it in the same directory) and add an import statement in the very first line of the new file so it looks like this:

    from kalite.project.settings.base import *
    # Put custom settings here...
    FOO = BAR

and then call kalite start with an additional argument pointing to your new settings module:

    kalite start --settings=kalite.my_settings

In the future, it is recommended not to keep your own settings module in the kalite code base but to put the file somewhere else in your python path, for instance in the current directory when running 'kalite --settings=my_module'.
  RemovedInKALite_v015_Warning
INFO:kalite:Invalidating the web cache.
INFO:kalite:Running videoscan.
INFO:kalite:Preloading exercise data for language en.

INFO:kalite:Preloading content data for language en.
INFO:kalite:Preloading topic tree data for language en.
INFO:kalite:Copying static media...
WARNING:py.warnings:/Applications/KA-Lite Monitor.app/Contents/Resources/ka-lite/python-packages/tastypie/resources.py:328: UserWarning: 'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.
  warnings.warn("'override_urls' is a deprecated method & will be removed by v1.0.0. Please rename your method to ``prepend_urls``.")

INFO:kalite:Running 2 due jobs... ("Secure Sync", "Download Videos")
```

The last line above tells us that ka-lite tried to run the pending jobs but stopped.  I checked the `~/.kalite/server.log` file but it has no content with 0 bytes.

**To double-check**

1. Make a clean install using build 165.
2. Use the site, but do not download a video.
3. Start and stop the server, either using the menu icon or the `kalite` executable on the `Terminal`.
4. Notice that this will work as intended.

So I think this issue will get fixed when we fix #3704 first.

**Comment by benjaoming** [comment] 2015-07-05 23:57
@cpauya we didn't implement proper logging :) So the log is truncated everytime you restart. This is to ensure that filesizes don't run away until we've implemented a proper global logging mechanism. This won't happen in 0.14, so remember to grab the logs right away :)

**Comment by aronasorman** [comment] 2015-08-07 18:28
A lot of churn has happened in the Mac installer since this was opened. Let's create another issue if this crops up again. @cpauya feel free to dissent.

**Closed by aronasorman** 2015-08-07 18:28 UTC
Labels: 0.14.x bug bash, Mac
