### ISSUE TITLE
Allow teachers to clear their own results on a unit test, so they can take it again

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#2338] opened 2014-09-01 05:19 UTC
Branch: nalanda

The Nalanda teachers have been going through the unit tests themselves, to become familiar with what is on them. After the test is over, however, they're blocked from retaking it, but often want to. We should either have it automatically let them start from scratch again when they finish, or have a button to clear their own results to let them start over.

**Comment by benjaoming** [comment] 2017-04-26 09:45
Closing as a duplicate of #2261, not even sure if it's relevant anymore: A teacher can continue to cycle through "unit tests" (supposing this is assessment items or questions in exercises) after completing the exercise:

![screenshot from 2017-04-26 11-43-29](https://cloud.githubusercontent.com/assets/374612/25428300/bbdc19d4-2a75-11e7-9990-eff5e6fb6c3e.png)

I would suggest that when fixing #2261, we just add some button to the same interface saying "clear my own results and retake this exercise".

**Closed by benjaoming** 2017-04-26 09:45 UTC
Labels: nalanda, new feature
