### ISSUE TITLE
Search autocomplete fails to link to content properly

### ISSUE THREAD

**Issue by rtibbles** [learningequality/ka-lite#2981] opened 2015-02-09 22:39 UTC
Branch: develop
Expected Behavior: Clicking on an item in the search autocomplete drop down should take you to that item
Current Behavior: Clicking navigates you to '/learn/{slug}' without the full path required for navigation
Steps to reproduce: Click into Search box, start typing the title of a video or exercise, click on one when it appears in the dropdown.
Screenshot(s):

![image](https://cloud.githubusercontent.com/assets/1680573/6117446/704d60fa-b069-11e4-83ef-13b4490e2ea6.png)

**Comment by jamalex** [comment] 2015-02-09 22:57
Duplicate of #issueiwasabouttoopen!

**Closed** 2015-02-13 23:33 UTC
Labels: 0.13.x bug bash, bug, high priority, ux issue
