### ISSUE TITLE
Check box is not working, because of which we are unable to go to the next question on version 0.15

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#4857] opened 2016-02-17 05:40 UTC
Detailed description:
The Check box to select the right option is not working on the exercise: Math --> Basic Geometry --> Shapes --> Classifying Shapes --> Recognizing triangle types
Because of which we are unable to proceed to the next question. 

Expected behavior:
The Check box should work and upon selecting the correct answer, the next question should be displayed.

Actual behavior:
1. On **http://demo.learningequality.org/learn/khan/math/basic-geo/basic-geo-shapes/basic-geo-classifying-shapes/recognizing-triangles/**
The check box seams to not work.
2. On a offline server that we have in one of the schools we are getting:
Unexpected error 504.
3. On one other offline server the check box is not working.

Note:
1. The check box is working for the question shown on the last screenshot. But it does not work on the question shown on the second screenshot.
2. This issue persists on all the offline servers.
3. Hope the same issue might persist on exercises that have check box response. 
4. Version 0.15 used

Please refer the screenshots for more details.

![screen shot 2016-02-17 at 11 08 04 am](https://cloud.githubusercontent.com/assets/13453618/13100815/fd544cb6-d566-11e5-9e20-638ecc0be970.png)
![screen shot 2016-02-17 at 11 08 13 am](https://cloud.githubusercontent.com/assets/13453618/13100818/fdd6470c-d566-11e5-93fd-d77ac94c34cd.png)
![screenshot from 2016-02-17 10_56_04](https://cloud.githubusercontent.com/assets/13453618/13100816/fd5b3ef4-d566-11e5-8248-31eb84053f15.png)

**Comment by MCGallaspy** [comment] 2016-02-17 18:37
The demo link works fine for me on Chrome Version 48. Which browser are you using?

**Comment by MCGallaspy** [comment] 2016-02-17 18:40
No, I spoke too soon. If you are referring specifically to the scalene-isoceles question, then I can confirm that it doesn't work. Thanks for the detailed report!

**Comment by rtibbles** [comment] 2016-02-26 16:36
I am guessing if this is specific to just this question, it is a weird interaction between KA Lite and Perseus?

**Comment by MCGallaspy** [comment] 2016-02-29 23:00
Maybe so, I have only confirmed the report but I'm not really sure what the underlying bug is. If I recall correctly, we have to specifically listen to some events emitted by objects in the perseus framework in order to trigger the correct action in KA Lite, right? That may be what's going on here -- we're not listening to the right event, since it's an object type that's not seen frequently in other questions.

**Comment by radinamatic** [comment] 2016-03-02 22:37
woff2 curse again, @rtibbles! These missing "things" are clickable, so Learner can't finish the exercise...

Confirmed on Beta1/Ubuntu/Chromium:

![woff2-again](https://cloud.githubusercontent.com/assets/1457929/13478082/9af083cc-e0cf-11e5-85db-1cfcbbed8cfb.png)

**Comment by rtibbles** [comment] 2016-03-02 23:27
Can you retake the screenshot with the Network tab request filter on
"Fonts"?

**Comment by radinamatic** [comment] 2016-03-02 23:29
Darn, I just shut that VM off to switch to Windows... I'll try as soon as I install here!

**Comment by radinamatic** [comment] 2016-03-03 01:12
@rtibbles, ok?

![woff3-again](https://cloud.githubusercontent.com/assets/1457929/13481309/e205f2fa-e0e4-11e5-90cf-7a6e812f71db.png)

![woff4-again](https://cloud.githubusercontent.com/assets/1457929/13481366/66843c9e-e0e5-11e5-9caf-e79fcdb2caa1.png)

**Comment by radinamatic** [comment] 2016-03-03 01:14
Missing images are a separate, XP issue, filing!

**Comment by rtibbles** [comment] 2016-03-03 03:22
Yeah, this is good. Confirms my earlier conclusions. It's not a problem
with files missing, but somehow the fonts not getting applied.

**Comment by rtibbles** [comment] 2016-03-09 00:29
Fixed in #4965

**Closed by rtibbles** 2016-03-09 00:29 UTC
Labels: bug, has PR
