### ISSUE TITLE
Server not Starting with 16.8

### ISSUE THREAD

**Issue by jjmiranda-clickmaths** [learningequality/ka-lite#5259] opened 2016-08-17 13:28 UTC
I've upgraded from 16.7 to 16.8. Once I run KA Lite, I get the pop-up saying that the server is starting but it never does.

Operating system: Windows 10
 - Version: 0.16.8
 - Browser: Google Chrome

Am I missing something? What should I be checking? 16.7 and all previous versions worked smoothly.

**Comment by benjaoming** [comment] 2016-09-07 14:42
Thanks for reporting the issue, it's understandable that you can't get out anymore data. I'm sorry about the slow response.

Our big meta-problem is that logging doesn't work on Windows... That issue is tracked here: https://github.com/learningequality/ka-lite/issues/5057

You can get around it by:

1) Stopping KA Lite
2) Going to the Windows command line, `Win+R` -> type: `cmd`
2) Starting kalite from command line with the `--foreground` option:

```
C:>cd C:\Python27
C:\Python27>cd Scripts
C:\Python27\Scripts>kalite start --foreground
```

This _might_ show you something useful.

Btw, to stop it again, press `CTRL+C`.

Please copy out the feedback from the command line and post it here...

**Comment by benjaoming** [comment] 2016-09-16 23:00
Supposing this is a duplicate of #5277

**Closed by benjaoming** 2016-09-16 23:00 UTC
