### ISSUE TITLE
Page not found when clicking on Sync to central server.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#4176] opened 2015-07-28 07:00 UTC
**Branch:** 0.14.x

**Expected Behavior:** Will not error when clicking on `device management page` button.

**Current Behavior:** Page not found error when clicking `device management page` button.

**Steps to reproduce:** 

1. Login as `admin`.
2. Click on `Register device` link in `Available Actions` column.
3. Click on `device management page` in info message.
4. Click on `Sync to central server!`.
5. Click on `device management page` in info message.

Error in the screenshot below:
![after-fix-the-4174](https://cloud.githubusercontent.com/assets/8664071/8925270/fcd19556-3538-11e5-838a-f063d55dbbc1.png)

**Comment by rtibbles** [comment] 2015-07-28 16:24
This is a duplicate of #4101.

**Closed by rtibbles** 2015-07-28 16:24 UTC
