### ISSUE TITLE
empty topic tree when DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4109] opened 2015-07-16 05:45 UTC
steps to reproduce:
1. delete the topics.json_en.cache file in your data/khan folder
2. set DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True in local_settings.py or your way of assigning tags
3. start kalite server
4. go to learn page and you will see an empty sidebar

**Comment by radinamatic** [comment] 2015-07-16 18:34
Since @66eli77 labeled this with `bug bash` I'm guessing he was experiencing it on 0.14. Just to confirm it's happening on **develop** too.

**Comment by benjaoming** [comment] 2015-07-18 01:12
I'm seeing the same in alpha9.

**Comment by benjaoming** [comment] 2015-07-18 01:22
Problem is this:

``` 
WARNING:kalite:Annotated exercise cache file failed in saving with error [Errno 13] Permission denied: '/usr/share/kalite/data/khan/exercises.json_en.cache'
INFO:kalite:Preloading content data for language en.
WARNING:kalite:Annotated content cache file failed in saving with error [Errno 13] Permission denied: '/usr/share/kalite/data/khan/contents.json_en.cache'
INFO:kalite:Preloading topic tree data for language en.
WARNING:kalite:Annotated topic cache file failed in saving with error [Errno 13] Permission denied: '/usr/share/kalite/data/khan/topics.json_en.cache'
``` 

These files cannot be in that location, they have to be treated as user data.

**Comment by benjaoming** [comment] 2015-07-20 11:54
Okay I'm going to work on the issue about saving cache files in a system-location.

@rtibbles if there are other causes of this bug, feel free to work on them concurrently, otherwise I'll let you know if this resolves the issue...

**Comment by benjaoming** [comment] 2015-07-20 15:18
Issue is resolved in the PR, I made a bunch of commit amendments, hence the odd list of commits above.

**Comment by MCGallaspy** [comment] 2015-07-22 23:55
@66eli77 can you try to reproduce this now that #4122 has been merged into `develop`?

**Comment by 66eli77** [comment] 2015-07-24 04:43
@MCGallaspy I make sure there is no topics.json_en.cache in my data/khan folder, then set DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP = True in local_settings.py  and start the server with ./bin/kalite start, when open the learn page, the sidebar is populated.

**Comment by benjaoming** [comment] 2015-07-24 11:08
@66eli77 FYI the cache files have been moved, that was part of the fix: They now live in ~/.kalite/cache

**Closed** 2015-07-24 11:08 UTC
Labels: 0.14.x bug bash, has PR, release blocker
