### ISSUE TITLE
Raspberry pi new install, database permission and port errors

### ISSUE THREAD

**Issue by darinlh** [learningequality/ka-lite#2695] opened 2014-11-16 07:17 UTC
I could use some help figuring this out, leaning towards a "ownership" issue vs permissions.

Any leads would be appreciated.

Fresh install of raspberry pi

followed https://learningequality.org/ka-lite/user-guides/install-guide-012

the pi is on connected to the internet via eth1
downloaded and installed from home directory 

error 
*************************************
pi@raspberrypi ~/ka-lite/ka-lite $ /home/pi/ka-lite/ka-lite/start.sh

Trying to start the web server.
INFO:kalite:RPi package selected.
DatabaseError: attempt to write a readonly database
Error: The web server was not started
pi@raspberrypi ~/ka-lite/ka-lite $

************************************

**Comment by jamalex** [comment] 2015-02-05 02:04
The problem is that in `setup_unix.sh` we just have:
`we_are_rpi=""`
when it should instead be detecting whether we're on an RPi, and putting the result in there. Hence, it never prompts to run the optimizations.

**Comment by darinlh** [comment] 2015-02-05 02:07
Thanks for catching that, I will do another top to bottom run this weekend and follow up with the results.

**Comment by jamalex** [comment] 2015-02-05 02:09
Note that we haven't fixed this yet, but I've flagged it so that it will be fixed in the latest, upcoming 0.13 release.

**Comment by darinlh** [comment] 2015-02-05 02:12
Ok will hold back for a bit, may wait until I have the new Rpi to run through, ie Raspberry Pi 2

**Comment by cpauya** [comment] 2015-03-06 02:48
@aronasorman I'm interested to work on this but I have hardware constraints... I can buy a Raspberry Pi but cannot find the wifi dongles as per documentation (Raspberry Pi WiPi adaptor or Edimax EW-7811Un).

Maybe we can test this even when using other wifi dongles (will look-up compatible ones on my area)?  I read above that we need to test that the RPi optimizations are run, I'll go ahead and order my Pi. :smiley_cat:

**Comment by jamalex** [comment] 2015-03-07 21:03
@cpauya Should be able to do this without a WiPi, just accessing it via Ethernet. The optimizations are related to setting up nginx, local_settings.py, etc.

**Closed** 2015-03-19 17:34 UTC
Labels: bug, release blocker
