### ISSUE TITLE
Video will not playback in Chrome for Android

### ISSUE THREAD

**Issue by Kevsy** [learningequality/ka-lite#5331] opened 2016-10-18 11:42 UTC
## Summary

A video will not have the 'play' button overlay on Chrome for Android - it is not possible for the user to play the video from within the browser. However the video can be saved for offline viewing in the system player.
## System information

_Please specify the KA Lite version you were using and your operating system!_
- Operating system: Ubuntu 14.04
- Version: 0.16.9
- Browser: Chrome for Android 53.0.2785.124, Android version 6.0.1
## How to reproduce
1. Navigate to a video with Chrome for Android
2. (success case) Navigate to same video using system browser
## Screenshots

Screen recording attached

Many thanks!
[no_chrome_android_playback.zip](https://github.com/learningequality/ka-lite/files/536085/no_chrome_android_playback.zip)

**Comment by Aypak** [comment] 2016-11-05 19:50
Hi @Kevsy , this could be due to not having the right permissions on the content directory. Try to make the directory world read/writable
`sudo chmod a+rw -R ~/.kalite`

**Comment by benjaoming** [comment] 2017-04-22 19:04
In #5349 we upgraded videojs, it's been released in 0.17.

I can confirm the following: The first time that I loaded a page with a video (Android X86 6.0R1 w/ Chrome 44.0), the video area was blank... when I scrolled downwards, it appeared. After that, videos have been appearing instantly.

I hope your issue is solved in 0.17, thanks for reporting and please invited to say in case it's persisting. And sorry that we have these issues, it's extremely complex to support video playback on all platforms, but we do our best to choose the most general solutions.

**Closed by benjaoming** 2017-04-22 19:04 UTC
