### ISSUE TITLE
Server not starting -database file already exists

### ISSUE THREAD

**Issue by MIchaelPStimpson** [learningequality/ka-lite#5416] opened 2017-02-20 23:25 UTC
## Summary
Server not starting -database file already exists

*Briefly describe what this is about*
The server says WARNING: Database file already exists! when I try to run it from command line. It doesnt run when I try to start the server from the tray.
## System information

*Please specify the KA Lite version you were using and your operating system!*

 - Operating system: Windows 10
 - Version: 0.17.0
 - Browser: Google Chrome

I tried looking around, but didn't find much. How can I fix this?

**Comment by radinamatic** [comment] 2017-02-22 13:54
Hi @MIchaelPStimpson!

I was unable to replicate your issue while starting the server from the command line:

![virtualbox_msedge - win10_preview_22_02_2017_14_51_54](https://cloud.githubusercontent.com/assets/1457929/23214359/b14fb766-f90e-11e6-8a4d-2cd822dba498.png)

Could you provide some additional details about your setup to help us debug the problem?

**Comment by MIchaelPStimpson** [comment] 2017-02-22 13:56
I had an issue with my first installation. I uninstalled and tried to reinstall, but it says the database already exists. I assume I just have to delete the old database or maybe run it without it trying to make a new one?

**Comment by radinamatic** [comment] 2017-02-22 14:03
If you do not have any important data on your first installation (like registered users, coach reports, etc.), you can overwrite the existing database.

I'm curious why do you use command line for installation, instead of running the installer... Could you make a screenshot of the command you used and the error message that says `WARNING: Database file already exists!`? Thanks!

**Comment by MIchaelPStimpson** [comment] 2017-02-22 14:13
I start the server and it says starting, but then nothing happens and I can't stop or start the server. When I check http://127.0.0.1:8008/ I see this screen
![image](https://cloud.githubusercontent.com/assets/10071798/23215078/b4d90622-f8d6-11e6-8c39-5da34e3c25da.png)

![image](https://cloud.githubusercontent.com/assets/10071798/23215006/6e4fb6ce-f8d6-11e6-803c-4d4e1aa2d26b.png)

I thought maybe if I used command line I could see what the problem was..

**Comment by benjaoming** [comment] 2017-02-22 14:19
`WARNING: Database file already exists!` is harmless, just means that a database is already there.

You can refer to your `server.log` file - it should contain information as to why the server isn't starting. It lives in the `.kalite` folder in your  home directory.

**Comment by MIchaelPStimpson** [comment] 2017-02-22 14:22
The only thing in the file was this..
[INFO] [2017-02-22 08:09:20,122] kalite: Setting up KA Lite; this may take a few minutes; please wait!
It's been running for the last 20 minutes and I have a good computer.

**Comment by benjaoming** [comment] 2017-03-16 13:44
@MIchaelPStimpson the server isn't supposed to be responding while you see `kalite: Setting up KA Lite; this may take a few minutes; please wait!` and no message that it has ended that process.

Do you see anything following this message, indicating what the current process is about - or does the log end with this message and no other messages after 20 minutes?

(p.s. sorry, I've been away for the past weeks doing deployments of KA Lite)

**Comment by benjaoming** [comment] 2017-03-30 12:58
@radinamatic we can try to replicate this by:

1. Installing KA Lite
1. Removing it
1. Installing it again

...to see if an existing database will cause the issue.

**Comment by radinamatic** [comment] 2017-04-12 11:10
Now that I think of it I don't believe I've ever seen the message `WARNING: Database file already exists!` in 2 years testing KA Lite, and unsurprisingly, I did not see it while replicating the steps recommended by @benjaoming above... 🤔

@MIchaelPStimpson Did you install the version 0.17 for the first time or you had some older versions and you tried to upgrade to 0.17?

**Comment by benjaoming** [comment] 2017-04-13 11:54
We can't reproduce it, not saying that it's invalid, but just that we can't fix it when we can't reproduce it and don't have sufficient information to diagnose it. I'm closing this for now.

HOWEVER! In 0.17.2, there will be additional logging for the automatic initialization of the server, so in case the error persist for @MIchaelPStimpson, there will be an option then to reopen with more information. See #5408

**Closed by benjaoming** 2017-04-13 11:54 UTC
