### ISSUE TITLE
get_uuid error on video exit

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3227] opened 2015-03-10 20:34 UTC
Branch: develop
Browser: Firefox 35

![screen shot 2015-03-10 at 1 30 54 pm](https://cloud.githubusercontent.com/assets/191955/6584661/fdf4f6e4-c729-11e4-9633-12b883e3604f.png)

Steps to reproduce:
1. Log in as admin
2. Visit unavailable video
3. Navigate away from video through sidebar
4. Watch the error pop up

**Comment by anuragkanungo** [comment] 2015-03-11 18:45
I am able to reproduce the error but still not debug the cause.
As the error is there because the user is None and I don't able to find why its not taking admin as the user in the request.

**Comment by aronasorman** [comment] 2015-03-11 20:23
Oh, I think the solution we want in here is to disable VideoLog API calls for admins.

**Comment by rtibbles** [comment] 2015-03-11 21:14
Yeah, this is caused by the save that gets triggered on the log when you navigate away from any content - in order to guarantee that any progress is recorded.

**Comment by anuragkanungo** [comment] 2015-03-11 21:29
@rtibbles , can you point where this save is happening ?

**Comment by rtibbles** [comment] 2015-03-11 22:17
distributed/static/js/distributed/content/views.js:185

**Comment by rtibbles** [comment] 2015-03-12 16:50
Fixed in #3269

**Closed by rtibbles** 2015-03-12 16:50 UTC
Labels: 0.13.x bug bash, bug, release blocker
