### ISSUE TITLE
Progress bar is not showing when downloading a video.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#4430] opened 2015-09-15 11:54 UTC
**Branch:** `Master (0.15.x)` 

**Current Behaviour:** When downloading a video, the progress bar will not show until the video download is done.

**Expected Behaviour:** Progress bar must be shown when the video download starts.

**Step to Reproduce:**

1. Login as admin.
1. Click on video tab, and select a video you want to download in the topic tree.
1. Click on `Download` button.

**Screenshot**:

![screen shot 2015-09-11 at 5 46 02 pm](https://cloud.githubusercontent.com/assets/8664071/9812011/1a762e54-58ad-11e5-8e3e-d05dbadc691d.png)

In the screenshot, the progress bar will not show until video download is done.

**Comment by djallado** [comment] 2015-09-17 12:55
The same issue in https://github.com/learningequality/installers/issues/164.

**Comment by MCGallaspy** [comment] 2015-09-18 17:49
Is this version 0.14.0?

**Comment by cpauya** [comment] 2015-09-21 08:32
This is for 0.15.x @MCGallaspy - here's the latest update based on [KA-Lite-Monitor.dmg-2015-09-21a.zip](https://drive.google.com/open?id=0Bwf_-YL9LvlVUVdfb1Vrc2psYWs)... notice that the progress bars are there now but with no indicator of progress because of the javascript errors.

![screenshot 2015-09-21 16 27 31](https://cloud.githubusercontent.com/assets/175580/9987860/19f751a0-607e-11e5-9be1-e287d0618e5a.png)

**Comment by djallado** [comment] 2015-09-21 08:50
@MCGallaspy thats 0.15.x

**Comment by 66eli77** [comment] 2015-09-23 07:20
@djallado @cpauya  cannot reproduce the issue with current 0.15.x
but I did get the same error message
<img width="267" alt="screen shot 2015-09-23 at 12 16 39 am" src="https://cloud.githubusercontent.com/assets/5577205/10039625/e1f2f244-6188-11e5-9f61-afe15e28f6ce.png">
<img width="692" alt="screen shot 2015-09-23 at 12 17 02 am" src="https://cloud.githubusercontent.com/assets/5577205/10039626/e61a7ec8-6188-11e5-83f2-0ab27f6f3885.png">

**Comment by 66eli77** [comment] 2015-09-23 23:49
okey, I spot this issue when I only download 1 video with very fast network.

**Comment by 66eli77** [comment] 2015-09-24 07:21
this PR #4480 seems to fix the issue by reducing the progress-check interval

**Comment by rtibbles** [comment] 2015-09-24 17:50
Fixed in #4480

**Closed by rtibbles** 2015-09-24 17:50 UTC
Labels: bug, has PR
