### ISSUE TITLE
Ugly error message on Language page with unregistered device

### ISSUE THREAD

**Issue by Antrikshy** [learningequality/ka-lite#3270] opened 2015-03-12 16:36 UTC
I went to the Language tab in Manage while logged in as admin on an unregistered device and got this:

![screen shot 2015-03-12 at 9 36 06 am](https://cloud.githubusercontent.com/assets/6601788/6622673/51efa5ec-c89b-11e4-88b4-e14b05d09c50.png)

Known?

EDIT: I get the same thing when trying to register.

**Comment by MCGallaspy** [comment] 2015-03-12 22:32
Seems like a duplicate of #3232.

**Closed by MCGallaspy** 2015-03-12 22:32 UTC
