### ISSUE TITLE
Document the `kalite` command

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#4755] opened 2015-12-11 18:49 UTC
It's not well documented -- the usage is only mentioned briefly in the release notes. In particular when describing to a user how to run a management command, the instructions will vary depending on the OS. On Linux (and OSX?) the `kalite` command can be run from the user's terminal, whereas in Windows the `../Python27/Scripts/kalite.bat` script must be run. Issue inspired by a user's email.

**Comment by rtibbles** [comment] 2016-02-01 21:11
Duplicate of #4326

**Closed by rtibbles** 2016-02-01 21:11 UTC
Labels: documentation, ready
