### ISSUE TITLE
Silent MemoryErrors

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3541] opened 2015-04-23 00:14 UTC
Branch: develop

Debugging https://github.com/learningequality/ka-lite/pull/3519 has led to strange failures at the very end of the KA Lite startup process, inside a Vagrant Virtualbox VM with 495 MB available (the default for trusty32). It turns out that at the very end of our startup sequence, `kalite`'s memory usage spikes up to around 508 MB, making the OS kill it, but somehow not leading python to print out a `MemoryError`. 

This leads me to believe that somewhere in our code is an `except` clause which catches all errors, including `MemoryError`s, and that's where the spike is happening. 

To replicate:
1.  Download the `Vagrantfile` version [here](https://github.com/aronasorman/ka-lite/blob/4ebd58ccd43a51376f8f25895483c4d803c6dad0/Vagrantfile). Notice that it doesn't increase the memory of the VM whatsoever. So it defaults to 495 MB.
2. `vagrant ssh` into your vagrant machine to run the following commands inside your VM.
3. Start the server and download `fr` and `xh`.
4. Run `kalite restart`.

**Result**
At the very end, it would show a successful startup message:
```
INFO:kalite:Preloading content data for language xh.
INFO:kalite:Preloading topic tree data for language xh.

0 static files copied, 2828 unmodified.
To access KA Lite from another connected computer, try the following address(es):
	http://10.0.2.15:8008/
	http://192.168.33.10:8008/
	http://127.0.0.1:8008/
```

But then doing a `curl http://127.0.0.1:8008` would return `connection refused`, indicating that our server did not start up.

**Comment by benjaoming** [comment] 2015-05-01 21:33
@aronasorman is this fixed now then? Or is the issue more generally about the silent failure of the cherrypy daemon? Because I was able to quite reliably make the cherrypy server die and the main process continue thinking that it had been started... and I'm not quite sure how to fix it in a nice way because this happens after `become_daemon()` in `django_cherrypy_wsgiserver.cherrypyserver`.

**Comment by MCGallaspy** [comment] 2015-06-02 18:43
For this, I'm going to specify any unqualified except clauses. That should make it easier to hunt down future errors.

**Comment by MCGallaspy** [comment] 2015-06-04 18:47
It turns out tracking down fishy `except` blocks is tricky. I also can't reproduce this error as described; any tips?

**Comment by MCGallaspy** [comment] 2015-06-04 18:48
I'm guessing part of my trouble in reproducing it was that we reduced memory use, too :)

**Comment by benjaoming** [comment] 2015-06-04 21:51
@MCGallaspy you don't have to, just raise your own exception as I described... my conclusion was that this is a universal thing.

**Comment by MCGallaspy** [comment] 2015-06-05 16:34
@benjaoming @aronasorman okay, I'm able to consistently kill the server process now; as you said an exception raised after `become_daemon()` will do the trick. I suspect now the error isn't an uncaught exception, but rather that the main process keeps going even if the server dies.

**Comment by MCGallaspy** [comment] 2015-06-05 17:09
I also think `become_daemon()` is also redundant given we're starting the server with `subprocess.Popen`. Could be implicated in the process leaks, too.

**Comment by benjaoming** [comment] 2015-06-05 17:41
@MCGallaspy at some point, we need the daemon behavior for `kalite start`. I think the decision to keep it in `kaserve` was because that command needed to be able to do daemon stuff, too, but it's best handled in a single place since there should be a Windows alternative, too (not remembering of `become_daemon` is win compatible).

**Comment by MCGallaspy** [comment] 2015-06-05 17:42
How about:

* Remove `become_daemon` from `runcherrypyserver`
* "Daemonize" management commands using `Popen` options instead (and as a bonus redirect output to a log file)
* Optionally monitor the state of subprocceses thus opened and handle them gracefully, instead of quietly dying

**Comment by benjaoming** [comment] 2015-06-05 17:45
@MCGallaspy can you really do this with Popen? As I remember it, this approach was full of problems, too, when the main process exits.

There is an awful lot of stuff written about how to daemonize things in a cross-platform way, and it ain't pretty :(

**Comment by benjaoming** [comment] 2015-06-05 17:46
But I would agree that trying the approach could be cool.

If you want to redirect to a log file, perhaps make it an option for `kalite start --kalite-log=/var/log/kalite.log` ?

**Comment by MCGallaspy** [comment] 2015-06-06 19:58
@benjaoming 
Suppose it depends on what you mean by daemonizing, but if we just want to:
* Create a new process that won't die when the parent process quits
* Redirect output away from stdout & pals

Then yes, it can be done with Popen and the only OS-dependent gotcha I'm aware of is already accounted for (the extra kwarg in Windows). Regarding monitoring subprocesses I mean creating another subprocess that keeps track of known processes and kills them all under certain conditions (i.e. when the server process dies, kill the cronserver process and any others) -- there is definitely a process leak, I personally have had the server process die and the other child processes created by kalitectl stay alive, eating my memory.

**Comment by MCGallaspy** [comment] 2015-06-19 23:14
#3878 is a stop-gap solution for this. Kicking to 0.15.

**Comment by MCGallaspy** [comment] 2015-08-20 18:01
Stale.

**Closed by MCGallaspy** 2015-08-20 18:01 UTC
Labels: bug, performance
