### ISSUE TITLE
Wrong url in sidebar

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3844] opened 2015-06-12 23:16 UTC
Sometimes the links do not take you to the correct destination in the sidebar if there are items that have similar names. Here specifically I clicked the exercise "Numbers to 120" and it took me to the video "Missing numbers between 0 and 120", which is something that I hadn't even yet dowloaded on my computer: 

![wrong link](https://cloud.githubusercontent.com/assets/6668144/8141595/3de3dd40-111e-11e5-8570-3dd9a876e6ca.PNG)

**Comment by jtamiace** [comment] 2015-06-12 23:18
And once you navigate to the wrong link and open up the sidebar again, that wrong link becomes broken/unresponsive.

**Comment by rtibbles** [comment] 2015-06-13 00:31
Duplicate of #3807

**Closed by rtibbles** 2015-06-13 00:31 UTC
