### ISSUE TITLE
Mismatch between number of videos said will be downloaded and number then queued

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4990] opened 2016-03-11 15:53 UTC
## Summary

I was upgrading an installation with all the 0.15 videos to 0.16, and wanting to download just the new videos. At first, the download button claimed only 411 new videos to download, but once the download began, it showed 7000+ in the queue.

It seems to be queuing all selected videos, rather than just the ones that are new?

## Branch or installer method

 - Branch: 0.16.x

## How to reproduce

1. Run 0.16.x branch from source, with content directory already containing many videos
1. Go to video download page, and select all topics, and start download.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/618416/13707351/1437ae88-e75e-11e5-8d5d-ba76019199e8.png)

![image](https://cloud.githubusercontent.com/assets/618416/13707363/234a4ab6-e75e-11e5-887d-5ad24f27b1a2.png)

**Comment by rtibbles** [comment] 2016-03-11 16:14
Duplicate of #4929 which was fixed in https://github.com/fle-internal/content-pack-maker/commit/00d88694fb767898ac765ac20d87e670ff408807

When did you last update your content pack?

**Comment by jamalex** [comment] 2016-03-11 16:26
3 times in a row prior to trying this (was having some other issues; also
couldn't get things to run without having run make dist). It was actually a
fresh install from last night, with the videos copied in before running any
commands. Content pack must have been latest from pantry server?

**Comment by jamalex** [comment] 2016-03-11 16:30
I ended up just going with the minimal content pack, I think, however.
Maybe it's older?

**Comment by jamalex** [comment] 2016-03-11 18:36
Let's leave this open until we can confirm the newest content packs solve the problem (once they're uploaded).

**Comment by MCGallaspy** [comment] 2016-03-16 21:58
Double checking now.

**Comment by MCGallaspy** [comment] 2016-03-17 00:29
Not fixed. Here's what I did:

1. Installed 0.15.1
2. Downloaded 10 videos
3. Upgraded to 0.16 using Windows installer from March 14 -- so the contentpack should be up to date-ish? Depends on what's on the build server then.
4. Selected 20 videos (10 previously downloaded) -- initially the menu showed 10 to be downloaded.
5. Clicked the download button, 20 downloads queued up:
![image](https://cloud.githubusercontent.com/assets/8888020/13832776/a16e853c-eb9c-11e5-9178-f97622d46d52.png)

**Comment by MCGallaspy** [comment] 2016-03-17 00:30
@rtibbles should the diff you linked be reflected on the build server content packs?

**Comment by MCGallaspy** [comment] 2016-03-17 22:28
Still extant even with the latest content pack from the download server. Looking into it now.

**Comment by rtibbles** [comment] 2016-03-25 23:40
Fixed in #5045

**Closed by rtibbles** 2016-03-25 23:40 UTC
Labels: bug, has PR, release blocker
