### ISSUE TITLE
Error message along with update command shown when trying to register device or when language section is accessed

### ISSUE THREAD

**Issue by tarunsharma1** [learningequality/ka-lite#3197] opened 2015-03-08 17:08 UTC
Branch :develop
Current Behavior: When signed in as super user and 'register your device' or the 'language' button (next to facilities and videos buttons in manage area) is clicked, an error outputing large html code is generated and also the faulty update command is asked to be run i.e python manage.py update.
On clicking the language button it asks you to register your device first but when register my device is clicked the same thing shows up.
![screenshot 104](https://cloud.githubusercontent.com/assets/8834964/6546709/93f62232-c5e3-11e4-8f49-1de2c6c26780.png)
Expected behavior : A nice clean error and no references to the faulty update command.
Steps to reproduce: Login as superuser
Click on the manage section on the top right corner
Next to the buttons facilities and videos, hit the button saying language.

**Comment by anuragkanungo** [comment] 2015-03-09 14:15
I believe this problem is because the Central Server is down today. (hub.learningequality.org)

But, surely we need to catch the error and display it in a cleaner way.

**Comment by aronasorman** [comment] 2015-03-09 15:57
Yeah, we'll need a more graceful way to handle this when the central server is down. Doesn't have to be a blocker for release though, so I've set this to 0.14, and then we can cherry-pick this for a 0.13 bugfix, if needed.

**Comment by anuragkanungo** [comment] 2015-03-12 15:05
@aronasorman,

I am facing this Issue now though I am able to reach learningequality.org .
So, possible error cause could be something else as well.

**Comment by tarunsharma1** [comment] 2015-03-12 15:07
Yes I'm facing this error too....when i click the languages button i get the error and it says please register device..and when i try to register also i get the same error and a request to update

**Comment by timon-langlotz** [comment] 2015-03-12 17:47
I have the same error. Is the hub still down? Tried to ping it, no response.

**Comment by radinamatic** [comment] 2015-03-12 17:52
Same over here, on both Videos and Language tabs.

**Comment by aronasorman** [comment] 2015-03-12 17:57
Ok, critical. @jamalex

**Comment by MCGallaspy** [comment] 2015-03-12 23:11
@jamalex in 0.12.10 I keep getting the same error, even with "fresh" databases. Leads me to believe its a genuine error with the central server.

**Comment by MCGallaspy** [comment] 2015-03-13 02:29
The default central server instance that we're running uses a backend (MySQL) that wasn't well-tested during development. #3253 should fix this issue once the central server's submodule has been updated.

**Comment by yohanboniface** [comment] 2015-03-15 12:19
Is there a workaround in between #3253 is shipped? I've a fresh install from today and I'm facing the same issue.

**Comment by yohanboniface** [comment] 2015-03-15 18:49
I've tried to switch to develop, but then I've hit #3302, and after a workaround I'm back on this one.

So is there any sort of stable branch/tarball/whatever I can use if I want to install on a Sunday, or given that it seems to affect the "central server" I'm shot?

**Comment by jamalex** [comment] 2015-03-16 03:47
@yohanboniface Working on a fix to the central server now, in https://github.com/learningequality/ka-lite/pull/3306 -- merging and launching shortly!

**Comment by jamalex** [comment] 2015-03-16 05:45
Central server should now be fixed (testing a one-click registration and it worked for me) -- please confirm that it works for you now as well, and we can (re-)close this issue. Thanks!

**Comment by yohanboniface** [comment] 2015-03-16 07:21
\o/

@jamalex it works, thanks a lot! :)

(Off topic note: is there any active IRC chan? I didn't reach one.)

**Comment by aronasorman** [comment] 2015-03-16 22:32
Hi @yohanboniface -- 

we're active on HipChat: https://www.hipchat.com/gzQfGFgv1

**Closed** 2015-03-16 22:32 UTC
Labels: beginner, bug, release blocker

**Comment by anuragkanungo** [comment] 2015-03-17 07:14
There have been different issue now, as pointed by @sharprakeshverma
Looking into it
![screenshot from 2015-03-17 12 42 15](https://cloud.githubusercontent.com/assets/4207886/6682787/54802866-cca3-11e4-843e-0fc4ef6bb235.png)

**Comment by anuragkanungo** [comment] 2015-03-17 07:29
The value of settings.CENTRAL_SERVER is False, which is throwing error

**Comment by anuragkanungo** [comment] 2015-03-17 07:33
In settings.py , we have
CENTRAL_SERVER = False  # Hopefully will be removed soon.

**Comment by anuragkanungo** [comment] 2015-03-17 07:40
We need settings.CENTRAL_SERVER_HOST there. 
This will work fine, if we don't have if DEBUG =True in local_settings.

But if DEBUG= True, then

I get error: [Errno url error] unknown url type: 'adhoc.learningequality.org'
We need our url to be like http://adhoc.learningrquality.org

**Comment by yohanboniface** [comment] 2015-03-18 15:11
Same error here ([Errno url error] unknown url type: 'adhoc.learningequality.org') when trying to register another server (on develop, but I will switch to master).

Is KA-lite unittested somehow?

**Comment by yohanboniface** [comment] 2015-03-18 15:25
Switched back to master, removed the database, rerun the `setup_unix.sh`, and now I'm back on the initial issue when trying to register:
![screenshot from 2015-03-18 16 23 45](https://cloud.githubusercontent.com/assets/146023/6712112/2c0987a4-cd8b-11e4-93f8-76d9e78cb8ba.png)

Is central server broken again, or is me missing a point? :s

**Comment by yohanboniface** [comment] 2015-03-18 17:10
OK, that was caused by my "DEBUG = True" local_settings.py file. Thanks @aronasorman for help!
