### ISSUE TITLE
Cannot launch KA Lite on Windows 7

### ISSUE THREAD

**Issue by Mufasa-yang** [learningequality/ka-lite#4005] opened 2015-07-03 01:01 UTC
OS:Windows 7 ultimate 32bits
version: 0.14.0

I downloaded installer from  http://field.learningequality.org/KALiteSetup-0.14.0.exe
and followed installer's instruction to finish setup, including Python automatic installation.
When all finished, I double clicked the icon on desktop, nothing happened but a leaf icon appeared on the right side of taskbar. I right clicked it and then clicked start server. Still nothing happened. 

during installation, this pop-up warned something but I don't know what it is
![error](https://cloud.githubusercontent.com/assets/13158538/8490820/4dcb6a9a-20e4-11e5-86c4-30bda2eaf0e5.png)

**Comment by radinamatic** [comment] 2015-07-03 01:08
I reported the same in #74.

**Comment by radinamatic** [comment] 2015-07-03 01:10
And it also was W7 32bits.

**Comment by MCGallaspy** [comment] 2015-07-03 01:15
@Mufasa-yang closing because it's a duplicate of https://github.com/learningequality/installers/issues/74, as @radinamatic says. If you are able to reproduce this reliably, please post the details in that thread.

**Closed by MCGallaspy** 2015-07-03 01:15 UTC
Labels: Windows
