### ISSUE TITLE
Screenshots in documentation are often too small to read (with no way to expand)

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#4030] opened 2015-07-06 01:10 UTC
Branch: 0.14.x/develop?

It looks like something changed in the way screenshots are captured, from 0.13 to 0.14 -- if you compare the old docs:
https://learningequality.org/docs/usermanual/userman_admin.html#user-management
with the new docs:
http://field.learningequality.org/develop/docs/usermanual/userman_admin.html#user-management
you can see that the resolution of the screen in the screenshot seems to have been increased, making the text two hard to read.

Two suggestions:
- Sort out the resolution issue, to render at a more readable scale.
- Allow the images to be clicked on to pop up a larger version (it looks like the images are actually big, but there's no way to expand them without right-click tricks).

**Comment by benjaoming** [comment] 2015-07-06 02:05
It seems to be an issue with pyvirtualdisplay :

        # Start a virtual headless display
        display = Display(visible=0, size=(1024, 768))
        display.start()

That should create a 1024x768 display, but the screenshots seem to be from a much larger window, I think the problem is here:

        # Selenium won't scroll to an element, so we have to make the window size is large enough so that everything is visible
        self.browser.set_window_size(1920, 1080)
        self.browser.implicitly_wait(3)

So instead of resizing the window, we could just maximize it and use javascript and jquery to scroll to the position of the element being captured *or* add an option for scrolling to the screenshot directive.

**Comment by benjaoming** [comment] 2015-07-06 02:16
Have a solution for this, building now, uploading in the morning!

**Comment by MCGallaspy** [comment] 2015-07-10 00:12
Fixed in #4075.

**Closed** 2015-07-10 17:45 UTC
Labels: documentation, has PR, release blocker
