### ISSUE TITLE
Points seen on dropdown is added twice as we earn them

### ISSUE THREAD

**Issue by mascot6699** [learningequality/ka-lite#4643] opened 2015-10-23 18:29 UTC
This is seen on develop branch.

Steps to reproduce.
1) Login as learner. 
2) See start any excercise and before answering note the point you have.
3) Solve a question. Note your points again. It will be equal to previous points plus twice the points earned in dropdown.

**Comment by MCGallaspy** [comment] 2016-02-08 23:37
I think this was resolved -- let me look through old PRs.

**Comment by MCGallaspy** [comment] 2016-02-19 23:21
On `0.16.x` I don't gain *any* points, sadly. Now looking in to this.

**Comment by MCGallaspy** [comment] 2016-02-25 22:23
Near as I can tell, I gain *no* points because the content item model doesn't define a `basepoints` field: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/topic_tools/content_models.py#L36

On the front-end, exercise models define the default value of basepoints to be 0: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/distributed/static/js/distributed/exercises/models.js#L24

ExerciseDataModel extends ContentDataModel, whose url is defined here: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/distributed/static/js/distributed/content/models.js#L55

So seemingly the basepoints field was dropped from content items? Or perhaps the basepoints for exercises *had* been calculated differently, but I'm having a hard time determining it from the commit history. Any insight?

**Comment by MCGallaspy** [comment] 2016-02-25 22:26
Seems to also be affecting videos -- I don't accumulate points for watching them.

**Comment by radinamatic** [comment] 2016-02-25 22:37
I'm watching a video right now and it seems to be adding points just fine, @MCGallaspy 
Alpha4 deb installer on Ubuntu, will retest on Windows (build 150) in a minute.

**Comment by radinamatic** [comment] 2016-02-25 22:44
Confirmed to be working on Windows 7 with build 150.
Are you having these issues on 0.16 branch?

**Comment by MCGallaspy** [comment] 2016-02-25 22:45
Yes, I am.

**Comment by shubhsingh594** [comment] 2016-02-26 05:18
can i work on this issue ?

**Comment by shubhsingh594** [comment] 2016-02-26 18:05
on the 0.16.x branch the score doesn’t update and remains as 0 through the exercise.

**Comment by MCGallaspy** [comment] 2016-02-26 18:34
@shubhsingh594 hold off, I'm actively working on this one already

**Comment by rtibbles** [comment] 2016-03-07 18:12
@MCGallaspy basepoints should be building on latest contentpacks - have you been able to replicate this?

**Comment by MCGallaspy** [comment] 2016-03-07 22:08
Yeah, now I'm able to replicate the behavior.

**Comment by rtibbles** [comment] 2016-03-09 01:03
Fixed in #4970

**Closed by rtibbles** 2016-03-09 01:03 UTC
Labels: bug, has PR, release blocker
