### ISSUE TITLE
Alignment bug for "get language pack" button

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3102] opened 2015-02-23 23:09 UTC
Logged in as teacher or admin, placement of button is a bit off. Also messes up at different screen size

![language alignment](https://cloud.githubusercontent.com/assets/6668144/6339786/ef8bb54c-bb6d-11e4-87f0-02c76c5ec083.PNG)

**Comment by MCGallaspy** [comment] 2015-02-23 23:31
Duplicate of #3084.

**Closed by MCGallaspy** 2015-02-23 23:31 UTC
