### ISSUE TITLE
"ValueError: I/O operation on closed file" when syncing with 0.16

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5030] opened 2016-03-23 17:49 UTC
## Summary

Fresh install of 0.16 latest build on Windows 7, one attempt to sync to my sharing network:

![syncerrors016](https://cloud.githubusercontent.com/assets/1457929/13994846/f9c0668a-f126-11e5-9b3d-74f202ad48d4.png)

There's only one Default Facility, no users in it, I just changed its name before trying to sync. 

## Branch or installer method

0.16 Installer (build 184) on Windows 7

## Traceback

Sync session error details:
```
Checking purgatory for unsaved models...
Purgatory is model-free! Congrats!
Initiating SyncSession...
Syncing models...
Uploaded : 1 (0 failed, 0 error(s))
Downloaded : 27 (0 failed, 0 error(s))
Uploaded : 0 (0 failed, 0 error(s))
Downloaded : 0 (0 failed, 0 error(s))
Closing session... (Total uploaded: 1, Total downloaded: 41, Total errors: 0)
Checking purgatory once more, to try saving any unsaved models...
Purgatory is model-free! Congrats!
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
```

###### Facilities tab:
![syncerrors016-2](https://cloud.githubusercontent.com/assets/1457929/13994926/5081a9c0-f127-11e5-8073-faa84a4c046e.png)

###### What I see in my sharing network on `http://staging.learningequality.org/zone/`:

![syncerrors016-3](https://cloud.githubusercontent.com/assets/1457929/13994963/751ac654-f127-11e5-9b88-eb9d69e13480.png)

**Comment by radinamatic** [comment] 2016-03-23 20:15
@jamalex I just tried again (assuming your latest changes are on central server) to sync this facility after creating one Learner user and doing a few exercises.

![syncerrors016-4](https://cloud.githubusercontent.com/assets/1457929/13999333/2aa5f37c-f13c-11e5-837c-4f2a1620e491.png)


```
Checking purgatory for unsaved models...
Purgatory is model-free! Congrats!
Initiating SyncSession...
Syncing models...
Exception uploading models (in api_client): ValidationError, , ()
Uploaded : 0 (0 failed, 1 error(s))
Downloaded : 0 (0 failed, 0 error(s))
Closing session... (Total uploaded: 0, Total downloaded: 0, Total errors: 1)
Checking purgatory once more, to try saving any unsaved models...
Purgatory is model-free! Congrats!
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file _cplogging.py, line 280
Traceback (most recent call last):
File "C:\Python27\lib\logging\__init__.py", line 880, in emit
stream.write(fs % msg)
ValueError: I/O operation on closed file
Logged from file middleware.py, line 36
Upload error: {'exercise_id': [u'This field cannot be blank.']}
Completed with 1 errors.
```

I'm going to do another fresh install and create a new sharing network on my account to see if anything changes.

**Comment by jamalex** [comment] 2016-03-24 21:53
I renamed this to distinguish it from https://github.com/learningequality/ka-lite/issues/4989 (which is fixed in https://github.com/learningequality/ka-lite/pull/5039).

The remaining issue for me here is the "ValueError: I/O operation on closed file" message being emitted when it tries to log. I'm unable to replicate this locally, however, on Ubuntu, when running from source (using either `runserver` or `start`). Can you describe the OS and installation method, as well as more of the steps to replicate, @radinamatic?

**Comment by jamalex** [comment] 2016-03-24 21:55
Also, if you sync and there are no errors (you'll need to use a fresh DB), does the `I/O operation on closed file` error make it show up as red and failed, or does the syncing process appear to succeed in that case?

**Comment by jamalex** [comment] 2016-03-25 00:53
From our testing, only seems to happen on Windows.

Error is in the following code in `c:\python27\lib\logging\__init__.py`:

```python
class StreamHandler(Handler):
    """
    A handler class which writes logging records, appropriately formatted,
    to a stream. Note that this class does not close the stream, as
    sys.stdout or sys.stderr may be used.
    """

    def __init__(self, stream=None):
        """
        Initialize the handler.

        If stream is not specified, sys.stderr is used.
        """
        Handler.__init__(self)
        if stream is None:
            stream = sys.stderr
        self.stream = stream

    def flush(self):
        """
        Flushes the stream.
        """
        self.acquire()
        try:
            if self.stream and hasattr(self.stream, "flush"):
                self.stream.flush()
        finally:
            self.release()

    def emit(self, record):
        """
        Emit a record.

        If a formatter is specified, it is used to format the record.
        The record is then written to the stream with a trailing newline.  If
        exception information is present, it is formatted using
        traceback.print_exception and appended to the stream.  If the stream
        has an 'encoding' attribute, it is used to determine how to do the
        output to the stream.
        """
        try:
            msg = self.format(record)
            stream = self.stream
            fs = "%s\n"
            if not _unicode: #if no unicode support...
                stream.write(fs % msg)
            else:
                try:
                    if (isinstance(msg, unicode) and
                        getattr(stream, 'encoding', None)):
                        ufs = u'%s\n'
                        try:
                            stream.write(ufs % msg)
                        except UnicodeEncodeError:
                            #Printing to terminals sometimes fails. For example,
                            #with an encoding of 'cp1251', the above write will
                            #work if written to a stream opened or wrapped by
                            #the codecs module, but fail when writing to a
                            #terminal even when the codepage is set to cp1251.
                            #An extra encoding step seems to be needed.
                            stream.write((ufs % msg).encode(stream.encoding))
                    else:
                        stream.write(fs % msg)
                except UnicodeError:
                    stream.write(fs % msg.encode("UTF-8"))
            self.flush()
        except (KeyboardInterrupt, SystemExit):
            raise
        except:
            self.handleError(record)
```

Specifically, it happens for the `stream.write` commands. It seems the stdout/stderr stream handlers are getting closed in some way.

**Comment by jamalex** [comment] 2016-03-25 00:56
Seems the error is "famous":

```
                # Causes famous 'ValueError: I/O operation on closed file'
                # self.__logObjs[handlerClass][loggerName]['handler'].close()
```
(from [here](https://svn.apache.org/repos/asf/hadoop/common/tags/release-0.16.4/src/contrib/hod/hodlib/Common/logger.py))

**Comment by radinamatic** [comment] 2016-03-25 01:03
Or "infamous"?

**Comment by jamalex** [comment] 2016-03-25 02:08
Ok, I've narrowed this down, but don't have a solution yet. Will probably need @benjaoming's input.

What I know:

- The error is not caused by anything to do with the syncing system. Instead, the syncing system (and chronograph in particular) is simply picking up other things being written to `stderr` during the process of syncing. So, it's giving a window into something that's actually happening all the time.
- The errors being written to `stderr` come from attempts by other places in the code to output to `logging.getLogger('django.request')`. These logging attempts are made either in our `LogRequests` middleware or by Django itself (for when it displays 404's). Thus, the more you refresh the page and move around the site during the sync process, the more errors will be shown.
- It doesn't happen at all when KA Lite is run with `--foreground`. Perhaps it's when it's trying to write to the server.log file, which seems to be filled only with "I/O operation" errors and nothing meaningful.
- It only happens on Windows.

@benjaoming, I heard mention that you might have made some changes to logging for 0.16? This is one of our last remaining blockers; could you give any tips?

**Comment by radinamatic** [comment] 2016-03-25 02:23
> Perhaps it's when it's trying to write to the server.log file, which seems to be filled only with "I/O operation" errors and nothing meaningful. It only happens on Windows.

I did wonder why is Windows `server.log` so useless.

**Comment by jamalex** [comment] 2016-03-28 18:34
This is "fixed" by https://github.com/learningequality/ka-lite/pull/5056, by disabling logging output on Windows. I'll open a non-blocking issue for getting logging working on Windows.

**Comment by jamalex** [comment] 2016-03-28 19:24
@radinamatic Please test this once a new Windows build is out.

**Closed by jamalex** 2016-03-28 19:24 UTC
Labels: bug, has PR, release blocker
