### ISSUE TITLE
client browser crash (firefox)

### ISSUE THREAD

**Issue by craigleat** [learningequality/ka-lite#4606] opened 2015-10-12 15:33 UTC
branch: 0.14
client: firefox browser on android, 7" tablet

firefox crashes when trying to load a video. The crash occurs while the video is loading and before playback. chrome works fine.

**Comment by 66eli77** [comment] 2015-10-14 19:38
Tested on 
branch: develop and 0.15.x
client: firefox browser on android, 7" tablet 
the issue is not observed

**Comment by rtibbles** [comment] 2016-02-01 20:53
Assumed fixed by @66eli77's report.

**Closed by rtibbles** 2016-02-01 20:53 UTC
Labels: browser compatibility
