### ISSUE TITLE
bin/kalite does not support PyPy

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3399] opened 2015-03-24 15:27 UTC
It always drops down to python2. Which is slow.

**Comment by aronasorman** [comment] 2015-03-24 16:14
Also, KA Lite isn't working in PyPy.

**Comment by benjaoming** [comment] 2015-03-24 21:40
It just defaults to `python2` if it's in the path. But you can override that behaviour by setting a `KALITE_PYTHON` env.

**Comment by benjaoming** [comment] 2015-03-24 21:40
https://github.com/learningequality/ka-lite/blob/develop/bin/kalite#L72

**Comment by aronasorman** [comment] 2015-03-24 21:41
Yeah, was hoping it would default to PyPy (since it's a "faster" python), but looks like KA Lite doesn't even work on PyPy in the first place.

**Comment by alexkchan** [comment] 2015-04-11 18:53
Downloaded the latest version of PyPy off Brew, Ka-Lite seems to be working fine with the latest develop

**Comment by aronasorman** [comment] 2015-09-01 15:22
Wil be fixed once https://github.com/learningequality/ka-lite/issues/4315 has been implemented.

**Comment by benjaoming** [comment] 2016-09-20 16:14
PyPy will be dropped:
https://github.com/learningequality/installers/issues/417

But it's a duplicate of #4315 anyways

**Closed by benjaoming** 2016-09-20 16:14 UTC
Labels: beginner, new feature

**Comment by benjaoming** [comment] 2016-10-02 10:53
Fixed in `0.17`, releasing at the end of October. But work on installers can start now with the prerelease of 0.17b1.
