### ISSUE TITLE
User Manual poor navigability

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4984] opened 2016-03-10 18:33 UTC
## Summary

Once I click in the user manual tag, I have to solely rely on the browser back button to navigate back to kalite.

The ideal situation is that I can go back using some navigation UI within the page. One possible solution could be that we keep the top nav bar display when show the user manual

## Branch or installer method

 - Branch: 0.16.x

**Comment by MCGallaspy** [comment] 2016-03-11 17:51
Duplicate of https://github.com/learningequality/ka-lite/issues/4977

**Closed by MCGallaspy** 2016-03-11 17:51 UTC
Labels: accessibility, ux / frontend
