### ISSUE TITLE
Videos playback in English when French/another language is expected

### ISSUE THREAD

**Issue by trexken** [learningequality/ka-lite#4378] opened 2015-09-04 17:39 UTC
We are trying to build a laptop with French, English, and Spanish KA Lite on it.  All three packages are there and loaded.  When you try to view a French video it comes up in English. We have schools this application is needed for and works well in French only but now we have others asking for more.

Thanks

Ken

**Comment by MCGallaspy** [comment] 2015-09-04 17:45
Adding further details to this issue, since @trexken stopped by our hipchat room:

On version 0.14.0, on Mint Linux 17.2, @trexken said:

>  the challenge is we change the default language from say English to French try to run the video that it says is there and it comes up in English.  Say the basic counting of the squirrels.

**Comment by trexken** [comment] 2015-09-04 17:49
So here is the path I have.  For one of the videdos I think should be coming up in French and the default language is French...http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/counting-with-small-numbers/
At least this can give you the path and video I am using as an example.  Thanks again

**Comment by EdDixon** [comment] 2015-09-04 22:29
I think I may have just stumbled into this issue as well in windows 8.1. Apparently if you have downloaded a videos without first changing the default language for the installation then it will continue to download those same videos in the former language regardless of changes to the default language? I am still testing this but so far it seems to be the case? I hope this helps?

**Comment by aronasorman** [comment] 2015-09-10 22:41
@trexken Seems like the "counting squirrels" video is currently unavailable in French. The bug here is that it's still being shown as available otherwise.

**Comment by aronasorman** [comment] 2015-09-10 22:42
We'll get a fix for this.

**Comment by rtibbles** [comment] 2016-02-01 20:43
This should be fixed by content pack work. @radinamatic please check this in your testing for 0.16.

**Comment by radinamatic** [comment] 2016-02-02 01:03
Will do!

TIL to love GH issue filtering features... :heart_eyes:

**Comment by mrpau-eduard** [comment] 2016-10-11 07:45
Hi @aronasorman and @radinamatic .
I try to replicate the issue which I used French and Spanish packs, but it seems the issue is not available anymore. The "counting squirrels” in `fr` and `es` dubbed video is working correctly. I was able to play the `fr` and `es` dubbed video for "counting squirrels”.

Do you have any idea how I can reproduce the issue which the videos for french packs are in English?

**Comment by radinamatic** [comment] 2016-10-11 07:49
@mrpau-eduard This issue is so old and pre-contentpacks that I'm not surprised it cannot be replicated. 

@trexken We are closing this for now. Please update your installation to 0.16.9 and file a new issue if this re-occurs.

**Closed by radinamatic** 2016-10-11 07:49 UTC
Labels: bug
