### ISSUE TITLE
UX issue: "Move to top" option should be introduced for long exercises and pages

### ISSUE THREAD

**Issue by sopu** [learningequality/ka-lite#3443] opened 2015-03-30 08:55 UTC
branch : develop

Current behavior: When any long exercise is loaded the page tries to scroll to the first MCQ option for example. So user has to scroll up to see the question.

Expected behavior: There should be a "move to top" button to improve UX.

**Comment by MCGallaspy** [comment] 2015-05-26 17:54
@sopu can you specify an exercise where this is an issue?

**Comment by MCGallaspy** [comment] 2015-05-26 17:55
Looks like this is a duplicate of #3444.

**Closed by MCGallaspy** 2015-05-26 17:55 UTC
Labels: enhancement
