### ISSUE TITLE
Cant register because Client device must be self-signed with a signature matching its own public key 

### ISSUE THREAD

**Issue by YourCyborg** [learningequality/ka-lite#2470] opened 2014-10-11 01:56 UTC
Fresh KA Lite install on Arch Linux for personal use. The server is being manually launched with ./start.sh each time in /home/matt/Apps/ka-lite. Google brought me to someone who had the same thing happen to them, and it was closed as manually launching the server prevented this problem.

https://github.com/learningequality/ka-lite/issues/2430

Upon signing in as an administrator and clicking on 'videos' to download some, I get the following after attempting registration:

Sorry, there was an error during registration. Please make sure your device is fully up to date (run python manage.py update and then stop/start the server).

The error message was: Client device must be self-signed with a signature matching its own public key.

This is what I get when I try doing python manage.py update.
[matt@arch ka-lite]$ cd kalite
[matt@arch kalite]$ python manage.py update
Traceback (most recent call last):
  File "manage.py", line 58, in <module>
    from django.core.management import execute_from_command_line
  File "/home/matt/Apps/ka-lite/python-packages/django/core/management/__init__.py", line 5, in <module>
    import imp
  File "/usr/lib/python3.4/imp.py", line 19, in <module>
    from importlib._bootstrap import SourcelessFileLoader, _ERR_MSG, _SpecMethods
ImportError: No module named 'importlib._bootstrap'

Anyone have any idea how to fix it?

**Comment by EdDixon** [comment] 2015-01-12 04:55
Experiencing this on iMac (python 2.7.6) after git master pull and checkout of develop with leq origin, @cpauya what does the label ready here represent and how best mitigate here for testing?

**Comment by cpauya** [comment] 2015-01-12 04:59
Hi @EdDixon - the `ready` label is the `This week` column at the [Waffle site](https://waffle.io/learningequality/ka-lite) of the project.  

Can't exactly remember why I have that there but I think I was supposed to work on it but got re-prioritized on other tasks.

**Comment by cpauya** [comment] 2015-01-12 05:01
I have dragged it back to the `Backlog` column at the [Waffle site](https://waffle.io/learningequality/ka-lite) (thus the `ready` label was removed as above) so we don't get confused.

**Comment by EdDixon** [comment] 2015-01-12 05:07
Cool and thanks! In the meantime I could try a completely fresh install which I think will resolve it here to get things working but, it might be best to leave it broke in order to test a proper fix? From the error messages it seems we need to either re-associate the old key to the deployment or (easier) generate a new one. Do you know which maybe the preferred solution or if this is being dealt with in some other way?

**Comment by EdDixon** [comment] 2015-01-12 05:26
On further testing found wiping all associated keys from (host) /config/settings and re-installing allowed registration 0.13.

**Comment by cpauya** [comment] 2015-01-12 05:35
Nice one @EdDixon!  I wasn't able to reproduce this but you are right that the keys are at http://127.0.0.1:8008/admin/config/settings/ - so reinstalling (or deleting the database then running setup again) would generate those keys.

There's also a management command `generatekeys` as:

```bash
Usage: manage.py generatekeys [options]

Generate a new public/private keypair
```
@aronasorman / @jamalex can this be used to "generate new set of keys" instead of reinstalling?

**Comment by aronasorman** [comment] 2015-01-13 21:37
I think that works, but just running setup / start.sh should also generate the keys when it's not there.

**Comment by EdDixon** [comment] 2015-01-14 07:21
@Aron right, this in regards to a git upgrade from .12 to .13 which seems
to require the new key be generated. If it is not there as in a new install
it should and I am sure would be automatically generated.

On Tue, Jan 13, 2015 at 2:37 PM, Aron Fyodor Asor <notifications@github.com>
wrote:

> I think that works, but just running setup / start.sh should also generate
> the keys when it's not there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/2470#issuecomment-69825128>
> .
>



-- 
Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE <https://learningequality.org/give/>, Support FLE via Amazon
Smile! <http://smile.amazon.com/ch/46-2676188>
M (575)-636-9549

**Comment by MCGallaspy** [comment] 2015-01-30 01:09
Okay, I've been looking at this and it seems like the steps to reproduce are:

1. Install 0.12 by running the setup scripts
2. Upgrade to 0.13 by pulling the source
3. Try to start the server
4. Experience error

Is that it?

**Comment by MCGallaspy** [comment] 2015-02-04 01:02
Attempted steps to reproduce:
1. Pull 0.12 and run setup scripts
2. Start server, login, and register
3. Run `python manage.py update git`
4. Start server

Still no error. Not able to reproduce this :::((((

**Comment by EdDixon** [comment] 2015-02-24 10:47
Maybe tied to issue 3116 just created involving line feeds when using windows installer.

**Comment by MCGallaspy** [comment] 2015-02-24 17:51
@EdDixon I'm not so sure, this issue doesn't seem specific to Windows.

**Comment by EdDixon** [comment] 2015-02-24 18:11
@MCGallaspy right you are here just have not encountered this first hand until dealing with broken batch scripts from the windows installer but your right original was Arch Linux!

**Comment by EdDixon** [comment] 2015-02-25 22:44
OK keeping in mind the OP was in regards to Arch Linux, this error has now presented itself on all platforms (except R-Pi / Android) as far as I know. Today after building clean windows installer per that GIT instruction and attempting to run I reproduced this error by:

1) running GUI installer and completing all prompts (this included installing the bundeled python no python previously installed)
2) starting the KA-Lite server (will occur either way but this particular one was from sys tray)
3) using systray to login into server where greeted with login prompt
4) login where registration error attached is presented
5) following those instruction running: python manage update, stoping and starting the server then trying to login again
6) which brings another error message showing what looks to be the full page raw html content in the message. (also attached)

You will notice in the screen shots I am in 8.1 but the same procedure and out comes also happens in windows 7 and XP. As far as I am aware a git install avoids this issue but testing for that next.

Hope this helps!

**Comment by MCGallaspy** [comment] 2015-03-13 01:37
Closing because up to now I haven't been able to reproduce the original issue, and the latest error is probably a duplicate of #3197.

**Comment by jamalex** [comment] 2015-04-09 19:24
Still extant, just very obscure replication conditions:
- Instantiate a `FacilityGroup` on the central server
- Try to register a Device to the central server that contains a description

Fix coming shortly!

**Closed** 2015-04-28 00:18 UTC
Labels: bug, has PR, release blocker
