### ISSUE TITLE
"service ka-lite start" starts...?

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4549] opened 2015-10-01 01:27 UTC
"service ka-lite start" starts...?

 **Branch**: 0.15, **ka-lite_0.15~b2-0ubuntu1_all.deb** installer  on Ubuntu 15.04

At this point I'm not even sure if this is an issue, or just me not being aware of how `service ka-lite start` command is actually supposed to work.

**Current Behavior**: 
So I have this fresh install (just a couple of users and videos so far, Spanish langpack, didn't even register the device yet...) for which I'm going through our [various testing scenarios](https://trello.com/b/rzujkB9F/ka-lite-release-testing-scenarios). 

The first issue I have with `service ka-lite start` command is that it does not give any output in the command line, as opposed to `kalite start`: after blinking for a while, the user just gets their prompt back with no feedback if the service started or not. For me that's an **UX fail**, but then again it may have no remediable solution (it's a command line, not a GUI), or maybe a more experienced command line user would know not to expect any, or would know what to do anyway.

So I go along and try logging as Admin from a networked PC, and first thing I notice is that it is not asking me to register the device. Then I go to the **Manage > Language** tab and I see this:

![kalite-service](https://cloud.githubusercontent.com/assets/1457929/10210333/c560e13c-67e5-11e5-8169-ec549a5a9870.png)

Should be noted that I did the `sudo apt-get purge ka-lite-gtk ka-lite ka-lite-bundle` routine and deleted the `~/.kalite` folder prior to installing this release from the .deb file. So the only conclusion I'm left with is that `service ka-lite start` command is starting the service from my dev repo (Danish and French langpacks attest to that) instead of the intended installation, and it's unclear to me how big of an issue this might be...

Anyway, maybe the biggest takeaway form this issue is that we need a better documentation for the `init.d script`. If we are testing it and offering it to the users, it certainly warrants a mention in the Administrator User Manual, and I couldn't find any.

**Comment by radinamatic** [comment] 2015-10-05 01:31
@benjaoming 

Testing the KA Lite Control Panel and I'm still unclear where is it starting the service...

Available languages are same as above, and diagnostics seems to report it uses the content from `var/ka-lite/.kalite/content` folder (not my dev repo, as I previously thought), but for example I can't view the videos that I downloaded on previous server start with `kalite start` (all present in `~/.kalite/content` folder). Actually, I have **3 kalite content** folders:

`~/.kalite/content` - presumably created by the latest ka-lite_0.15~b2-0ubuntu1_all.deb installer:

`~/ka-lite/content` - my dev repo:

`var/ka-lite/.kalite/content` - no idea... :unamused: 


Should I delete this latest one to properly test the latest release?

**Comment by benjaoming** [comment] 2015-10-05 09:19
@radinamatic 

Could you be more clear about what the issue is?

To find out which folder you're using, do:

    kalite shell
    >>> from django.conf import settings
    >>> print settings.CONTENT_ROOT

If you wanna know which folder your system service is using, you can look at the UI or check which user is running kalite through `/etc/ka-lite/username`.

**Comment by radinamatic** [comment] 2015-10-05 12:43
Output of the `kalite shell` command:

```
didi@didi-Inspiron-3531:~$ kalite shell
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> print settings.CONTENT_ROOT
/home/didi/.kalite/content
>>>
```

`/etc/ka-lite/username` is `ka-lite`

The **issue** is that when I open the Terminal and type `kalite start`, I get apparently completely different installation compared to the one I get when opening the KA Lite Control Panel and pressing the button "Start server" . You can appreciate the differences in the below collage: the one on the left seems to be from last week's **ka-lite_0.15~b2-0ubuntu1_all.deb** installer, the one on the right is opened from KA Lite Control Panel (or by `service ka-lite start` command):

![kalite-start-vs-cp](https://cloud.githubusercontent.com/assets/1457929/10280137/36f2f938-6b6b-11e5-8917-b5810fc5d708.png)


KA Lite Control Panel log and diagnostic outputs:

![kalite-cp](https://cloud.githubusercontent.com/assets/1457929/10280312/8817e3ae-6b6c-11e5-93df-f3c5af4b5e0d.png)


These to me seem to be two completely different KA Lite installations, with its own sets of users, downloaded videos and language packs. I can't possibly imagine why would this be the intended design, and I'm guessing the `sudo apt-get purge ka-lite-gtk ka-lite ka-lite-bundle` and deleting the previous `~/.kalite` folder were not enough to purge my system from previous installations.   

This seems to me as a potential issue for the upgrade process in general (installing new release on top of previous ones), and more to the point and present need: how do I make sure that I'm testing KA Lite Control Panel with the latest release, and it's newly downloaded content? That's why I'm asking should I delete the `var/ka-lite/.kalite/content` folder, as I was under the impression that KA Lite stores the content only in the `~/.kalite` folder and nowhere else.

**Comment by benjaoming** [comment] 2015-10-05 12:53
screenshot overload @radinamatic :)

Running `kalite` implies running it as the user that invokes it.

The problem is this:

You are not running the system like an end-user.

If you had run `kalite` without having your dev installation, you would have had a warning about what you were doing. Installing `ka-lite` to run with the `ka-lite` user will generate a warning if you invoke `kalite` from the terminal as a different user that doesn't have a `~/.kalite` folder. But you do because of your dev installations.

Your screenshots seem to miss the username setting available in the UI. Are you aware of it?

**Comment by radinamatic** [comment] 2015-10-05 14:52
> screenshot overload @radinamatic :)

Just trying to make my point clear(er)... ;)

> Running kalite implies running it as the user that invokes it.
> The problem is this:
> You are not running the system like an end-user.

Ok, let me try the new release with a newly created user which has no dev installation whatsoever. That should clear up this mess, right?

**Comment by benjaoming** [comment] 2015-10-05 15:04
@radinamatic yes, as long as you stop running `kalite` as a different user from the one you specify in your /etc/ka-lite/username -- that's the root of confusion which the ka-lite-gtk addresses. Once again:

> Your screenshots seem to miss the username setting available in the UI. Are you aware of it?

**Comment by radinamatic** [comment] 2015-10-05 15:16
> yes, as long as you stop running kalite as a different user from the one you specify in your /etc/ka-lite/username -- that's the root of confusion which the ka-lite-gtk addresses.

Ok, I'll get back to you on this, 'cause a part from my faulty understanding of it, I believe that part of the installation process could use some improvements in how it's presented to the user.

> Your screenshots seem to miss the username setting available in the UI. Are you aware of it?

No, and I'm not even sure to what setting are you referring, can you add a screenshot of your own where it is visible?

**Comment by benjaoming** [comment] 2015-10-05 18:17
It seems a bit this issue is about ka-lite-gtk? :)

https://github.com/learningequality/ka-lite-gtk/

You find the username setting here:

![screenshot from 2015-10-05 20 16 23](https://cloud.githubusercontent.com/assets/374612/10289321/097fdc86-6b9e-11e5-8338-749f6944b2b2.png)

**Comment by radinamatic** [comment] 2015-10-05 18:28
I have no idea why I didn't have my own username in that setting. I'll reinstall after this latest cleanup, and report back with the result on the gtk own Issues.

**Comment by benjaoming** [comment] 2015-10-05 18:42
@radinamatic probably because you had a different username put in /etc/ka-lite/username

**Comment by radinamatic** [comment] 2015-10-05 18:53
I get that this is the case, my point is that since I don't remember doing it intentionally, it has probably been done automatically as a consequence of me not understanding some part of the installation process or the indication that I should have, for it to work properly. **That** is what we must improve: indications to the users on how to install the correct way so they don't end up with the same problem.

I may not be the sharpest rock in the bunch, but I've been around here for six months now, and if I can make this mistake, than the instructions for the user who is even less familiar with KA Lite and/or Linux certainly need to be clearer.

**Comment by benjaoming** [comment] 2015-10-05 19:38
> I get that this is the case, my point is that since I don't remember doing it intentionally, it has probably been done automatically as a consequence of me not understanding some part of the installation process or the indication that I should have, for it to work properly. That is what we must improve: indications to the users on how to install the correct way so they don't end up with the same problem.

Sane defaults. Convention over configuration.

See: https://en.wikipedia.org/wiki/Convention_over_configuration

The user installing ka-lite is supposed to be chosen by default as the user for which to run the system service. If not, it's a bug that should be reported.

Remember to do `apt-get purge ka-lite ka-lite-bundle` to be sure you don't have old configurations floating around.

**Comment by radinamatic** [comment] 2015-10-06 16:35
I did do both the `sudo apt-get purge ka-lite-gtk ka-lite ka-lite-bundle` and deleted the `~/.kalite` folder prior to installing the 0.15 release last week, but it seems that /etc/ka-lite/ folder is not removed by `purge` if not empty (I added that to the testing scenarios on Trello).

I haven't, however, did anything to `var/ka-lite/.kalite/` folder for the above installation, as I had no idea that it existed... :(
I have now deleted both `var/ka-lite/.kalite/` and `/etc/ka-lite/ `

Thank for the Wikipedia link, sounds tota11y logical, but I still do not understand at which point is this *default* user **ka-lite** created. Opening a [separate issue](https://github.com/learningequality/installers/issues/212), maybe there I get to see the bottom of it.

**Comment by benjaoming** [comment] 2015-10-06 19:21
I believe the issue is better addressed in the above installers issue -- thanks for opening it! :)

I don't think there's anything wrong with your approach, seems you cleaned up nicely before installing. Perhaps your Software Center did indeed skip the question out of unknown reasons.

**Closed by benjaoming** 2015-10-06 19:21 UTC
