### ISSUE TITLE
KA Lite server not running

### ISSUE THREAD

**Issue by aterry06** [learningequality/ka-lite#5177] opened 2016-06-19 09:20 UTC
Summary
After installation of KA Lite v0.16.6, I keep clicking on the 'Start Server' but it does not respond

*Briefly describe what this is about*
I have uninstalled and reinstalled several times. I then downloaded the codes and copy 'kalite.bat' to Python27>>Scripts as this file was not present after installation. I am still unable to contact server through web browser.
![image](https://cloud.githubusercontent.com/assets/8449485/16176429/7bf72cd0-35cc-11e6-80d7-2bbdc8e12c4a.png)

 installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.* 
 - Installer: Windows 7 pro 64-bit
 - Version: 0.16.6

or:

 - Branch: develop (?)

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by aterry06** [comment] 2016-06-19 10:21
The '.kalite' file that should be installed under User>>Username>> is also not being install under the current version 0.16.6

**Comment by cpauya** [comment] 2016-06-20 02:42
Hi @aterry06 - that's weird if the `kalite.bat` is not there after installation.  Something might have happened when during install.  I think you meant the `.kalite` directory.

Can you please answer the following to help us trace this:

1. Did you have a previous installation of `KA Lite` or did you do a fresh install?
2. Do you have an existing Python prior to installation?  If yes, which version?

We will try to reproduce this based on your platform.  Thanks for reporting this.

**Comment by aterry06** [comment] 2016-06-20 03:52
Hi

Both installations were new... The kalite.bat in the Python27>>Scripts
directory was not installed and the .kalite in the users>>username>>.kalite
was not installed... I downloaded v0.16.5 and  and installed it and it
worked fine.

Allan Terry

**Comment by harishgangwar** [comment] 2016-06-20 04:12
I am also facing the same issue on installation of kalite-0.16.6 .
OS : WindowXP

**Comment by benjaoming** [comment] 2016-06-20 09:50
Hi @harishgangwar and @aterry06 !

Thanks for the report! Let's get this fixed pronto!

Would you be able to start it from command line with the `--foreground` option?

Best,
Ben

**Comment by djallado** [comment] 2016-06-20 18:04
I tried to build windows installer in my local using static file from https://pypi.python.org/packages/6a/ed/be049d7cdd8ff4d05a2fe2c5748be72e43f3721638a782dc224748036f0d/ka-lite-static-0.16.5.tar.gz, and it's work fine.

But if I use static file from https://pypi.python.org/packages/c0/0f/6fe40bad69bb1700ce7a7dacf7a71c074a083b6e590c3b49f142b81dbc9c/ka-lite-static-0.16.6.post1.tar.gz, KA Lite server will not run.

I think the problem is on the latest ka-lite-static.

**Comment by harishgangwar** [comment] 2016-06-21 02:26
Hi @benjaoming  I am not able start it from command line because kalite file is not there in script directory under python. 
![ka1](https://cloud.githubusercontent.com/assets/19798337/16216043/3ef4a62c-3785-11e6-97c1-6e7b3c8bd938.png)

**Comment by benjaoming** [comment] 2016-06-21 08:58
@djallado 
[We haven't changed setup.py](https://github.com/learningequality/ka-lite/commits/master/setup.py) since December, and all the logic regarding placing `kalite.bat` in `Scripts` is in this file. [The same thing goes for our `kalite` executable](https://github.com/learningequality/ka-lite/commits/master/bin/kalite).

I can't really imagine why this would break if not in the installer.

What @harishgangwar reports, with the possibly too short installation time, sounds like an installer issue?

**Comment by benjaoming** [comment] 2016-06-21 10:23
@djallado another argument would be that the ka-lite-static python source is used in the Debian installers, too, and you've tested them :)

**Comment by djallado** [comment] 2016-06-21 10:45
@benjaoming: Yes. I can now build windows in installer using ka-lite-static-0.16.6.post1 in my local and it's working properly now. I set environment variable "KALITE_BUILD_VERSION=0.16.6.post1", but when I set that to just "KALITE_BUILD_VERSION=0.16.6" the windows build installer is problematic. @aronasorman: We will check it on dungeon because the windows build installer is only 83MB.

**Comment by benjaoming** [comment] 2016-06-21 14:12
Moving to installers repo:

https://github.com/learningequality/installers/issues/409

**Closed by benjaoming** 2016-06-21 14:12 UTC

**Comment by benjaoming** [comment] 2016-06-21 17:57
Problem is fixed, and downloading a new windows installer is reported to work.

Record keeping: The problem was due to a broken content pack in the Windows installer.
