### ISSUE TITLE
Prompts within lessons

### ISSUE THREAD

**Issue by aleeshanderson** [learningequality/ka-lite#3998] opened 2015-07-02 23:16 UTC
Branch: 0.14
Date: 7/2/15
Expected behavior: ?
Actual behavior: there are prompts that help a user to input the correct form of answer, but they are not necessary after the user has successfully answered their first question. Maybe there could be a button for a user to open the prompt if they feel like they need a suggestion. Also, the prompts obstruct the clock which is what you are supposed to answer the question about.
Steps to reproduce (be detailed!): "Open telling time with a labeled clock" lesson on google chrome

![screen shot 2015-07-02 at 4 12 33 pm](https://cloud.githubusercontent.com/assets/12928107/8489899/a70a7920-20d5-11e5-9e28-b6c92de20b38.png)

**Comment by rtibbles** [comment] 2016-02-01 19:54
Duplicate of #3984

**Closed by rtibbles** 2016-02-01 19:54 UTC
Labels: ux / frontend
