### ISSUE TITLE
Where is my orange dot???

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#5036] opened 2016-03-24 17:06 UTC
## Summary

`/learn/khan/math/arithmetic/multiplication-division/multiplication_fun/number_line/` exercise is missing the essential orange dot. Compare with screenshots from @rtibbles  #4981.
Woff2 font problem?

## Branch or installer method

Upgrade scenario on OSX Yosemite from 0.15 to 0.16 with .pkg build 99.

## Traceback or relevant snippet from server.log

```
Usual WOFF2 font missing errors in the console
```

## How to reproduce

1. Login as Learner.
2. Navigate to /learn/khan/math/arithmetic/multiplication-division/multiplication_fun/number_line/
3. Observe.

#### On Firefox:
![where-is-my-orange-dot-ff](https://cloud.githubusercontent.com/assets/1457929/14024555/f1859634-f1e9-11e5-9287-5e68499648fc.png)

#### On Chrome
![where-is-my-orange-dot-chrome](https://cloud.githubusercontent.com/assets/1457929/14024568/061ff940-f1ea-11e5-8f7f-d13069bd58d0.png)

## Real-life consequences

Exercise cannot be completed.

**Comment by 66eli77** [comment] 2016-03-24 23:19
I can confirm the same issue, missing orange dot, on Mac 0.16.x

**Comment by radinamatic** [comment] 2016-03-24 23:27
Confirmed on Beta3 deb installer on Ubuntu 15.10:

![missing-orange-dot](https://cloud.githubusercontent.com/assets/1457929/14034066/e65f3eb4-f21f-11e5-99d5-b3fa30e04396.png)

I can't even figure out what is supposed to render the dot... The only two 404s are the infamous WOFF2 fonts... :unamused:

**Comment by jamalex** [comment] 2016-04-12 19:54
Fly-by diagnosis:

It looks like KA is now using Perseus for https://www.khanacademy.org/math/arithmetic/absolute-value/add-sub-negatives/e/number_line_2, whereas we're still using an old khan-exercises version (http://127.0.0.1:8008/api/content/khan/number_line_2/)? Very strange. Same was true of 0.15, but the dot worked back then (http://demo.learningequality.org/learn/khan/math/pre-algebra/negatives-absolute-value-pre-alg/add-sub-negatives-pre-alg/number_line_2/). Any sense of why we might be preferring khan-exercises over Perseus versions, @rtibbles or @aronasorman?

**Comment by radinamatic** [comment] 2016-04-12 19:59
Compare with screenshots from @rtibbles' issue #4981. 

Orange dot seems to have disappeared at some point between March 10 and 24.

**Comment by harishbalachandran** [comment] 2016-04-21 04:27
**Facing the same problem on following Installer method:**
OS: Ubuntu version 14 LTS
Installer: "pip install ka-lite" and "sudo kalite manage setup"
Version: 0.16.1
assessment file: en.zip (697.1 MB)

**Note:** 
This problem is universal across all the exercises that has number line with orange dot.

**Screen shots:**
![screenshot from 2016-04-21 09_35_44](https://cloud.githubusercontent.com/assets/13453618/14697998/4429cfc2-07a7-11e6-8570-21e6dffe2d85.png)

**Comment by benjaoming** [comment] 2016-04-27 12:30
Confirmed fixed in #5105

![screenshot from 2016-04-27 14 30 07](https://cloud.githubusercontent.com/assets/374612/14852085/8ef0006c-0c84-11e6-9358-ce14776d4649.png)

**Closed** 2016-04-27 12:30 UTC
Labels: has PR, release blocker

**Comment by radinamatic** [comment] 2016-05-05 22:58
@benjaoming I'm not seeing the infamous orange dot, but `Invalid number line configuration` error in this exercise:
(0.16.5 on Ubuntu 16.04)

![ubuntu16 ready running - oracle vm virtualbox_438](https://cloud.githubusercontent.com/assets/1457929/15059792/80271370-1325-11e6-913e-068d9d6e3477.png)

**Comment by benjaoming** [comment] 2016-05-06 11:00
That sounds very strange, I have it running fine on 14.04 -- having everything up and running and facing a problem in a browser is hardly related to the platform. Could you try the same exercise in English?

(btw. I have it working perfectly, 0.16.5 install from ka-lite-bundle deb, clean install on 14.04)

**Comment by radinamatic** [comment] 2016-05-06 11:37
Good intuition... 👍 
Dot is there when UI is in English, but error appears on both Spanish and Portuguese:

![ubuntu16 ready running - oracle vm virtualbox_439](https://cloud.githubusercontent.com/assets/1457929/15071945/aeb18364-138f-11e6-88f2-3260af8345a4.png)

**Comment by benjaoming** [comment] 2016-05-06 11:49
@rtibbles did we dig up another possibly critical problem with translations - possibly related to #5107 ?

@radinamatic could you start a new issue report regarding this specific problem? It's difficult for others to understand what's going on from deep down an old issue about something else :) (although seemingly related, the above issue was fixed and the nature of this problem is a different one)
