### ISSUE TITLE
TestSessionTimeout tests intermittently fail

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3041] opened 2015-02-12 22:24 UTC
In `develop` branch, in `kalite/distributed/tests/...`, these tests seem to fail intermittently. We should take a closer look and make sure best practices are being used in those tests. This is not a high priority right now, though.

**Comment by MCGallaspy** [comment] 2015-04-15 21:13
The way we resolve this will probably depend on what comes out of the discussion for #3521. @benjaoming is this another instance where we can use Django client tests instead of `LiveServerTestCase`s?

**Comment by MCGallaspy** [comment] 2015-04-15 21:30
[Django docs suggest](https://docs.djangoproject.com/en/1.5/topics/testing/overview/#module-django.test.client) client test cases are not appropriate in this instance:

>Use in-browser frameworks like Selenium to test rendered HTML and the behavior of Web pages, **namely JavaScript functionality**.

**Comment by benjaoming** [comment] 2015-04-16 10:48
Yeah, agreeing with the docs :) If it involves JS, use Selenium... if it doesn't use the test client. Maybe the difference can be expressed in the naming conventions of the behave helpers? Like `test_with_javascript_that_element_exists`.

**Comment by MCGallaspy** [comment] 2015-04-16 18:54
> Maybe the difference can be expressed in the naming conventions of the behave helpers?

Instead of using behave to test how a template is rendered, I'd like to use the unittest framework. In principle, can't we comprehensively test our views as black boxes just by feeding in different requests and inspecting the returned HTML? In many cases this won't be possible, since the behavior of the site depends on AJAX stuff after the template is rendered (both in this instance and in #3521) . In some cases it might be possible to shift some of the client-side code into the Django templating engine and test it without Selenium, but we seem to be moving in the opposite direction.

**Comment by aronasorman** [comment] 2015-09-01 15:02
Duplicate of https://github.com/learningequality/ka-lite/issues/2668.

**Closed by aronasorman** 2015-09-01 15:02 UTC
Labels: enhancement, refactoring and cleanup
