### ISSUE TITLE
Error in downloading 4ThUMRAvUkY: HTTPConnectionPool(host='s3.amazonaws.com', port=80): Max retries exceeded with url: /KA-youtube-converted/4ThUMRAvUkY.mp4/4ThUMRAvUkY.mp4 (Caused by <class 'socket.error'>: [Errno 10054] ); continuing to next video. ...

### ISSUE THREAD

**Issue by jiangjianshan** [learningequality/ka-lite#5329] opened 2016-10-15 08:08 UTC
Hello,

   The following message has been got when I try to download the video from Math part:
![image](https://cloud.githubusercontent.com/assets/20179047/19408515/c02680cc-92f1-11e6-9c55-5c57febecab1.png)

   Sometimes the download will hang up there even several hours past.
![image](https://cloud.githubusercontent.com/assets/20179047/19408564/0dd6c7c2-92f3-11e6-95f9-9821d467a36e.png)

   It's not all the videos got this error but a lot of them are look like that. The network's speed seems OK because I can download other files from other websites very fast.  Is any setting I can do to solve this problem?

   The system information are following:
1. KA Lite version : 0.16.9
2. Operating system: Windows 7 64 bit
3. Brower: Chrome
4. Python: 2.7.12

**Comment by benjaoming** [comment] 2016-10-25 11:04
Hmm, the URL seems to work: http://s3.amazonaws.com/KA-youtube-converted/4ThUMRAvUkY.mp4/4ThUMRAvUkY.mp4

The problem seems to be that `socket.error` isn't intelligently handled. The file is just removed from the queue, although the download should have been retried.

Could you comment some more on the quality of your internet connection? Is it likely that the download failed and retried?

**Comment by benjaoming** [comment] 2016-10-25 11:05
I'm closing this issue because it won't be fixed independently, but it can be referred to our more general overhaul of downloading/scheduling  #4907

**Comment by benjaoming** [comment] 2016-10-25 11:05
Thanks for reporting this btw! The issue is legit!

**Closed by benjaoming** 2016-10-25 11:05 UTC
