### ISSUE TITLE
Register Device - "AttributeError: 'bool' object has no attribute 'strip'" on develop branch

### ISSUE THREAD

**Issue by timon-langlotz** [learningequality/ka-lite#3302] opened 2015-03-14 19:22 UTC
I just installed the KA-Lite server on a fresh Raspberry Pi installation from the develop branch. When trying to register the device, I get the following error:

Error
Sorry, but there was an error while trying to load the page.
(AttributeError: 'bool' object has no attribute 'strip')

**Comment by yohanboniface** [comment] 2015-03-15 18:25
Same error when I try to run develop to workaround #3197.

The cause seems to be that `settings.CENTRAL_SERVER` is `False` while the code is expecting for an URL:

            if urllib.urlopen(settings.CENTRAL_SERVER).getcode() != 200:

**Comment by yohanboniface** [comment] 2015-03-15 18:40
But with a little hack to workaround this issue, I'm back on #3197 issue :/

**Comment by MCGallaspy** [comment] 2015-03-18 21:51
@anuragkanungo so can I close this issue in light of the above PR? The title suggests it's a "partial fix".

**Comment by aronasorman** [comment] 2015-03-19 15:30
https://github.com/learningequality/ka-lite/commit/73efb72b44c4a8cf0ffe75f6e193fdb22c8e002d Fixes this for real.

**Closed by aronasorman** 2015-03-19 15:30 UTC
Labels: bug, release blocker
