### ISSUE TITLE
Enter key does not advance to the next question within all assessments

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#4641] opened 2015-10-22 04:10 UTC
Encountered on 0.15.0 on Windows hosts (both XP and 10 however I suspect all OS are affected) within some of the newer assessments, I have noticed that pressing the enter key to submit an answer does not advance to the next question within the assessment. Referencing #2833 because it also dealt with similar anomalies while pressing the enter key within assessments. Actually clicking on the check answer button with the mouse works as expected. Screen shot shows what happens after the student presses enter to submit an answer.

![2015-10-21_22-07-55](https://cloud.githubusercontent.com/assets/4349806/10656817/4b4180d0-7840-11e5-94e9-1e2605a5e422.png)

To Replicate:
After installation navigate to Learn > Computing > Computer Programming > Intro to JavaScript Drawing and Animation > Variables > and take the Variables quiz submitting answers using the either enter key.

**Comment by rtibbles** [comment] 2016-02-01 20:56
@radinamatic Please attempt to replicate and report back.

**Comment by radinamatic** [comment] 2016-03-02 23:01
I'm getting `Uncaught TypeError: Cannot read property 'getWidget' of undefined` on this exercise, @rttibles.

User can't proceed with Enter key, and clicking the `Check Answer` just keeps throwing the same error:

![variables](https://cloud.githubusercontent.com/assets/1457929/13478742/c76876a0-e0d2-11e5-8518-ed35d4995e17.png)

**Comment by benjaoming** [comment] 2017-04-13 21:45
Without triaging this issue, I think it can be safely unmarked as a milestone because no deployments have told us of an urgency.

**Comment by mrpau-eugene** [comment] 2017-06-29 10:17
Closing this as it has been already solved https://github.com/learningequality/ka-lite/pull/2910 and confirmed to be working.

**Closed by mrpau-eugene** 2017-06-29 10:17 UTC
Labels: bug
