### ISSUE TITLE
Problems with arguments in kalitectl.py

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3892] opened 2015-06-17 19:21 UTC
See #3890. In the version of `kalitectl.py` now extant on `develop`, one needs to pass in --options to the kalitectl.py before the command, otherwise it's proxied to django management commands, e.g.:
```sh
kalite --port=1234 start --a-django-option
```
instead of
```sh
kalite start --port=1234 --a-django-option
```

In the version reverted by #3890 that is resolved, but then extra arguments are discarded, so the following two commands (for example) are equivalent:
```sh
kalite test my_test_label
kalite test
```
And this is true for all management commands that take extra arguments.

**Comment by aronasorman** [comment] 2015-06-17 19:29
Duplicate of #3891 :) But this is better written, so let's keep this!

**Closed** 2015-06-19 22:54 UTC
