### ISSUE TITLE
How to install KAlite 0.16.5 in windows 7 32 bit OS? Do I have to install Python alos?

### ISSUE THREAD

**Issue by pareshkumar127** [learningequality/ka-lite#5136] opened 2016-06-06 06:51 UTC
## Summary

*Briefly describe what this is about*

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows/OSX/Debian (?)
 - Version: 0.15.1 (?)

or:

 - Branch: develop (?)

## Traceback or relevant snippet from server.log

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

*If applicable*

**Comment by benjaoming** [comment] 2016-06-06 18:44
@amodia Does the bundled Python .msi not work for 32 bit?

**Comment by radinamatic** [comment] 2016-06-06 19:37
@pareshkumar127 

Python installer is bundled with KA Lite Windows installer, and it will run as a first step during the installation process. Are you getting a specific error when you try to install on Windows 7? Please post a screenshot so we can investigate!

**Comment by pareshkumar127** [comment] 2016-06-07 03:22
Dear Sir,
I have installed KA Lite in my PC. When I am starting ka Lite by double
clicking , it is showing the server is starting, please wait and nothing
opens. What does it mean?

Regards.

On 7 June 2016 at 01:07, Radina Matic <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>
>
> Python installer is bundled with KA Lite Windows installer, and it will
> run as a first step during the installation process. Are you getting a
> specific error when you try to install on Windows 7? Please post a
> screenshot so we can investigate!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224064601>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43aSlFLbJXA9hCNafAqJxlJXGCNOFks5qJHcTgaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-07 03:31
Nothing should open.  If the server is started, _then_ you should use a browser to open http://127.0.0.1:8008/

Reference: http://ka-lite.readthedocs.io/en/0.16.x/installguide/install_all.html

**Comment by amodia** [comment] 2016-06-07 05:15
@benjaoming I tested the bundled python on KA Lite 0.16.5 in windows 7 32 bit and it's working fine.

Here's the screenshots.
![screen shot 2016-06-07 at 12 32 30 pm](https://cloud.githubusercontent.com/assets/8663934/15846380/12fa80ea-2caf-11e6-8ffb-1d493ee5e2db.png)

![screen shot 2016-06-07 at 12 31 11 pm](https://cloud.githubusercontent.com/assets/8663934/15846383/1c7e51dc-2caf-11e6-9b99-cbe3e56e70f5.png)
@pareshkumar127 If you don't have a python2.7.9+ version on your machine the KA Lite installer will pop up a window to ask you to install the recommended python version.

![screen shot 2016-06-07 at 12 31 58 pm](https://cloud.githubusercontent.com/assets/8663934/15846387/2cca8150-2caf-11e6-973e-f05c8e8b7e63.png)
The KA Lite 0.16.5 installer has it's own bundled python 2.7.10 to install on your machine.

**Comment by benjaoming** [comment] 2016-06-08 21:38
@pareshkumar127 there doesn't seem to be a problem in using Win 32 bit, so I'm going to close this. If you are experiencing an error of some kind, please feel free to post a description of the nature of the error and how we may reproduce it.

Thanks,
Ben

**Closed by benjaoming** 2016-06-08 21:38 UTC

**Comment by pareshkumar127** [comment] 2016-06-09 03:11
Dear Sir,
I installed KA Lite in my PC. But when I am starting it by starting the
sever the message comes as " server is starting , please wait" and then
nothing happens. KA lite does not open. Please help.

Regards.

On 9 June 2016 at 03:08, Benjamin Bach <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127> there doesn't seem to
> be a problem in using Win 32 bit, so I'm going to close this. If you are
> experiencing an error of some kind, please feel free to post a description
> of the nature of the error and how we may reproduce it.
>
> Thanks,
> Ben
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224737179>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43U_NVzok6uUNUtUrOrEbg_nxBoWlks5qJzZfgaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-09 03:18
@pareshkumar127, please confirm you have done these steps;
- start the server, and;
- open web browser for http://127.0.0.1:8008/

**Comment by pareshkumar127** [comment] 2016-06-09 03:30
Dear Sir,
When I am connecting 127.0.0.1:8008/
I am getting a message
This site can’t be reached

*127.0.0.1* refused to connect.


I am using a proxy server

On 9 June 2016 at 08:48, James Cameron <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>, please confirm you
> have done these steps;
>
>    - start the server, and;
>    - open web browser for http://127.0.0.1:8008/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224790698>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43ZBuJwNlK39tinJNHQ2ZyGYgZ13-ks5qJ4YFgaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-09 04:04
@pareshkumar127, thanks, I did not know you were using a proxy server.  Your proxy server will not be able to reach your ka-lite server using 127.0.0.1, because the numbers have special meaning only inside one computer, and the proxy server is a different computer.

You might try alternate method in user manual;
http://ka-lite.readthedocs.io/en/0.16.x/installguide/install_all.html

Copy and paste below:

> To access KA Lite from other machines, you will need to connect to the same network as the installation computer and access port 8008 using the its IP address. For example, if the installation computer has the IP address 192.168.0.104 on your network then you can access it from other machines on the same network at the address http://192.168.0.104:8008.

**Comment by pareshkumar127** [comment] 2016-06-09 04:46
Dear Sir,
My IP address is 10.143.34.82. So, How do I have to start? Where I have to
write http:// 10.143.34.82:8008 ?

Regards.

On 9 June 2016 at 09:34, James Cameron <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>, thanks, I did not
> know you were using a proxy server. Your proxy server will not be able to
> reach your ka-lite server using 127.0.0.1, because the numbers have special
> meaning only inside one computer, and the proxy server is a different
> computer.
>
> You might try alternate method in user manual;
> http://ka-lite.readthedocs.io/en/0.16.x/installguide/install_all.html
>
> Copy and paste below:
>
> To access KA Lite from other machines, you will need to connect to the
> same network as the installation computer and access port 8008 using the
> its IP address. For example, if the installation computer has the IP
> address 192.168.0.104 on your network then you can access it from other
> machines on the same network at the address http://192.168.0.104:8008.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224795126>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43VKTRaqtyJLYPSvSyI83654vcFuFks5qJ5DegaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-09 04:51
@pareshkumar127, you would open a web browser, then in the URL entry bar, click, erase what is already there, and then type http://10.143.34.82:8008 and press enter.  Or click on the link in this message, which will stop working if your IP address changes.  Let me know result.

**Comment by pareshkumar127** [comment] 2016-06-09 04:57
Dear Sir,
PFA error report

On 9 June 2016 at 10:21, James Cameron <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>, you would open a web
> browser, then in the URL entry bar, click, erase what is already there, and
> then type http://10.143.34.82:8008 and press enter. Or click on the link
> in this message, which will stop working if your IP address changes. Let me
> know result.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224799389>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43TFSPa-Aj-yNupP_4vcezmil5pTOks5qJ5u9gaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-09 05:05
@pareshkumar127, sorry, I don't know what a PFA error report is, I tried Googling it and found nothing useful.  If this is a problem with your proxy server, please work with the owner of the proxy server.

**Comment by pareshkumar127** [comment] 2016-06-09 05:14
Sir,
I meant to say that I have attached the error report, PFA means ( please
find attached) after  typing http://10.143.34.82:8008 in the browser. I got
an error and that report is taken on print screen Attached for your
reference.

Regards.

On 9 June 2016 at 10:35, James Cameron <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>, sorry, I don't know
> what a PFA error report is, I tried Googling it and found nothing useful.
> If this is a problem with your proxy server, please work with the owner of
> the proxy server.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224800879>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43Q9l2KDSaCwZkWT2-9udnkf7noiiks5qJ58tgaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-09 05:43
@pareshkumar127, both your attachments were dropped by github mail gateway; use github directly if you want to attach an image.

**Comment by pareshkumar127** [comment] 2016-06-09 06:04
The error message is : The 10.143.34.82 page is not working.

On 9 June 2016 at 11:13, James Cameron <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>, both your
> attachments were dropped by github mail gateway; use github directly if you
> want to attach an image.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224805128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43Xo7QaZON2peQurLRtxPbROj0Q-hks5qJ6gNgaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by quozl** [comment] 2016-06-09 06:11
@pareshkumar127, thanks, that error message is non-technical, it doesn't explain why it is not working, so my guess is that a firewall on your computer prevents connections to it, or the proxy server refuses to connect to computers in the local network.  Both are common scenarios.

You might try one more method, for evaluation or testing ka-lite;
- in your web browser disable the proxy server setting,
- then try to open http://127.0.0.1:8008/ again.

If you need to use ka-lite among a group of computers, some redesign of your network may be required.

**Comment by radinamatic** [comment] 2016-06-09 11:20
@quozl Thanks for stepping in and helping with this issue! I'll update our docs with details of your answer to add the info about proxies.

@pareshkumar127: If you are seeing a specific error on your computer it's best if you make a screenshot of it (and any other relevant information regarding your system) and attach those image files here.  That way is the issue are easier to investigate and troubleshoot! 😉

**Comment by pareshkumar127** [comment] 2016-06-09 11:30
- n your web browser disable the proxy server setting,
   - then try to open http://127.0.0.1:8008/ again.

As per your advice I disabled the proxy server settings and try to open
http://127.0.0.1:8008/ again. The error message is attached.

On 9 June 2016 at 16:50, Radina Matic <notifications@github.com> wrote:

> @quozl <https://github.com/quozl> Thanks for stepping in and helping with
> this issue! I'll update our docs with details of your answer to add the
> info about proxies.
>
> @pareshkumar127 <https://github.com/pareshkumar127>: If you are seeing a
> specific error on your computer it's best if you make a screenshot of it
> (and any other relevant information regarding your system) and attach those
> image files here. That way is the issue are easier to investigate and
> troubleshoot! 😉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224866942>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43Zi78hHPCCup5UY0xGSPHgK23vNWks5qJ_b0gaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com

**Comment by radinamatic** [comment] 2016-06-09 11:43
@pareshkumar127: I'm unable to see the error message you attached. You seem to be using email to reply to GitHub notification, and you probably need to switch to using the GitHub interface to attach the images/screenshots of errors.

Did you try contacting your network administrator to see what is the proper configuration for your proxy server?

**Comment by pareshkumar127** [comment] 2016-06-09 11:51
Ok I shall try again tomorrow.

Thanks .

On 9 June 2016 at 17:13, Radina Matic <notifications@github.com> wrote:

> @pareshkumar127 <https://github.com/pareshkumar127>: I'm unable to see
> the error message you attached. You seem to be using email to reply to
> GitHub notification, and you probably need to switch to using the GitHub
> interface to attach the images/screenshots of errors.
>
> Did you try contacting your network administrator to see what is the
> proper configuration for your proxy server?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/5136#issuecomment-224871357>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASz43Qaq38OK5UjDWlJ0aZrfgeCoNXdHks5qJ_xsgaJpZM4Ium1j>
> .
>



-- 
*Paresh Kumar Mishra*
AGM ( Inst & Auto )
Bokaro Steel Plant ( SAIL)
Bokaro Steel City
Jharkhand, 827004
Ph: 8986871850, 06542-286568
email:pareshkumar127@gmail.com
