### ISSUE TITLE
Initial Login message alert is not dismissed

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4540] opened 2015-09-29 23:02 UTC
Initial Login message alert is not dismissed

**Branch**: 0.15, **ka-lite_0.15~b2-0ubuntu1_all.deb** installer  on Ubuntu 15.04

**Expected Behavior**: 
The initial login message after install `Please login with the admin account you created...` should not appear after the superuser has been created, and especially not when another user has logged in. 

**Current Behavior**: 
Superuser is created, and after login more learners and coach users have been created. The message keeps appearing even after learner user is logged in:

![login](https://cloud.githubusercontent.com/assets/1457929/10180470/c931527a-670d-11e5-84c8-29f43c8742b6.png)

Not sure if that might be the cause, but the device is not registered, and for admin and coach users, there is a message to register instead:

![login_coach](https://cloud.githubusercontent.com/assets/1457929/10180582/9f6d1518-670e-11e5-8044-38b048656e00.png)

**Comment by benjaoming** [comment] 2016-06-13 15:18
This is a duplicate of #4920

**Closed by benjaoming** 2016-06-13 15:18 UTC
