### ISSUE TITLE
Search bar button literally off by one pixel....

### ISSUE THREAD

**Issue by jtamiace** [learningequality/ka-lite#3859] opened 2015-06-12 23:55 UTC
My OCD tendencies are showing

![search bar button](https://cloud.githubusercontent.com/assets/6668144/8141934/c582f3c6-1123-11e5-8520-f4fcc13cfa49.PNG)

**Comment by aronasorman** [comment] 2015-06-12 23:56
duplicate of https://github.com/learningequality/ka-lite/issues/3851

**Closed by aronasorman** 2015-06-12 23:56 UTC
