### ISSUE TITLE
Unable to download videos when m2crypto is available

### ISSUE THREAD

**Issue by mariospr** [learningequality/ka-lite#5126] opened 2016-05-25 20:52 UTC
## Summary

When trying to run KA Lite 0.16.5 while having version 0.21.1 of the python-m2crypto package installed in my Ubuntu/Debian-like systems, I could not download any video from the administration interface, apparently becaus of "peer did not return certificate" errors happening all the time:
![dev _25_05_2016_14_37_30](https://cloud.githubusercontent.com/assets/2197259/15555102/1cd6cc44-22bf-11e6-8c7b-1bd60fa3da26.png)

A quick test using newer versions of python-m2crypto (tried 0.22 and 0.24 for now) made the error go away, but still there are **no videos available after the process finishes**, even if the page says that all videos have been "downloaded successfully".

Finally, monitoring the contents of `~/.kalite/content` with `watch` while downloading the videos I've observed something weird going on, regardless of the version of python-m2crypto being available: KA Lite definitely starts downloading the video files (I see them growing on disk) but then deletes each of them systematically after finishing the download, leaving the computer with no videos in the end. Notice that I can see the "peer did not return certificate error" with m2crypto == 0.21, while no error message is shown with m2crypto >= 0.22, but perhaps the same error is still there and is behind this mysterious deletions?

Last, just for the sake of testing a bit more, I've tried the same procedure on my Fedora 23 machine after installing the m2crypto package (version 0.22) and I observed the same phenomena: it looks like it's downloading (I can see files growing in `~/.kalite/content`, but there are no videos in the end).

## Branch or installer method

I could reproduce this with version 0.16.5 of KA Lite installed via 2 different ways:
  * Using the debian package from [this PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite)
  * Installing with `sudo pip install ka-lite-static`

Also, I could reproduce this in three different OS's:
  * Endless OS (Debian like system) (32bit and 64bit) 
  * Debian Testing (64 bit)
  * Fedora 23 (64 bit)

## Traceback or relevant snippet from server.log

No relevant logs seen (happy to collect more info if somebody guides me, though)

## How to reproduce

1. Install latest stable version KA Lite (0.16.5 atm) from PIP or from the debian package [from here](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite) 
2. Make sure you have the python-m2crypto (Debian/Ubuntu) or m2crypto (fedora) package installed
3. Launch KA Lite with `kalite start` and open a browser at http://localhost:8008
4. Login into the administration interface and try to download some videos

### Expected outcome

Videos are downloaded without visible errors shown neither during the process nor at the end (should report that all videos were "successfully downloaded"), and can be found and played offline afterwards.

### Actual outcome

If [python-]mcrypto 0.21 is installed (maybe older versions too, but I haven't checked), a "peer did not return certificate" error is shown while downloading videos, the process reports an error like "0 of N videos were downloaded" at the end of the process, and no videos are available for playback.

If [python-]mcrypto >= 0.22 is installed, no error is shown during or after the process, which will be reported as a "success", but no videos will be available for playback in any case, as the relevant files won't exist in the CONTENT_ROOT directory.

In both cases, monitoring the contents of CONTENT_ROOT while KA Lite is downloading videos shows that the videos are being properly downloaded, but deleted once the process completes. 

## Screenshots

N/A

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

It's a quite obscure error that points into the direction of m2crypto and then makes you believe that, once you upgraded that component, is fixed (as you don't see any visible error anymore), but still you can see any videos after downloading because they keep being deleted.

For now, I believe I can live without having m2crypto installed (I only had it because of `osc` anyway) and rely on the alternative, RSA-based, codepath. Still, it would be nice if it could be fixed in KA Lite, as it seems like something is wrong with the m2crypto codepath for some reason

**Comment by radinamatic** [comment] 2016-05-26 16:05
I was unable to replicate this with 0.16.5 on Ubuntu 16.04 with m2crypto 0.22 installed after KA Lite. Videos do download and play correctly.

I'll retest in fresh VM snapshot by installing it before KA Lite to see if I can replicate.

**Comment by mariospr** [comment] 2016-05-26 17:46
@radinamatic Thanks for the quick feedback and for trying this out! While it's a bit of a surprise that it worked for you there, perhaps it indicates an issue somewhere else that for some reason my systems trigger when python-m2crypto is installed?

If you're trying a VM, would it be possible to check Fedora 23 64bit? I can reliably reproduce that in my laptop with that configuration, so I'm hoping you will be able too (notice that I don't see the error while downloading, but just that the videos get deleted afterwards).

Thanks again

**Comment by mariospr** [comment] 2016-05-26 17:48
Ah, also. You might need to restart KA Lite's server (and maybe Ctrl + R in the browser?) to test this properly if you install/uninstall m2crypto **after** having KA Lite installed. At least that's what I did.

**Comment by radinamatic** [comment] 2016-05-26 19:19
Hola Mario ¡tienes toda la razón! 😃 

You nailed it, if I restart the server after installing `m2crypto`, the video download feature behaves exactly as you described (seems to work, but the videos get deleted after the download finishes). I do get the alert message saying `0 of 3 videos downloaded` (so at least there's a small measure of feedback for the user that something has gone awry):

![selection_450](https://cloud.githubusercontent.com/assets/1457929/15586835/b92219a6-2386-11e6-923e-7bbeb6fed2b9.png)

Also, removing the `m2crypto` package restores the download feature correctly, so this is officially confirmed!

I don't have Fedora VM at hand, but will try to setup one for further testing.

**Comment by benjaoming** [comment] 2016-05-26 20:11
@mariospr great reporting, thanks!!

As I understand it, videos are downloaded via HTTPS from youtube, and m2crypto adds extensions to urllib which is used for downloading.

If there's an error during a download, the file is deleted. That's to make sure we don't have garbage files.

I'm curious if you can test stuff again with the newer m2crypto versions in case something was missed, like restarting kalite before testing? Because the exceptions that cause files to be deleted should be re-raised, so we should in theory be able to see what the error is... and otherwise, the file should be preserved.. that's just an initial idea, could be more complicated than that since m2crypto is hooking into core libraries.

A quick fix is to remove it, and I'm gonna possibly make it an option dependency for the future since it seems it *is* in fact optional (but recommended for low-spec devices).

**Comment by mariospr** [comment] 2016-05-26 20:13
Ha! Not that I'm happy to see the bug exists, but it's good to see I'm not crazy after all... :-)

Please, let me know if you need me to make some additional quick tests tomorrow (ideally with more or less clear instructions, since python/django is not really my thing) and I'll happy to help debugging & investigating this if I can.

That said, I'll be on holidays from May the 28th until June the 6th, hopefully totally offline, so if you see a big gap in my responses during that period you know why :-).

Mil gracias!

**Comment by mariospr** [comment] 2016-05-26 20:20
[Just say this other comment while, literally, I was clicking on "comment" to post my other reply] 

> @mariospr great reporting, thanks!!

You're welcome. Happy to help, as usual.

> As I understand it, videos are downloaded via HTTPS from youtube, and m2crypto adds extensions to urllib which is used for downloading.
> 
> If there's an error during a download, the file is deleted. That's to make sure we don't have garbage files.

That's the unconfirmed theory I had in my mind, good to see it confirmed now :)

> I'm curious if you can test stuff again with the newer m2crypto versions in case something was missed, like restarting kalite before testing?

See my comment https://github.com/learningequality/ka-lite/issues/5126#issuecomment-221944011: I already did that (restarting the server before testing), and even more hardcore things such as stopping the server + uninstalling + installing again + starting it... and that failed.

Also, so far I've tested with m2crypto 0.21 (the one in Endless OS atm), 0.22 (Ubuntu, Fedora) and 0.24 (from Debian), and all of them exposed the same issue. Only difference I could see is that 0.21 would show the "peer did not receive certificate" error, but videos would be deleted in every case.

> Because the exceptions that cause files to be deleted should be re-raised, so we should in theory be able to see what the error is... and otherwise, the file should be preserved.. that's just an initial idea, could be more complicated than that since m2crypto is hooking into core libraries.

If you could provide me easy-enough instructions on how to do some extra debugging (e.g. "put a print in <file>:<line> and see the error) soon enough, I'll be happy to test it tomorrow before leaving on holidays, if it does not take too much time (need to close other things too). Otherwise I can always do it after June the 6th, though.

> A quick fix is to remove it, and I'm gonna possibly make it an option dependency for the future since it seems it is in fact optional (but recommended for low-spec devices).

Sounds good. JFTR, removing m2crypto is what I did for now to continue with my KA Lite experiments, which is apparently not a big deal since the only package that depends on it is osc, which I don't really need in non-development machines. That said, it would be nice to get it fixed, which is why I reported it in the first place :)

**Comment by mariospr** [comment] 2016-05-27 16:40
Quick message just to let you know I'm leaving the computer aside for a few days so forgive me in advance if it takes me a while to reply to any message here. Will be back on June 6th, though! :)

**Comment by benjaoming** [comment] 2016-06-06 09:29
Oh he's back today today!! :) I'm gonna work on this, please stay tuned @mariospr :)

**Comment by mariospr** [comment] 2016-06-06 10:33
Yes, I'm back today. Thanks for working on this, and let me know if I can be of any help.

**Comment by benjaoming** [comment] 2016-06-06 17:44
@mariospr you are most welcome to directly test the PR branch above :) It should work, though, I've written it while having m2crypto installed, and I can confirm that the latest m2crypto release is also broken with urllib.

**Comment by mariospr** [comment] 2016-06-08 11:40
Just to confirm that I've configured my development environment following [this instructions](https://github.com/learningequality/ka-lite/wiki/Getting-started) today to test the PR and I can confirm it fixes the issue: with m2crypto 0.24 installed I can no longer reproduce the issue after checking out the 0.16.x with the PR merged, while I can reproduce it if I `--reset hard` my branch to a previous point.

Thanks!

**Comment by case485** [comment] 2016-06-12 13:44
Was there any short term work around for this, i am leaving for Haiti and would like to make sure and update the videos prior to leaving. I tried to uninstall m2crypto but as Mario said it still starts the download but removes it, only with no error being displayed. Thanks for all the work you are collectively doing its truly changing peoples lives.

**Comment by benjaoming** [comment] 2016-06-12 17:54
@case485 
Please install with the PPA `ka-lite-proposed`, I've put KA Lite 0.16.6a1, which has the fix included. [Read the docs on installing with PPA](http://ka-lite.readthedocs.io/en/latest/installguide/advanced.html#debian-ubuntu-subscribe-to-updates-through-a-ppa) but remember to replace location of PPA with `learningequality:ka-lite-proposed`. The new release will be published in an hour or so (Launchpad is currently building).

You can also use this recipe to install the latest build directly from PyPi on top of the old .deb release for RPI, but it's a bit more hack-ish: https://github.com/learningequality/ka-lite/issues/5139#issuecomment-224277003

**Comment by case485** [comment] 2016-06-12 21:11
@benjaoming  thanks for the help - tried to add the ppa but i'm running on a raspberrypi3 and looks like the ppa does not match, errors out  when running the command : 

pi@raspberrypi:~ $ sudo add-apt-repository ppa:learningequality/ka-lite-proposed
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie

**Comment by benjaoming** [comment] 2016-06-12 22:18
@case485 ah yes the Ubuntu PPAs don't have a distribution label matching that, but edit it manually: 

    sudo nano /etc/apt/sources.list.d/*ka-lite*

..and change raspbian to "ubuntu" and "jessie" to "trusty".

**Comment by case485** [comment] 2016-06-12 22:28
@benjaoming - the listing for my /etc/apt/sources.list.d/
root@raspberrypi:/etc/apt/sources.list.d# ls
getdeb.list  raspi.list

I did run the first command successfully to install ppa : 
sudo apt-get install software-properties-common python-software-properties
the second command is where it fails looking for a specific version:
sudo add-apt-repository ppa:learningequality/ka-lite

**Comment by benjaoming** [comment] 2016-06-12 22:32
@case485 

    sudo echo "deb http://ppa.launchpad.net/learningequality/ka-lite-proposed/ubuntu trusty main" >> /etc/apt/sources.list.d/ka-lite-ppa.list
    sudo apt-get update

If it complains about a missing repo key, you should be able to retrieve the key like this:

    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0123456789abcdef

...where 0123456789abcdef is the ID of the missing key.

**Comment by benjaoming** [comment] 2016-06-17 17:12
Closing this for now, as I'm no longer able to reproduce it. Please yell if there are still issues.

**Closed by benjaoming** 2016-06-17 17:12 UTC
Labels: has PR
