### ISSUE TITLE
0.13 doesn't work on Tablets

### ISSUE THREAD

**Issue by anuragkanungo** [learningequality/ka-lite#2949] opened 2015-02-06 18:03 UTC
The side bar which contains the topics takes up whole space and we can't see the last exercises/topics and there is no horizontal sliding.

Either side bar should resize or should be allowed to slide horizontally.

**Comment by aronasorman** [comment] 2015-02-06 19:42
Not sure if this is high priority. Maybe it can be fixed in a point release, if @antrikshy doesn't have time to do this.

**Comment by Antrikshy** [comment] 2015-02-06 23:10
I'm working on this. I think I have a way to calculate the `left` CSS property of the entire sidebar in order to hide the left-most panels after a threshold. I'm having some trouble actually applying it.

**Comment by MCGallaspy** [comment] 2015-02-07 02:13
I think this is pretty important. @Antrikshy when you're working on it next let me know, perhaps together we can knock it out quickly.

**Comment by Antrikshy** [comment] 2015-02-09 21:09
Oh hey, this is a duplicate of #2859. And yeah, we should work on this together @MCGallaspy.

**Comment by jamalex** [comment] 2015-02-20 18:45
Duplicate

**Closed by jamalex** 2015-02-20 18:45 UTC
Labels: bug, nalanda
