### ISSUE TITLE
Uncaught TypeError when click Learn tab

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#3865] opened 2015-06-13 00:43 UTC
Browser: Chrome
Mac installer
Reproduce: open your browser's console and click on Learn tab, you will see the following error message
Uncaught TypeError: Cannot read property 'appendChild' of null
MathJax.js?config=/static/perseus/ke/third_party/MathJax/2.1/config/KAthJax-8f02f65cba7722b3e529bd9…:29

**Comment by jtamiace** [comment] 2015-06-19 17:48
I only get this error logged in as a student, and on the landing page console also get this error:

"Uncaught TypeError: Cannot read property 'attributes' of undefined"

Error occurs in line 68 of kalite/distributed/static/js/distributed/contentrec/views.js

**Comment by rtibbles** [comment] 2015-06-24 16:56
@jtamiace The issue you are describing is #3884. It is currently fixed in an open PR.

@66eli77 The TypeError is caused by stuff internal to MathJax, it doesn't seem to affect anything else, so I don't think it is a release blocker, but would be nice to track down.

**Comment by rtibbles** [comment] 2015-07-09 19:10
Note: This is fixed in #4056

**Closed** 2015-07-16 18:36 UTC
