### ISSUE TITLE
Upgrade to .16.5 failed on linux

### ISSUE THREAD

**Issue by cts-prog3** [learningequality/ka-lite#5146] opened 2016-06-09 05:57 UTC
Upgrade to 15.5 failed on linux

 - Installer: ka-lite_0.16.5-0ubuntu1_all.deb
 - Version: 0.16.5
-  64 bit Ubuntu trusty

dpkg: error processing archive /opt/ka-lite/ka-lite_0.16.5-)ubuntu1_all.deb conflicting packages - not installing ka-lite
![kalite16 5 upgrade](https://cloud.githubusercontent.com/assets/7528702/15920096/b3882e3e-2e5a-11e6-8f98-38c312996768.PNG)

**Comment by benjaoming** [comment] 2016-06-09 20:39
Hi @cts-prog3 

This looks like a case of "feature not a bug"

We release to variations of KA Lite.

1) "ka-lite" a small basic package with no exercise data in which you download exercise data and videos afterwards
2) "ka-lite-bundle" which includes exercise data and is roughly 300 MB

You seem to have installed ka-lite-bundle 0.15.1 but trying to install ka-lite-bundle 0.16.5.

Fetch the 0.16.5 ka-lite-bundle from here: https://learningequality.org/r/deb-bundle-installer-0-16

Please let me know if this fixed your problem!

Also please note if this is for a deployment that within days from now, we are releasing 0.16.6 with some significant bug fixes for exercises.

**Comment by benjaoming** [comment] 2016-06-17 17:07
Closing this for now, let me know if it's still a problem!

**Closed by benjaoming** 2016-06-17 17:07 UTC
