### ISSUE TITLE
KA Lite static files are not loaded automatically.

### ISSUE THREAD

**Issue by djallado** [learningequality/ka-lite#5054] opened 2016-03-28 07:34 UTC
## Summary

*After a successful installation, static files are not automatically loaded  when user open KA Lite in browser.*

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

 - Installer: Windows/OSX
 - Version: 0.16.x 

or:

 - Branch: 0.16.x

## How to reproduce

1. Install build [100 for OS X] (http://dungeon.learningequality.org/browse/KL-MT16-100/artifact/shared/KA-Lite-0.16-OSX-Installer/KA-Lite.pkg) or build [200 for Windows] (http://dungeon.learningequality.org/browse/KL-KALITE016-200).
1. After a successful installation, open it on browser.

## Screenshots

![staticfiles](https://cloud.githubusercontent.com/assets/8664071/14073136/21e6d95c-f4f9-11e5-95e2-24b5416c3998.png)
OS X Yosemite

![winstaticfiles](https://cloud.githubusercontent.com/assets/8664071/14073145/31e88fbc-f4f9-11e5-98c1-382ad8417519.png)
Windows IE10 - Windows 7

**Comment by cpauya** [comment] 2016-03-28 07:50
Confirmed this issue on a locally-built .pkg for OS X installer using the `ka-lite/0.16` branch.

**Comment by djallado** [comment] 2016-03-28 07:57
I tested it using IE11 - Windows 7 and static files are loaded properly. 
Screenshot:
![staticie11-win7](https://cloud.githubusercontent.com/assets/8664071/14073687/ba7c263c-f4fd-11e5-9d2e-9aefc7de32b0.png)

**Comment by amodia** [comment] 2016-03-28 07:59
I replicate this issue on OS X mavericks build 100 and IE11 windows 7 build 200. I just run the command `kalite manage collectstatic` on the terminal and the static files are loaded.

![screen shot 2016-03-28 at 9 53 46 am](https://cloud.githubusercontent.com/assets/8663934/14073651/6c81c716-f4fd-11e5-9d0d-3182a6ecfac1.png)

**Comment by cpauya** [comment] 2016-03-28 08:10
I reverted this change on my local: https://github.com/learningequality/ka-lite/commit/129b135cf9dc38d74a5dcb55ba4436f7ef1693f4#diff-742941b56a8caf848f892cfd5ca1559bL480 and built a local .pkg and it worked.  

Much as I want to make the change, but I have no idea if that's the correct fix for this or if it's safe to revert that change.

/cc: @aronasorman @MCGallaspy

**Comment by radinamatic** [comment] 2016-03-28 14:00
Windows build 199, all loads correctly on IE9/Windows 7:

![ie9 - win7 0 16 build 199](https://cloud.githubusercontent.com/assets/1457929/14079441/0d9d05fc-f4fe-11e5-83bc-5144c6464477.png)

**Comment by MCGallaspy** [comment] 2016-03-28 19:58
Seems inconsistent -- is this an issue with IE11 vs IE10? Can you consistently replicate this issue? Does it matter whether you're upgrading or installing "fresh"? @cpauya the change you identified was introduced in Windows build 197. It's a critical change for upgrading on the raspberry pi as described in the commit message, so if we need to revert it then another fix needs to be made.

**Comment by cpauya** [comment] 2016-03-29 00:49
We will review this again today @MCGallaspy - but the issue manifests on IE10 on Windows 7 for our tests.

I will try to trace this on ka-lite and submit a PR if lucky.

**Comment by djallado** [comment] 2016-03-29 03:23
Static files will be loaded properly by running `kalite manage collectstatic` in command line on IE10 Windows 7.
Screenshot:
![ie10](https://cloud.githubusercontent.com/assets/8664071/14097115/8e44904c-f5a0-11e5-8dfd-a33bddfc7d96.png)

**Comment by djallado** [comment] 2016-03-29 04:51
I tested build 205 and static files work properly after a successful installation. 
Here's the screenshots:
![205](https://cloud.githubusercontent.com/assets/8664071/14098279/c9d7a39a-f5ac-11e5-8f23-02553bca9f59.png)
Using IE10 Windows 7


![205ie11](https://cloud.githubusercontent.com/assets/8664071/14098284/d97ffb6c-f5ac-11e5-8a70-400ad29fc278.png)
Using IE11 Windows 7

**Comment by jamalex** [comment] 2016-03-29 05:20
Can you try again now with the old installers that showed the issue, to make sure they still show the issue? If they do, and the new installers don't, we should be good to say it's solved. If it now doesn't happen with the old ones anymore, this may need more investigation.

**Comment by djallado** [comment] 2016-03-29 07:52
The cause of not loading of static files is that, I closed the terminal during installation like in the screenshot.
![terminal](https://cloud.githubusercontent.com/assets/8664071/14100521/a29c6158-f5c0-11e5-8812-d421c805a5fe.png)
I waited it for more than 3 minutes but nothing happened so I closed the terminal. Then I click `Finish` button in `KA Lite Setup Wizard`. 

I tested it again and I waited the terminal to close for more than 4 minutes and click `Finish` button in `KA Lite Setup Wizard`.
Then static files are loaded properly. I'm using build 200 on IE10 Windows 7.  I tested the upgrade from 0.15.1 to build 200, and it loads the static files correctly.

**Comment by jamalex** [comment] 2016-03-29 15:28
Ah, yeah -- and that could happen with users, as well, especially since the terminal window doesn't say anything like "Please wait... do not close this window". If possible, it would be better to not show the window at all, and just show a spinner saying "Please wait, this may take a while...".

Could you open an issue on the installers repo for that, and then close this one?

**Comment by MCGallaspy** [comment] 2016-03-29 16:55
> If possible, it would be better to not show the window at all, and just show a spinner saying "Please wait, this may take a while...".

I don't agree, the alternative is that the user stares at an unmoving setup wizard -- that's why I started showing the command prompts, despite the possibility that the user might close them. I think a better solution would be to produce friendly/informative output with these management commands.

**Comment by jamalex** [comment] 2016-03-29 21:33
> showing the command prompts

I agree that staring at an unmoving wizard is also problematic, and your solution seems like a good short-term compromise. I wasn't proposing this new issue be release-blocking *or* targeted for 0.16, just that we should recognize that what we currently have can be improved, and create an issue to track that.

Popup terminals aren't user friendly (for non-tech-savvy users), no matter what text is shown in the console. Popping up a new window is already suboptimal, but consoles in particular scare people, and make them assume something has gone wrong.

**Comment by aronasorman** [comment] 2016-03-30 00:27
Fixed in latest mac build.

**Closed by aronasorman** 2016-03-30 00:27 UTC
Labels: bug, has PR, release blocker
