### ISSUE TITLE
Cannot view some images on ipads and iphones

### ISSUE THREAD

**Issue by fabizeid** [learningequality/ka-lite#5332] opened 2016-10-31 21:42 UTC
## Summary

Some  images are not showing on IOS devices. I have tried displaying the page on several iphones and ipads but images of some sections would not show.

## System information

I have used a current installation as well as the live demo page,
 - Operating system: IOS
 - Version: 9.3.5 (13G36)
 - Browser: Safari

## How to reproduce

1. From Ipad or Iphone
2. Open Safari
3. Go to: http://demo.learningequality.org/learn/khan/math/basic-geo/basic-geo-lines/basic-geo-lines-rays-angles/recognizing_rays_lines_and_line_segments/

## Screenshots
https://cloud.githubusercontent.com/assets/4076318/19872588/3b6caf30-9fc3-11e6-9233-28df84efa355.PNG

**Comment by radinamatic** [comment] 2016-10-31 21:51
Thank you for reporting this @fabizeid! 

@mrpau-dev I don't have iPad/iPhone to test this, could you try to replicate on your end?

**Comment by cpauya** [comment] 2016-11-01 01:24
@fabizeid can you specify what iOS version did you use?

@radinamatic Sure.  We can use the Xcode's iOS Simulator to test this if we don't have a physical iOS device.

**Comment by fabizeid** [comment] 2016-11-01 16:10
You could reproduce it using an online emulator for IOS:

https://appetize.io/demo?device=ipadair&scale=50&orientation=landscape&osVersion=9.3

This demo has a 60 seconds timeout. You could copy the reproduction steps link and paste it in safari to gain time. Or you could use http://jsfiddle.net/appetize/mtuftsm8/, press on the home key, then start safari and try it out there (this example has no time out).
I found many threads when I googled:  ios svg not showing
 maybe some might be related to the same problem.

**Comment by radinamatic** [comment] 2016-11-01 16:48
Thanks for the tip & suggestions @fabizeid!
We'll try to reproduce this as soon as possible!

**Comment by fabizeid** [comment] 2016-11-01 16:51
Not in a hurry, let the guys enjoy their holidays. Thanks for the great product!

**Comment by cpauya** [comment] 2016-11-02 04:01
Thanks for the emulator link @fabizeid.  To validate this issue, here's a screenshot of the demo link on an iPad Air Simulator v10.0.

![simulator screen shot 2 nov 2016 11 35 02 am](https://cloud.githubusercontent.com/assets/175580/19915933/ad347ae8-a0f0-11e6-870c-7db6f0fe7b5e.png)

@radinamatic To launch the iOS Simulator, you will need Xcode in your Mac.  I use two ways to launch it:

1. Use spotlight search, then type "simulator".  This is the quickest way. 😸 
2. Open Xcode, then click on `Xcode -> Open Developer Tool -> Simulator` menu.

The default iOS device (or the last one you launched) should launch in the Simulator, I think it will launch an iPhone simulator.

To select another iOS device to simulate, click on the `Hardware -> Device -> iOS version` menu.
<img width="1144" alt="screenshot 2016-11-02 11 45 34" src="https://cloud.githubusercontent.com/assets/175580/19916108/0e595270-a0f2-11e6-9bb2-91fcc78c5c88.png">

Experiment with the `Hardware -> Device` menu options to simulate using the iOS device on a Mac.  

As you've noticed, I have v10.0 on my Simulator.  Although the issue is also seen in this version, it is good to download v9.3 that was mentioned in this issue.  To do that, select Xcode then launch it's `Preferences` window, select the `Components` tab which will list the other Simulators you can download, select the one you need because they are large, more than 1GB big.

<img width="862" alt="screenshot 2016-11-02 11 54 52" src="https://cloud.githubusercontent.com/assets/175580/19916272/84a9148c-a0f3-11e6-96e7-f7604cd13622.png">

Happy iOS Simulating! 😸

**Comment by radinamatic** [comment] 2016-11-02 13:33
Wow, @cpauya, awesome tutorial!!! 😍
Thank you! 🙇‍♀️

**Comment by benjaoming** [comment] 2016-12-17 00:29
The demo server is running 0.16.5, I'm going to see if we can get it updated.

Meanwhile, this issue looks like a duplicate of https://github.com/learningequality/ka-lite/issues/5140 which was fixed for 0.16.7

Please reopen if I'm mistaken.

**Closed by benjaoming** 2016-12-17 00:29 UTC
