### ISSUE TITLE
Tighter integration with BitTorrent protocol to allow downloading of specific videos P2P

### ISSUE THREAD

**Issue by jamalex** [learningequality/ka-lite#33] opened 2013-01-23 22:37 UTC
We have a torrent file with the complete set of videos:
https://dl.dropbox.com/u/1080765/ka-lite-content-resized.torrent

But it's effectively impossible to download just a subset of the videos by topic, since the files are all in the same folder, and named by YouTube ID. Possible solutions:
1. Separate the video files into separate folders within the torrent file. Problem: many videos are in multiple topics, so there would be duplication.
2. Separate torrents for different subtopics. Problem: same as in 1, plus fragmentation of the seeder space.
3. Be able to select within the KA Lite Update interface which videos to download (as we currently support), but have them get downloaded via BitTorrent instead of from the S3 servers. Challenge: integrating pure-Python BitTorrent packages into KA Lite.

Clearly, option 3 would be ideal, but will take some work. I created this issue so we can discuss and gather expertise. Go team!

**Comment by benjaoming** [comment] 2015-01-12 21:51
Here is a cool, contemporary that's worth looking into:

http://syncthing.net/

One of the challenges that are solved (which I think is important) is about uPnP:

Simple. Syncthing doesn't need IP addresses or advanced configuration: it just works, over LAN and over the Internet. Every machine is identified by an ID. Just give your ID to you friends, share a folder and watch: UPnP will do if you don't want to port forward or you don't know how.

**Comment by benjaoming** [comment] 2015-01-12 22:03
Discussion on differences between Syncthing (former name was Pulse!) and BtSync:

https://discourse.syncthing.net/t/how-is-pulse-different-to-bittorrent-sync/1083/15

**Comment by benjaoming** [comment] 2015-01-12 22:28
Highlights from the discussion:

* Pulse has local network announcement (eg: nodes in the same LAN can communicate offline).
* Response to above: This is incorrect. BitTorrent Sync has LAN broadcast. BTS also allows you to disable tracker use for all your shares or on a per-share basis.

BTSync is NOT open source, nor is the protocol. From looking a bit around on their site, I'd say it's a bad match for something like KA Lite. They collect data, sell it to third-parties, use targetted advertising, and they even admit that some information is personally identifiable.

Most critical about BTSync is that I think it's a little hard to see how it would be possible to run your own syncing "in the offline wilderness". It'd be great if a syncing mechanism like this would be able to discover nodes and their resources on a network without any uplink to The Big Cloud.

Syncthing is not made with the intention of sharing data publicly:

*syncthing was never meant for public distribution of data (at least not yet). If you share your data publicly, you obviously don't care who sees your data (although I understand that's for discussion, and I hope syncthing/Pulse adds such a feature in the future).*

Also, regarding Python compatibility, it's interesting to have a look at how this project interacts with syncthing (btw it's Windows+Linux compatible GTK project with a system tray icon):

https://github.com/syncthing/syncthing-gtk

**Comment by benjaoming** [comment] 2015-01-12 22:59
One big drawback of Syncthing seems to be that you can't disable encryption (OP claims it's possible with BTSync). For the case of KA Lite, spending valuable resources on encryption would seem a bit odd, since educational materials are (I guess) considered as insensitive and non-private.

https://discourse.syncthing.net/t/disable-data-encryption/416/43

The discussion reveals significant performance issues caused by the DHT and encryption mechanisms. They affect both CPU and transfer speeds and the cases look severe especially on phones..

https://github.com/syncthing/syncthing/issues/1157

Seeing the current interest and community support of Syncthing, it might be that issues are quickly resolved and that it's good to jump on this fast-moving train...

**Comment by neolefty** [comment] 2015-01-13 02:01
I agree an open-source alternative is preferable. And Syncthing certainly
has momentum! But as far as I can tell it hasn't added an automatic peer
discovery feature. I keep waiting for that, but it seems anathema to the
Syncthing design philosophy. From the Getting Started page (
https://github.com/syncthing/syncthing/wiki/Getting-Started):

Two devices will only connect and talk to each other if they both know
> about the others' device ID. Since the configuration must be mutual for a
> connection to happen, device IDs don't need to be kept secret.


Every node has to be explicitly configured with the identity of every other
node in the system. Whenever someone joins the group, their ID would need
to be added to every server they want to receive files from. I think this
is an Achilles heel because it prevents easy scalability, and frankly I
think it is a critical mis-feature if you want to share non-confidential
files such as educational videos.

In contrast, btsync grants admission to the group to anyone holding the
key, without requiring existing members to do anything. The new member can
receive data from any existing member, in full P2P fashion.

I can imagine a promiscuous mode for Syncthing where those device IDs are
automatically distributed, but as far as I know it isn't on the horizon
(and it might have internal scaling problems of its own in contrast to DHTs
where the peer lists are dynamic).

**Comment by benjaoming** [comment] 2015-01-13 03:15
@neolefty 
Yeah, I think you're right that for Syncthing to work, we would need a new layer: So for two KA Lite devices to sync, they have to handshake, by which they exchange Syncthing Device IDs. That way, the Syncthing client won't have to view all devices in case there are thousands.. but just the subset of devices that it wants to get videos from.

In order for Internet connected devices to sync from multiple sources in the cloud, we would need our own kind of tracker to distribute sources.

A whole different problem that I guess exists for both, is to select which files are desired from each folder.

KA Lite would want to ask: Which videos are available from source X? ...and then get a list of videos, each video possibly with a tracker link of its own.

For Syncthing, the analogy to this would be that each KA Lite item (e.g. video) has a Device ID and a repository of its own!?

**Comment by neolefty** [comment] 2015-01-13 07:22
If that all worked, I could see some advantages, but it sounds like a major
development effort, adding features to Syncthing (or building a management
system on top of it). At that point we may be better off with something
simpler like rsync.

On further reflection, I think it's a blocker that Syncthing doesn't have a
read-only peer option, which is a killer feature of btsync. It lets KA Lite
share videos without worrying that they will be deleted or corrupted
downstream. Syncthing has an all-or-nothing trust system, with no read-only
option. An accident downstream could cause headaches for everyone.

The closest I see is an issue about "non-trusted servers" that is under
heavy discussion:

https://github.com/syncthing/syncthing/issues/109

This is the kind of thing we'd need, but with the encryption turned off so
that the non-trusted server would be able to read the files. Our
"non-trusted" means something different: In the Syncthing issue, the
critical issue is to not share data with a non-trusted server. In our
usage, the critical issue is to not allow accidental deletion or corruption
(and to ensure open sharing).

**Comment by EdDixon** [comment] 2015-01-13 15:50
User and abuser of rsync here but maybe something like this to keep it inside the python framework (note: I have never used this py script before but it sounds like it might fit)? https://pypi.python.org/pypi/rsync.py

**Comment by benjaoming** [comment] 2015-01-13 15:52
@neolefty 
I agree, really good points. So maybe it can be separated into two cases:

1) Online: Syncing against the internet where the torrent distribution method is a big advantage as it allows peers to distribute their content without relying on central servers. Furthermore, it takes some load off the central servers. As per discussion, Syncthing is not really the thing for this, while BTsync or perhaps another torrent-based distribution mechanism can support content creation and distribution in a P2P fashion much better.

2) Offline: Syncing with a known (local) source. E.g. the local computer centre responsible from school A visits school B with a device containing school A's resources, and they start syncing. Rsync or similar is a much better tool for this. But it should also work online? Such that school A can directly lookup school B? Making it work online requires security and uPnP-like stuff that's why I'm mentioning it....

But perhaps in general, the true term is not **"syncing"** because it's really about downloading content from a source -- not uploading anything since that would reverse the roles?

**Comment by benjaoming** [comment] 2015-01-13 16:04
@EdDixon 
Yup, definitely not a bad option! Rsync should be available also on all platforms.. but it might be a little more complicated for Windows, not sure. OSX comes with built-in rsync... not sure about iOS. For doing I/O intense operations, it'd be nice to have something natively compiled such as Rsync. Some other benefits of Rsync: It can do SSH, it can resume, it handles the network layer, it verifies that things are written correctly, it can compress data before transferring, it's super-tested.

**Comment by EdDixon** [comment] 2015-01-13 16:27
Another thought I had about this however, is due to restrictions in some
countries, censoring media, etc, a true torrent compatible system that
could be used with something like tor might be the right step in our
mission towards learning equality for all? I feel like I could be opening
Pandora's box here but what are our thoughts on that?

On Tue, Jan 13, 2015 at 9:04 AM, benjaoming <notifications@github.com>
wrote:

> @EdDixon <https://github.com/EdDixon>
> Yup, definitely not a bad option! Rsync should be available also on all
> platforms.. but it might be a little more complicated for Windows, not
> sure. OSX comes with built-in rsync... not sure about iOS. For doing I/O
> intense operations, it'd be nice to have something natively compiled such
> as Rsync. Some other benefits of Rsync: It can do SSH, it can resume, it
> handles the network layer, it verifies that things are written correctly,
> it can compress data before transferring, it's super-tested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/33#issuecomment-69768151>
> .
>



-- 
Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE <https://learningequality.org/give/>, Support FLE via Amazon
Smile! <http://smile.amazon.com/ch/46-2676188>
M (575)-636-9549

**Comment by benjaoming** [comment] 2015-01-13 16:54
@EdDixon 
Regarding censorship and tools to avoid it, I think those tools are - as you say - already available. So you can use Tor to hide your identity and activities*), and VPN is also an option.

Even, if we are doing the rsync thing, people can proxy/tunnel their SSH connections and this would provide both encryption and enough disguise to "leave the censoring country" without them seeing the cargo or the destination/source.

*) However, Tor and torrent *isn't a good idea*: https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea

**Comment by MCGallaspy** [comment] 2015-03-23 22:29
Superseded by #2467.

**Closed by MCGallaspy** 2015-03-23 22:29 UTC
Labels: enhancement, internationalization
