### ISSUE TITLE
videos icons.gif not found

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4318] opened 2015-08-28 20:54 UTC
branch: develop
browser: chrome
reproduce: go to video downloading page, the video tree has no icons
![screen shot 2015-08-28 at 1 52 06 pm](https://cloud.githubusercontent.com/assets/5577205/9556778/36ac6e02-4d8c-11e5-9f83-d5d7e5ca7e0b.png)

**Comment by aronasorman** [comment] 2015-09-01 17:25
Can confirm, it's not showing up when I run `kalite manage runserver --settings=kalite.project.settings.dev`. Cannot download videos.

**Comment by aronasorman** [comment] 2015-09-01 18:32
Duplicate of https://github.com/learningequality/ka-lite/issues/4294.

**Closed by aronasorman** 2015-09-01 18:32 UTC
Labels: bug
