### ISSUE TITLE
Warning: Channel khan does not exist.

### ISSUE THREAD

**Issue by fairdklab** [learningequality/ka-lite#4958] opened 2016-03-03 13:28 UTC
## Summary

Getting a warning about a channel that *does* exist.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16b1

## Traceback or relevant snippet from server.log

```
kalite@fair-server:~$ kalite shell
[WARNING] [2016-03-03 14:23:51,857] kalite: Channel khan does not exist.
```

## How to reproduce

1. Install default 0.16b1 deb
1. Start it or just open `kalite shell`

**Comment by rtibbles** [comment] 2016-03-03 21:10
Duplicate of #4906

**Closed by rtibbles** 2016-03-03 21:10 UTC
