### ISSUE TITLE
i cant login as administrator user

### ISSUE THREAD

**Issue by sajjadahmad300** [learningequality/ka-lite#5472] opened 2017-06-15 22:49 UTC
## Summary
when i open kalite server it ask to login admin account but when i click on login tab nothing happen.it doesn't show full content like videos,docs etc on upper menu. 
*Briefly describe what this is about*
once i uninstalled also ,
## System information

*Please specify the KA Lite version you were using and your operating system!*
window 10,i don't exact version no. but i am using latest.
 - Operating system: ?window 10
 - Version: 0.16.?
 - Browser: ?on all browser like mozilla ,chrome etc

## Traceback or relevant snippet from server.log

```
![untitled](https://user-images.githubusercontent.com/29186700/27204833-c5ebf9d2-5246-11e7-8a06-3fe4428f89aa.png)

INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```
login with admin account create user and facility
## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware, for instance how it affects your deployment)
once i install kalite and then and uninstall when second time i reinstall the problem occur.
*If applicable*

**Comment by mrpau-eugene** [comment] 2017-06-16 07:45
Hi @sajjadahmad300 how many minutes have you waited after loading KA-Lite on browser?
Just waiting a little bit longer might do the trick.

I think this is a similar issue to this one https://community.learningequality.org/t/ka-lite-doesnt-serve-javascript-assets-in-windows-10/246/10

**Comment by benjaoming** [comment] 2017-07-24 13:08
@mrpau-eugene he posted a link to an image:

![user-screenshot](https://user-images.githubusercontent.com/29186700/27204833-c5ebf9d2-5246-11e7-8a06-3fe4428f89aa.png)

**Comment by benjaoming** [comment] 2017-07-24 13:08
Closing as a duplicate of https://github.com/learningequality/ka-lite-installers/issues/456

**Closed by benjaoming** 2017-07-24 13:08 UTC
