### ISSUE TITLE
Not able to Download videos.

### ISSUE THREAD

**Issue by iCHAIT** [learningequality/ka-lite#4817] opened 2016-02-05 17:15 UTC
I have set up ka-lite on my local machine, when I try to download a video from the Videos Tab it shows size of selected videos as 0.0 MB - 

![screen shot 2016-02-05 at 10 41 50 pm](https://cloud.githubusercontent.com/assets/8472314/12853432/1183d6c2-cc5a-11e5-87ec-a9acd201ce9b.png)

Moreover, when I hit the download button, it shows a banner at the top and nothing happens, it does not show any progress bar that I can see in the ka-lite DEMO.

![screen shot 2016-02-05 at 10 42 38 pm](https://cloud.githubusercontent.com/assets/8472314/12853442/187cf59e-cc5a-11e5-8acd-4286c6cc9fce.png)

Checked out from develop branch, the 0.16.x branch also gives the same problem.

**Comment by aronasorman** [comment] 2016-02-05 17:22
Can you try downloading a video, waiting 5 minutes, then checking to see if it was downloaded?

Possible causes for this:
1. We're downloading, but not simply showing the progress bar.
2. Actual video downloading doesn't trigger.
3. Video is getting downloaded, but we're not updating our content DB to show the newly available video.

**Comment by iCHAIT** [comment] 2016-02-05 17:23
Okay, trying it out.

**Comment by iCHAIT** [comment] 2016-02-05 17:32
Currently I am downloading the video and waiting as suggested.

Just wanted to notify this - https://i.imgur.com/cjEWZvq.png

My shell is making some API calls constantly, if that helps to figure out what's going wrong.

**Comment by iCHAIT** [comment] 2016-02-05 17:36
@aronasorman Waited for around 10 min., the video didn't download :(

**Comment by aronasorman** [comment] 2016-02-05 17:45
@iCHAIT thanks! The traceback is helpful. So out of those three possible bug causes, we basically eliminated the first possibility. Now we have these two:

2. Actual video downloading doesn't trigger.
3. Video is getting downloaded, but we're not updating our content DB to show the newly available video.

Now, open your kalite-specific python shell by running `kalite shell`. That should have all the paths set, and we can import any kalite-specific modules in that shell.

Once that's open, run these commands in the opened python shell:

```python
from django.conf import settings
settings.CONTENT_ROOT
```

`from django.conf import settings` loads the settings for kalite. One of those settings is `CONTENT_ROOT`, the folder where we place content.

Running those commands should print out a folder in your system. Said folder contains content that you have, including downloaded videos. Can you poke around that folder and see if there's anything that looks like a video in there?

**Comment by iCHAIT** [comment] 2016-02-05 17:49
The command refers to the folder `content`, and their is no video in that folder. There is a pdf, a text file, and an assessment folder which contains an empty folder named Khan.

**Comment by aronasorman** [comment] 2016-02-05 17:50
@iCHAIT thanks! So that means video downloading doesn't start. Thanks for helping us get to the root issue!

**Comment by iCHAIT** [comment] 2016-02-05 17:53
@aronasorman Glad I could help :)

**Comment by iCHAIT** [comment] 2016-02-08 18:33
@aronasorman I just realized that I am experiencing the same issue on the branch 0.15.x as well? What's possibly going wrong on my side?

**Comment by radinamatic** [comment] 2016-02-08 21:50
Unable to exactly replicate this on 0.16:

1. Topic tree is **slow**, it takes a full minute to load.
2. Once I select videos and press the button, it takes 30-40 seconds for the `Launched process...` alert to appear.
3. I takes almost another minute for download progress bar to appear.
4. On some videos there is `pop from empty list` error, but the video is downloaded and present in `/ka-lite/content` folder.  

![update_videos___ka_lite](https://cloud.githubusercontent.com/assets/1457929/12900066/ae897560-ceb4-11e5-9e87-81e6fb7e665c.png)

The error is not consistent, it fires up on some videos, not in others:
![update_videos___ka_lite_success](https://cloud.githubusercontent.com/assets/1457929/12900334/0bee1cc8-ceb6-11e5-8dcb-2af8a6a45bc0.png)
```
2016-02-08 22:32:08,561 - INFO:kalite: Error in downloading fsTD_jqseBA: database is locked; continuing to next video.
INFO:kalite:Error in downloading fsTD_jqseBA: database is locked; continuing to next video.
2016-02-08 22:32:08,565 - INFO:kalite: Error: pop from empty list
INFO:kalite:Error: pop from empty list
2016-02-08 22:32:08,565 - INFO:kalite: Cancelling process videodownload
INFO:kalite:Cancelling process videodownload
[08/Feb/2016 22:32:09] "GET /api/updates/progress?process_id=3&_=1454966991099 HTTP/1.1" 200 172
[08/Feb/2016 22:32:18] "GET /api/videos/topic_tree?parent=math&_=1454966991100 HTTP/1.1" 200 4948
[08/Feb/2016 22:32:19] "GET /api/videos/topic_tree?parent=early-math&_=1454966991101 HTTP/1.1" 200 606
[08/Feb/2016 22:32:21] "GET /api/videos/topic_tree?parent=cc-early-math-add-sub-basics&_=1454966991102 HTTP/1.1" 200 524
[08/Feb/2016 22:32:22] "GET /api/videos/topic_tree?parent=cc-early-math-add-sub-intro&_=1454966991103 HTTP/1.1" 200 334
[08/Feb/2016 22:32:23] "GET /static/images/distributed/circle-complete.png HTTP/1.1" 304 0
[08/Feb/2016 22:34:24] "POST /api/videos/start?lang=en HTTP/1.1" 200 60
[08/Feb/2016 22:34:24] "GET /api/updates/progress?process_name=videodownload&_=1454966991104 HTTP/1.1" 200 2
2016-02-08 22:34:25,189 - DEBUG:kalite: Cannot set priority, psutil module not installed
DEBUG:kalite:Cannot set priority, psutil module not installed
2016-02-08 22:34:25,190 - DEBUG:kalite: Setting videodownload to 1 total stages.
DEBUG:kalite:Setting videodownload to 1 total stages.
[08/Feb/2016 22:34:26] "GET /api/updates/progress?process_name=videodownload&start_time=2016-02-08T21:34:24.000Z&_=1454966991105 HTTP/1.1" 200 140
[08/Feb/2016 22:34:26] "GET /api/updates/progress?process_id=4&_=1454966991106 HTTP/1.1" 200 140
2016-02-08 22:34:26,704 - INFO:kalite: Downloading 'Introduction to addition'
INFO:kalite:Downloading 'Introduction to addition'
[08/Feb/2016 22:34:28] "GET /api/updates/progress?process_id=4&_=1454966991107 HTTP/1.1" 200 185
[08/Feb/2016 22:34:30] "GET /api/updates/progress?process_id=4&_=1454966991108 HTTP/1.1" 200 179
[08/Feb/2016 22:34:32] "GET /api/updates/progress?process_id=4&_=1454966991109 HTTP/1.1" 200 179
ERROR:root:Video was not found!
Traceback (most recent call last):
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/videos.py", line 43, in download_video
    raise URLNotFound("Video was not found!")
URLNotFound: Video was not found!
2016-02-08 22:34:34,274 - DEBUG:kalite: Retrieving youtube video fsTD_jqseBA via youtube-dl
DEBUG:kalite:Retrieving youtube video fsTD_jqseBA via youtube-dl
[08/Feb/2016 22:34:34] "GET /api/updates/progress?process_id=4&_=1454966991110 HTTP/1.1" 200 179
[08/Feb/2016 22:34:36] "GET /api/updates/progress?process_id=4&_=1454966991111 HTTP/1.1" 200 179
[08/Feb/2016 22:34:38] "GET /api/updates/progress?process_id=4&_=1454966991112 HTTP/1.1" 200 178
2016-02-08 22:35:35,530 - INFO:kalite: Downloaded 1 of 1 videos successfully.
INFO:kalite:Downloaded 1 of 1 videos successfully.
2016-02-08 22:35:35,595 - DEBUG:kalite: Completing process videodownload
DEBUG:kalite:Completing process videodownload


```

**Comment by rtibbles** [comment] 2016-02-23 23:49
Seem to have replicated this issue on my end.

**Comment by radinamatic** [comment] 2016-02-24 00:51
Confirmed on **ka-lite-bundle_0.16-a3-0ubuntu1_all.deb**.

Download button does not seem active, even once desired videos are selected. No JS errors:

![video-dwonload](https://cloud.githubusercontent.com/assets/1457929/13271829/f4c2c5b0-da97-11e5-8cef-a5bebcbb5b40.png)
 
`Scan content folder for videos` button seems active, displays the info message once pressed, but does not seem to be working, or at least takes too long to scan (there are only 5 videos present in the folder).

**Comment by rtibbles** [comment] 2016-02-24 00:52
There seems to be a general issue with the progress tracking that @aronasorman has reported on language pack download too, so, this would explain the issue with the downloading and scanning.

**Comment by radinamatic** [comment] 2016-02-24 00:54
:+1: 

Saved from reporting that one too... ;)

**Comment by radinamatic** [comment] 2016-02-24 17:20
Small update, as you are probably aware of this: after rebooting the VM, videos that I copied yesterday in the content folder now display properly as present, and the downloaded Spanish langpack seems functional... So videoscan/langpack download seems to be working, just not displaying progress :)

**Comment by rtibbles** [comment] 2016-02-24 17:21
Yep, the above PR provides a minimal fix for that - just fixing it up so that it doesn't interfere with the reason that @benjaoming made the change I basically reverted too.

**Comment by benjaoming** [comment] 2016-02-24 23:24
@rtibbles I don't think you reverted anything, just fixed the error in --foreground flag. All good! Progress is making progress!

**Comment by rtibbles** [comment] 2016-02-24 23:58
Fixed in #4909 - @radinamatic if you could confirm this fix in testing, would be good.

**Comment by radinamatic** [comment] 2016-02-25 00:03
Getting right on it!

**Comment by radinamatic** [comment] 2016-02-25 00:16
Seems to be working fine now! :smile: 
@rtibbles  @benjaoming :+1: 

![update_videos016](https://cloud.githubusercontent.com/assets/1457929/13305664/3b46aa9a-db5d-11e5-9e7e-69c80f975d6d.png)

**Comment by rtibbles** [comment] 2016-02-25 00:17
:+1:

**Closed by rtibbles** 2016-02-25 00:17 UTC
Labels: has PR, release blocker

**Comment by radinamatic** [comment] 2016-02-25 00:21
Although I don't see the progress bar on langpack download page... :( 
Or that still needs a separate fix? @rtibbles 

```
[INFO] [2016-02-25 01:15:32,389] django.request: HTTP Request /api/languagepacks/start - Response: 200
[25/Feb/2016 01:15:32] "POST /api/languagepacks/start HTTP/1.1" 200 72
[25/Feb/2016 01:15:32] "GET /api/updates/progress?process_name=languagepackdownload&_=1456359285734 HTTP/1.1" 200 2
[INFO] [2016-02-25 01:15:32,465] kalite: Downloading content pack.
[25/Feb/2016 01:15:34] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285735 HTTP/1.1" 200 2
[25/Feb/2016 01:15:36] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285736 HTTP/1.1" 200 2
[25/Feb/2016 01:15:38] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285737 HTTP/1.1" 200 2
[25/Feb/2016 01:15:40] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285738 HTTP/1.1" 200 2
[INFO] [2016-02-25 01:15:41,904] kalite: Moving content files to the right place.
[25/Feb/2016 01:15:42] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285739 HTTP/1.1" 200 2
[WARNING] [2016-02-25 01:15:42,465] kalite: No es-ES_icu.js file found in locale_path /Users/didim/LE/ka-lite/locale/
[INFO] [2016-02-25 01:15:42,465] kalite: Writing i18nized js file to /Users/didim/LE/ka-lite/content/locale/js/i18n/es-ES.js
[INFO] [2016-02-25 01:15:43,189] kalite: Looking for available content items.
[INFO] [2016-02-25 01:15:43,289] kalite: Annotating content for language: es-ES, channel: khan
[ERROR] [2016-02-25 01:15:43,292] kalite: No content database file found
Process CommandProcess-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/django_utils/command.py", line 61, in run
    call_command(self.cmd, *self.args, **self.kwargs)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/didim/LE/ka-lite/python-packages/fle_utils/django_utils/command.py", line 214, in execute
    super(LocaleAwareCommand, self).execute(*args, **kwargs)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 88, in handle
    self.download(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 101, in download
    self.process_content_pack(zf, lang)
  File "/Users/didim/LE/ka-lite/kalite/distributed/management/commands/retrievecontentpack.py", line 126, in process_content_pack
    call_command("annotate_content_items", language=lang)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/didim/LE/ka-lite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/management/commands/annotate_content_items.py", line 43, in handle
    annotate_content_models(database_path=database_path, channel=channel, language=language)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 133, in wrapper
    output = function(*args, **kwargs)
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 655, in annotate_content_models
    for path, update in content_models:
  File "/Users/didim/LE/ka-lite/kalite/topic_tools/content_models.py", line 560, in iterator_content_items
    items = Item.select().dicts().iterator()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2797, in iterator
    return iter(self.execute().iterator())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2787, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 2470, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3199, in execute_sql
    self.commit()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3048, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such column: t1.sort_order
[25/Feb/2016 01:15:44] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285740 HTTP/1.1" 200 2
[25/Feb/2016 01:15:46] "GET /api/updates/progress?process_name=languagepackdownload&start_time=2016-02-25T00:15:32.000Z&_=1456359285741 HTTP/1.1" 200 2
```

**Comment by rtibbles** [comment] 2016-02-25 00:24
Could you open a new issue with this traceback? Also seems to be an issue finding the new db.

**Comment by radinamatic** [comment] 2016-02-25 00:28
No prob, passing this to a separate issue.

However, I just switched videos to Portughese, and `pop form empty list` and `TypeError: node is null` errors appeared. Not sure if we are out of the woods yet here... 

![update_videos016-pt-br](https://cloud.githubusercontent.com/assets/1457929/13305874/14305f08-db5f-11e5-9e76-d4ee8452ca3a.png)
