### ISSUE TITLE
Missing Xhosa contents

### ISSUE THREAD

**Issue by lihle** [learningequality/ka-lite#5120] opened 2016-05-17 13:29 UTC
Dear Khan Lite, 

Everytime I try install kalite videos for the beta language pack - Xhosa, which is our local language it doesn't give me the tree to select the video's from as it does with the English. Even if we scan for video's it says Scanning started, but never brings up the tree as with English. I have tried everything on different computer and the same result everywhere. Please see the attached screen shots. Let me know if this is a bug.

I am using ubuntu version 14.04 LTS and the kalite version is 0.16.5 

 - Installer: Debian (Ubuntu 14.04 LTS
![screenshot from 2016-05-17 14 42 06](https://cloud.githubusercontent.com/assets/19408984/15323812/0485a09c-1c44-11e6-8592-c5162ccac006.png)
)
 - Version: 0.16.5 (KA lite)

![screenshot from 2016-05-17 14 42 41](https://cloud.githubusercontent.com/assets/19408984/15324180/b8f2dce2-1c45-11e6-8cc2-60c9bf9d1153.png)

If you look at the screen shots, you will see that on the English package I can choose the videos I want to download, unlike the Xhosa package that doesn't even give an option to choose from.

**Comment by benjaoming** [comment] 2016-05-17 16:34
Hi @lihle - thanks for a good report!

Since Xhosa videos [do exist](https://xh.khanacademy.org/), I would assume that the content pack is badly built. What say ye, Mr. @aronasorman ? :)

**Comment by lihle** [comment] 2016-05-18 06:49
Hi there

How do I fix the problem then?

**Comment by lihle** [comment] 2016-05-18 09:08
Hi guys, thanks for  your time.

Thanks for taking time to help me with my problem. Just for your
information the xhosa videos are working fine on ka-lite version 0.15.1 and
the tree displays correctly.

Hope this information helps.

Best regards,
Lihle

**Comment by benjaoming** [comment] 2016-05-18 14:07
Hi @lihle - In 0.15.1, we were using a different format to store exercise and content data in KA Lite. So we introduced the concept of "content packs". Those are generated on our servers, and I fear that something has gone wrong generating the Xhosa content pack, although I can't say for sure, so I'm asking others to share their experience :)

**Comment by lihle** [comment] 2016-05-18 14:39
Dear Benjamin,

Thank you for your time. As I have said when I opened the issue, I have
tried to install it on various computers and servers in various ways over
three days now and all have the same result. Doesn't matter what I do, I
can't get the video tree to display, where the English one works every time.

So I think your analysis that the "concept pack" didn't build correctly
seems like the issue. You are welcome to use Team Viewer should you want to
log onto our server to see what the problem is if that can help?

Please let me know what your finding are, as we are currently in the
process of installing Ka-lite in the rural schools in our area as these
schools got tablets and a servers sponsored. We are also going to use your
Khan-Lighthouse Outerbox in the future for schools who don't have servers.

All these students in these schools talk the local language of Xhosa and
mostly don't speak English. So the Xhosa video's are crucial for the
success of our program.

Let me know if there is anything that I can do to assist you to help solve
the problem.

Looking forward to hear from you!
Thank you so much for your amazing work.

Best Regards,
Lihle

**Comment by benjaoming** [comment] 2016-05-18 15:26
>  All these students in these schools talk the local language of Xhosa and mostly don't speak English. So the Xhosa video's are crucial for the success of our program. 

Thanks for explaining the nature and severity of the issue. I'm hoping to see this prioritized very soon in one way or the other. Our team is very occupied, but this is not something we should sit over, we'll figure it out! What's your time lines for deploying?

**Comment by lihle** [comment] 2016-05-19 09:55
Dear Benjamin,

Thank you for taking the time to address the issue. It is kindly
appreciated. We have a continual relationship with the schools, so for now
we will deploy the system without the video's so that students can at least
start with the exercises. Once a fix is available I will go back to the
schools to install the fix. Let me know if you struggle to reproduce the
problem on your side.

So in theory, no deadline except that the students can't use video's for
now...

Thank you again for your help!
Enjoy your day,
Ruan

**Comment by benjaoming** [comment] 2016-06-07 17:19
@radinamatic would you be able to confirm Ruan's and Lihle's problem and if necessary add some comments about reproducing the issue?

@lihle - we'll get to the bottom of this, we have been experiencing some issues with language codes and Khan Academy's API changes combined with out own internal changes.

**Comment by aronasorman** [comment] 2016-06-07 21:32
Hi @lihle -- thanks for reporting this!

After digging a bit, it seems that KA's API doesn't serve any kind of subtitled or dubbed video at all. So the content pack maker is filtering out all nodes from the topic tree.

**Comment by aronasorman** [comment] 2016-06-07 21:33
The solution in here is to reintegrate the spreadsheet that was used by KA before -- I believe @cpauya is currently handling that. We'll update this issue once we're done!

**Comment by lihle** [comment] 2016-06-08 13:08
I appreciate it very much that you taking time to help me with my problem,
am sure you have other commitments that maybe you were suppose to be handle
but you taking that time helping me. I appreciate it even more that you
giving me the updates on your progress with me problem.
Hoping to hear from you guys when you have something.

thank you

**Comment by benjaoming** [comment] 2016-06-11 17:37
@aronasorman do you have any knowledge as to why KA.org doesn't serve Xhosa through the API, and is there any way to convince them to do so -- so we can avoid spreadsheets :)

**Comment by benjaoming** [comment] 2016-06-17 18:50
This is an issue that will be fixed separately in content packs and is not as such tied to the 0.16.7 release. Watch this issue or our mailing list for an announcement.

**Comment by benjaoming** [comment] 2016-06-18 15:10
Closing #5091 as a duplicate.

Affected languages seem to be: Burmese (my), Indonesian (id), Kannada (ka), Swahili (sw), Tamil (ta), Xhosa (xh), Zulu (zul)

**Comment by lihle** [comment] 2016-06-21 10:45
Morning

I am very thankful for taking your time to help me with my issue, I know
you very busy with other matters and don't mean to put pressure on you guys
I just want to follow up on the progress regarding my issue.

Enjoy your day, appreciate everything you doing for me.

**Comment by benjaoming** [comment] 2016-06-21 10:58
@lihle 

A list of all dubbed video contents is being added to the automated builder => https://github.com/fle-internal/content-pack-maker/pull/30

Not sure if you have access to that ticket, but it's just been updated 2 hours ago. Once it's solved, we have to allow for another 1-2 days for the content packs to be rebuilt by the servers. It's a lot of content and API calls.

**Comment by lihle** [comment] 2016-06-22 07:18
Morning

I appreciate you taking your time, you are amazing. I am also thankful for
the feedback you giving on this issue, looking forward to hearing from you
again.

Enjoy your day

**Comment by benjaoming** [comment] 2016-06-25 01:30
Thanks @lihle :)

What say thee great @cpauya about the progress of fle-internal/content-pack-maker#30 ? :)

**Comment by cpauya** [comment] 2016-06-26 02:19
Hi @benjaoming 😸 

The PR https://github.com/fle-internal/content-pack-maker/pull/30 has been updated / fixed by @amodia as reviewed earlier and can now be reviewed again by @aronasorman.  We hope to close it by this week so we can generate the updated content packs.

**Comment by benjaoming** [comment] 2016-06-27 16:28
Hurray! I'll add it to the release notes of 0.16.7 so we get the word out once it's released!

**Comment by radinamatic** [comment] 2016-06-27 16:48
@cpauya @aronasorman 
Ping me too, once the new contentpacks are ready for testing! :+1:

**Comment by lihle** [comment] 2016-07-27 08:42
Hi guys
I am just following up with you concerning my video issue. I know you
working very hard on helping me and I appreciate it very much which is why
I wanted to check the progress on that issue.
Thank you very much and enjoy your day

On 21 Jun 2016 12:58 pm, "Benjamin Bach" <notifications@github.com> wrote:

@lihle <https://github.com/lihle>

A list of all dubbed video contents is being added to the automated builder
=> fle-internal/content-pack-maker#30
<https://github.com/fle-internal/content-pack-maker/pull/30>

Not sure if you have access to that ticket, but it's just been updated 2
hours ago. Once it's solved, we have to allow for another 1-2 days for the
content packs to be rebuilt by the servers. It's a lot of content and API
calls.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/learningequality/ka-lite/issues/5120#issuecomment-227406926>,
or mute the thread
<https://github.com/notifications/unsubscribe/ASgoWCmImHwJJNPQlPpW5KKWatZV9yC0ks5qN8PDgaJpZM4IgRrR>
.

**Comment by arceduardvincent** [comment] 2016-07-28 14:51
Hi @lihle the issue doesn't replicate anymore see image attachment. 
I used the [content-pack](http://pantry.learningequality.org/downloads/ka-lite/0.16/content/contentpacks/) from the pantry `en.zip`.
Generate dubbed video mappings fix found at  [fle-internal/content-pack-maker#30](https://github.com/fle-internal/content-pack-maker/pull/30).

![screen shot 2016-07-28 at 10 35 52 pm 2](https://cloud.githubusercontent.com/assets/4099119/17216692/407d92cc-5514-11e6-8279-634046a2813f.png)

**Comment by benjaoming** [comment] 2016-07-28 15:56
@arceduardvincent - that's great news! So things should in theory work for an version of 0.16 provided that a new English content pack is downloaded first.

But I'd recommend to wait for the 0.16.7 as many other issues will be solved in this one :)

Closing this, thanks for testing @arceduardvincent !

**Closed by benjaoming** 2016-07-28 15:56 UTC
Labels: content / perseus

**Comment by lihle** [comment] 2016-08-17 14:49
Hi there

I just wanted to check with you guys if that Xhosa video package issue has
been dealt with, if so how do I get it.

thanks a lot for your time and much importantly for your help, appreciate
it.
Lihle

**Comment by benjaoming** [comment] 2016-08-17 15:01
@lihle yes, it has been fixed. There are new content packs available for download. Thanks for reporting this and please say if you have any further issues.

To retrieve a content pack, either use the command line `retrievecontentpack` or get it from **Manage -> Language**.
