### ISSUE TITLE
Videos not Updated after Download Process 

### ISSUE THREAD

**Issue by Chapi15** [learningequality/ka-lite#5139] opened 2016-06-06 21:01 UTC
## Summary
When I want to download videos the download process starts without any bug, but when the time for updating or uploading them to the server comes, an error appears.

 By the way, I'm new to Linux and the use of Servers, Python, and the Raspberry Pi. 

## Branch and installer method
 - Installer: Debian (Raspbian)
 - Version: 0.16.5 
 - Branch: master

## Expected Behaviour 
Videos are downloaded successfully and then the server's contents are updated.

## Current Behaviour 
Videos are not downloaded, a message telling the process encountered an error appears. The server's contents are not updated.

## How to reproduce
1. Go to the "Videos" Section
2. Select a video from any of the available topics
3. Download the selected video
4. Wait until the download finishes
5. Check if the video was uploaded or if a message notifying an error appeared. The message should say there was an error during the update process

## Screenshots
Download Process
![screen shot 2016-06-06 at 14 29 56](https://cloud.githubusercontent.com/assets/19766522/15836813/d04b5096-2bf3-11e6-9c58-261f8251cc39.png)

Error Message 
![screen shot 2016-06-06 at 14 30 11](https://cloud.githubusercontent.com/assets/19766522/15836814/d08b7900-2bf3-11e6-9461-0fdcfab7eb46.png)

## Real-life consequences 
It affects the deployment by not having the full content available. The community would only have exercises for practicing, but not the lectures and videos of each topic.

**Comment by benjaoming** [comment] 2016-06-07 13:17
Sorry sorry sorry, this is fixed in #5138 which I think @jamalex has concluded the review of, I'm just waiting for a final green light.

It'll be released in 0.16.6, you can use the fixed development version by running `pip install ka-lite --pre`, after that, du `sudo rm -rf /usr/share/kalite/python-packages/requests` to remove the very old version of `requests` that is installed together with ka-lite-raspberry-pi.

Closing this as it's a duplicate of #5126 but please subscribe yourself to the other issue to get notified as soon as it's released (during this week).

**Closed by benjaoming** 2016-06-07 13:17 UTC

**Comment by Chapi15** [comment] 2016-06-07 17:55
Ok, I will check those issues and do what you wrote above @benjaoming. Thanks for your help and for your review about my report
