### ISSUE TITLE
Internet Explorer 7

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#2925] opened 2015-01-30 23:26 UTC
I'm doing a pilot at 3 correctional facilities in Virginia in preparation for a statewide roll out. I've noticed issues with the practice menu when using KaLite on Windows XP or 7 clients running IE 7. The user cannot type the answer in the field.

I was not able to try other versions of IE, most of my users are on IE 10 or 11 and have no issues. Since upgrade of IE is a challenge without Internet connectivity, I just installed Chrome. Thought I'd report in case it's an unknown issue.

**Comment by cts-prog3** [comment] 2015-03-03 01:13
I am having the same problem with not being able to type the answer in the answer field.  What did you end up doing?  I am using Internet Explorer 8.

**Comment by aronasorman** [comment] 2015-03-03 05:20
@EdDixon can you try replicating this?

**Comment by waltonrp** [comment] 2015-03-03 11:06
I had to install Chrome. Windows XP will not go higher than 8, I needed Internet access to get the Window 7 machines higher than 8, since there are a lot more dependent updates needed. a stand-alone installer for Chrome seemed the quickest fix. Problem is I can't secure Chrome through policy (I heard that there is a way, but have not explored)

**Comment by MCGallaspy** [comment] 2015-03-05 20:24
Closed since you found a workaround and this is a duplicate of #3171, which seems to have a more active discussion right now.

**Closed by MCGallaspy** 2015-03-05 20:24 UTC
Labels: bug, high priority

**Comment by EdDixon** [comment] 2015-03-06 03:38
Hi just wanted to be sure this gets out to all that may need it Google does
have an enterpris
e version of chrome available!  https://www.google.com/work/chrome/browser/

Thanks,

On Thu, Mar 5, 2015 at 1:24 PM, Michael Gallaspy <notifications@github.com>
wrote:

> Closed #2925 <https://github.com/learningequality/ka-lite/issues/2925>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/learningequality/ka-lite/issues/2925#event-247062644>.
>



-- 
Ed Dixon
Corrections Adviser
Foundation for Learning Equality <http://learningequality.org/>
Give to FLE <https://learningequality.org/give/>, Support FLE via Amazon
Smile! <http://smile.amazon.com/ch/46-2676188>
M (575)-636-9549
