### ISSUE TITLE
Xhosa Language Pack not working

### ISSUE THREAD

**Issue by ruancilliers** [learningequality/ka-lite#3500] opened 2015-04-10 15:14 UTC
Dear Khan Lite,

The Xhosa Language packs are not working. Please see the attached screen shots...

branch:master
Note this is the latest update available ( I updated the Khan server yesterday - 8 April 2015)

Screen Shot 1 - Firstly, after I downloaded the Xhosa language pack, I don't have the tree available to see which video's I still need.

I then had to copy the Xhosa Videos into the content directory manually and re-install the Khan Server, otherwise I could not see the Xhosa dubbed video's (See screenshot 2). Is there a better way to do this than re-installing the whole server after I copied the Xhosa video's into the content directory.

Screen Shot 2 - After the re-installation I can see the video's that I added into the Content directory (In this case the Basic Addition Xhosa Video)

Screen Shot 3 - After selecting the Xhosa dubbed video "xh", I still get the English version as you can see in Screen shot 4.

Screen Shot 4 - Even is I try to change back to Xhosa, the English version is still automatically selected and played.

So the two questions is (1) How do I download the Xhosa Video list and update the display list after I copied all the Xhosa Videos into the Content Directory  and (2) How do I play the Xhosa version, once it sows as is the screen shots below?

Looking forward to hear from you!
Ruan
![1-downloading the xhosa videos does not work](https://cloud.githubusercontent.com/assets/11680550/7090654/e0878c32-dfa4-11e4-9ede-68f6032a46f4.png)
![2-selecting the xhosa dubbed videos does not work when the xhosa language is selected](https://cloud.githubusercontent.com/assets/11680550/7090655/e08f3fb8-dfa4-11e4-9df0-cda392b7fa89.png)
![3-english settings when i select xhosa](https://cloud.githubusercontent.com/assets/11680550/7090656/e09f036c-dfa4-11e4-83dd-7e912ce5a0b9.png)
![4-change to xhosa language and it then plays the english version](https://cloud.githubusercontent.com/assets/11680550/7090657/e0a07076-dfa4-11e4-91b1-9e80e58d8763.png)

**Comment by aronasorman** [comment] 2015-04-14 18:15
Downloaded Xhosa. Can replicate on 0.12.

**Comment by ruancilliers** [comment] 2015-04-14 19:20
Dear Aron,

Do you mean you could replicate this problem, or do you mean that you downloaded the Xhosa package and it worked on your side? Is there any other steps that you need from my side or could you replicate the problem successfully? If not, I'm happy that you log into my server with teamviewer or a similar program so that you can see what the issue is.

Thank you for your support. We are really excited to have the Xhosa video's for our Village...

**Comment by aronasorman** [comment] 2015-04-15 19:49
@ruancilliers not working on my side. Just to confirm, I've checked the crowdin projects for both `ka-lite` and `khanacademy`, and they both don't have translations. So I'm focusing my debugging solely on the dubbed videos.

Moving forward, I noticed that loading the topic tree for Xhosa (http://127.0.0.1:8008/api/videos/topic_tree?lang=xh) returns `None`, which gets converted to the JSON `null` value. I'll be debugging why that happens.

**Comment by aronasorman** [comment] 2015-04-15 19:51
@ruancilliers can you check that URL and see if that returns `null` for your installation too?

**Comment by aronasorman** [comment] 2015-04-15 19:53
Oh and also, there's no basic addition mapping for Xhosa: https://docs.google.com/a/learningequality.org/spreadsheets/d/1k5xh2UXV3EchRHnYzeP6-YGKrmba22vsltGSuU9bL88/edit#gid=0

Which means your example won't work. To make basic addition work, you have to request KA to update their dubbed video mapping (the spreadsheet linked above.)

**Comment by ruancilliers** [comment] 2015-04-15 20:33
Dear Aron, 

Just to confirm, yes I only look at dubbed video's so you are on the right track. I did check the link in the spreadsheet and I could find the mapping for the Xhosa video for basic addition. So I'm not sure why you say you can't find it. Search for the string OCCY8Hk7_dQ in the document. This is the basic addition Xhosa dubbed video. Also you will find it on youtube https://www.youtube.com/watch?v=OCCY8Hk7_dQ
In the shared document that you send, this is on line 274 on excel which looks like this... 
271    02-01-2012	02-20-2011	Basic addition	cc-by-nc-sa	Math	Arithmetic	Addition and subtraction	Intro to addition and subtraction	basic-addition (Xhosa Dubbed Column - OCCY8Hk7_dQ)

Am I understanding this correctly? 

Thank you for you support,
Ruan

**Comment by ruancilliers** [comment] 2015-04-16 17:30
Dear Aron,

Just to confirm, I do get a null value return when I type in the url as you requested. See the attached screen shot...

Let me know if you need anything else from me. 
Great!
Ruan

![null value returned](https://cloud.githubusercontent.com/assets/11680550/7187148/0042a06a-e46f-11e4-8dcf-d0f3cc114094.JPG)

**Comment by ruancilliers** [comment] 2015-04-21 19:12
Hi Aron, 

Just to let you know, I managed to get all of the dubbed video links to display... I just had to copy the video's into the content folder and the xhosa dubbed links automatically appeared. Still all of the xhosa links plays the english version. So I guess with the next update all of the dubbed Xhosa links should work?

Thank you for your assistance and let me know if you need any other information.

Enjoy your day,
Ruan

**Comment by aronasorman** [comment] 2015-04-21 19:15
Oh, strange. Sorry for not responding @ruancilliers, I'm still trying to figure out why it's returning a `null` value. I'll keep working on this to find the root cause, and hopefully have a fix for the 0.13 line.

**Comment by ruancilliers** [comment] 2015-04-21 19:20
Fantastic! Thank you for your time Aron. Let me know if you need any other analysis to be done from my side. If you need logs etc. let me know... Chat then soon!

**Comment by aronasorman** [comment] 2015-04-21 21:06
Testing on 0.13: Not working on Xhosa.. Tested French, working perfectly.

**Comment by ruancilliers** [comment] 2015-04-21 21:09
Hi Aron,

Can I supply you with logs to help find the bug? Please let me know how I
can assist. Thank you so much for your time and effort on this bug. I will
help in any way that I can...

Ruan

On Tue, Apr 21, 2015 at 11:06 PM, Aron Fyodor Asor <notifications@github.com

**Comment by aronasorman** [comment] 2015-04-21 21:15
@ruancilliers thanks. I'm getting these files when downloading Xhosa videos:
```
  -rw-rw-r--  1 aron aron 5377045 Apr 21 12:17 content9XZypM2Z3Ro.mp4
  -rw-rw-r--  1 aron aron   98304 Apr 21 12:17 content9XZypM2Z3Ro.png
  -rw-rw-r--  1 aron aron 3650105 Apr 21 13:45 contentkFy-c5jxbio.mp4
  -rw-rw-r--  1 aron aron   58492 Apr 21 13:47 contentkFy-c5jxbio.png
  -rw-rw-r--  1 aron aron 3593029 Apr 21 13:42 contentOCCY8Hk7_dQ.mp4
  -rw-rw-r--  1 aron aron   56444 Apr 21 13:43 contentOCCY8Hk7_dQ.png
  -rw-rw-r--  1 aron aron 4545270 Apr 21 13:47 contentvq_CHZ9ajnc.mp4
  -rw-rw-r--  1 aron aron   74116 Apr 21 13:48 contentvq_CHZ9ajnc.png
  -rw-rw-r--  1 aron aron     904 Apr 21 09:20 
```
Notice that it's putting the videos in the root dir and concatenated with `content` rather than putting them in the content dir. I wonder if that's the reason? Is it the same in your case @ruancilliers?

**Comment by ruancilliers** [comment] 2015-04-21 21:40
Hi Aron,

This could most probably be the issue... Unfortunately I don't have the
option of downloading Xhosa Video's. See the attachment. How do I check
which version I'm on to make sure I'm on the latest version?

Thank you,
Ruan

On Tue, Apr 21, 2015 at 11:15 PM, Aron Fyodor Asor <notifications@github.com

**Comment by aronasorman** [comment] 2015-04-21 21:44
The installation you're running on your screenshots is the 0.12.x line. To know the precise version, look inside `kalite/version.py`.

Also, we just released the release candidate for this upcoming version of KA Lite, 0.13.0. If you wanna test it out, you can download the windows installer from [here](https://learningequality.org/downloads/ka-lite/0.13/installers/windows/KALiteSetup-0.13.0-rc1.exe).

**Comment by aronasorman** [comment] 2015-04-21 21:44
Also, the above might be an issue with 0.13.x too. I'll try fixing it today-tomorrow and see if we can get it in for 0.13.

**Comment by ruancilliers** [comment] 2015-04-21 22:14
Great Aron,

Thank you for your help. I hope you can get the bug fix before you release
the 0.13 line...

Really appreciate your help. Let me know when you have fixed it and I will
test the candidate version on my side...

(In South Africa it is 00:15am now, so I will continue the support tomorrow)
Great!
Ruan

On Tue, Apr 21, 2015 at 11:44 PM, Aron Fyodor Asor <notifications@github.com

**Comment by aronasorman** [comment] 2015-04-21 22:48
It's working now, I've successfully played a foreign language video (that I presume is Xhosa). Will push a fix.

**Comment by ruancilliers** [comment] 2015-04-21 23:09
That is FANTASTIC news! Thank you so much Aron!

On Wed, Apr 22, 2015 at 12:48 AM, Aron Fyodor Asor <notifications@github.com

**Comment by aronasorman** [comment] 2015-04-21 23:58
Nice, github has a feature where this will auto-close when 0.13 gets merged to master :)

**Comment by ruancilliers** [comment] 2015-04-22 06:13
Thank you Aron, by when will 0.13 be merged to the master, so that I can do
an update on our server? Is there a prospective date yet?

**Comment by aronasorman** [comment] 2015-04-22 15:45
The merge date is scheduled this Monday, April 27. Although you can pull it now and download the latest videos by running:

```
git clone https://github.com/learningequality/ka-lite.git --depth 1 --branch v0.13.x
```

on a different directory.

And then copy over the database to that new copy of KA Lite and see if it fixes Xhosa language packs for you.

**Closed** 2015-04-28 00:18 UTC
Labels: bug, internationalization
