### ISSUE TITLE
Missing Assessment items in ka-lite-bundle

### ISSUE THREAD

**Issue by radinamatic** [learningequality/ka-lite#4182] opened 2015-07-28 20:54 UTC
Missing Assessment items in ka-lite-bundle

**Branch**: 0.14 alpha12 installed today from PPA on Ubuntu 15.04

With the code provided by @rtibbles 

```
bin/kalite shell
...
from kalite.topic_tools import get_exercise_cache
cache = get_exercise_cache()
for key, value in cache.iteritems():
    if not value.get("available", False):
        print key
```

Shell listed these 4 exercises as missing:

```
increasing-decreasing-intervals-of-functions
dividing_decimals
dividing_fractions_word problems_2
matrix_determinant
```

Filing this so we can make sure the content is updated for 0.15 with these available.

**Comment by aronasorman** [comment] 2015-08-07 20:59
Seems to be "solved" in the Windows installer? I'm assuming it's been solved for the deb installer as well.

**Comment by radinamatic** [comment] 2015-08-07 21:00
Not solved, but circumventable.

**Comment by radinamatic** [comment] 2015-08-07 21:01
Sorry, no, this one is not solved @aronasorman !
These are **really** missing!

**Comment by radinamatic** [comment] 2015-08-07 21:03
The rest is just not visible because of the availability stamping issue.

**Comment by aronasorman** [comment] 2015-09-01 15:50
I believe this issue has been fixed with the latest 0.14.

**Comment by radinamatic** [comment] 2015-10-07 01:15
Prompted by today's testing @EdDixon is doing on a similar problem, I revisited this issue with `ka-lite-bundle 0.15~b3-0ubuntu1`, and unfortunately, the problem got worse. 

The above script by @rtibbles now gives me **103** exercises missing! 
```
cellular-division-questions
somatosensation-questions
construct-basic-exponential-functions-from-initial-value-and-common-ratio
lymphatic-system-questions
solubility-equilibria-questions
graphs-of-rational-functions
increasing-decreasing-intervals-of-functions
axons--physics-and-chemistry-at-work-in-the-body
fluids-at-rest-questions
divide-polynomials-by-monomials
rh-passage-4
rh-passage-2
flow-and-poiseuille-s-law-in-operation
rh-passage-1
equilibrium-questions
matrix_determinant
dividing_decimals
surface-areas
gamma-knife-radiosurgery
stoichiometry-questions
sound-questions
thin-lenses-questions
electrostatics-questions
dividing_fractions_word problems_2
newton-s-laws-and-equilibrium-questions
activation-of-t-lymphocytes
the-role-of-the-bicarbonate-buffer-system-in-regulating-blood-ph
redox-reactions-questions
hormonal-regulation-questions
a-young-patient-with-type-1-diabetes
analyze-vertical-asymptotes-of-rational-functions
initial-steps-in-the-metabolism-of-dietary-monosaccharides
isothermal-titration-calorimetry-in-drug-development
taste-and-smell-quiz
patient-with-a-missing-cerebellum
end-behavior-of-rational-functions
enzymes-questions
physics-of-walking-and-running
using-optical-traps-to-manipulate-single-dna-strands
typhoid-toxin
attention-questions
interpret-formulas-of-basic-exponential-functions
drug-dependence-questions
endocrine-system-questions-1
glucose-6-phosphate-dehydrogenase-and-the-most-important-function-of-the-pentose-phosphate-pathway
simplifying_rational_expressions_3
simplifying_rational_expressions_2
simplifying_rational_expressions_1
genetic-mutations-questions
pancreatitis-and-pancreatic-cells
dermoscopy
adding_and_subtracting_rational_expressions_3
rational-equations-3
stereochemistry-questions
proton-beam-therapy--particle-accelerators-in-medicine
proteins-questions
electromyography-and-passive-filters--circuitry-in-action
acid-base-questions
biosignaling-questions
normal-forces-questions
shortwave-diathermy-in-rehabilitative-medicine
could-complete-darkness-be-the-cure-for-amblyopia-
muscular-system-questions
quiz--js-libraries
graphs-of-basic-exponential-functions
rh-passage-3
cytoskeleton-questions
fluids-in-motion-questions
understanding-cardiac-pressure-volume-curves
multiplying_and_dividing_rational_expressions_2
multiplying_and_dividing_rational_expressions_3
multiplying_and_dividing_rational_expressions_1
clinical-applications-of-tuning-forks
macromolecules-skill-assessment
counting-systems-and-the-piraha-tribe-
a-physical-model-of-human-sitting
construct-basic-exponential-functions-from-table-or-graph
psychological-disorders-questions
free-energy--photosynthesis--and-cellular-respiration-
interpret-graphs-and-tables-of-basic-exponential-functions
endocrine-system-questions-2
adding_and_subtracting_rational_expressions_2
adding_and_subtracting_rational_expressions_5
driving-and-talking-on-a-cell-phone
human-physiological-development
periodic-table-questions
prokaryotes-questions
selection-of-radionuclides-for-radiopharmaceuticals
electrochemistry-questions
solving_rational_equations_2
perky-effect
remainder-theorem-of-polynomials
embodied-cognition--hockey--does-expertise-impact-text-understanding-
congestive-heart-failure-and-diuretics
dividing-polynomials-with-remainders
forces-on-inclined-planes-Zheng
the-physics-of-eyesight-correction
measuring-glomerular-filtration-rate-of-the-kidneys-with-inulin
thermodynamics-questions
adding_and_subtracting_rational_expressions
divide-polynomials-by-binomials
dot-structures-questions
congruent_triangles_1
```

I tried to open a few of them randomly, and they are indeed missing, but I can only see the 301 response:

![missing-assessment](https://cloud.githubusercontent.com/assets/1457929/10326900/f1337878-6ca0-11e5-8737-44951020aeac.png)

![missing-assessment2](https://cloud.githubusercontent.com/assets/1457929/10326937/83b91220-6ca1-11e5-8eec-8aa1a6facb55.png)


cc/ @aronasorman @benjaoming

**Comment by radinamatic** [comment] 2015-10-07 17:33
I can confirm this happening on Windows XP with the latest 0.15 installer, after adding exercises from the `khan_assessment.zip`. The exact and same 103 exercises are missing as in the above report on the Ubuntu installation with `ka-lite-bundle`.

**Comment by benjaoming** [comment] 2015-10-08 14:13
0.14.2 is stille okay :)

```
>>> from kalite.topic_tools import get_exercise_cache
>>> cache = get_exercise_cache()
>>> cnt=0
>>> for key, value in cache.iteritems():
...     if not value.get("available", False):
...         cnt+=1
...         
...     
... 
>>> cnt
4
```

**Comment by rtibbles** [comment] 2015-10-08 15:24
@radinamatic As soon as new installers are built, this should, hopefully, be resolved. Please verify!

**Comment by radinamatic** [comment] 2015-10-08 15:26
I already tried on XP with the latest `khan_assessments.zip` that Jamie posted, but I'm still getting 103 missing. Hopefully it will be resolved with the new installers!

**Comment by rtibbles** [comment] 2015-10-08 15:28
Hrm - that should be the only difference, alack. It may be that we just have some bad exercises in there.

**Comment by radinamatic** [comment] 2015-10-08 15:33
Can I somehow **undo** the previous `kalite manage unpack_assessment_zip` commands, or is the new installation the only way to know?

**Comment by rtibbles** [comment] 2015-10-08 15:33
Unpacking the new zip over the old one should be sufficient.

**Comment by rtibbles** [comment] 2015-10-08 15:40
Ah, seems like @jamalex and I had a miscommunication. Hopefully this should be resolved when the full assessment item rebuilding has occurred.

**Comment by jamalex** [comment] 2015-10-08 16:54
Hopefully now fixed, once https://github.com/learningequality/ka-lite/pull/4592 is merged.

**Comment by rtibbles** [comment] 2015-10-08 16:57
@radinamatic can you test with this new zip? http://pantry.learningequality.org/downloads/ka-lite/0.15/content/khan_assessment.zip

**Comment by radinamatic** [comment] 2015-10-08 21:00
With this latest zip I only get 5 assessments reported as missing:
```
increasing-decreasing-intervals-of-functions
matrix_determinant
dividing_decimals
dividing_fractions_word problems_2
multiplying-and-dividing-whole-numbers-by-powers-of-10
```

These 5 do present as missing with the `This content was not found! Please contact your coach or an admin to have it downloaded.` warning:

![missing-ai0](https://cloud.githubusercontent.com/assets/1457929/10379680/f3abe6ec-6e0f-11e5-8ce9-5b23d616d7db.png)

The rest from the previous script output do not appear as missing or grayed out, neither in search, nor they trigger the warning. However, no content seem to load, and they do throw an  `Uncaught ReferenceError: $_ is not defined:

![missing-ai](https://cloud.githubusercontent.com/assets/1457929/10379644/af413458-6e0f-11e5-8af3-f8fc17bb05ce.png)

**Comment by rtibbles** [comment] 2015-10-08 23:46
So... looks like the issue here is that someone (qua muggins, aka me) forgot to update Perseus.

**Comment by radinamatic** [comment] 2015-10-09 22:36
Today's installer on XP: no errors, and content loads except the pic:

![no-pic](https://cloud.githubusercontent.com/assets/1457929/10407120/e4b8bee4-6ee6-11e5-98bf-22158e29beba.png)

Happens in both English and Spanish version - only the pic is missing.

**Comment by radinamatic** [comment] 2015-10-09 22:38
And with this latest fix, we are back to 4 missing according to @rtibbles script:
```
increasing-decreasing-intervals-of-functions
matrix_determinant
dividing_decimals
dividing_fractions_word problems_2
```

**Comment by rtibbles** [comment] 2015-10-09 22:43
Are pictures missing from any other questions?

**Comment by MCGallaspy** [comment] 2015-10-09 22:44
IMO if the problem is contained to 4 items, then we should consider releasing with a list of "Known Issues", then proceed to tackle in the next cycle.

**Comment by rtibbles** [comment] 2015-10-09 22:55
I agree. This will also be resolved by the changes @aronasorman and I have
planned for building content data in 0.16.

**Comment by radinamatic** [comment] 2015-10-09 22:57
> Are pictures missing from any other questions?

The missing one is a `svg`, I'm going through the rest of them (103), and I only found one `png` that displays well. I'll annotate any & all that are missing for future testing.

**Comment by radinamatic** [comment] 2015-10-09 23:02
`graphs-of-rational-functions`

![graphs-of-rational-functions](https://cloud.githubusercontent.com/assets/1457929/10407402/94dbdbf0-6eea-11e5-9866-a1b058e3e4bd.png)

Also `SVGs`.

**Comment by radinamatic** [comment] 2015-10-09 23:10
`surface-areas`

![surface-areas](https://cloud.githubusercontent.com/assets/1457929/10407495/9f8928e0-6eeb-11e5-96c4-d02b5ab3a674.png)

Sofar all `SVGs`.

**Comment by radinamatic** [comment] 2015-10-09 23:41
Doesn't seem broken, but *hay caca*, as we say over here... ;)

`graphs-of-basic-exponential-functions`

![graphs-of-basic-exponential-functions](https://cloud.githubusercontent.com/assets/1457929/10407768/de91c534-6eef-11e5-9c79-4af51a5267d3.png)

**Comment by radinamatic** [comment] 2015-10-09 23:48
`a-physical-model-of-human-sitting`

![a-physical-model-of-human-sitting](https://cloud.githubusercontent.com/assets/1457929/10407844/f017ce06-6ef0-11e5-80e0-05ee8f3ed6ac.png)

**Comment by radinamatic** [comment] 2015-10-10 00:11
`construct-basic-exponential-functions-from-table-or-graph`

![construct-basic-exponential-functions-from-table-or-graph](https://cloud.githubusercontent.com/assets/1457929/10407904/d310981e-6ef1-11e5-8a03-ac96d94c7f56.png)

**Comment by radinamatic** [comment] 2015-10-10 00:22
To recap:

###### 4 missing completely with the alert `This content was not found! Please contact your coach or an admin to have it downloaded.`:
```
increasing-decreasing-intervals-of-functions
matrix_determinant
dividing_decimals
dividing_fractions_word problems_2
```

###### From the above 103 that were previously missing but not anymore, these 6 have missing `svg` images: 

`graphs-of-rational-functions`
`surface-areas`
`graphs-of-basic-exponential-functions`
`a-physical-model-of-human-sitting`
`construct-basic-exponential-functions-from-table-or-graph`
`congruent_triangles_1`

**Comment by radinamatic** [comment] 2015-11-19 21:41
Rechecked all the above missing `svg` images and they are now present and accounted for in the latest `deb` installers by @benjaoming from here:
http://ppa.launchpad.net/learningequality/ka-lite-proposed/ubuntu/pool/main/k/ka-lite-source/

However, the 4 assessment items that were missing since the beginning are still, missing.

Also, console reports 3 `woff2` fonts missing, called by `perseus` and `bundle_common`:
```
NotFound: (404, "The path '/static/fonts/glyphicons-halflings-regular.woff2' was not found.")
NotFound: (404, "The path '/static/fonts/KaTeX_Main-Regular.woff2' was not found.")
NotFound: (404, "The path '/static/fonts/KaTeX_Math-Italic.woff2' was not found.")
```

**Comment by rtibbles** [comment] 2016-02-01 20:19
@radinamatic Please make sure this is resolved during testing for 0.16.

**Comment by aronasorman** [comment] 2016-02-23 20:15
Is this now fixed @benjaoming?

**Comment by radinamatic** [comment] 2016-02-23 20:24
I'll re-check this with Alpha3 deb installer and report back, @aronasorman!

**Comment by radinamatic** [comment] 2016-02-24 01:41
After searching manually the 4 above exercises, none report as missing, although I can't seem to find `matrix_determinant` anywhere... However, where did the `get_exercise_cache` go? Did somebody refactor it to oblivion? @rtibbles above script is not working anymore:

```
didi@didi-virtualbox:~/Desktop$ kalite shell
[WARNING] [2016-02-24 00:45:10,803] kalite: Channel khan does not exist.
Python 2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from kalite.topic_tools import get_exercise_cache
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name get_exercise_cache
>>>
```

**Comment by rtibbles** [comment] 2016-02-24 02:00
It is an ex-method.

```
from kalite.topic_tools.content_models import get_content_items
nodes = get_content_items()
exercises = [node for node in nodes if node.get("kind")=="Exercise"]
```

**Comment by rtibbles** [comment] 2016-03-01 23:53
No longer relevant now that we prefilter exercises and set availability to True before distribution.

**Closed by rtibbles** 2016-03-01 23:53 UTC
Labels: bug, release blocker
