### ISSUE TITLE
Can't authenticate from client on windows domain

### ISSUE THREAD

**Issue by waltonrp** [learningequality/ka-lite#5142] opened 2016-06-08 00:55 UTC
## Summary

I have about 10 KA Lite servers on v13.2, when we looked at V14, we had an issue that users (admin, coach, learner) can't log on from any computer that is Windows domain member. I'm trialing v16.5 at a couple of sites and having the same issue.

When a user tried to log on, the logon "popup" just blinks and resets to blank fields.
All other aspects of KA Lite appear to be working fine.
From a client computer not on the domain, but on the same subnet, same DHCP server, users can logon, access exercises, records, etc.
This is a corrections environment, clients have to be on the domain.

KA Lite Servers are running Ubuntu 16.04 LTS
KA Lite server is not domain member, it's on same subnet, static IP
I'm the domain admin, I'm not knowingly doing anything, group policy, etc that would get in the way of a user authenticating on KA Lite server.

Is there any log file that I could pull that might give us a hint?
## Branch or installer method

_Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred._
- Installer: Debian
- Version: 16.5

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

**Comment by benjaoming** [comment] 2016-06-11 16:37
Hi @waltonrp 

Thanks for the report!

> From a client computer not on the domain, but on the same subnet

Are there any differences other than this? Mainly: Is it the same browser?

**Comment by waltonrp** [comment] 2016-06-12 02:40
It’s the same browser, IE11. There are no other differences. Next week when on site, I’ll try to take one of the affected domain client machines off the domain and see if KA lets me authenticate….

Robert Walton
Regional Information Technology Specialist
DOC -CTSU

**Comment by benjaoming** [comment] 2016-06-12 12:59
@waltonrp is it `ka-lite` or `ka-lite-raspberry-pi` ?

If you could run `kalite start --foreground`, we can look at the logs to maybe troubleshoot which requests are problematic or never reach the server.

**Comment by waltonrp** [comment] 2016-06-13 11:34
I'm going to be at a site where I can look at this in production later. I ran the command here is result:


aguila@KALITE-Server01:~$ kalite start --foreground
Running 'kalite start' in foreground...

Stand by while the server loads its data...

To access KA Lite from another connected computer, try the following address(es):
    http://192.168.0.69:8008/
To access KA Lite from this machine, try the following address:
    http://127.0.0.1:8008/

[INFO] [2016-06-13 07:28:29,044] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Listening for SIGHUP.
[INFO] [2016-06-13 07:28:29,044] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Listening for SIGTERM.
[INFO] [2016-06-13 07:28:29,044] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Listening for SIGUSR1.
[INFO] [2016-06-13 07:28:29,044] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Bus STARTING
[INFO] [2016-06-13 07:28:29,044] cherrypy.error: [13/Jun/2016:07:28:29]  Loading and serving the Django application
[INFO] [2016-06-13 07:28:29,047] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Started monitor thread '_TimeoutMonitor'.
[INFO] [2016-06-13 07:28:29,176] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Serving on 0.0.0.0:8008
[INFO] [2016-06-13 07:28:29,177] cherrypy.error: [13/Jun/2016:07:28:29] ENGINE Bus STARTED
[INFO] [2016-06-13 07:29:13,949] django.request: HTTP Request / - Response: 200
[INFO] [2016-06-13 07:29:15,060] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/fonts/style.css HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,112] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/js/i18n/en.js HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,113] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/django_js_reverse/js/reverse.js HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,157] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/js/distributed/bundles/bundle_common.js HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,157] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/js/distributed/bundles/bundle_homepage.js HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,157] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/js/inline/bundles/bundle_inline_help.js HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,158] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/js/distributed/bundles/bundle_base.js HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,540] django.request: HTTP Request /_generated/dynamic.css - Response: 200
[INFO] [2016-06-13 07:29:15,541] django.request: HTTP Request /_generated/dynamic.js - Response: 200
[INFO] [2016-06-13 07:29:15,945] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/images/horizontal-logo-small.png HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,948] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/images/distributed/FLE.png HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,949] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/images/distributed/CC-BY-NC-SA.png HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,949] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/images/distributed/favicon.ico HTTP/1.1" 404 1394 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,950] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:15] "GET /static/images/logo_10_enlarged_2.png HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:15,970] django.request: HTTP Request /securesync/api/user/status/ - Response: 200
[INFO] [2016-06-13 07:29:16,102] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:16] "GET /static/images/jquery-ui-icons/ui-bg_flat_75_ffffff_40x100.png HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:29:16,120] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:29:16] "GET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 - "http://127.0.0.1:8008/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"
[INFO] [2016-06-13 07:30:30,977] django.request: HTTP Request / - Response: 200
[INFO] [2016-06-13 07:30:31,094] django.request: HTTP Request /_generated/dynamic.css - Response: 200
[INFO] [2016-06-13 07:30:31,114] django.request: HTTP Request /_generated/dynamic.js - Response: 200
[INFO] [2016-06-13 07:30:31,348] django.request: HTTP Request /securesync/api/user/status/ - Response: 200
[INFO] [2016-06-13 07:30:31,357] cherrypy.access.139727691945488: 127.0.0.1 - - [13/Jun/2016:07:30:31] "GET /static/images/distributed/favicon.ico HTTP/1.1" 404 1394 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0"



Robert Walton
Regional Information Technology Specialist

DOC - CTSU
________________________________

**Comment by benjaoming** [comment] 2016-06-13 11:43
@waltonrp that log looks fine, but is it a log of a failed request? I can see that all the requests are going for the `127.0.0.1` host, so it looks like you're displaying KA Lite on the same machine as it's running on.

**Comment by benjaoming** [comment] 2016-06-13 11:44
@waltonrp the problem occurs when accessing `http://192.168.0.69:8008/` on a client computer, right?

**Comment by waltonrp** [comment] 2016-06-13 12:04
This server is one that was showing the problem, but I took home to work on. The ip is from my home network. I’m taking that server to a production site today and wil give static ID on the domain and see if I get the same error. I’ll email you as soon as that is done.

Robert Walton
Regional Information Technology Specialist
DOC -CTSU

**Comment by benjaoming** [comment] 2016-06-13 13:13
@waltonrp but is the problem reproducible when accessing `127.0.0.1` on the server itself?

**Comment by waltonrp** [comment] 2016-06-13 13:34
No. Only from client on the domain. I can always log on via local host

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by waltonrp** [comment] 2016-06-13 14:42
Okay, I’m confused. I set up new version of server here today, Domain environ. Moved user data to new server and everyone seems to be logging on okay.  This is a Server 2012 domain, the other is 2008r2. I’ll be at site having issue on Wednesday and pull log file there.

Appreciate your patience

Bob Walton

**Comment by benjaoming** [comment] 2016-06-13 16:39
No problem, awaiting further input... I'm hoping you can't reproduce it ;)

**Comment by benjaoming** [comment] 2016-06-17 17:09
@waltonrp any news on this?

**Comment by waltonrp** [comment] 2016-06-20 20:31
Hey Benjamin. Sorry, I couldn't get to work on the issue last week. Tuesday and Wednesday of this week, I'll be onsite at a facility doing the same upgrade and see if I have the issue again. Sorry for the delay.....


Robert Walton
Regional Information Technology Specialist

DOC - CTSU
________________________________

**Comment by benjaoming** [comment] 2016-06-21 08:59
That's understandable, no worries, we'll be around :)

**Comment by waltonrp** [comment] 2016-06-23 16:58
Benjamin,

Attached is the log. I found that I can logon to KAlite from Chrome, but not from IE 11 either on or off domain. My laptop defaults to chrome, so that is what had me thinking that it was working off the domain. I had to run the start foreground command twice, first time it didn’t start so you should see that in log.  I’m going to leave this site up as is so I can test out anything there, it’s not far from my home..

Robert Walton
Regional Information Technology Specialist
DOC -CTSU

**Comment by benjaoming** [comment] 2016-07-27 21:15
Hi @waltonrp -- sorry about the late response. You cannot attach files to emails you've sent as a response to a Github issue. Please log in to Github and share the relevant contents of the file if still relevant.

**Comment by benjaoming** [comment] 2016-08-01 14:36
Hi @waltonrp - any news?

Regarding the Chrome / IE11 issue. It means you have no issues whatsoever with Chrome? What are the exact symptoms for IE11, and are they really related to this windows domain or could there be another factor? Could you post a screenshot maybe? - remember not mail attachments, use the Github interface ;)

**Comment by waltonrp** [comment] 2016-08-01 14:50
The only thing I have is the users cannot log on from IE11. Chrome works fine. 

Robert Walton
Regional Information Technology Specialist
DOC – CTSU – Field Services Unit

**Comment by benjaoming** [comment] 2016-12-17 00:49
Closing this mainly because it sounds like a network issue. I would suggest asking for help on http://community.learningequality.org/ if it persists.

If you find it is a problem with KA Lite itself, please feel welcome to comment here, and we can pick up where we left :)

**Closed by benjaoming** 2016-12-17 00:49 UTC
