### ISSUE TITLE
Server not starting in KA-Lite 0.16.9 

### ISSUE THREAD

**Issue by yogeshmr** [learningequality/ka-lite#5277] opened 2016-09-13 13:15 UTC
## Summary

After upgrading KA-Lite from 0.16.7 to 0.16.9, the server is not starting.
![image](https://cloud.githubusercontent.com/assets/21152041/18474791/72731c56-79e1-11e6-982b-92903608457a.png)

## System information
 - Operating system:  Windows 7
 - Version: 0.16.9
 - Browser: Chrome

## The following result is obtained in the command prompt

![image](https://cloud.githubusercontent.com/assets/21152041/18474837/a27b0bf2-79e1-11e6-8eba-2d06cb27d627.png)

Lots of orphan .pyc files get created and I am deleting them and trying but still in vain.

The requests folder in the below path is empty:
C:\Python27\share\kalite\python-packages\requests

**Comment by benjaoming** [comment] 2016-09-13 13:33
Thanks for reporting quickly and with a neat traceback! :)

The problem is apparently common: http://stackoverflow.com/a/32988728/405682

Could you try the two proposed solutions?

Using your default `pip` command should install python packages in the same environment that KA Lite uses, but it's hard to say if it'll work. In case none of the two commands work, try removing the entire folder `dist-packages/requests` (not the same as the previous `python-packages`) and the install the `requests` library straight from pip.

**Comment by yogeshmr** [comment] 2016-09-13 15:10
@benjaoming 

I deleted the contents of the requests folder in the path "C:\Python27\share\kalite\dist-packages\requests" and I think that fixed the issue.

Although I tried other things given in http://stackoverflow.com/a/32988728/405682 before deleting the contents of the requests folder.

Thank you very much for helping!!!!!!!

Below provides the snapshot of the commands that I tried before and after deleting the contents of the dist-packages\requests folder:

![image](https://cloud.githubusercontent.com/assets/21152041/18479216/d4023e7e-79f1-11e6-81e3-7e24dd145ee3.png)


![image](https://cloud.githubusercontent.com/assets/21152041/18479246/f4e8aa42-79f1-11e6-9cff-db1f56da0cf2.png)

![image](https://cloud.githubusercontent.com/assets/21152041/18479294/172f88aa-79f2-11e6-9990-a8439c39285d.png)


At last, the "kalite start" command worked:

![image](https://cloud.githubusercontent.com/assets/21152041/18479323/377ebeb4-79f2-11e6-8ecc-b289dfee09db.png)

**Comment by yogeshmr** [comment] 2016-09-13 15:12
The last image in the above comment should be 

![image](https://cloud.githubusercontent.com/assets/21152041/18479417/855b0340-79f2-11e6-8f0d-a0a3e5071154.png)

**Comment by benjaoming** [comment] 2016-09-13 16:25
@yogeshmr -- the fix is a mix: Apparently, the bundled `requests` library causes issues on Windows. We bundled a very old version 1.1.0, see #5241 for the sad reason.

In order to fix it, it seems you had to

1. Delete `dist-packages/requests`
1. `pip install requests` -- it seems that both 2.1.0 and 2.11.1 are working for you.

(the other way around didn't have any effect because KA Lite was still using its own 1.1.0 version)

I don't think the issue pertains the upgrade/reinstallation of `urllib3` since it's bundled straight into `requests`.

**Comment by yogeshmr** [comment] 2016-09-13 17:40
@benjaoming  I think I am able to understand you ( I am an Electronics guy, so only now starting with Python).

Please note that right now when everything is working, the "C:\Python27\share\kalite\dist-packages\requests" folder is empty. The dist-packages folder has request folders shown in below image, none of which is 2.1.0 or 2.11.1. 
![image](https://cloud.githubusercontent.com/assets/21152041/18484455/206beab2-7a06-11e6-9786-776f1e8a4a3b.png)

But there is a "C:\Python27\Lib\site-packages\requests-2.11.1.dist-info" located under the site-packages and there is "C:\Python27\Lib\site-packages\requests" which does contains some files and folders.

**Comment by benjaoming** [comment] 2016-09-13 17:43
@yogeshmr probably only contain meta data pointing to the empty `requests/` folder - shouldn't make a difference. But you can delete all of them!

We should get a fix out, but I'm afraid that the nature of the issue means there's a conflict: What fixed an issue for the Mac installer now causes an issue on Windows. Att @cpauya 

What we can do, is to remove the need for the old requests version. This can be done in 0.17. But it will be a month or so before we're ready with that release.

**Comment by yogeshmr** [comment] 2016-09-13 17:46
@benjaoming  Sounds Gr8. Thanks a lot! :+1:

**Comment by benjaoming** [comment] 2016-09-13 18:08
You're welcome! Oh, just for the record... the error was actually most likely introduced in 0.16.8 where we changed `requests`'s version, not the latest release :)

**Comment by yogeshmr** [comment] 2016-09-13 18:24
@benjaoming Actually I did face the problem with 0.16.8 but did not report it instead continued to use 0.16.7 for my other installations :) But now I know that I have to report issues here and can get them fixed!

**Comment by mrpau-richard** [comment] 2016-09-14 10:33
Hi @yogeshmr & @benjaoming I was able to reproduced this issue in KA Lite windows upgrade from 0.16.7 to 0.16.9.
![temp-b](https://cloud.githubusercontent.com/assets/8663934/18508892/ba6df252-7aa8-11e6-8b33-f27553cbeb2f.JPG)

But if I base from 0.16.8 to 0.16.9 KA Lite release upgrade KA Lite will work fine.
![temp-a](https://cloud.githubusercontent.com/assets/8663934/18508969/08505a28-7aa9-11e6-84e6-45598febf8ef.JPG)

**Comment by benjaoming** [comment] 2016-09-14 12:45
@mrpau-richard did you do the proposed steps from our Release Notes (see Known Issues) ? There might be more than 1 cause of this problem.

**Comment by mrpau-richard** [comment] 2016-09-15 07:36
@benjaoming I read the 0.16.9 release notes, I think the another one may cause this issue is the [Old versions of pip](https://github.com/learningequality/ka-lite/issues/5264).

I also tested by upgrading `request` from 1.1.0 to 2.10.0 will fix this issue.

**Comment by benjaoming** [comment] 2016-09-15 12:19
@mrpau-richard great thanks, I was just wondering if this issue was solely because of the bundled `requests` library... *it is*, as I can tell from the symptoms reported here.

**Comment by spatiald** [comment] 2016-09-17 01:36
Same issue here...
**Hardware** - Intel CAP (customized)
**OS** - Ubuntu 12.04
**KA Lite versions** - 0.6.8 and 0.6.9

```
Traceback (most recent call last):
  File "/usr/share/kalite/kalitectl.py", line 118, in <module>
    from fle_utils.internet.functions import get_ip_addresses
  File "/usr/share/kalite/python-packages/fle_utils/internet/functions.py", line 8, in <module>
    import requests
  File "/usr/share/kalite/dist-packages/requests/__init__.py", line 52, in <module>
    from . import utils
  File "/usr/share/kalite/dist-packages/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/share/kalite/dist-packages/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "/usr/share/kalite/dist-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/share/kalite/dist-packages/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/usr/share/kalite/dist-packages/requests/packages/urllib3/connectionpool.py", line 45, in <module>
    from .util import get_host, is_connection_dropped, ssl_wrap_socket
  File "/usr/share/kalite/dist-packages/requests/packages/urllib3/util/__init__.py", line 5, in <module>
  File "/usr/share/kalite/dist-packages/requests/packages/urllib3/util/response.py", line 4, in <module>
ImportError: cannot import name HeaderParsingError
```

This error occurred was before and after running:
```
pip install urllib3 --upgrade
pip install requests --upgrade
```
Tried to restart kalite...same traceback as above.

I then tried:
```
pip install -I requests==2.1.0
pip install requests --upgrade
```
Tried to restart kalite...same traceback as above.

I then backed up and deleted my requests folder (like @yogeshmr):
/usr/share/kalite/dist-packages/requests

Tried to restart kalite...and it worked.  I also believe the bundled requests is causing issues.  Let me know if you need anything else.

Btw, reverting back to 0.6.7 and below also fixes the issues...another plug that the old requests version is causing issues.

**Comment by benjaoming** [comment] 2016-09-17 13:38
Okay, then we have to concede and quickly get a fix out for KA Lite 0.16 series.

@spatiald can you run `kalite shell` ?

If so, try this:

```
import requests
print requests.__version__
print requests.__file__
```

**Comment by spatiald** [comment] 2016-09-17 18:53
@benjaoming  As requested...
```
root@WRTD-303N-Server:~# kalite shell
Python 2.7.3 (default, Apr 10 2013, 05:46:21) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import requests
>>> print requests.__version__
2.11.1
>>> print requests.__file__
/usr/local/lib/python2.7/dist-packages/requests/__init__.pyc 
```

**Comment by benjaoming** [comment] 2016-09-19 11:11
@spatiald Thanks - that's very odd but valuable to know. Seems like it's a problem with the path environment.

FYI this is how it looks on my test installation:

```
pi@raspberrypi:~ $ kalite shell
Python 2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import kalite
>>> kalite.__version__
'0.16.9'
>>> import requests
>>> requests.__version__
'1.1.0'
>>> requests.__file__
'/usr/share/kalite/dist-packages/requests/__init__.py'
>>>
```


Could you try running this? It should tell us how imports are resolved...

```
import sys
print sys.path
```

**Comment by spatiald** [comment] 2016-09-19 12:46
```
Python 2.7.3 (default, Apr 10 2013, 05:46:21) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import sys
>>> print sys.path
['/usr/share/kalite/python-packages', '/usr/share/kalite/dist-packages', '/usr/share/kalite/kalite', '/usr/share/kalite', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
>>> 
root@WRTD-303N-Server:~# kalite --version
0.16.9
```

**Comment by benjaoming** [comment] 2016-09-19 15:55
Thanks, the path looks good! I found the problem in the debian installer scripts. It's an unfortunate typo.

Will correct and re-release!

**Comment by benjaoming** [comment] 2016-09-19 22:24
@spatiald - I've fixed the installer, released an updated version of the .debs, the download links have been updated here: http://ka-lite.readthedocs.io/en/latest/installguide/install_all.html#linux

The PPAs will be ready soon.

**Comment by spatiald** [comment] 2016-09-20 01:10
Alright, thank you...will test shortly and let you know.

**Comment by benjaoming** [comment] 2016-10-02 10:02
The current `develop` branch has bumped `requests` to 2.11.1 and no longer stores python files in "data files" locations, so the mess with *pyc files is over - the Windows installer invokes setuptools which cleans up *pyc in target locations.

This will be released as 0.17 at the end of October... but please feel encouraged to try out the beta release on PyPi `pip install ka-lite --pre`

@mrpau-richard in case you have a working Windows installer build for `develop` on the Bamboo server, could you reference it here?

**Closed by benjaoming** 2016-10-02 10:02 UTC

**Comment by mrpau-richard** [comment] 2016-10-03 09:44
Hi @benjaoming I try to build using develop branch in Bamboo server, and I getting this [error logs](http://dungeon.learningequality.org/download/KL-MTBW-JOB1/build_logs/KL-MTBW-JOB1-42.log), We try to investigate the error.
In my local I successfully build the KA Lite .whl file using `make dist` command.

**Comment by benjaoming** [comment] 2016-10-03 17:21
@mrpau-richard - that's to be expected, I've opened up this issue regarding updating the Bamboo builds: https://github.com/learningequality/installers/issues/424
