### ISSUE TITLE
ka-lite_0.14.alpha2-0ubuntu1_all.deb not working on RPi

### ISSUE THREAD

**Issue by 66eli77** [learningequality/ka-lite#4018] opened 2015-07-03 21:47 UTC
platform: raspberry pi
./deb link: http://ppa.launchpad.net/benjaoming/ka-lite/ubuntu/pool/main/k/ka-lite-source/?C=M;O=D
steps to reproduce:
1. download the .deb file from the link above
2. install the .deb file with command

        $ sudo dpkg -i ka-lite_0.14.alpha2-0ubuntu1_all.deb
3. then run these commands

        $ sudo pip install ka-lite-static
        $ kalite manage setup
        $ kalite start
4. you will get the this error message
```
TypeError: 'NoneType' object is not callable
```

**Comment by EdDixon** [comment] 2015-07-03 23:59
It is a known issue but I can also verify this to be the state on debian current stable as well.

**Comment by radinamatic** [comment] 2015-07-04 09:38
Not sure if it is related (or if it is what @EdDixon refers to), but I got the same message on Ubuntu (with previously working installation) after running the `kalite manage generaterealdata`. See #4012.

**Comment by benjaoming** [comment] 2015-07-06 12:26
#4014 is merged so the non-sense failure should be replaced by something a bit better.

The issue seems to be that a thread fails. That thread is most likely the one running cronserver_blocking.

I'm a bit confused about when what was merged, but we changed the order of starting cronserver_blocking and may have previously encountered "leaked" processes locking the database.

So to test this again:

1. grap the alpha3
1. ensure that no leaked kalite processes remain
1. Test it again, especially with @radinamatic 's reproducable test case.

**Comment by radinamatic** [comment] 2015-07-06 15:54
@benjaoming where can we "grab" alpha3? Launchpad still shows alpha2...

**Comment by benjaoming** [comment] 2015-07-06 16:20
*cooking* 

See:

#4028

**Comment by radinamatic** [comment] 2015-07-06 16:24
My apologies Chef Ming... 
Kids are getting hungry... :P

**Comment by aronasorman** [comment] 2015-08-07 18:30
A raspberry pi specific deb has been created. Feel free to file an issue if this is still the case.

**Closed by aronasorman** 2015-08-07 18:30 UTC
Labels: bug
