### ISSUE TITLE
Computing topic description is a simple 's'

### ISSUE THREAD

**Issue by aronasorman** [learningequality/ka-lite#3841] opened 2015-06-12 23:06 UTC
Browser: Firefox 37

![image](https://cloud.githubusercontent.com/assets/191955/8141517/e9eb0e1c-111c-11e5-920a-0fee31b4e0c9.png)

**Comment by 66eli77** [comment] 2015-06-12 23:07
see #3834

**Comment by rtibbles** [comment] 2015-06-13 00:29
Duplicate of #3834. Note: This is a problem of data that is being pulled from KA itself.

**Closed by rtibbles** 2015-06-13 00:29 UTC
