### ISSUE TITLE
Error when trying to register.

### ISSUE THREAD

**Issue by richard-ive-m4** [learningequality/ka-lite#3287] opened 2015-03-13 18:36 UTC
Hi,

I followed the instructions here: https://github.com/learningequality/ka-lite/blob/master/INSTALL.md

But when I try and register my device I get this error:

![selection_007](https://cloud.githubusercontent.com/assets/4996821/6644926/df69fbb0-c9af-11e4-96c0-36094c6b72ad.png)

Thanks.

**Comment by aronasorman** [comment] 2015-03-13 19:02
Duplicate of #3197.

**Closed by aronasorman** 2015-03-13 19:02 UTC
