### ISSUE TITLE
Sidebar not hiding when entering from hompage's Next steps

### ISSUE THREAD

**Issue by jinchuika** [learningequality/ka-lite#4563] opened 2015-10-02 21:40 UTC
**Branch**: master
**Build**: 0.15b2 (installed from PPA)
**Expected behavior**: Clicking on one of the Next Steps links should show the exercise after hiding the sidebar.
**Actual behavior**: The sidebar doesn't hide when you enter to the exercise via Next Steps. The exercises is loaded and you can hide the sidebar after.

![output-v](https://cloud.githubusercontent.com/assets/5230176/10258122/3b33b874-6919-11e5-8f9d-80148f56519e.gif)

**Comment by MCGallaspy** [comment] 2016-02-17 01:22
I can't replicate this. The sidebar closes fine for me. However, I encountered another (possibly related) issue, where the "Next Steps" card links to a *topic* instead of a content item, so that the sidebar simply is open to that point and no content is loaded.

**Comment by rtibbles** [comment] 2016-02-17 01:39
Part of the next steps card links to a topic, part to the content, so that is intended behaviour, @MCGallaspy.

**Comment by MCGallaspy** [comment] 2016-02-19 23:17
*All* of my next steps cards lead to topics.

![image](https://cloud.githubusercontent.com/assets/8888020/13191849/971fb10e-d71b-11e5-869d-c02e01779a13.png)

Contrary to my expectations, clicking the "topic" icon leads to the same topic for all of them: `/learn/khan/math/early-math/`

Clicking the name of the item leads directly to that item. If this is expected behavior, please close the issues @rtibbles.

**Comment by radinamatic** [comment] 2016-02-22 01:35
I was also unable to replicate the original issue 0.15 (Ubuntu & Windows). I have a vague memory of this being fixed at some point, but can't find the respective PR. 

So, clicking the title of the item leads to the item itself (video/exercise), clicking the Topic (arrow icon) opens the sidebar leaving the user to select one item from that topic. 

![contentrec](https://cloud.githubusercontent.com/assets/1457929/13207225/5da35564-d90c-11e5-935d-2f8d5a23605a.png)


The only thing I find might be confusing to the user is if they decide to close the sidebar at that point, and end up on a completely blank page. Wouldn't it be better for contentrec to remain "active" behind the sidebar, **until** the user actually chooses one item from it? Right now content recommendation page seems to "disappear" while the sidebar is loaded...

**Comment by MCGallaspy** [comment] 2016-02-24 00:12
@radinamatic you raise some good points. Closing this issue because the original seems to be resolved., but perhaps we can re-open some new issues/feature requests from the above discussion.

**Closed** 2016-02-24 00:12 UTC
Labels: release blocker

**Comment by rtibbles** [comment] 2016-02-29 20:20
I think this issue has now genuinely been resolved by #4923 also.
