### ISSUE TITLE
Vertical angles exercise does not load the questions after solving 6 questions. 

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/ka-lite#5316] opened 2016-10-04 10:40 UTC
## Summary

Path: Math --> Geometry --> Angles & Intersecting lines --> Vertical Angles --> Vertical Angles exercise.

When a user starts solving problems on the Vertical angles exercise the questions does not load after solving 6 questions. 
## System information
- Operating system: Ubuntu 14.04LTS
- Version: 0.16.X all versions 
- Browser: Chrome
## How to reproduce
1. Go to the vertical angle exercise.
2. Start solving the exercise.
3. After 6 questions the questions will not show up.
## Real-life consequences (anything community should be aware, for instance how it affects your deployment)

6200+ Kids are not able to complete the exercise.
## Screenshots

![screenshot from 2016-10-04 15_57_04](https://cloud.githubusercontent.com/assets/13453618/19071262/d0b0ef16-8a4c-11e6-9048-5ef1f23f10d7.png)
![screenshot from 2016-10-04 15_57_46](https://cloud.githubusercontent.com/assets/13453618/19071263/d0b5b596-8a4c-11e6-95ff-516ef7ec2b1c.png)
![screenshot from 2016-10-04 15_57_56](https://cloud.githubusercontent.com/assets/13453618/19071264/d0b81b6a-8a4c-11e6-8be4-fa3f1c30c5cd.png)
![screenshot from 2016-10-04 15_58_08](https://cloud.githubusercontent.com/assets/13453618/19071266/d0bce8ac-8a4c-11e6-9e6e-6ddfebc6439a.png)
![screenshot from 2016-10-04 15_58_48](https://cloud.githubusercontent.com/assets/13453618/19071265/d0ba0a9c-8a4c-11e6-84c6-11480a36e524.png)

**Comment by benjaoming** [comment] 2017-01-16 17:52
@harishbalachandran thanks for reporting

It looks like KA.org has rearranged these exercises. Could you see if you are able to reproduce using the same browser etc. on upstream exercises?

https://www.khanacademy.org/math/geometry-home/geometry-angles/geometry-vert-comp-supp/e/vertical_angles

@radinamatic can you tell if the reorganization has also happened in our latest English content pack? Because it might also contain fixes for these Javascript issues.

**Comment by radinamatic** [comment] 2017-01-17 12:14
The latest English contentpack from this morning. 
KA has indeed rearranged this exercise, now it is here:

![virtualbox_windows 7_17_01_2017_13_02_03](https://cloud.githubusercontent.com/assets/1457929/22019911/d4dab016-dcb5-11e6-8341-6b3d3a04bb19.png)

On another hand, I was not able to reproduce the same issue:

1. I'm able to continue past the 6th exercise, and new tasks load correctly.
2. Recording points stops at 48 when 8 tasks are completed correctly - this is not an error, but differs from the screenshots above.

![virtualbox_windows 7_17_01_2017_13_05_07](https://cloud.githubusercontent.com/assets/1457929/22020103/c4296de2-dcb6-11e6-8acc-3e1802f882be.png)

3. There is indeed a `no element found` error in the console, but nothing in the UI. The output from the debugger is this:
```
{"attempts": 16, "attempts_before_completion": 8, "complete": true, "completion_counter": null, "completion_timestamp": "2017-01-17T04:03:15", "counter": null, "deleted": false, "exercise_id": "vertical_angles", "id": "9a794d54d542546bb9c973963fce6f51", "language": null, "latest_activity_timestamp": "2017-01-17T04:03:59", "points": 48, "resource_uri": "/api/exerciselog/9a794d54d542546bb9c973963fce6f51/", "signature": null, "signed_version": 1, "streak_progress": 100, "struggling": false, "user": "/securesync/api/user/7b798d43178a47319159cc9a55afbbff/"}
```

**Comment by radinamatic** [comment] 2017-01-17 13:02
No issues whatsoever in Chromium on Ubuntu 16.10:

![virtualbox_ubuntu 16 10_17_01_2017_14_00_40](https://cloud.githubusercontent.com/assets/1457929/22021410/6f8abbcc-dcbd-11e6-9a06-a93f51771102.png)

@benjaoming I think we can close this!

**Comment by benjaoming** [comment] 2017-01-17 13:40
Yes, added to release notes and closing!

**Closed by benjaoming** 2017-01-17 13:40 UTC
Labels: content / perseus
