### ISSUE TITLE
Missing chars in current font being used in the assessment response area in XP

### ISSUE THREAD

**Issue by EdDixon** [learningequality/ka-lite#3673] opened 2015-05-19 21:04 UTC
The green and red check marks after the student submits an answer to an assessment are not showing in newer builds. As I understand it those are font based and are not png/svg pics. This issue does not exist in later versions of WIndows and seems only to be an issue for Windows XP. 
![2015-05-19_14-52-19](https://cloud.githubusercontent.com/assets/4349806/7713924/2c03a554-fe38-11e4-87e5-c7dce0206621.png)

**Comment by MCGallaspy** [comment] 2015-05-19 21:16
Duplicate of #3587.

**Closed by MCGallaspy** 2015-05-19 21:16 UTC

**Comment by EdDixon** [comment] 2015-05-19 21:22
Sorry Mike was unaware we had one for this thanks
