### ISSUE TITLE
exercises are missing, Swahili

### ISSUE THREAD

**Issue by ptr998** [learningequality/ka-lite#5091] opened 2016-04-18 08:15 UTC
Our system upgraded from 0.14 to 0.15 to make the Swahili language to work.
On the learning menu, the Exercises are missing, the menus are inactive. Videos are available.
Any hint?

**Comment by benjaoming** [comment] 2016-05-02 19:12
What installer are you using? Windows / Mac / OSX?

Have you re-downloaded language packs and assessment items?

**Comment by benjaoming** [comment] 2016-06-13 11:40
Possibly related: #5120 

@aronasorman it's true, the Swahili content pack is almost zero in size and has no exercises at all.

This is true for 7 languages.

**Comment by aronasorman** [comment] 2016-06-13 23:36
Should be solved by @cpauya adding in the spreadsheets when checking for dubbed videos.

Since this is a content pack issue, we can make the release separately from the content packs (which get updated daily). I'll make a comment here once we fix this on the content packs.

**Comment by benjaoming** [comment] 2016-06-17 18:51
This is an issue that will be fixed separately in content packs and is not as such tied to the 0.16.7 release. Watch this issue or our mailing list for an announcement.

**Comment by benjaoming** [comment] 2016-06-18 15:11
Closing as a duplicate of #5120 so we can track progress in one place.

**Closed by benjaoming** 2016-06-18 15:11 UTC
Labels: content / perseus
